import json

data = {
    "title": "Compounds and Solubility Trends of Alkaline Earth Metals",
    "unitSlug": "chemistry-of-metals",
    "topicSlug": "molecular-formula-and-uses-of-quick-lime-bleaching-powder-magnesia-plaster-of-paris-and-epsom-salt-solubility-of-hydroxides-carbonates-and-sulphates-of-alkaline-earth-metals-stability-of-carbonate-and-nitrate-of-alkaline-earth-metals",
    "topicTitle": "Molecular formula and uses of quick lime, bleaching powder, magnesia, plaster of Paris and Epsom salt; solubility of hydroxides, carbonates and sulphates of alkaline earth metals; stability of carbonate and nitrate of alkaline earth metals",
    "relevance": 100,
    "notes": [
        "**Quick Lime ($CaO$) — Production via Calcination of Limestone**: Quick lime (calcium oxide) is produced by the thermal decomposition of limestone (calcium carbonate) at high temperatures (900–1000 °C) in a lime kiln: $CaCO_3(s) \\xrightarrow{900-1000^{\\circ}C} CaO(s) + CO_2(g) \\quad \\Delta H = +178 \\text{ kJ mol}^{-1}$. The reaction is endothermic and reversible; removal of $CO_2$ drives it forward. Industrial kilns use counter-current flow for energy efficiency. The product is a white, amorphous solid with a high melting point (2613 °C).",
        "**Quick Lime ($CaO$) — Chemical Properties**: $CaO$ is a basic oxide that reacts vigorously with water (slaking) to form calcium hydroxide $Ca(OH)_2$ (slaked lime), releasing $63.7 \\text{ kJ mol}^{-1}$ of heat: $CaO(s) + H_2O(l) \\rightarrow Ca(OH)_2(s)$. It reacts with acidic oxides ($SiO_2$, $P_4O_{10}$, $SO_2$) to form salts: $CaO + SiO_2 \\rightarrow CaSiO_3$ (calcium silicate, slag). It absorbs $CO_2$ from air forming $CaCO_3$, so it must be stored in airtight containers.",
        "**Quick Lime ($CaO$) — Uses in Steel Making and Cement**: In steelmaking (basic oxygen furnace), $CaO$ acts as a flux to remove acidic impurities ($Si$, $P$, $S$) as slag ($CaSiO_3$, $Ca_3(PO_4)_2$, $CaS$). About 50–60 kg of lime per tonne of steel. In cement manufacture, $CaO$ is the primary component (60–67%) of Portland cement clinker, formed by sintering limestone with clay at 1450 °C to give $3CaO\\cdot SiO_2$ (alite) and $2CaO\\cdot SiO_2$ (belite). Also used as a drying agent for gases and organic liquids.",
        "**Bleaching Powder ($CaOCl_2$) — Preparation**: Bleaching powder (calcium hypochlorite chloride) is prepared by passing chlorine gas over dry slaked lime at 40 °C: $2Ca(OH)_2(s) + 2Cl_2(g) \\rightarrow CaOCl_2(s) + CaCl_2(s) + 2H_2O(l)$. The product is a mixture of $Ca(OCl)Cl$ (calcium hypochlorite chloride). Industrial process uses Hasenclever or Bachmann plant with counter-current flow. Commercial grade contains 30–35% available chlorine.",
        "**Bleaching Powder ($CaOCl_2$) — Mechanism of Bleaching Action**: The bleaching action is due to the formation of hypochlorous acid ($HOCl$) in aqueous solution: $CaOCl_2 + H_2O \\rightarrow Ca^{2+} + Cl^- + OCl^-$, $OCl^- + H_2O \\rightleftharpoons HOCl + OH^-$. $HOCl$ is a powerful oxidising agent: it oxidises coloured substances to colourless products via nascent oxygen: $HOCl \\rightarrow HCl + [O]$, $Coloured \; substance + [O] \\rightarrow Colourless \; product$. Bleaching is permanent (oxidative), unlike $SO_2$ which is temporary (reductive).",
        "**Bleaching Powder ($CaOCl_2$) — Uses for Water Treatment and Disinfection**: Used for disinfection of drinking water (0.5–2 ppm available chlorine), swimming pools, and sewage treatment. $HOCl$ kills bacteria/viruses by oxidising cellular proteins and enzymes. Also used in textile/paper industry for bleaching cotton, linen, wood pulp. In laboratory, used to prepare chlorine gas: $CaOCl_2 + 2HCl \\rightarrow CaCl_2 + H_2O + Cl_2 \\uparrow$. Loses available chlorine on storage due to auto-decomposition: $2CaOCl_2 \\rightarrow 2CaCl_2 + O_2$.",
        "**Magnesia ($MgO$) — Production from Magnesite**: Magnesia (magnesium oxide) is obtained by calcining magnesite ($MgCO_3$) or dolomite ($CaMg(CO_3)_2$) at 800–1000 °C: $MgCO_3(s) \\xrightarrow{800-1000^{\\circ}C} MgO(s) + CO_2(g)$. Dead-burnt magnesia (sintered at 1500–2000 °C) is dense and unreactive; caustic-calcined magnesia (700–1000 °C) is reactive. Also produced from seawater by precipitation of $Mg(OH)_2$ followed by calcination.",
        "**Magnesia ($MgO$) — Refractory Properties and Uses**: $MgO$ has an extremely high melting point (2852 °C) and low thermal conductivity, making it an excellent refractory material for furnace linings (basic refractories in steelmaking), crucibles, and fire bricks. As an antacid (milk of magnesia, $Mg(OH)_2$ suspension), it neutralises stomach acid: $Mg(OH)_2 + 2HCl \\rightarrow MgCl_2 + 2H_2O$. Used as an electrical insulator in heating elements (e.g., tubular heaters) due to high dielectric strength and thermal conductivity.",
        "**Plaster of Paris ($CaSO_4 \\cdot \\frac{1}{2}H_2O$) — Preparation from Gypsum**: Plaster of Paris (calcium sulphate hemihydrate) is made by partially dehydrating gypsum ($CaSO_4 \\cdot 2H_2O$) at 120–130 °C (393–403 K): $CaSO_4 \\cdot 2H_2O(s) \\xrightarrow{120-130^{\\circ}C} CaSO_4 \\cdot \\frac{1}{2}H_2O(s) + \\frac{3}{2}H_2O(g)$. Overheating ($>200^{\\circ}C$) gives anhydrite ($CaSO_4$) which sets very slowly. The hemihydrate exists in $\\alpha$- (high strength, dense) and $\\beta$- (porous, commercial) forms.",
        "**Plaster of Paris ($CaSO_4 \\cdot \\frac{1}{2}H_2O$) — Setting Reaction and Expansion**: On mixing with water, it rehydrates to gypsum, forming a colloidal gel that crystallises into an interlocking needle-like structure: $CaSO_4 \\cdot \\frac{1}{2}H_2O + \\frac{3}{2}H_2O \\rightarrow CaSO_4 \\cdot 2H_2O \; (\\Delta H = -16.7 \\text{ kJ mol}^{-1})$. The setting is exothermic and accompanied by a slight expansion (~0.1–0.5%) due to crystal growth pressure — crucial for faithful mould replication. Setting time: 5–15 min (controllable by accelerators like $NaCl$ or retarders like borax).",
        "**Plaster of Paris — Uses in Casts and Moulds**: Used for orthopaedic casts (lightweight, porous, radiolucent), dental impressions, surgical bandages, statuary, decorative mouldings, chalk, and fireproofing. In ceramics, used for slip-casting moulds (absorbs water from slip). Not suitable for outdoor use (water-soluble). $\\alpha$-hemihydrate gives stronger casts for dental/orthopaedic use.",
        "**Epsom Salt ($MgSO_4 \\cdot 7H_2O$) — Properties and Uses**: Epsom salt (magnesium sulphate heptahydrate) is a colourless crystalline solid, soluble in water (71 g/100 mL at 20 °C). As a laxative, $Mg^{2+}$ ions draw water into intestines osmotically (dose: 10–30 g in water). As bath salt, it is absorbed transdermally (controversial) and used for muscle relaxation, soreness relief. In agriculture, it corrects Mg deficiency in soils (chlorophyll synthesis) — applied as foliar spray (2% solution) or soil amendment. Also used in dyeing, tanning, and as a drying agent.",
        "**Solubility Trends of Alkaline Earth Metal Hydroxides**: Solubility increases down the group: $Be(OH)_2$ (insoluble, amphoteric) $\\ll Mg(OH)_2$ (sparingly soluble, $K_{sp} = 5.6 \\times 10^{-12}$) $< Ca(OH)_2$ (sparingly soluble, $K_{sp} = 5.5 \\times 10^{-6}$) $< Sr(OH)_2$ (moderately soluble) $< Ba(OH)_2$ (quite soluble, $3.9 \\text{ g/100 mL}$ at 20 °C). $Ra(OH)_2$ is most soluble. Reason: lattice energy decreases faster than hydration energy down the group due to increasing ionic radius ($Be^{2+} \\approx 45 \\text{ pm}$, $Ba^{2+} \\approx 135 \\text{ pm}$). $Be(OH)_2$ is amphoteric: $Be(OH)_2 + 2OH^- \\rightarrow [Be(OH)_4]^{2-}$.",
        "**Solubility Trends of Alkaline Earth Metal Sulphates**: Solubility decreases down the group: $BeSO_4$ (very soluble, $42 \\text{ g/100 mL}$) $> MgSO_4$ (soluble, $71 \\text{ g/100 mL}$) $> CaSO_4$ (sparingly soluble, $0.21 \\text{ g/100 mL}$, $K_{sp} = 2.4 \\times 10^{-5}$) $> SrSO_4$ (sparingly soluble, $0.013 \\text{ g/100 mL}$) $> BaSO_4$ (very insoluble, $0.00024 \\text{ g/100 mL}$, $K_{sp} = 1.1 \\times 10^{-10}$). Reason: large $SO_4^{2-}$ anion; lattice energy dominates over hydration energy as cation size increases. $BaSO_4$ insolubility used in qualitative analysis (group IV) and as radiocontrast agent (barium meal).",
        "**Solubility Trends of Alkaline Earth Metal Carbonates**: All carbonates are sparingly soluble but solubility decreases slightly down group: $BeCO_3$ (unstable, hydrolyses) $> MgCO_3$ ($0.02 \\text{ g/100 mL}$) $\\approx CaCO_3$ ($0.0013 \\text{ g/100 mL}$) $> SrCO_3$ ($0.0011 \\text{ g/100 mL}$) $> BaCO_3$ ($0.0022 \\text{ g/100 mL}$). $K_{sp}$ values: $MgCO_3 \; 6.8 \\times 10^{-6}$, $CaCO_3 \; 3.3 \\times 10^{-9}$, $SrCO_3 \; 5.6 \\times 10^{-10}$, $BaCO_3 \; 2.6 \\times 10^{-9}$. Trend is irregular due to competing lattice/hydration energies. $BeCO_3$ exists only in $CO_2$ atmosphere (hydrolyses: $BeCO_3 + H_2O \\rightarrow Be(OH)_2 + CO_2$).",
        "**Thermal Stability of Carbonates — Increasing Down the Group**: Carbonates decompose to oxide + $CO_2$: $MCO_3(s) \\xrightarrow{\\Delta} MO(s) + CO_2(g)$. Decomposition temperatures: $BeCO_3$ (unstable at RT) $< MgCO_3$ (350 °C) $< CaCO_3$ (900 °C) $< SrCO_3$ (1290 °C) $< BaCO_3$ (1360 °C) $< RaCO_3$ (highest). Reason: larger $M^{2+}$ stabilises large $CO_3^{2-}$ anion better (lower polarising power, less distortion of $CO_3^{2-}$ electron cloud). $Be^{2+}$ high charge density strongly polarises $CO_3^{2-}$, weakening $C-O$ bonds. Compare with alkali metals: $Li_2CO_3$ decomposes (~1300 °C), $Na_2CO_3$ stable to >1800 °C — alkali carbonates more stable due to $+1$ charge.",
        "**Thermal Stability of Nitrates — Increasing Down the Group**: Nitrates decompose to oxide + $NO_2$ + $O_2$: $2M(NO_3)_2(s) \\xrightarrow{\\Delta} 2MO(s) + 4NO_2(g) + O_2(g)$. Decomposition temperatures: $Mg(NO_3)_2$ (330 °C) $< Ca(NO_3)_2$ (560 °C) $< Sr(NO_3)_2$ (570 °C) $< Ba(NO_3)_2$ (590 °C). Trend parallels carbonates. $Be(NO_3)_2$ is covalent, hydrolyses readily. Compare with alkali metals: $LiNO_3$ decomposes to $Li_2O$, others ($Na-K-Cs$) give nitrites ($MNO_2$) + $O_2$. Alkaline earth nitrates all give oxides due to $+2$ charge."
    ],
    "confusion": [
        "❌ Quick lime ($CaO$) and slaked lime ($Ca(OH)_2$) are the same. ✅ Quick lime is $CaO$ (anhydrous oxide); slaked lime is $Ca(OH)_2$ (hydrated product of $CaO + H_2O$). They have different properties and uses.",
        "❌ Bleaching powder is pure $Ca(OCl)_2$. ✅ Bleaching powder is a mixed salt $Ca(OCl)Cl$ (calcium hypochlorite chloride), not pure calcium hypochlorite. Commercial grade contains $CaCl_2$, $Ca(OH)_2$, and unreacted $CaCO_3$.",
        "❌ Bleaching action of bleaching powder is due to chlorine gas release. ✅ Bleaching is due to hypochlorous acid ($HOCl$) formation in water, which releases nascent oxygen. $Cl_2$ release occurs only with acid, not during normal bleaching.",
        "❌ Plaster of Paris sets by simple drying/evaporation of water. ✅ Setting is a chemical hydration reaction forming crystalline gypsum ($CaSO_4 \\cdot 2H_2O$) with crystal interlocking and slight expansion — not mere drying.",
        "❌ All alkaline earth metal hydroxides are strong bases with similar solubility. ✅ $Be(OH)_2$ is amphoteric and insoluble; $Mg(OH)_2$ is weakly basic and sparingly soluble; $Ba(OH)_2$ is a strong base and quite soluble. Basicity and solubility increase down the group.",
        "❌ Sulphates become more soluble down the group like hydroxides. ✅ Sulphates show the opposite trend: solubility decreases down the group ($BeSO_4$ very soluble $\\rightarrow BaSO_4$ very insoluble) because the large $SO_4^{2-}$ anion makes lattice energy dominant.",
        "❌ Thermal stability of carbonates decreases down the group (like Group 1). ✅ For alkaline earth metals, thermal stability of carbonates increases down the group (opposite to Group 1 where $Li_2CO_3$ is least stable). This is due to decreasing polarising power of $M^{2+}$ down the group."
    ],
    "practice": [
        "**Problem 1**: 50 g of limestone ($CaCO_3$, 95% pure) is calcined. Calculate the mass of quick lime ($CaO$) produced and the volume of $CO_2$ evolved at STP.\n\n**Solution**:\nMolar mass $CaCO_3 = 100 \\text{ g mol}^{-1}$, $CaO = 56 \\text{ g mol}^{-1}$.\nMass of pure $CaCO_3 = 50 \\times 0.95 = 47.5 \\text{ g}$.\nMoles of $CaCO_3 = 47.5 / 100 = 0.475 \\text{ mol}$.\nFrom stoichiometry: 1 mol $CaCO_3 \\rightarrow$ 1 mol $CaO$ + 1 mol $CO_2$.\nMass of $CaO = 0.475 \\times 56 = 26.6 \\text{ g}$.\nVolume of $CO_2$ at STP = $0.475 \\times 22.4 = 10.64 \\text{ L}$.\n\n**Answer**: $CaO = 26.6 \\text{ g}$; $CO_2 = 10.64 \\text{ L}$ at STP.",
        "**Problem 2**: Calculate the available chlorine (% w/w) in a bleaching powder sample if 2.5 g of it liberates iodine from KI requiring 25 mL of 0.1 M $Na_2S_2O_3$ for titration.\n\n**Solution**:\nReactions: $OCl^- + 2I^- + 2H^+ \\rightarrow I_2 + Cl^- + H_2O$; $I_2 + 2S_2O_3^{2-} \\rightarrow 2I^- + S_4O_6^{2-}$.\n1 mol $OCl^- \\equiv$ 1 mol $I_2 \\equiv$ 2 mol $S_2O_3^{2-}$.\nMoles of $Na_2S_2O_3 = 0.1 \\times 0.025 = 0.0025 \\text{ mol}$.\nMoles of $OCl^-$ (available Cl) = $0.0025 / 2 = 0.00125 \\text{ mol}$.\nMass of $Cl_2$ equivalent = $0.00125 \\times 71 = 0.08875 \\text{ g}$.\n% Available chlorine = $(0.08875 / 2.5) \\times 100 = 3.55%$.\n\n**Answer**: 3.55% available chlorine.",
        "**Problem 3**: 10 g of gypsum ($CaSO_4 \\cdot 2H_2O$) is heated to 130 °C. Calculate the mass of Plaster of Paris obtained and the mass of water lost.\n\n**Solution**:\nMolar mass $CaSO_4 \\cdot 2H_2O = 172 \\text{ g mol}^{-1}$, $CaSO_4 \\cdot \\frac{1}{2}H_2O = 145 \\text{ g mol}^{-1}$.\nMoles of gypsum = $10 / 172 = 0.05814 \\text{ mol}$.\nMass of Plaster of Paris = $0.05814 \\times 145 = 8.43 \\text{ g}$.\nMass of water lost = $10 - 8.43 = 1.57 \\text{ g}$ (theoretical: $0.05814 \\times 27 = 1.57 \\text{ g}$).\n\n**Answer**: Plaster of Paris = 8.43 g; Water lost = 1.57 g.",
        "**Problem 4**: The solubility product ($K_{sp}$) of $BaSO_4$ is $1.1 \\times 10^{-10}$ at 298 K. Calculate its solubility in mol L$^{-1}$ and g/100 mL. Will a precipitate form if equal volumes of 0.001 M $BaCl_2$ and 0.001 M $Na_2SO_4$ are mixed?\n\n**Solution**:\n$BaSO_4(s) \\rightleftharpoons Ba^{2+} + SO_4^{2-}$; $K_{sp} = s^2$.\n$s = \\sqrt{1.1 \\times 10^{-10}} = 1.05 \\times 10^{-5} \\text{ mol L}^{-1}$.\nMolar mass $BaSO_4 = 233.4 \\text{ g mol}^{-1}$.\nSolubility in g/100 mL = $1.05 \\times 10^{-5} \\times 233.4 \\times 0.1 = 2.45 \\times 10^{-4} \\text{ g/100 mL}$.\nOn mixing equal volumes: $[Ba^{2+}] = [SO_4^{2-}] = 0.0005 \\text{ M}$.\nIonic product = $(5 \\times 10^{-4})^2 = 2.5 \\times 10^{-7} > K_{sp}$.\nSince IP > $K_{sp}$, precipitate forms.\n\n**Answer**: $s = 1.05 \\times 10^{-5} \\text{ M}$ ($2.45 \\times 10^{-4} \\text{ g/100 mL}$); Yes, precipitate forms.",
        "**Problem 5**: Arrange the following in order of increasing thermal stability and explain: $MgCO_3$, $CaCO_3$, $BaCO_3$, $BeCO_3$.\n\n**Solution**:\nOrder: $BeCO_3 < MgCO_3 < CaCO_3 < BaCO_3$ (increasing stability).\nDecomposition temperatures: $BeCO_3$ (unstable at RT) $< MgCO_3$ (350 °C) $< CaCO_3$ (900 °C) $< BaCO_3$ (1360 °C).\nExplanation: Thermal stability depends on polarising power of cation ($M^{2+}$). Smaller cation with high charge density ($Be^{2+}$, $r \\approx 45 \\text{ pm}$) strongly polarises the large $CO_3^{2-}$ anion, weakening $C-O$ bonds and lowering decomposition temperature. As ionic radius increases down the group ($Mg^{2+}$ 72, $Ca^{2+}$ 100, $Ba^{2+}$ 135 pm), polarising power decreases, $CO_3^{2-}$ is less distorted, and stability increases.\n\n**Answer**: $BeCO_3 < MgCO_3 < CaCO_3 < BaCO_3$.",
        "**Problem 6**: A 4.0 g mixture of $MgCO_3$ and $BaCO_3$ on heating gives 0.896 L $CO_2$ at STP. Find the % composition of the mixture.\n\n**Solution**:\nMoles $CO_2 = 0.896 / 22.4 = 0.04 \\text{ mol}$.\nLet $x$ g = $MgCO_3$, $(4-x)$ g = $BaCO_3$.\nMolar masses: $MgCO_3 = 84$, $BaCO_3 = 197$.\n$x/84 + (4-x)/197 = 0.04$.\nMultiplying by $(84 \\times 197) = 16548$: $197x + 84(4-x) = 0.04 \\times 16548 = 661.92$.\n$197x + 336 - 84x = 661.92$.\n$113x = 325.92$.\n$x = 2.884 \\text{ g}$ ($MgCO_3$).\n$(4-x) = 1.116 \\text{ g}$ ($BaCO_3$).\n% $MgCO_3 = (2.884/4) \\times 100 = 72.1%$.\n% $BaCO_3 = (1.116/4) \\times 100 = 27.9%$.\n\n**Answer**: $MgCO_3$ = 72.1%, $BaCO_3$ = 27.9%."
    ],
    "universalFacts": [
        "The Great Pyramid of Giza (~2.3 million limestone blocks) used an estimated 5.5 million tonnes of limestone; if fully calcined, it would yield ~3.1 million tonnes of quick lime and release ~2.4 million tonnes of $CO_2$ — equivalent to annual emissions of ~500,000 cars.",
        "Bleaching powder was the first widely used chemical disinfectant for drinking water; its introduction in the 1850s (John Snow's cholera investigations) dramatically reduced waterborne diseases. Modern water treatment uses chlorine gas or sodium hypochlorite, but calcium hypochlorite tablets are still used for emergency disinfection and swimming pools.",
        "Plaster of Paris gets its name from large gypsum deposits near Paris (Montmartre). The $\\alpha$-hemihydrate form (dental stone) is made by autoclaving gypsum under steam pressure — it has higher density, strength, and lower water/powder ratio than the commercial $\\beta$-form.",
        "Epsom salt was originally obtained by evaporating mineral waters from Epsom, Surrey, England (discovered 1618). It was a major commercial product for centuries; today most is synthetic. The 'Epsom salt bath' for muscle soreness lacks strong clinical evidence but remains a popular home remedy — the $Mg^{2+}$ transdermal absorption claim is scientifically debated.",
        "Barium sulphate ($BaSO_4$) is the standard radiocontrast agent for 'barium meals/swallows' in X-ray imaging of the GI tract. Its extreme insolubility ($K_{sp} = 1.1 \\times 10^{-10}$) prevents toxic $Ba^{2+}$ absorption. About 300 g of $BaSO_4$ suspension is ingested; it coats the oesophagus, stomach, and intestines, providing high contrast due to Ba's high atomic number (Z=56)."
    ],
    "animation3D": "chemistry-of-metals",
    "motionGraphics": "chemistry-of-metals"
}

out_path = "C:/Users/ASUS/Desktop/rn/content/ravikishan/class-11-notes/chemistry/chemistry-of-metals/concepts/08-molecular-formula-and-uses-of-quick-lime-bleaching-powder-magnesia-plaster-of-paris-and-epsom-salt-solubility-of-hydroxides-carbonates-and-sulphates-of-alkaline-earth-metals-stability-of-carbonate-and-nitrate-of-alkaline-earth-metals.json"

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Written successfully")
print("Notes:", len(data["notes"]))
print("Confusion:", len(data["confusion"]))
print("Practice:", len(data["practice"]))
print("Facts:", len(data["universalFacts"]))
