@echo off
cd /d "%~dp0"
echo Starting backend server...
start "Backend" cmd /c "npm run dev:backend"
echo Starting frontend server...
start "Frontend" cmd /c "npm run dev -w frontend"
echo Both servers starting...
timeout /t 15 >nul
echo Opening browser...
start http://localhost:5173
