/**
 * Biology Lab Content Migration Tool
 * 
 * Scans content/ravikishan/ for biology content and generates
 * lab registry entries and theory panel data.
 * 
 * Usage: npx tsx content-tools/migrate-biology.ts
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs";
import { join } from "path";

const CONTENT_ROOT = join(__dirname, "..", "..", "content", "ravikishan");
const OUTPUT_FILE = join(__dirname, "..", "..", "frontend", "lib", "biology-lab-content.ts");

interface ContentFile {
  path: string;
  data: any;
}

interface LabEntry {
  id: string;
  title: string;
  unitSlug: string;
  unitTitle: string;
  topics: string[];
  components: string[];
}

function scanContentDir(dir: string): ContentFile[] {
  const files: ContentFile[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...scanContentDir(fullPath));
    } else if (entry.name.endsWith(".json")) {
      try {
        const data = JSON.parse(readFileSync(fullPath, "utf-8"));
        files.push({ path: fullPath, data });
      } catch {
        // Skip invalid JSON
      }
    }
  }
  return files;
}

function extractBiologyContent(files: ContentFile[]): LabEntry[] {
  const labs: Record<string, LabEntry> = {};

  for (const { path, data } of files) {
    const relPath = path.replace(CONTENT_ROOT + "\\", "").replace(/\\/g, "/");
    const parts = relPath.split("/");
    
    // Match: ravikishan/class-11-notes/biology/{unit-slug}/{type}/{filename}.json
    if (parts[1] !== "class-11-notes" || parts[2] !== "biology") continue;
    
    const unitSlug = parts[3];
    const contentType = parts[4]; // concepts, formula, notes, pyqs, sets, examples, mindmap
    const filename = parts[5]?.replace(".json", "") || "index";

    const labId = `bio-${unitSlug}-${contentType}`;
    
    if (!labs[labId]) {
      labs[labId] = {
        id: labId,
        title: `${data.title || unitSlug} — ${contentType}`,
        unitSlug,
        unitTitle: data.unitTitle || unitSlug,
        topics: data.topics || [filename],
        components: [],
      };
    }
    
    if (!labs[labId].components.includes(contentType)) {
      labs[labId].components.push(contentType);
    }
  }

  return Object.values(labs);
}

function generateTypeScript(labs: LabEntry[]): string {
  return `/**
 * Auto-generated biology lab content mapping.
 * Generated by content-tools/migrate-biology.ts
 * DO NOT EDIT MANUALLY
 */

export interface BiologyLabContent {
  id: string;
  title: string;
  unitSlug: string;
  unitTitle: string;
  topics: string[];
  components: string[];
  content?: {
    concepts?: string;
    formulas?: string;
    notes?: string;
    pyqs?: string[];
    examples?: string[];
  };
}

export const BIOLOGY_LAB_CONTENT: Record<string, BiologyLabContent> = ${JSON.stringify(
    labs.reduce((acc, lab) => {
      acc[lab.id] = lab;
      return acc;
    }, {} as Record<string, LabEntry>),
    null,
    2
  )};

export const BIOLOGY_LAB_IDS = Object.keys(BIOLOGY_LAB_CONTENT);

export function getLabContent(id: string): BiologyLabContent | undefined {
  return BIOLOGY_LAB_CONTENT[id];
}
`;
}

function main() {
  console.log("Scanning content directory:", CONTENT_ROOT);
  
  if (!require("fs").existsSync(CONTENT_ROOT)) {
    console.log("Content directory not found. Creating empty mapping.");
    const empty = generateTypeScript([]);
    writeFileSync(OUTPUT_FILE, empty);
    console.log("Generated empty mapping at", OUTPUT_FILE);
    return;
  }

  const files = scanContentDir(CONTENT_ROOT);
  console.log(`Found ${files.length} JSON files`);

  const labs = extractBiologyContent(files);
  console.log(`Extracted ${labs.length} biology lab entries`);

  const output = generateTypeScript(labs);
  writeFileSync(OUTPUT_FILE, output);
  console.log(`Written to ${OUTPUT_FILE}`);
  
  // Summary
  const byUnit: Record<string, number> = {};
  for (const lab of labs) {
    byUnit[lab.unitSlug] = (byUnit[lab.unitSlug] || 0) + 1;
  }
  console.log("\nContent by unit:");
  for (const [unit, count] of Object.entries(byUnit)) {
    console.log(`  ${unit}: ${count} files`);
  }
}

main();
