/**
 * Lab Studios — D: the remaining multi-scene suites, simulators and
 * symbol boards. These labs are themselves suites of many scenes, so each
 * studio spec covers the suite's *core* visual idea — the one idea every
 * scene inside shares — rather than duplicating every scene.
 */

import type { StudioSpec } from "./types";

export const SUITES: Record<string, StudioSpec> = {
  /* ── Physics suites & sims ── */
  "ph-3d-advanced": {
    studio: "Advanced physics — relativity and the nucleus",
    blurb: "Time dilation between two observers, and a nucleus balancing its protons and neutrons: the two ideas the advanced suite keeps returning to.",
    defaultView: "relativity",
    parts: [
      {
        shape: { kind: "box", size: [3.4, 2.2, 2.2] },
        at: [-3.6, 0, 0],
        material: "glass",
        color: 0x38bdf8,
        opacity: 0.3,
        motion: { kind: "flow", from: [-5.6, 0, 0], to: [2.6, 0, 0], speed: 0.5, count: 2 },
        views: ["relativity"],
        label: { text: "Moving frame (spaceship)", sub: "its clock runs slow: Δt = Δt₀/√(1 − v²/c²)", at: [-3.6, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "box", size: [2.6, 1.6, 1.6] },
        at: [3.6, 0, 0],
        material: "metal",
        color: 0x64748b,
        views: ["relativity"],
        label: { text: "Rest frame (laboratory)", sub: "the observer whose clock defines Δt₀", at: [3.6, 3.0, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [-3.6, 0, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["relativity"],
        label: { text: "Light clock", sub: "the thought experiment that forces the result", at: [-1.0, -3.0, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 1.1, noise: 0.12 },
        at: [0, 0, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["nuclear"],
        label: { text: "Nucleus", sub: "Z protons (+) repelling, A−Z neutrons holding", at: [-3.8, 3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [1.4, 0.6, 0],
        material: "metal",
        color: 0xf97316,
        repeat: { count: 5, spread: [1.0, 0.8, 0.8] },
        views: ["nuclear"],
        label: { text: "Protons", sub: "electrostatic repulsion tries to tear the nucleus apart", at: [3.4, 2.6, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "sphere", r: 0.24 },
        at: [-1.4, -0.6, 0],
        material: "metal",
        color: 0x22d3ee,
        repeat: { count: 6, spread: [1.2, 0.9, 0.8] },
        views: ["nuclear"],
        label: { text: "Neutrons", sub: "add strong-force glue without adding repulsion", at: [-2.4, -3.0, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "torus", r: 1.8, tube: 0.05 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["nuclear"],
        label: { text: "Binding energy per nucleon", sub: "peaks near iron — why fusion and fission split there", at: [0, -3.6, 0], color: "#4ade80" },
      },
    ],
    views: [
      {
        id: "relativity",
        label: "Relativity",
        hint: "Two frames, one speed of light.",
        rows: [
          { name: "Time dilation", fn: "A moving clock runs slow by the Lorentz factor γ.", why: "The formula and γ = 1/√(1 − v²/c²) are asked directly." },
          { name: "Postulates", fn: "Same light speed in all inertial frames; physics is identical in them.", why: "Everything follows from these two statements." },
          { name: "Length contraction", fn: "Moving objects are shortened along their motion by 1/γ.", why: "The paired consequence of time dilation." },
          { name: "Mass–energy", fn: "E = mc² links rest mass to energy.", why: "The basis of all nuclear-energy calculations." },
        ],
      },
      {
        id: "nuclear",
        label: "The nucleus",
        hint: "Why heavy nuclei need neutrons.",
        shell: "ghost",
        rows: [
          { name: "Forces in balance", fn: "Strong nuclear attraction against proton–proton repulsion.", why: "The stability argument for the neutron/proton ratio." },
          { name: "Binding energy", fn: "Δm c² from the mass defect.", why: "The standard numerical on nuclear stability." },
          { name: "Fission & fusion", fn: "Both move nuclei toward iron's binding-energy peak.", why: "Why energy is released on both sides of iron." },
        ],
      },
    ],
    theory: {
      look: "A translucent blue spaceship gliding past a grey laboratory block with a yellow light clock inside, and beside it a red lumpy nucleus carrying orange protons and cyan neutrons inside a green binding-energy ring.",
      principle: "Special relativity rests on two postulates — the speed of light is the same in every inertial frame, and the laws of physics are identical in all of them — forcing moving clocks to run slow (Δt = γΔt₀) and moving lengths to contract by 1/γ, with E = mc² linking mass to energy. In the nucleus the strong force binds nucleons against proton–proton repulsion; the binding energy per nucleon, Δm c², peaks near iron, which is why both fusion of light nuclei and fission of heavy ones release energy.",
      why: "The two postulates, time dilation and length contraction with γ, mass–energy equivalence, and the binding-energy peak are the recurring marks.",
    },
  },

  "ph-3d-classic": {
    studio: "Classic mechanics bench — the foundation set-up",
    blurb: "Block, pulley and inclined plane: the three set-ups every mechanics numerical is written on, each with its standard equations attached.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "plane", w: 12, h: 5 },
        at: [0, -1.6, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["external", "incline"],
      },
      {
        shape: { kind: "box", size: [2.2, 1.2, 1.2] },
        at: [-2.6, -0.4, 0],
        material: "metal",
        color: 0x64748b,
        motion: { kind: "flow", from: [-4.6, -0.4, 0], to: [2.6, -0.4, 0], speed: 0.35, count: 2 },
        views: ["external", "incline"],
        label: { text: "Block on a surface", sub: "N = mg cos θ · f = μN · a = F(net)/m", at: [-2.6, 2.6, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "torus", r: 0.8, tube: 0.12 },
        at: [3.6, 1.8, 0],
        material: "metal",
        color: 0xb45309,
        motion: { kind: "spin", axis: "y", speed: 1.6 },
        views: ["external", "pulley"],
        label: { text: "Pulley (ideal: massless, frictionless)", sub: "same tension on both sides", at: [5.2, 3.6, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "tube", points: [[-2.6, 0.2, 0], [3.6, 1.0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["pulley"],
        label: { text: "String — constant tension", sub: "a = (m₂ − m₁)g / (m₁ + m₂) for Atwood's machine", at: [0.2, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "cone", r: 2.2, h: 0.01 },
        at: [3.6, 1.8, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0x94a3b8,
        views: ["incline"],
        label: { text: "Inclined plane at θ", sub: "resolve along and down the slope — then apply F = ma", at: [3.6, -3.4, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "sphere", r: 0.4 },
        at: [0.4, 2.8, 0],
        material: "organ",
        color: 0xef4444,
        views: ["projectile"],
        motion: { kind: "flow", from: [-2.0, 1.2, 0], to: [4.4, 0.6, 0], speed: 0.4, count: 3 },
        label: { text: "Projectile", sub: "independent horizontal and vertical motions", at: [0.4, 4.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[-2.0, 1.0, 0], [-1.0, 2.4, 0], [0.4, 3.0, 0], [2.2, 2.8, 0], [4.4, 1.4, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["projectile"],
        label: { text: "Parabolic path", sub: "R = u² sin 2θ/g · H = u² sin²θ/2g · T = 2u sin θ/g", at: [0.4, 4.2, 0], color: "#4ade80" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Bench (real)",
        hint: "The three classic set-ups together.",
        rows: [
          { name: "Free-body diagram", fn: "One diagram per body, forces only.", why: "The universal first step that earns method marks." },
          { name: "Choosing axes", fn: "Align axes with the motion, not the page.", why: "Correct axis choice halves the algebra." },
        ],
      },
      {
        id: "pulley",
        label: "Pulleys & strings",
        hint: "Atwood's machine and tension.",
        shell: "ghost",
        rows: [
          { name: "Ideal string", fn: "Same tension throughout; same speed on both sides.", why: "The two constraints every pulley problem uses." },
          { name: "Atwood's machine", fn: "a = (m₂ − m₁)g/(m₁ + m₂).", why: "The standard result asked as a derivation and numerical." },
        ],
      },
      {
        id: "incline",
        label: "Inclined plane",
        hint: "Resolving along the slope.",
        shell: "ghost",
        rows: [
          { name: "Resolution", fn: "mg sin θ along the slope; mg cos θ into it.", why: "The normal force follows from the second component." },
          { name: "Friction", fn: "f = μN opposes the tendency of motion.", why: "Static versus kinetic distinction is examined." },
        ],
      },
      {
        id: "projectile",
        label: "Projectile motion",
        hint: "Two independent motions at right angles.",
        shell: "ghost",
        rows: [
          { name: "Independence", fn: "Horizontal motion is uniform; vertical is uniformly accelerated.", why: "The principle that generates all projectile formulae." },
          { name: "Standard results", fn: "T = 2u sin θ/g, H = u² sin²θ/2g, R = u² sin 2θ/g.", why: "Range is maximum at θ = 45° — the special case." },
        ],
      },
    ],
    theory: {
      look: "A grey block sliding on a dark bench toward an amber pulley hung with a blue string, a steel wedge representing the incline, and a red projectile tracing a green parabola overhead.",
      principle: "Every mechanics numerical is built on the same discipline: draw a free-body diagram for each object, choose axes aligned with the motion, and apply Newton's second law along each axis. Strings under ideal conditions carry one tension and connect the accelerations of the bodies they join, giving the Atwood result a = (m₂ − m₁)g/(m₁ + m₂). On an incline the weight resolves into mg sin θ along and mg cos θ into the surface, setting both the acceleration and the normal force. A projectile combines uniform horizontal motion with free vertical fall.",
      why: "Free-body discipline, the Atwood formula, incline resolution, and the three projectile results with the 45° maximum are the exact marks.",
    },
  },

  "advanced-circuit": {
    studio: "Advanced circuits — networks and meters",
    blurb: "A real two-loop network: Kirchhoff's rules assigning branch currents, Wheatstone bridge balance, and the potentiometer comparing emfs without drawing current.",
    defaultView: "network",
    parts: [
      {
        shape: { kind: "tube", points: [[-4, 2, 0], [4, 2, 0], [4, -2, 0], [-4, -2, 0], [-4, 2, 0]], radius: 0.06 },
        material: "metal",
        color: 0xb45309,
        views: ["network", "bridge"],
        label: { text: "Two-loop network", sub: "three branches, two independent loops", at: [0, 3.6, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "box", size: [1.2, 0.9, 0.9] },
        at: [0, 2, 0],
        material: "wood",
        color: 0x4b5563,
        views: ["network", "bridge"],
        label: { text: "R₂ (bridge branch)", sub: "current here is the unknown Kirchhoff's finds", at: [0, 4.6, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "box", size: [1.2, 0.9, 0.9] },
        at: [-4, 0, 0],
        material: "wood",
        color: 0x4b5563,
        views: ["network"],
      },
      {
        shape: { kind: "box", size: [1.2, 0.9, 0.9] },
        at: [4, 0, 0],
        material: "wood",
        color: 0x4b5563,
        views: ["network"],
      },
      {
        shape: { kind: "torus", r: 0.7, tube: 0.1 },
        at: [-4, 2, 0],
        material: "metal",
        color: 0x1d4ed8,
        views: ["network"],
        label: { text: "Ammeters in each branch", sub: "one per branch — three unknowns, three equations", at: [-6.0, 4.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "torus", r: 0.9, tube: 0.12 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "metal",
        color: 0xfacc15,
        views: ["bridge"],
        label: { text: "Wheatstone bridge", sub: "balanced when P/Q = R/S — galvanometer reads zero", at: [0, -3.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "cylinder", r1: 0.14, h: 7 },
        at: [0, 0, 2.2],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0x94a3b8,
        views: ["potentiometer"],
        label: { text: "Potentiometer wire", sub: "uniform — potential drop per unit length is constant", at: [0, 3.2, 2.2], color: "#cbd5e1" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.05 },
        at: [-2.4, 0, 2.2],
        material: "emissive",
        color: 0x22c55e,
        views: ["potentiometer"],
        label: { text: "Null point", sub: "no current through the galvanometer — true emf comparison", at: [-4.4, 2.6, 2.2], color: "#4ade80" },
      },
    ],
    views: [
      {
        id: "network",
        label: "Kirchhoff networks",
        hint: "Loops and junctions on a real circuit.",
        rows: [
          { name: "Junction rule", fn: "ΣI = 0 at every node.", why: "Charge conservation — the first equation of every solution." },
          { name: "Loop rule", fn: "ΣΔV = 0 round every closed loop.", why: "Energy conservation — the remaining equations." },
          { name: "Sign discipline", fn: "Fix directions, keep them, trust the algebra's negatives.", why: "Most lost marks are sign errors, not physics errors." },
        ],
      },
      {
        id: "bridge",
        label: "Wheatstone bridge",
        hint: "Four resistors and a null detector.",
        shell: "ghost",
        rows: [
          { name: "Balance condition", fn: "P/Q = R/S.", why: "Unknown resistance from three known ones." },
          { name: "Null method", fn: "Balance needs no calibration — the reading is a zero.", why: "Why null methods are inherently accurate." },
          { name: "Meter bridge", fn: "The same idea on a uniform wire with a sliding contact.", why: "The practical form asked in numericals." },
        ],
      },
      {
        id: "potentiometer",
        label: "Potentiometer",
        hint: "Comparing emfs without loading the cell.",
        shell: "ghost",
        rows: [
          { name: "Principle", fn: "Potential drop along a uniform wire is proportional to length.", why: "The one-line principle everything rests on." },
          { name: "Null point", fn: "Zero galvanometer current means the measured emf is undistorted.", why: "Why it beats a voltmeter for emf." },
          { name: "Comparison", fn: "ε₁/ε₂ = l₁/l₂ at the two null points.", why: "The standard numerical." },
        ],
      },
    ],
    theory: {
      look: "An amber wire rectangle carrying grey resistor boxes and a blue ring ammeter, a yellow bridge ring at its heart, and behind them a long silver potentiometer wire with a green null-point glow.",
      principle: "Any circuit network is solved by Kirchhoff's two rules: currents sum to zero at every junction (charge conservation) and potential changes sum to zero round every loop (energy conservation) — enough equations for every unknown branch current, provided sign conventions are held consistently. A balanced Wheatstone bridge P/Q = R/S passes no current through its galvanometer, turning resistance measurement into a null method; the potentiometer applies the same null idea along a uniform wire, where drop is proportional to length, to compare emfs without drawing current from the cells.",
      why: "The two Kirchhoff statements with sign discipline, the balance condition, and the null-method principle are the recurring marks.",
    },
  },

  /* ── Simulators ── */
  "ph-sim-gravity": {
    studio: "Gravity sim — projectiles and orbits from one law",
    blurb: "The same inverse-square law drawing a cannonball's parabola and holding a satellite's ellipse: only the launch speed differs.",
    defaultView: "orbits",
    parts: [
      {
        shape: { kind: "sphere", r: 1.6, noise: 0.04 },
        at: [0, 0, 0],
        material: "organ",
        color: 0x2563eb,
        views: ["orbits", "projectile"],
        label: { text: "Central body", sub: "F = GMm/r² — the same law for both paths", at: [-4.2, 3.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 0.25 },
        at: [4.6, 0, 0],
        material: "metal",
        color: 0xe2e8f0,
        motion: { kind: "spin", axis: "y", speed: 2.4 },
        views: ["orbits"],
        label: { text: "Orbiting body", sub: "falling forever and always missing", at: [4.6, 2.8, 0], color: "#e2e8f0" },
      },
      {
        shape: { kind: "torus", r: 4.6, tube: 0.03 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["orbits"],
        label: { text: "Circular orbit: v = √(GM/r)", sub: "T² ∝ r³ — Kepler's third", at: [-4.2, -3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [-2.6, 2.2, 0],
        material: "organ",
        color: 0xef4444,
        motion: { kind: "flow", from: [-4.4, 0.6, 0], to: [3.2, -0.4, 0], speed: 0.4, count: 3 },
        views: ["projectile"],
        label: { text: "Projectile", sub: "path curves only because gravity keeps pulling", at: [-1.0, 4.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[-4.4, 0.4, 0], [-2.6, 2.6, 0], [0, 3.2, 0], [2.6, 2.4, 0], [4.6, 0.2, 0]], radius: 0.04 },
        material: "emissive",
        color: 0xfacc15,
        views: ["projectile"],
        label: { text: "Faster launch → flatter fall → orbit", sub: "8 km/s closes the curve", at: [0, 4.6, 0], color: "#fde047" },
      },
    ],
    views: [
      {
        id: "orbits",
        label: "Orbits",
        hint: "Circular motion under gravity.",
        rows: [
          { name: "Orbital speed", fn: "v = √(GM/r) — faster when closer.", why: "Substituting into mv²/r = GMm/r² is the expected derivation." },
          { name: "Kepler's laws", fn: "Elliptical paths, equal areas in equal times, T² ∝ r³.", why: "All three follow from the one inverse-square law." },
          { name: "Escape speed", fn: "v_e = √(2GM/R) — √2 times the circular-orbit speed.", why: "The comparison is asked directly." },
        ],
      },
      {
        id: "projectile",
        label: "Projectiles",
        hint: "The same gravity, shorter timescales.",
        shell: "ghost",
        rows: [
          { name: "One law, two paths", fn: "A projectile is an orbit that hits the ground first.", why: "The unifying insight this studio exists for." },
          { name: "Weightlessness", fn: "Orbiting bodies are in continuous free fall.", why: "Why astronauts float — a conceptual favourite." },
          { name: "g variation", fn: "Falls with height and depth from its surface value.", why: "The standard two-case numerical." },
        ],
      },
    ],
    theory: {
      look: "A blue planet with a silver moon on a green circular orbit ring, and a red projectile arcing along a yellow path that, at higher speed, would close into that same orbit.",
      principle: "Newton's law F = GMm/r² explains both the parabola of a cannonball and the ellipse of a satellite — the only difference is launch speed. Setting gravity as the centripetal force gives the orbital speed v = √(GM/r) and Kepler's T² ∝ r³; multiplying the launch speed by √2 gives escape. An orbiting body is simply falling continuously around its planet, which is why its occupants feel weightless.",
      why: "The orbital-speed derivation, Kepler's third, escape speed with its √2 factor, and the free-fall explanation of weightlessness are the exact marks.",
    },
  },

  "ph-sim-bounce": {
    studio: "Bounce sim — restitution in action",
    blurb: "A ball losing height on every bounce: the coefficient of restitution visible in the ratio of successive heights, and energy quietly leaving the system.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.03 },
        at: [0, 1.6, 0],
        material: "organ",
        color: 0xf97316,
        motion: { kind: "pulse", amount: 0.25, speed: 1.2 },
        views: ["external", "restitution"],
        label: { text: "Bouncing ball", sub: "e = speed after / speed before at the surface", at: [-3.8, 3.6, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "box", size: [12, 0.5, 4] },
        at: [0, -2.0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["external", "restitution"],
        label: { text: "Floor", sub: "deforms slightly — the lost energy becomes heat and sound", at: [3.6, -3.4, 0], color: "#475569" },
      },
      {
        shape: { kind: "tube", points: [[0, 3.4, 0], [0, 1.2, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["restitution"],
        label: { text: "h₁ → e²h₁ → e⁴h₁…", sub: "heights shrink geometrically — the examinable result", at: [2.8, 2.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[-5.4, -2.2, 0], [-4.4, 0.8, 0], [-3.2, -2.2, 0], [-2.4, 0.2, 0], [-1.8, -2.2, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["restitution"],
        label: { text: "Total distance", sub: "h(1+e²)/(1−e²) — a converging series", at: [-4.6, 1.6, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The bounce",
        hint: "Drop, deform, rebound lower.",
        rows: [
          { name: "Collision with a surface", fn: "Same restitution rule as body–body collisions.", why: "Connects to the momentum chapter directly." },
          { name: "Energy ledger", fn: "Each bounce converts a fraction e² of KE to heat and sound.", why: "The missing energy is never destroyed — only moved." },
        ],
      },
      {
        id: "restitution",
        label: "Restitution",
        hint: "e measured from heights.",
        shell: "ghost",
        rows: [
          { name: "Definition", fn: "e = v(after)/v(before) for the bounce.", why: "The ratio definition must be stated exactly." },
          { name: "Height ratio", fn: "h₂/h₁ = e², so e = √(h₂/h₁).", why: "The standard practical: measure e from a drop test." },
          { name: "Series result", fn: "Total distance = h(1+e²)/(1−e²); total time likewise converges.", why: "The classic limiting-sum numerical." },
        ],
      },
    ],
    theory: {
      look: "An orange ball caught mid-bounce above a dark floor, a green height ladder shrinking by e² each step, and a blue zig-zag trace of the complete bouncing path.",
      principle: "At every bounce the coefficient of restitution e — the ratio of separation to approach speed — decides how much vertical speed survives, so each rebound height is e² times the previous one. The bounce heights form a geometric sequence, and summing the infinite series gives the total distance h(1+e²)/(1−e²) and total time; the energy 'lost' each impact reappears as heat and sound in the deformed surfaces.",
      why: "The e² height ratio, the experimental determination of e, and the convergent-series totals are the recurring marks.",
    },
  },

  "ph-sim-acceleration": {
    studio: "Acceleration sim — reading motion graphs live",
    blurb: "One cart, three graphs: position, velocity and acceleration generated together, so a steeper s–t line is instantly a larger v–t value.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [2.0, 1.0, 1.0] },
        at: [-2.6, 0.6, 0],
        material: "metal",
        color: 0x64748b,
        motion: { kind: "flow", from: [-5.0, 0.6, 0], to: [5.0, 0.6, 0], speed: 0.45, count: 2 },
        views: ["external", "graphs"],
        label: { text: "Cart", sub: "one object, three linked graphs", at: [-2.6, 3.0, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "plane", w: 13, h: 4 },
        at: [0, -0.6, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["external", "graphs"],
        label: { text: "Track", sub: "uniform a = 2 m/s² from rest", at: [0, -2.8, 0], color: "#475569" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [-3.4, 3.4, -1.4],
        material: "emissive",
        color: 0x38bdf8,
        views: ["graphs"],
        label: { text: "s–t: parabola", sub: "curving upward means positive acceleration", at: [-3.4, 5.2, -1.4], color: "#7dd3fc" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [0, 3.4, -1.4],
        material: "emissive",
        color: 0x22c55e,
        views: ["graphs"],
        label: { text: "v–t: straight line", sub: "its slope IS the acceleration", at: [0, 5.2, -1.4], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [3.4, 3.4, -1.4],
        material: "emissive",
        color: 0xfacc15,
        views: ["graphs"],
        label: { text: "a–t: horizontal line", sub: "constant acceleration is flat", at: [3.4, 5.2, -1.4], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-1.2, -1.4, 1.4], [3.2, -1.4, 1.4]], radius: 0.03 },
        material: "emissive",
        color: 0xf472b6,
        views: ["graphs"],
        label: { text: "Area under v–t = displacement", sub: "the graph-to-motion bridge", at: [1.0, -3.0, 1.4], color: "#f9a8d4" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The cart",
        hint: "Uniformly accelerated motion.",
        rows: [
          { name: "Acceleration", fn: "The rate of change of velocity.", why: "Definition before formula — the opening mark." },
          { name: "From rest", fn: "u = 0 simplifies all three equations of motion.", why: "Half the numericals set u = 0 without saying so." },
        ],
      },
      {
        id: "graphs",
        label: "Motion graphs",
        hint: "The three graphs and their links.",
        shell: "ghost",
        rows: [
          { name: "Slope reading", fn: "Slope of s–t is v; slope of v–t is a.", why: "The two slope rules answer most graph questions." },
          { name: "Area reading", fn: "Area under v–t is displacement.", why: "Turns graph questions into geometry questions." },
          { name: "Shape recognition", fn: "Parabola, line and flat line always occur together.", why: "Identifying uniform acceleration from shapes is the skill tested." },
        ],
      },
    ],
    theory: {
      look: "A grey cart rolling along a dark track under three glowing panels — a blue upward-curving parabola, a green straight line and a yellow flat line — joined by a pink baseline marking the area under the velocity graph.",
      principle: "For uniformly accelerated motion the three graphs are linked: the slope of the position–time graph is velocity, the slope of the velocity–time graph is acceleration, and the area under the velocity–time graph is displacement. Uniform acceleration therefore appears simultaneously as an upward-curving parabola in s–t, a straight line in v–t and a horizontal line in a–t, and the equations of motion are just the algebraic form of those graphical facts.",
      why: "The slope and area rules, and identifying the motion from graph shapes, are exactly what graph questions reward.",
    },
  },

  "ph-sim-threebody": {
    studio: "Three-body sim — why prediction has limits",
    blurb: "Two bodies dance on an exact ellipse; add a third and the long-term future becomes incalculable — chaos made visible.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 1.0, noise: 0.05 },
        at: [-2.0, 0, 0],
        material: "organ",
        color: 0xf59e0b,
        views: ["external", "chaos"],
        label: { text: "Star A", sub: "pulls on every other body at once", at: [-4.6, 3.0, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.05 },
        at: [2.4, 0.8, 0],
        material: "organ",
        color: 0xef4444,
        views: ["external", "chaos"],
        label: { text: "Star B", sub: "with two bodies the orbits stay predictable", at: [4.4, 2.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "torus", r: 3.2, tube: 0.04 },
        at: [-0.4, 0.4, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["external"],
        label: { text: "Two-body orbit — closed and stable", sub: "an exact ellipse forever", at: [-0.4, -3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.06 },
        at: [0.4, -0.6, 1.2],
        material: "metal",
        color: 0x38bdf8,
        views: ["chaos"],
        label: { text: "Third body", sub: "no closed-form solution exists for three", at: [0.4, -3.2, 1.2], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-3.0, 1.6, 1.2], [-1.4, -0.8, 1.2], [0.6, 1.8, 1.2], [2.6, -1.2, 1.2], [3.8, 0.6, 1.2]], radius: 0.035 },
        material: "emissive",
        color: 0xa855f7,
        views: ["chaos"],
        label: { text: "Sensitive dependence", sub: "tiny changes grow — numerical methods only", at: [2.0, 3.4, 1.2], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Two bodies",
        hint: "The solvable case.",
        rows: [
          { name: "Two-body problem", fn: "Reduces to one body orbiting a fixed centre — Kepler's ellipses.", why: "The reduction is the standard derivation route." },
          { name: "Closed orbits", fn: "The same ellipse repeats forever.", why: "Predictability is the benchmark chaos is measured against." },
        ],
      },
      {
        id: "chaos",
        label: "Three bodies",
        hint: "The unsolvable case.",
        shell: "ghost",
        rows: [
          { name: "No general solution", fn: "Three mutually attracting bodies have no closed-form orbit.", why: "A famous result — naming it earns the mark." },
          { name: "Chaos", fn: "Small changes in initial conditions grow exponentially.", why: "Why long-range prediction fails even with perfect laws." },
          { name: "Numerical stepwise", fn: "Compute position by position, updating all forces each step.", why: "How the simulator itself works." },
        ],
      },
    ],
    theory: {
      look: "An amber star and a red star locked on a green elliptical ring, and a small blue third body threading a wild violet path that never repeats.",
      principle: "Two bodies under mutual gravity follow exact, repeating ellipses because the problem reduces to one body orbiting a fixed centre. Adding a third destroys the reduction: no general closed-form solution exists, and the motion shows sensitive dependence on initial conditions — chaos — so predictions must be computed numerically step by step, each small error growing with time.",
      why: "The two-body reduction, the non-existence result for three bodies, and sensitive dependence as the definition of chaos are the exact marks.",
    },
  },

  "ph-sim-double-pendulum": {
    studio: "Double pendulum — simple rules, wild motion",
    blurb: "Two connected bobs: each swing obeys exactly F = ma, yet the combined path never repeats — the classic demonstration of deterministic chaos.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cylinder", r1: 0.3, h: 0.4 },
        at: [0, 3.4, 0],
        material: "metal",
        color: 0x64748b,
        views: ["external", "chaos"],
        label: { text: "Fixed pivot", sub: "the only constrained point", at: [-3.4, 4.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "tube", points: [[0, 3.2, 0], [1.6, 1.6, 0]], radius: 0.04 },
        material: "metal",
        color: 0xb45309,
        views: ["external", "chaos"],
        label: { text: "Rod 1 — length L₁", sub: "θ₁ measured from the vertical", at: [3.0, 3.0, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.04 },
        at: [1.6, 1.6, 0],
        material: "organ",
        color: 0xef4444,
        views: ["external", "chaos"],
        label: { text: "Bob m₁", sub: "its position depends on θ₁ alone", at: [3.6, 1.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[1.6, 1.6, 0], [0.2, -0.4, 0]], radius: 0.04 },
        material: "metal",
        color: 0xb45309,
        views: ["external", "chaos"],
        label: { text: "Rod 2 — length L₂", sub: "θ₂ measured from rod 1", at: [0.6, -2.0, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.04 },
        at: [0.2, -0.4, 0],
        material: "organ",
        color: 0x3b82f6,
        views: ["external", "chaos"],
        label: { text: "Bob m₂", sub: "depends on both angles — the coupling that creates chaos", at: [-2.8, -1.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[0.2, -0.6, 0], [1.2, -1.4, 0], [0.6, -2.4, 0], [1.8, -2.8, 0], [1.0, -3.6, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xa855f7,
        views: ["chaos"],
        label: { text: "Path of m₂", sub: "never repeats, never escapes — strange but bounded", at: [3.6, -3.6, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The pendulum",
        hint: "Two rods, two bobs, two angles.",
        rows: [
          { name: "Two coordinates", fn: "θ₁ and θ₂ locate the whole system.", why: "Two degrees of freedom is all chaos needs." },
          { name: "Coupling", fn: "The second bob's motion disturbs the first.", why: "The coupling is what makes the equations nonlinear." },
          { name: "Energy", fn: "KE + PE stays constant — energy is not the mystery here.", why: "Chaos is about predictability, not energy loss." },
        ],
      },
      {
        id: "chaos",
        label: "Chaos",
        hint: "Deterministic yet unpredictable.",
        shell: "ghost",
        rows: [
          { name: "Deterministic chaos", fn: "Exact equations, unpredictable long-term behaviour.", why: "The definition must include both halves." },
          { name: "Small differences grow", fn: "Two nearly identical starts diverge quickly.", why: "Sensitive dependence demonstrated, not just stated." },
          { name: "Single pendulum contrast", fn: "One rod is periodic and perfectly predictable (for small swings).", why: "The comparison that isolates what changed." },
        ],
      },
    ],
    theory: {
      look: "A grey ceiling pivot holding two amber rods: a red bob on the first, a blue bob on the second, with a violet ribbon tracing the lower bob's tangled but bounded path.",
      principle: "A double pendulum has two degrees of freedom, θ₁ and θ₂, and the coupling between them makes the equations of motion nonlinear. Although the system is fully deterministic and conserves energy exactly, its long-term behaviour is unpredictable: trajectories that begin almost identically separate exponentially fast — deterministic chaos. A single pendulum, by contrast, is periodic and predictable, which is what makes the double version the standard demonstration that complexity needs only simple rules.",
      why: "Degrees of freedom, nonlinear coupling, the two halves of the chaos definition, and the single-pendulum contrast are the exact marks.",
    },
  },

  "ph-sim-pi-collisions": {
    studio: "π collisions — digits falling out of momentum conservation",
    blurb: "A small block between a wall and a heavy one: the number of clicks it makes encodes 3, 31, 314, 3141… from nothing but mass ratios and elastic collisions.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [0.3, 6, 4] },
        at: [-5.6, 0, 0],
        material: "metal",
        color: 0x475569,
        views: ["external", "digits"],
        label: { text: "Wall", sub: "reverses the small block perfectly — elastic too", at: [-5.6, 4.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "box", size: [1.6, 1.6, 1.6] },
        at: [-2.4, 0.8, 0],
        material: "metal",
        color: 0x38bdf8,
        motion: { kind: "flow", from: [-3.4, 0.8, 0], to: [0.4, 0.8, 0], speed: 0.9, count: 2 },
        views: ["external", "digits"],
        label: { text: "Small block m", sub: "shuttles back and forth — each impact is one 'click'", at: [-2.4, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "box", size: [3.0, 3.0, 3.0] },
        at: [2.8, 0, 0],
        material: "organ",
        color: 0xf59e0b,
        views: ["external", "digits"],
        label: { text: "Large block 100ⁿm", sub: "mass ratio 1 : 100ⁿ gives 314… (n digits of π)", at: [3.4, 3.8, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[-4.6, -2.6, 0], [4.6, -2.6, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["digits"],
        label: { text: "Count the collisions", sub: "1:1 → 3 · 1:100 → 31 · 1:10000 → 314 · 1:10⁶ → 3141", at: [0, -4.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 12, h: 4 },
        at: [0, -4.2, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["external", "digits"],
      },
    ],
    views: [
      {
        id: "external",
        label: "The set-up",
        hint: "Two blocks and a wall, all collisions perfectly elastic.",
        rows: [
          { name: "Perfectly elastic", fn: "Both momentum and kinetic energy conserved at every impact.", why: "The two conservation laws are the entire engine." },
          { name: "The wall", fn: "Reverses the small block's velocity without losing energy.", why: "Turns the track into a closed loop of collisions." },
        ],
      },
      {
        id: "digits",
        label: "The surprise",
        hint: "Collision counts spelling π's digits.",
        shell: "ghost",
        rows: [
          { name: "Counting clicks", fn: "Mass ratio 1:100ⁿ yields the first n+1 digits of π.", why: "The astonishing result that makes this sim famous." },
          { name: "Why it works", fn: "Energy and momentum conservation define an angle whose bisection generates the digits.", why: "A hidden rotation links classical mechanics to π." },
          { name: "Special case check", fn: "Equal masses: exactly 3 collisions (3.14… truncated).", why: "The sanity check examiners love." },
        ],
      },
    ],
    theory: {
      look: "A grey wall on the left, a small blue block shuttling toward a large amber block, and a green tally line beneath counting the clicks.",
      principle: "Set a small block of mass m moving toward a stationary block of mass 100ⁿm, with a wall behind the small block, and make every collision perfectly elastic. Momentum and kinetic energy conservation then determine every exchange, and the total number of collisions before the blocks separate equals the first n+1 digits of π: three for equal masses, thirty-one for a hundredfold ratio, and so on — a hidden rotational structure connecting elementary mechanics to the digits of π.",
      why: "The dual conservation setup, the collision-count result, and the equal-mass sanity check are the marks this studio makes memorable.",
    },
  },

  /* ── Symbol boards ── */
  "ph-symbols-atomic": {
    studio: "Atomic symbols board — every letter in its place",
    blurb: "A real atom with each symbol pinned to the structure it names: Z, N, A, isotopes and the notation that carries them.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.1 },
        at: [0, 0, 0],
        material: "organ",
        color: 0xef4444,
        views: ["external", "notation"],
        label: { text: "Nucleus: Z protons, N neutrons", sub: "A = Z + N — the mass number", at: [-4.2, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.14 },
        at: [2.6, 0, 0],
        material: "emissive",
        color: 0x38bdf8,
        repeat: { ring: 1, radius: 2.6 },
        views: ["external", "notation"],
        motion: { kind: "spin", axis: "y", speed: 1.8 },
        label: { text: "Z electrons (neutral atom)", sub: "Z is the atomic number — the element's identity", at: [4.4, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.1 },
        at: [0, 0, 0],
        material: "organ",
        color: 0xf59e0b,
        opacity: 0.6,
        views: ["isotopes"],
        repeat: { count: 2, spread: [4.4, 0, 0] },
        label: { text: "Isotopes: same Z, different N", sub: "chemical behaviour identical, mass different", at: [-2.0, -3.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "plane", w: 5, h: 2.4 },
        at: [0, 3.6, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["notation"],
        label: { text: "ᴬzX notation", sub: "A top-left of X… mass; Z bottom-left… charge identity", at: [0, 5.2, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The atom",
        hint: "Nucleus and electrons.",
        rows: [
          { name: "Atomic number Z", fn: "Counts protons; identifies the element.", why: "Z, not A, defines what the atom is." },
          { name: "Mass number A", fn: "Protons + neutrons.", why: "The two numbers and their sum are asked constantly." },
          { name: "Neutrality", fn: "Electrons = protons in a neutral atom.", why: "Ions break this balance — the next question." },
        ],
      },
      {
        id: "isotopes",
        label: "Isotopes & ions",
        hint: "Same element, different mass or charge.",
        shell: "ghost",
        rows: [
          { name: "Isotopes", fn: "Same Z, different N — same chemistry, different mass.", why: "Why ¹H, ²H, ³H behave alike chemically." },
          { name: "Isobars", fn: "Same A, different Z.", why: "The companion term, frequently confused." },
          { name: "Ions", fn: "Electrons lost or gained; Z unchanged.", why: "Charge comes from electrons, never protons." },
        ],
      },
      {
        id: "notation",
        label: "Notation",
        hint: "Reading and writing nuclide symbols.",
        shell: "ghost",
        rows: [
          { name: "ᴬzX", fn: "A as superscript, Z as subscript, X the symbol.", why: "Writing it correctly is itself a mark." },
          { name: "Nuclear equations", fn: "Balance A and Z separately on both sides.", why: "The governing rule for all decay equations." },
        ],
      },
    ],
    theory: {
      look: "A red nucleus with orange and amber neighbours, a ring of blue electrons in orbit, and a violet panel showing the ᴬzX layout.",
      principle: "An atom's identity is its proton number Z; its mass number A is protons plus neutrons, written as ᴬzX. Atoms of the same element with different neutron counts are isotopes — chemically identical but different in mass — while isobars share A, not Z. In a neutral atom the electron count equals Z, and nuclear equations stay balanced by conserving A and Z separately on the two sides.",
      why: "Z versus A, isotope versus isobar, ion formation, and balanced nuclear notation are the exact marks.",
    },
  },

  "ph-symbols-electricity": {
    studio: "Circuit symbols board — the language of circuits",
    blurb: "Every standard symbol beside the real object it stands for: cell, resistor, meter, switch — so any drawn circuit can be read like a sentence.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [1.8, 1.2, 1.2] },
        at: [-4.4, 1.2, 0],
        material: "metal",
        color: 0x334155,
        views: ["external", "sources"],
        label: { text: "Cell / battery", sub: "long line = +, short line = −; battery = several cells", at: [-4.4, 3.4, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "box", size: [1.1, 0.8, 0.8] },
        at: [0, 1.2, 0],
        material: "wood",
        color: 0x4b5563,
        views: ["external", "sources"],
        label: { text: "Resistor / rheostat", sub: "rectangle in IEC style; zig-zag in older books", at: [0, 3.4, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "torus", r: 0.5, tube: 0.1 },
        at: [3.4, 1.2, 0],
        material: "metal",
        color: 0x1d4ed8,
        views: ["external", "meters"],
        label: { text: "Ammeter (A) — series", sub: "circle with A; voltmeter V sits in parallel", at: [3.8, 3.4, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "box", size: [0.9, 0.6, 0.4] },
        at: [-2.4, -1.4, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["external", "meters"],
        label: { text: "Switch (open/closed)", sub: "break in the line — the circuit's grammar for on/off", at: [-2.4, -3.4, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "tube", points: [[-5.6, -1.4, 0], [5.6, -1.4, 0]], radius: 0.04 },
        material: "emissive",
        color: 0xb45309,
        repeat: { count: 2, spread: [0, 0.9, 0] },
        views: ["external"],
        label: { text: "Wires — straight lines", sub: "junction = solid dot; cross without dot = no connection", at: [0.6, -3.6, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "plane", w: 6, h: 2.2 },
        at: [0, 4.6, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["meters"],
        label: { text: "V across, A in series — always", sub: "the placement rule behind every correct reading", at: [0, 6.4, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Symbols (real)",
        hint: "Each symbol next to its physical part.",
        rows: [
          { name: "Cell and battery", fn: "One cell or several in series; polarity marked by line length.", why: "Misreading polarity flips every sign that follows." },
          { name: "Wires and junctions", fn: "Straight lines; dots mark real connections.", why: "The dot rule distinguishes connected from crossing." },
        ],
      },
      {
        id: "sources",
        label: "Sources & loads",
        hint: "Where energy enters and is spent.",
        shell: "ghost",
        rows: [
          { name: "Resistor styles", fn: "Rectangle (IEC) or zig-zag (ANSI) — same meaning.", why: "Both appear across textbooks and papers." },
          { name: "Rheostat vs resistor", fn: "Arrow = variable.", why: "The arrowed symbol means adjustable." },
          { name: "Internal resistance", fn: "Drawn as r beside the cell's emf.", why: "Distinguishes ideal from real sources." },
        ],
      },
      {
        id: "meters",
        label: "Meters & controls",
        hint: "Reading instruments in place.",
        shell: "ghost",
        rows: [
          { name: "Ammeter", fn: "Series, ideally zero resistance.", why: "Placement errors short-circuit the ammeter's reading." },
          { name: "Voltmeter", fn: "Parallel, ideally infinite resistance.", why: "The paired rule — asked as a single combined question." },
          { name: "Switch", fn: "Opens or closes the loop.", why: "Series switch controls everything after it." },
        ],
      },
    ],
    theory: {
      look: "A dark cell box, a grey resistor block, a blue ring ammeter and a silver switch, all wired by amber lines under a violet banner carrying the meter-placement rule.",
      principle: "Circuit diagrams are a language: a cell's long and short lines set polarity, rectangles or zig-zags are resistors (arrowed when variable), circled letters are meters, and solid dots mark genuine junctions. Reading it correctly depends on two placement rules — ammeters in series with the element whose current they measure, voltmeters in parallel across it — because an ideal ammeter has no resistance and an ideal voltmeter has infinite resistance.",
      why: "Symbol reading, the junction-dot rule, and the series/parallel meter placement are the exact marks.",
    },
  },

  "ph-symbols-waves": {
    studio: "Wave symbols board — the vocabulary of oscillation",
    blurb: "One drawn wave with every symbol pinned to it: a, λ, T, f, and the wave equation tying them together.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "tube", points: [[-7, 0, 0], [-6, 1.4, 0], [-5, 0, 0], [-4, -1.4, 0], [-3, 0, 0], [-2, 1.4, 0], [-1, 0, 0], [0, -1.4, 0], [1, 0, 0], [2, 1.4, 0], [3, 0, 0], [4, -1.4, 0], [5, 0, 0], [6, 1.4, 0], [7, 0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        motion: { kind: "wave", amplitude: 0.3, speed: 1.5 },
        views: ["external", "symbols"],
        label: { text: "The wave itself", sub: "y = a sin(ωt − kx)", at: [-4.6, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-6, 1.6, 0], [-6, 0, 0]], radius: 0.035 },
        material: "emissive",
        color: 0xfacc15,
        views: ["symbols"],
        label: { text: "Amplitude a", sub: "crest height from the middle — decides loudness/brightness", at: [-7.2, 2.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-3, 2.0, 0], [1, 2.0, 0]], radius: 0.035 },
        material: "emissive",
        color: 0x22c55e,
        views: ["symbols"],
        label: { text: "Wavelength λ", sub: "crest-to-crest — decides colour or pitch", at: [-1.0, 3.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[2.6, -1.8, 0], [6.2, -1.8, 0]], radius: 0.035 },
        material: "emissive",
        color: 0xf97316,
        views: ["symbols"],
        label: { text: "Period T and frequency f = 1/T", sub: "one oscillation's time; set by the source", at: [4.4, -3.2, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "plane", w: 5, h: 2 },
        at: [4.8, 2.6, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["external"],
        label: { text: "v = fλ", sub: "the equation connecting all four symbols", at: [4.8, 4.4, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The wave",
        hint: "All four quantities on one curve.",
        rows: [
          { name: "Amplitude a", fn: "Maximum displacement from equilibrium.", why: "Energy carried scales as a² — the standard link." },
          { name: "Wavelength λ", fn: "Distance for one full cycle.", why: "Measured crest-to-crest or trough-to-trough." },
          { name: "Frequency f", fn: "Oscillations per second, fixed by the source.", why: "Does not change between media — the common trap." },
          { name: "Wave equation", fn: "v = fλ connects them all.", why: "The one formula every wave numerical uses." },
        ],
      },
      {
        id: "symbols",
        label: "Angular forms",
        hint: "ω and k in the full expression.",
        shell: "ghost",
        rows: [
          { name: "Angular frequency", fn: "ω = 2πf.", why: "Appears in every oscillation equation." },
          { name: "Wave number", fn: "k = 2π/λ.", why: "Pairs with ω in y = a sin(ωt − kx)." },
          { name: "Phase", fn: "The ωt − kx argument; constant phase moves at v.", why: "Phase difference questions start from this term." },
        ],
      },
    ],
    theory: {
      look: "A blue sine train with a yellow amplitude arrow at its first crest, a green wavelength bracket across one cycle, an orange period marker below, and a violet panel carrying v = fλ.",
      principle: "A sinusoidal wave is described by four quantities: amplitude a (maximum displacement, deciding energy ∝ a²), wavelength λ (one cycle's length), frequency f (cycles per second, fixed by the source and unchanged between media), and speed v, linked by v = fλ. In the full expression y = a sin(ωt − kx) the angular frequency ω = 2πf and wave number k = 2π/λ combine into a phase whose constant values move along at the wave speed.",
      why: "The four definitions, the constancy of frequency across media, the wave equation, and the ω–k–phase vocabulary are the exact marks.",
    },
  },

  "math-symbols": {
    studio: "Math symbols board — notation that carries meaning",
    blurb: "The core symbols of school mathematics laid out with what each one strictly means, where students misread them, and the notation of sets, functions and calculus.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [-4.2, 1.6, 0],
        material: "emissive",
        color: 0x38bdf8,
        views: ["external", "sets"],
        label: { text: "∈, ⊂, ∪, ∩, ∅", sub: "belongs to · subset of · union · intersection · empty set", at: [-4.2, 3.8, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [0, 1.6, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["external", "relations"],
        label: { text: "⇒, ⇔, ∴, ∵", sub: "implies · if and only if · therefore · because", at: [0, 3.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [4.2, 1.6, 0],
        material: "emissive",
        color: 0xf59e0b,
        views: ["external", "relations"],
        label: { text: "f(x), f: A → B, f⁻¹", sub: "function, its domain/codomain, its inverse", at: [4.2, 3.8, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [-4.2, -1.8, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["external", "calculus"],
        label: { text: "dy/dx, ∫, lim", sub: "rate of change · accumulation · approach", at: [-4.2, -3.8, 0], color: "#f87171" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [0, -1.8, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["external", "calculus"],
        label: { text: "Σ, n!, |x|, ≈", sub: "sum · factorial · modulus · approximately", at: [0, -3.8, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.6 },
        at: [4.2, -1.8, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["external", "calculus"],
        label: { text: "ℝ, ℤ, ℕ, ℚ", sub: "real · integer · natural · rational number sets", at: [4.2, -3.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "plane", w: 14, h: 0.3 },
        at: [0, 0.1, 0],
        material: "metal",
        color: 0x475569,
        views: ["external"],
      },
    ],
    views: [
      {
        id: "external",
        label: "All boards",
        hint: "The six families of notation.",
        rows: [
          { name: "Precision", fn: "Each symbol means one thing — no near-synonyms in mathematics.", why: "Mixing up ⇒ with ⇔ is the classic logic error." },
          { name: "Reading order", fn: "Symbols compress full sentences; unpack them aloud first.", why: "The habit that prevents misreading dense expressions." },
        ],
      },
      {
        id: "sets",
        label: "Set notation",
        hint: "Membership, containment, combination.",
        shell: "ghost",
        rows: [
          { name: "∈ versus ⊂", fn: "∈ for elements, ⊂ for subsets.", why: "The most common symbol error in set questions." },
          { name: "∪ and ∩", fn: "Union = or, intersection = and.", why: "Translating worded sets into symbols is the skill." },
          { name: "∅ and complements", fn: "Empty set and A′.", why: "Needed for De Morgan's law applications." },
        ],
      },
      {
        id: "relations",
        label: "Logic & functions",
        hint: "Implication and mappings.",
        shell: "ghost",
        rows: [
          { name: "⇒ versus ⇔", fn: "One-way implication versus equivalence.", why: "The direction matters in every proof." },
          { name: "Function notation", fn: "f: A → B with domain A.", why: "Domain questions hinge on reading this correctly." },
          { name: "Inverse f⁻¹", fn: "Undoes f, defined only when f is one-to-one.", why: "The condition is the examined part." },
        ],
      },
      {
        id: "calculus",
        label: "Calculus & numbers",
        hint: "Change, accumulation, and number sets.",
        shell: "ghost",
        rows: [
          { name: "dy/dx", fn: "The instantaneous rate of change.", why: "Not a fraction — the reading earns the mark." },
          { name: "∫ and lim", fn: "Signed area and limiting value.", why: "The two ideas calculus is built from." },
          { name: "Number sets", fn: "ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ.", why: "The containment chain decides which answers are valid." },
        ],
      },
    ],
    theory: {
      look: "Six glowing panels in a 3×2 layout — blue set symbols, green logic arrows, amber function notation, red calculus operators, violet summation symbols and yellow number-set letters — held on a dark rail.",
      principle: "Mathematical notation is a precise language. Set symbols (∈, ⊂, ∪, ∩, ∅) distinguish membership from containment and 'or' from 'and'; logical symbols separate one-way implication from equivalence; function notation f: A → B names domain, codomain and rule, with f⁻¹ existing only for one-to-one maps. Calculus notation compresses the two central ideas — rate of change (dy/dx) and accumulation (∫) — while the number-set chain ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ controls which solutions are admissible.",
      why: "The ∈/⊂ distinction, ⇒/⇔ direction, domain reading, the meaning of dy/dx, and the number-set containment chain are the exact marks.",
    },
  },
};
