/**
 * Lab Studios — Chemistry: periodic table, molecules, microscopy and the
 * syllabus/theory suites.
 */

import type { StudioSpec } from "./types";

export const CHEMISTRY: Record<string, StudioSpec> = {
  /* ── Periodic table (canonical CEE all-blocks table lives above) ── */
  "ch-3d-periodic": {
    studio: "Periodic trends studio — the table in 3D",
    blurb: "The periods and groups standing as real columns: atomic radius shrinking across a period, metallic character falling, and each block's identity explained.",
    defaultView: "trends",
    parts: [
      {
        shape: { kind: "plane", w: 13, h: 8 },
        at: [0, -2.6, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["trends", "blocks"],
      },
      {
        shape: { kind: "cylinder", r1: 0.45, h: 1.2 },
        at: [-5.4, 0.4, 0],
        material: "metal",
        color: 0xf87171,
        repeat: { count: 3, spread: [0, 0, 1.6] },
        views: ["trends"],
        label: { text: "Left: large, metallic atoms", sub: "radius falls left → right across a period", at: [-6.4, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "cylinder", r1: 0.28, h: 1.2 },
        at: [0, 0.4, 0],
        material: "metal",
        color: 0xfacc15,
        repeat: { count: 3, spread: [0, 0, 1.6] },
        views: ["trends"],
        label: { text: "Middle: shrinking radii", sub: "nuclear charge pulls the same shell in", at: [0.2, 3.2, 0], color: "#fde047" },
      },
      {
        shape: { kind: "cylinder", r1: 0.2, h: 1.2 },
        at: [5.2, 0.4, 0],
        material: "glass",
        color: 0x38bdf8,
        repeat: { count: 3, spread: [0, 0, 1.6] },
        views: ["trends"],
        label: { text: "Right: small, non-metallic", sub: "high electron gain enthalpy — they accept electrons", at: [5.8, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 1.8 },
        at: [-5.4, 0.6, -2.6],
        material: "metal",
        color: 0xa855f7,
        views: ["blocks"],
        label: { text: "s-block (groups 1–2)", sub: "last electron enters an s orbital — always metals", at: [-5.0, 3.8, -2.6], color: "#c084fc" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 1.8 },
        at: [0, 0.6, -2.6],
        material: "metal",
        color: 0xf97316,
        views: ["blocks"],
        label: { text: "p-block (groups 13–18)", sub: "metals, metalloids and non-metals all appear", at: [0.2, 3.8, -2.6], color: "#fb923c" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 1.8 },
        at: [5.2, 0.6, -2.6],
        material: "metal",
        color: 0x22c55e,
        views: ["blocks"],
        label: { text: "d-block (transition)", sub: "variable oxidation states, coloured ions", at: [5.6, 3.8, -2.6], color: "#4ade80" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 1.8 },
        at: [5.2, 0.6, 2.6],
        material: "metal",
        color: 0xef4444,
        views: ["blocks"],
        label: { text: "f-block (inner transition)", sub: "lanthanides and actinides — kept below the table", at: [5.6, -3.8, 2.6], color: "#fca5a5" },
      },
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.05 },
        at: [0, 1.6, 2.8],
        material: "emissive",
        color: 0x94a3b8,
        views: ["trends"],
        label: { text: "Noble gases", sub: "full octet — the group-18 reference point", at: [0, 4.4, 2.8], color: "#cbd5e1" },
      },
    ],
    views: [
      {
        id: "trends",
        label: "Periodic trends",
        hint: "How properties move across a period and down a group.",
        rows: [
          { name: "Atomic radius", fn: "Falls across a period (same shell, more charge); rises down a group (new shell).", why: "Both directions and their reasons are asked separately." },
          { name: "Ionisation energy", fn: "Rises across a period, falls down a group.", why: "The exception between groups 2/13 and 15/16 is a favourite mark." },
          { name: "Metallic character", fn: "Falls across, rises down; most metallic at the bottom-left.", why: "Ties electropositivity to position." },
          { name: "Electronegativity", fn: "Rises across a period; fluorine is the reference maximum.", why: "The bond-type prediction follows from it." },
        ],
      },
      {
        id: "blocks",
        label: "Blocks",
        hint: "Where the last electron lands.",
        shell: "ghost",
        rows: [
          { name: "s-block", fn: "Groups 1 and 2; soft, reactive metals.", why: "Their +1/+2 ions decide their chemistry." },
          { name: "p-block", fn: "Groups 13–18, spanning metal to noble gas.", why: "The only block with all three classes of element." },
          { name: "d-block", fn: "Transition metals with variable oxidation states and coloured compounds.", why: "Why coloured ions form is the reasoning mark." },
          { name: "f-block", fn: "Lanthanides and actinides, placed below to keep the table compact.", why: "The placement reason is a one-mark item." },
        ],
      },
    ],
    theory: {
      look: "A dark table surface carrying three rows of columns — tall red ones on the left, mid yellow ones in the middle, small blue glassy ones on the right — with four colour-coded block columns (violet, orange, green, red) marking s, p, d and f.",
      principle: "The periodic table arranges elements by atomic number so that properties recur periodically. Across a period nuclear charge rises while the shell stays the same, so radius falls, ionisation energy and electronegativity rise, and metallic character falls; down a group each new shell raises the radius and lowers the ionisation energy. The s, p, d and f blocks record which subshell receives the last electron and therefore predict the chemistry of each region.",
      why: "Trend directions with their reasons, the known exceptions, and block identity with its chemical consequences are the exact periodic-table marks.",
    },
  },

  /* ── Molecular builder ── */
  "molecular-builder": {
    studio: "Molecule builder — geometry you can rotate",
    blurb: "Real molecular models: water bent at 104.5°, methane tetrahedral, ammonia pyramidal — each shape explained by the electron pairs that surround its central atom.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.04 },
        at: [-3.6, 0.4, 0],
        material: "organ",
        color: 0xef4444,
        views: ["external", "shapes"],
        label: { text: "H₂O — bent, 104.5°", sub: "two lone pairs squeeze the bonding pairs", at: [-5.6, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [-4.4, 1.3, 0.5],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 2, spread: [1.6, -0.6, 0.4] },
        views: ["external", "shapes"],
      },
      {
        shape: { kind: "sphere", r: 0.6, noise: 0.04 },
        at: [0.2, 0.4, 0],
        material: "metal",
        color: 0x64748b,
        views: ["external", "shapes"],
        label: { text: "CH₄ — tetrahedral, 109.5°", sub: "four identical bonds repel equally", at: [0.2, 3.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [1.3, 1.2, 0.6],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 4, spread: [2.0, 1.4, 1.6] },
        views: ["external", "shapes"],
      },
      {
        shape: { kind: "sphere", r: 0.58, noise: 0.04 },
        at: [4.2, 0.4, 0],
        material: "organ",
        color: 0x3b82f6,
        views: ["external", "shapes"],
        label: { text: "NH₃ — pyramidal, 107°", sub: "one lone pair — between water and methane", at: [4.8, 3.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [5.3, 1.1, 0.4],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 3, spread: [1.6, 0.9, 1.2] },
        views: ["external", "shapes"],
      },
      {
        shape: { kind: "tube", points: [[-3.4, -2.2, 0], [-2.2, -1.6, 0], [-1.0, -2.4, 0]], radius: 0.09 },
        material: "emissive",
        color: 0x22c55e,
        views: ["bonds"],
        label: { text: "Covalent bond", sub: "shared electron pair between non-metals", at: [-1.0, -1.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.35, noise: 0.05 },
        at: [1.4, -2.2, 0],
        material: "metal",
        color: 0xfacc15,
        views: ["bonds"],
        label: { text: "Cation (+)", sub: "gives up electrons", at: [2.0, -3.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.35, noise: 0.05 },
        at: [3.2, -2.2, 0],
        material: "metal",
        color: 0x38bdf8,
        views: ["bonds"],
        label: { text: "Anion (−)", sub: "accepts them — electrovalent bond", at: [3.8, -3.8, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "plane", w: 6.5, h: 2.6 },
        at: [0.2, -4.4, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["external"],
        label: { text: "Shape follows VSEPR", sub: "electron pairs repel — lone pairs most", at: [0.2, -6.0, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Three molecules (real)",
        hint: "Water, methane and ammonia to scale.",
        rows: [
          { name: "Water", fn: "Bent at 104.5° because two lone pairs compress the bond angle.", why: "The lone-pair explanation is the whole mark." },
          { name: "Methane", fn: "Perfectly tetrahedral at 109.5° — no lone pairs.", why: "The reference angle everything else is compared to." },
          { name: "Ammonia", fn: "Pyramidal at 107° — one lone pair.", why: "Sits between the other two, which is the comparison asked." },
        ],
      },
      {
        id: "shapes",
        label: "VSEPR logic",
        hint: "Why each molecule has its shape.",
        shell: "ghost",
        rows: [
          { name: "VSEPR", fn: "Electron pairs arrange to minimise repulsion.", why: "The named theory behind every shape." },
          { name: "Repulsion order", fn: "LP–LP > LP–BP > BP–BP.", why: "This order explains every angle reduction." },
          { name: "Predicting", fn: "Count bond pairs + lone pairs on the central atom.", why: "The working procedure for unseen molecules." },
        ],
      },
      {
        id: "bonds",
        label: "Bond types",
        hint: "Ionic, covalent and the bonds between molecules.",
        shell: "ghost",
        rows: [
          { name: "Electrovalent", fn: "Complete transfer from metal to non-metal.", why: "Explains high melting points and conductivity when molten." },
          { name: "Covalent", fn: "Shared pairs between non-metals.", why: "Explains low melting points and non-conduction." },
          { name: "Hydrogen bonding", fn: "H attached to N, O or F attracts a lone pair on a neighbour.", why: "Why water boils so high and ice floats." },
        ],
      },
    ],
    theory: {
      look: "Three molecular models in a row — a red water molecule bent, a grey methane tetrahedron, a blue ammonia pyramid — with hydrogen spheres as small white shells, and below them a green covalent pair and a yellow/blue ionic pair under a violet VSEPR banner.",
      principle: "Molecular geometry follows VSEPR: electron pairs around a central atom spread to minimise repulsion, with lone pairs repelling more than bonding pairs. Water's two lone pairs squeeze its angle to 104.5°, ammonia's one gives 107°, and methane's none leaves the perfect 109.5° tetrahedron. Bonds are electrovalent when electrons transfer between metal and non-metal, and covalent when shared; hydrogen bonding between N/O/F–H groups and neighbouring lone pairs explains water's anomalously high boiling point.",
      why: "The angle sequence 104.5° < 107° < 109.5° with its lone-pair reasoning, the VSEPR procedure, and bond-type property comparisons are the recurring marks.",
    },
  },

  /* ── Micro-world ── */
  "ch-3d-micro": {
    studio: "Micro-world — ions, crystals and solutions",
    blurb: "A salt crystal dissolving: the lattice held by electrostatic force, water molecules prising it apart, and the ions that make the solution conduct.",
    defaultView: "dissolving",
    parts: [
      {
        shape: { kind: "box", size: [2.6, 2.6, 2.6] },
        at: [-2.6, 0, 0],
        material: "glass",
        color: 0xbae6fd,
        views: ["dissolving", "lattice"],
        label: { text: "NaCl crystal lattice", sub: "each Na⁺ touches six Cl⁻ — cubic close packing", at: [-4.4, 3.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.28 },
        at: [-2.0, 0.4, 0.4],
        material: "metal",
        color: 0xfacc15,
        repeat: { count: 4, spread: [1.2, 1.2, 1.2] },
        views: ["lattice"],
        label: { text: "Na⁺ (small cation)", sub: "lost one electron shell — smaller than the atom", at: [-2.0, 3.4, 1.8], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.4 },
        at: [-3.2, -0.4, -0.4],
        material: "metal",
        color: 0x22d3ee,
        repeat: { count: 4, spread: [1.2, 1.2, 1.2] },
        views: ["lattice"],
        label: { text: "Cl⁻ (large anion)", sub: "gained an electron — larger than the atom", at: [-3.8, -3.4, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "plane", w: 12, h: 0.4 },
        at: [1.4, -2.8, 0],
        material: "glass",
        color: 0x22d3ee,
        opacity: 0.35,
        views: ["dissolving"],
        label: { text: "Water — the universal solvent", sub: "polar molecules surround each ion", at: [1.4, -4.2, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.16 },
        at: [0.6, 0.6, 0],
        material: "emissive",
        color: 0x3b82f6,
        repeat: { count: 6, spread: [3.2, 1.8, 1.4] },
        views: ["dissolving"],
        label: { text: "Hydrated Na⁺", sub: "oxygen end of water faces the cation", at: [0.6, 3.4, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 0.2 },
        at: [2.4, -0.6, 0],
        material: "emissive",
        color: 0xef4444,
        repeat: { count: 6, spread: [3.0, 2.0, 1.2] },
        views: ["dissolving"],
        label: { text: "Hydrated Cl⁻", sub: "hydrogen ends face the anion", at: [3.6, -3.4, 0], color: "#f87171" },
      },
      {
        shape: { kind: "cylinder", r1: 1.5, h: 3.6 },
        at: [5.4, 0, 0],
        material: "glass",
        color: 0xe0f2fe,
        opacity: 0.4,
        views: ["solution"],
        label: { text: "Saturated solution", sub: "no more solute dissolves at this temperature", at: [6.0, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "box", size: [0.8, 0.8, 0.8] },
        at: [5.0, -2.4, 0],
        material: "glass",
        color: 0xbae6fd,
        views: ["solution"],
        label: { text: "Undissolved solute", sub: "dissolution ⇌ crystallisation equilibrium", at: [4.4, -4.2, 0], color: "#bae6fd" },
      },
    ],
    views: [
      {
        id: "dissolving",
        label: "Dissolution",
        hint: "Water pulling a lattice apart.",
        rows: [
          { name: "Hydration", fn: "Water dipoles surround and separate the ions.", why: "The energy change of hydration decides solubility." },
          { name: "Polarity", fn: "Water's dipole lets it screen charge.", why: "Why ionic compounds dissolve in water but not hexane." },
          { name: "Conductivity", fn: "Mobile ions make the solution conduct.", why: "Links dissolution to electrolysis." },
        ],
      },
      {
        id: "lattice",
        label: "Crystal lattice",
        hint: "The ordered ionic array.",
        shell: "ghost",
        rows: [
          { name: "Lattice energy", fn: "The energy to separate one mole of the crystal into gaseous ions.", why: "Its magnitude explains melting points." },
          { name: "Ion sizes", fn: "Cations are smaller, anions larger than their atoms.", why: "A routinely examined comparison." },
          { name: "Coordination", fn: "Each Na⁺ is surrounded by six Cl⁻ and vice versa.", why: "The geometry of the cubic lattice." },
        ],
      },
      {
        id: "solution",
        label: "Saturation & concentration",
        hint: "How much can dissolve, and how we count it.",
        shell: "ghost",
        rows: [
          { name: "Saturation", fn: "Dissolution and crystallisation run at equal rates.", why: "A dynamic equilibrium example from daily life." },
          { name: "Molarity", fn: "Moles of solute per litre of solution.", why: "The standard concentration unit in titration numericals." },
          { name: "Effect of temperature", fn: "Most solids dissolve more when heated.", why: "The basis of recrystallisation." },
        ],
      },
    ],
    theory: {
      look: "A translucent blue salt cube at the left edge of a wide cyan water surface, yellow and cyan ions streaming off it wrapped in blue and red water dipoles, and on the right a glass beaker holding a saturated solution with a small undissolved crystal at the bottom.",
      principle: "Ionic crystals are held by electrostatic attraction in a cubic lattice where each ion touches several of the opposite charge. Water, being polar, hydrates the ions — oxygen ends toward cations, hydrogen ends toward anions — and the balance of lattice energy against hydration energy decides whether the salt dissolves. In solution the mobile ions carry current, and at saturation dissolution and crystallisation proceed at equal rates.",
      why: "Lattice versus hydration energy, ion-size comparisons, hydration geometry, and molarity calculations are the standard marks.",
    },
  },
};
