/**
 * Lab Studios — Physics: fields, current electricity, magnetism, waves,
 * thermodynamics and the heat determinations.
 */

import type { StudioSpec } from "./types";

export const PHYSICS_EM: Record<string, StudioSpec> = {
  /* ── Electrostatics ── */
  "ph-3d-electrostatics": {
    studio: "Electrostatics — charges, field and potential",
    blurb: "Two real charges on a bench: the field lines they produce, the potential well between them, and the force on a third charge placed in the field.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.5 },
        at: [-3.2, 0, 0],
        material: "metal",
        color: 0xef4444,
        views: ["external", "field", "potential", "force"],
        label: { text: "+Q₁", sub: "source charge, positive", at: [-5.8, 2.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.5 },
        at: [3.2, 0, 0],
        material: "metal",
        color: 0x3b82f6,
        views: ["external", "field", "potential", "force"],
        label: { text: "−Q₂", sub: "source charge, negative", at: [5.8, 2.6, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "plane", w: 13, h: 7 },
        at: [0, -2.0, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["external"],
      },
      {
        shape: { kind: "tube", points: [[-3.2, 0.6, 0], [0, 1.8, 0], [3.2, 0.6, 0]], radius: 0.03 },
        material: "emissive",
        color: 0x22c55e,
        views: ["field"],
        repeat: { count: 6, spread: [0, 0.5, 2.4] },
        label: { text: "Field lines", sub: "leave +, enter −; never cross", at: [0, 4.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.2 },
        at: [0.4, 1.2, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["force"],
        label: { text: "Test charge +q", sub: "placed in the field", at: [0.4, 3.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[0.4, 1.2, 0], [-1.6, 1.6, 0]], radius: 0.05, endRadius: 0.02 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["force"],
        label: { text: "Repulsion from +Q₁", sub: "like charges repel", at: [-3.6, 3.0, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[0.4, 1.2, 0], [2.4, 0.8, 0]], radius: 0.05, endRadius: 0.02 },
        material: "emissive",
        color: 0xec4899,
        views: ["force"],
        label: { text: "Attraction to −Q₂", sub: "unlike charges attract", at: [3.6, 2.6, 0], color: "#f472b6" },
      },
      {
        shape: { kind: "plane", w: 9, h: 5 },
        at: [0, 3.0, -3.4],
        rot: [0, 0, 0],
        material: "emissive",
        color: 0x6366f1,
        views: ["potential"],
        label: { text: "V = kQ/r", sub: "a scalar — add algebraically, watch the signs", at: [0, 5.4, -3.4], color: "#a5b4fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Charges (real)",
        hint: "Two point charges fixed in position.",
        rows: [
          { name: "Point charges", fn: "Ideally zero-size; every result is written from their centres.", why: "'Point' versus 'extended' decides which formulas are valid." },
          { name: "Separation r", fn: "Measured centre to centre.", why: "The inverse-square law is meaningless without the right r." },
        ],
      },
      {
        id: "field",
        label: "Field lines",
        hint: "Direction of the force a positive test charge would feel.",
        shell: "ghost",
        rows: [
          { name: "Field lines", fn: "Run from positive to negative charge and never intersect.", why: "The no-crossing rule is a classic one-marker." },
          { name: "Coulomb's law", fn: "F = kQ₁Q₂/r² with k = 9 × 10⁹ N m² C⁻².", why: "Magnitude and the 1/r² dependence are both asked." },
          { name: "Uniform field", fn: "Parallel, equally spaced lines between two plates give E = V/d.", why: "The bridge between electrostatics and capacitors." },
        ],
      },
      {
        id: "potential",
        label: "Potential",
        hint: "The scalar companion to the field.",
        shell: "ghost",
        rows: [
          { name: "Potential", fn: "V = kQ/r, a scalar added with sign.", why: "Scalar addition is easier than the vector field — and often the intended route." },
          { name: "Relation to E", fn: "E = −dV/dr.", why: "Explains why the field is zero where the potential is flat." },
          { name: "Equipotentials", fn: "Surfaces of constant V, everywhere perpendicular to the field lines.", why: "The perpendicularity is the standard diagram question." },
        ],
      },
      {
        id: "force",
        label: "Force on a test charge",
        hint: "Direction and magnitude of the resultant.",
        shell: "ghost",
        rows: [
          { name: "Direction", fn: "Along the tangent to the field line, away from + and toward −.", why: "The sign convention decides the answer's direction." },
          { name: "Superposition", fn: "The total force is the vector sum of the individual Coulomb forces.", why: "Three-charge problems are solved only by adding components." },
        ],
      },
    ],
    theory: {
      look: "A red positive charge and a blue negative charge facing each other on a bench, with green field lines springing from one and entering the other, and a small yellow test charge carrying two labelled force vectors on the centre line.",
      principle: "Two point charges exert F = kQ₁Q₂/r² on each other along the line joining them. The field at a point is the force per unit positive charge, drawn as lines that leave positives and enter negatives and never cross. Potential is the scalar V = kQ/r; it adds algebraically, and its slope gives the field, E = −dV/dr. Equipotential surfaces are perpendicular to the field lines everywhere.",
      why: "The inverse-square form, the direction rules for positive and negative charges, scalar versus vector addition, and the E = −dV/dr link are the exact points examined.",
    },
  },

  /* ── Current electricity ── */
  "ph-3d-electricity-i": {
    studio: "Current electricity — the circuit, live",
    blurb: "A real cell with its internal resistance, an ammeter and voltmeter in their correct places, and the same loop with potentials marked so Kirchhoff's rules can be read off.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [2.6, 1.4, 1.4] },
        at: [-5, 0, 0],
        material: "metal",
        color: 0x334155,
        views: ["external", "loop", "potentials"],
        label: { text: "Cell (emf ε, r)", sub: "terminal voltage V = ε − Ir", at: [-7.2, 2.4, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "tube", points: [[-5, 0.7, 0], [5, 0.7, 0]], radius: 0.05 },
        material: "metal",
        color: 0xb45309,
        views: ["external", "loop", "potentials"],
        label: { text: "Connecting wire", sub: "assumed to have no resistance", at: [2.2, 2.2, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[5, 0.7, 0], [5, -1.2, 0], [-5, -1.2, 0], [-5, 0.7, 0]], radius: 0.05 },
        material: "metal",
        color: 0xb45309,
        views: ["external", "loop", "potentials"],
      },
      {
        shape: { kind: "box", size: [1.1, 0.8, 0.8] },
        at: [0, -1.2, 0],
        material: "wood",
        color: 0x4b5563,
        views: ["external", "loop", "potentials"],
        label: { text: "External resistor R", sub: "where the electrical energy becomes heat", at: [0.2, -3.0, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "torus", r: 0.55, tube: 0.16 },
        at: [3.2, 0.7, 0],
        material: "metal",
        color: 0x1d4ed8,
        views: ["external", "loop"],
        label: { text: "Ammeter (series)", sub: "reads the same current everywhere in a series loop", at: [4.6, 3.0, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "box", size: [0.9, 0.9, 0.6] },
        at: [-2.4, 0.7, 0.8],
        material: "metal",
        color: 0x7c3aed,
        views: ["external", "loop"],
        label: { text: "Voltmeter (parallel)", sub: "must be in parallel and have high resistance", at: [-3.6, 3.0, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "tube", points: [[-4.6, 0.7, 0], [4.6, 0.7, 0]], radius: 0.09, endRadius: 0.09 },
        material: "emissive",
        color: 0x22d3ee,
        views: ["loop"],
        motion: { kind: "flow", from: [-4.6, 0.7, 0], to: [4.6, 0.7, 0], speed: 0.35, count: 12 },
        label: { text: "Conventional current I", sub: "+ to − through the external circuit", at: [1.0, 4.0, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "box", size: [0.35, 0.2, 0.2] },
        at: [-5, 0.7, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["potentials"],
        label: { text: "Across the cell: +ε", sub: "rise in potential", at: [-7.0, -2.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "box", size: [0.35, 0.2, 0.2] },
        at: [0, -1.2, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["potentials"],
        label: { text: "Across R: −IR", sub: "fall in potential", at: [2.2, -3.6, 0], color: "#4ade80" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Circuit (real)",
        hint: "The wired loop exactly as it is built on the bench.",
        rows: [
          { name: "Cell", fn: "Supplies emf ε but has its own internal resistance r.", why: "The terminal voltage is less than the emf whenever current flows." },
          { name: "Ammeter", fn: "Connected in series; ideally zero resistance.", why: "Wrong placement (parallel) is the standard circuit error." },
          { name: "Voltmeter", fn: "Connected in parallel; ideally infinite resistance.", why: "A finite voltmeter resistance perturbs the very quantity it measures." },
        ],
      },
      {
        id: "loop",
        label: "Current flow",
        hint: "Charge carriers moving round the closed loop.",
        rows: [
          { name: "Conventional current", fn: "Taken from + to − outside the cell.", why: "Direction convention questions keep appearing." },
          { name: "Drift velocity", fn: "I = nAev_d — very small, while the signal travels near light speed.", why: "The distinction between drift and signal speed is a classic trap." },
          { name: "Terminal voltage", fn: "V = ε − Ir.", why: "Links emf to the measurable voltage." },
          { name: "Maximum power transfer", fn: "P is maximum when R = r.", why: "A frequently asked special case." },
        ],
      },
      {
        id: "potentials",
        label: "Potential changes",
        hint: "Kirchhoff's loop rule read off the model.",
        shell: "ghost",
        rows: [
          { name: "Loop rule", fn: "The algebraic sum of potential changes round any closed loop is zero.", why: "The statement must be given as a conservation law." },
          { name: "Junction rule", fn: "Current in equals current out at every junction.", why: "Charge conservation at a node." },
          { name: "Sign convention", fn: "Rise when moving − to + through a source; fall through a resistor.", why: "Sign errors here lose the whole numerical." },
        ],
      },
    ],
    theory: {
      look: "A dark cell with thick copper wires looping to a grey resistor, a blue ring ammeter in series and a violet voltmeter box across the component, with cyan current markers drifting round the loop and the potential rises and falls marked at the cell and the resistor.",
      principle: "In a closed loop charge is conserved, so the current is the same in every series element and the algebraic sum of potential changes is zero. The cell supplies ε but loses Ir inside itself, giving the terminal voltage V = ε − Ir. Electrical energy is converted to heat in the external resistance at a rate I²R, and the transfer is maximised when the external resistance equals the internal resistance.",
      why: "Meter placement, terminal voltage versus emf, the two Kirchhoff statements and their sign conventions, drift versus signal speed, and the R = r maximum-power condition are all directly examinable.",
    },
  },

  /* ── Magnetism ── */
  "ph-3d-magnetic": {
    studio: "Magnetic field — current, force and induction",
    blurb: "A straight conductor with its real circular field, a current-carrying coil on an iron core, and the force a field exerts on a moving charge.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [14, 0.3, 6] },
        at: [0, -2.2, 0],
        material: "wood",
        color: 0x6b4423,
        views: ["external", "field", "force", "solenoid"],
      },
      {
        shape: { kind: "cylinder", r1: 0.12, h: 8 },
        at: [0, 0, 0],
        material: "metal",
        color: 0xb45309,
        views: ["external", "field", "force"],
        label: { text: "Straight conductor", sub: "current I flows along it", at: [-3.4, 2.8, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "torus", r: 1.5, tube: 0.03 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22d3ee,
        views: ["field"],
        repeat: { count: 4, spread: [0, 1.8, 0] },
        label: { text: "Concentric field circles", sub: "B = μ₀I/2πr — falls with distance", at: [3.6, 3.6, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [2.6, 1.0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["force"],
        label: { text: "Moving charge +q", sub: "experiences F = qvB sin θ", at: [4.8, 2.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[2.6, 1.0, 0], [2.6, 3.0, 0]], radius: 0.05, endRadius: 0.02 },
        material: "emissive",
        color: 0xef4444,
        views: ["force"],
        label: { text: "Force F", sub: "perpendicular to both v and B", at: [4.0, 3.4, 0], color: "#f87171" },
      },
      {
        shape: { kind: "cylinder", r1: 0.9, h: 4.2 },
        at: [0, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0x475569,
        views: ["solenoid"],
        label: { text: "Iron core", sub: "concentrates the flux — becomes an electromagnet", at: [0, 3.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "torus", r: 1.1, tube: 0.09 },
        at: [0, 0, 0],
        rot: [0, Math.PI / 2, 0],
        material: "metal",
        color: 0xb45309,
        views: ["solenoid"],
        repeat: { count: 9, spread: [0, 0, 3.6] },
        label: { text: "Solenoid winding", sub: "B = μ₀nI inside — nearly uniform", at: [2.8, 3.0, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "tube", points: [[-1.2, 0, 0], [1.6, 0, 0]], radius: 0.06, endRadius: 0.02 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["solenoid"],
        label: { text: "Magnetic axis → N pole", sub: "field leaves the north end", at: [2.4, -3.0, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Conductor (real)",
        hint: "A straight current-carrying wire.",
        rows: [
          { name: "Straight conductor", fn: "Produces a field whose lines are circles centred on the wire.", why: "Shape of the field lines is asked as a diagram question." },
          { name: "Direction by right-hand grip", fn: "Thumb along the current, fingers curl with B.", why: "The rule must be named, not just used." },
        ],
      },
      {
        id: "field",
        label: "Field around a wire",
        hint: "Concentric circles, denser near the conductor.",
        shell: "ghost",
        rows: [
          { name: "Field magnitude", fn: "B = μ₀I/2πr for a long straight conductor.", why: "The 1/r dependence and μ₀'s value are both required." },
          { name: "Superposition", fn: "Fields from several wires add as vectors.", why: "The basis of force-between-parallel-wires questions." },
          { name: "Force between wires", fn: "Parallel currents attract, antiparallel repel.", why: "This is the definition of the ampere." },
        ],
      },
      {
        id: "force",
        label: "Force on a charge",
        hint: "The Lorentz force on a moving charge.",
        shell: "ghost",
        rows: [
          { name: "Lorentz force", fn: "F = qvB sin θ, perpendicular to both v and B.", why: "The sine dependence and the perpendicularity are both asked." },
          { name: "Circular motion", fn: "For v ⊥ B the charge moves in a circle of radius r = mv/qB.", why: "Cyclotron and mass-spectrometer questions start here." },
          { name: "Zero-force case", fn: "A charge moving along the field feels no magnetic force.", why: "The θ = 0 special case." },
        ],
      },
      {
        id: "solenoid",
        label: "Electromagnet",
        hint: "A coil on an iron core and the field it produces.",
        shell: "ghost",
        rows: [
          { name: "Solenoid field", fn: "B = μ₀nI inside, nearly uniform and axial.", why: "Compare with the wire's 1/r field — a standard contrast." },
          { name: "Iron core", fn: "Increases the flux thousands of times.", why: "Why an iron core is used is a one-mark question." },
          { name: "Poles", fn: "Field emerges from the north end.", why: "End identification from the current direction." },
        ],
      },
    ],
    theory: {
      look: "A copper rod standing on a bench ringed by cyan field circles that crowd close to the wire, a green charge with its red force vector, and a second view showing an iron rod wound with a solenoid whose blue field arrows run along the axis.",
      principle: "A current produces a magnetic field: circles of magnitude B = μ₀I/2πr around a long straight conductor, and a nearly uniform axial field B = μ₀nI inside a solenoid. The direction follows the right-hand grip rule. A charge moving in a field experiences the Lorentz force qvB sin θ, perpendicular to both the velocity and the field, which for v perpendicular to B produces circular motion of radius mv/qB.",
      why: "The field-line shape, the 1/r against uniform contrast, the sine factor and perpendicularity of the Lorentz force, the radius of the circular path, and the role of the iron core are the recurring marks.",
    },
  },

  /* ── EM waves ── */
  "ph-3d-em": {
    studio: "Electromagnetic wave — E and B in step",
    blurb: "A real plane wave travelling in space with its electric and magnetic fields perpendicular to each other, the transverse c = 1/√(μ₀ε₀) relation, and the spectrum that shares the same physics.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "tube", points: [[-8, 0, 0], [8, 0, 0]], radius: 0.03 },
        material: "emissive",
        color: 0x475569,
        views: ["external", "wave", "spectrum"],
        label: { text: "Direction of propagation (E × B)", sub: "the wave travels this way", at: [0, -3.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "sphere", r: 0.16 },
        at: [-3.2, 1.4, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["wave"],
        repeat: { count: 22, spread: [9.0, 0, 0] },
        label: { text: "Electric field E", sub: "oscillates in a plane — red crests", at: [-2.0, 4.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.16 },
        at: [-3.2, 0, 2.0],
        material: "emissive",
        color: 0x3b82f6,
        views: ["wave"],
        repeat: { count: 22, spread: [9.0, 0, 0] },
        label: { text: "Magnetic field B", sub: "perpendicular to E and to the direction of travel", at: [2.0, 1.6, 3.2], color: "#60a5fa" },
      },
      {
        shape: { kind: "plane", w: 10, h: 4 },
        at: [0, 2.6, 0],
        rot: [0, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["spectrum"],
        label: { text: "Radio → microwave → IR → visible → UV → X → γ", sub: "same speed c in vacuum, different wavelength", at: [0, 4.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 6 },
        at: [0, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "glass",
        color: 0xe0f2fe,
        views: ["external"],
        label: { text: "Transverse wave", sub: "no medium needed — travels through vacuum", at: [3.6, 3.0, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Wave (real)",
        hint: "A transverse wave needing no medium.",
        rows: [
          { name: "Transverse nature", fn: "E and B both oscillate perpendicular to the travel direction.", why: "The perpendicularity is the defining picture question." },
          { name: "No medium required", fn: "EM waves cross vacuum at c = 3 × 10⁸ m s⁻¹.", why: "The difference from sound is a favourite comparison." },
        ],
      },
      {
        id: "wave",
        label: "E and B in step",
        hint: "The two fields rising and falling together.",
        rows: [
          { name: "In phase", fn: "E and B peak and trough at exactly the same instant.", why: "'In phase' is the precise wording the paper wants." },
          { name: "Amplitude ratio", fn: "E₀/B₀ = c.", why: "A quick numerical that follows directly." },
          { name: "Wave speed", fn: "c = 1/√(μ₀ε₀) in vacuum.", why: "Links optics to electromagnetism — Maxwell's result." },
        ],
      },
      {
        id: "spectrum",
        label: "Spectrum",
        hint: "One physics, seven bands.",
        shell: "ghost",
        rows: [
          { name: "Order by wavelength", fn: "Radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.", why: "The order is asked directly." },
          { name: "Common speed", fn: "All travel at c in vacuum; only λ and f differ.", why: "Explains why the refractive index varies across the spectrum." },
          { name: "Energy", fn: "E = hf, so shorter wavelength means more energetic photons.", why: "Connects the spectrum to the photoelectric effect." },
        ],
      },
    ],
    theory: {
      look: "A ruled axis of travel with a red train of field crests rising above it and a blue train crossing at right angles, the two rising and falling in step, and a banded strip listing the seven regions of the spectrum.",
      principle: "A changing electric field generates a magnetic field and vice versa, so the two sustain each other and travel. In a plane electromagnetic wave E and B are mutually perpendicular and both perpendicular to the direction of propagation, they oscillate in phase, and their amplitudes are in the ratio E₀/B₀ = c, where c = 1/√(μ₀ε₀). Every member of the spectrum shares this structure and speed in vacuum; only wavelength and frequency differ, and the photon energy follows E = hf.",
      why: "The mutual perpendicularity, the in-phase statement, the amplitude ratio, the c = 1/√(μ₀ε₀) derivation, and the spectral ordering are all standard examination points.",
    },
  },

  /* ── Thermodynamics ── */
  "ph-3d-thermodynamics": {
    studio: "Thermodynamics — the four processes on real gas",
    blurb: "A cylinder of gas with its piston and thermometer: isothermal, adiabatic, isobaric and isochoric paths drawn on the same working substance, plus the P–V loop that shows the work done.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cylinder", r1: 1.4, r2: 1.4, h: 5.0, open: false },
        at: [0, 0, 0],
        material: "glass",
        color: 0xdbeafe,
        views: ["external", "isothermal", "adiabatic", "pv"],
        label: { text: "Cylinder of ideal gas", sub: "n moles, temperature T", at: [-4.4, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "cylinder", r1: 1.35, r2: 1.35, h: 0.5 },
        at: [0, 1.6, 0],
        material: "metal",
        color: 0x64748b,
        views: ["external", "isothermal", "adiabatic", "pv"],
        label: { text: "Frictionless piston", sub: "moves freely — the volume changes", at: [3.8, 3.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "tube", points: [[1.4, 0, 0], [3.4, 0, 0], [3.4, 2.4, 0]], radius: 0.06 },
        material: "metal",
        color: 0x94a3b8,
        views: ["external", "isothermal", "adiabatic"],
        label: { text: "Thermometer", sub: "reads T — constant in an isothermal change", at: [5.4, 2.0, 0], color: "#e2e8f0" },
      },
      {
        shape: { kind: "disc", r: 0.9 },
        at: [0, -2.6, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0xf97316,
        views: ["isothermal", "adiabatic"],
        label: { text: "Heat reservoir / insulation", sub: "Q = 0 for an adiabatic change", at: [3.2, -3.4, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "tube", points: [[-6, -2, 0], [-2, -2, 0], [-2, 2, 0], [3, 2, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["isothermal"],
        label: { text: "Isothermal: PV = constant", sub: "slow change with free heat exchange", at: [-5.0, 3.0, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-6, -2, 0], [-3.4, -2, 0], [-3.4, 2.4, 0], [3, 2.4, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf43f5e,
        views: ["adiabatic"],
        label: { text: "Adiabatic: PVᵞ = constant", sub: "steeper — no heat enters or leaves", at: [-4.6, 3.4, 0], color: "#fb7185" },
      },
      {
        shape: { kind: "tube", points: [[-6, -2, 0], [-6, 2, 0], [-3.4, 2.4, 0], [3, 2.4, 0]], radius: 0.045 },
        material: "emissive",
        color: 0xfacc15,
        views: ["pv"],
        repeat: { count: 4, spread: [0, 0.6, 0] },
        label: { text: "P–V diagram", sub: "closed loop area = net work done by the gas", at: [-4.4, 3.6, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-1.2, -1.6, 0], [1.4, -1.6, 0], [1.4, 1.8, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["pv"],
        label: { text: "Work W = ∫P dV", sub: "the area under each path", at: [3.4, 0.4, 0], color: "#4ade80" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Apparatus (real)",
        hint: "Gas in a cylinder with a movable piston.",
        rows: [
          { name: "Cylinder and piston", fn: "Allow the volume to change while the gas does work.", why: "Work done by a gas is defined through this displacement." },
          { name: "Thermometer", fn: "Reports the temperature that appears in PV = nRT.", why: "Isothermal versus adiabatic is decided by whether T changes." },
        ],
      },
      {
        id: "isothermal",
        label: "Isothermal",
        hint: "Slow change with the temperature held constant.",
        shell: "ghost",
        rows: [
          { name: "Condition", fn: "T constant, so PV = constant (Boyle's law).", why: "The condition is the first line of the derivation." },
          { name: "Work done", fn: "W = nRT ln(V₂/V₁) = 2.303 nRT log₁₀(V₂/V₁).", why: "The logarithmic form and the 2.303 conversion are both asked." },
          { name: "Internal energy", fn: "ΔU = 0 because U depends only on T for an ideal gas.", why: "So Q = W exactly — the neatest first-law application." },
        ],
      },
      {
        id: "adiabatic",
        label: "Adiabatic",
        hint: "No heat exchange, so the gas cools as it expands.",
        shell: "ghost",
        rows: [
          { name: "Condition", fn: "Q = 0; the process must be fast or well insulated.", why: "The two practical routes to adiabatic behaviour." },
          { name: "Relation", fn: "PVᵞ = constant with γ = C_P/C_V.", why: "The exponent and its definition are both marked." },
          { name: "First law", fn: "ΔU = −W: the gas does work at the expense of its own internal energy.", why: "Explains the cooling on expansion." },
          { name: "Adiabatic versus isothermal", fn: "The adiabatic curve is steeper on a P–V diagram.", why: "A guaranteed graph-comparison question." },
        ],
      },
      {
        id: "pv",
        label: "P–V work",
        hint: "Where the work done can be measured as an area.",
        shell: "ghost",
        rows: [
          { name: "Work done", fn: "W = ∫P dV — the area under the path.", why: "Turns every process question into a geometry question." },
          { name: "Cycle", fn: "Net work is the enclosed area, taken positive clockwise.", why: "The sign convention for a cycle is asked directly." },
          { name: "Isobaric / isochoric", fn: "Isobaric W = PΔV; isochoric W = 0.", why: "The two degenerate cases follow from the same integral." },
        ],
      },
    ],
    theory: {
      look: "A glass cylinder of pale gas stopped by a metal piston, with a side thermometer and a heat pad beneath it. Two curve families are drawn beyond the cylinder: a shallow isothermal and a steeper adiabatic, then the P–V loop whose enclosed area is the net work.",
      principle: "The first law, ΔQ = ΔU + ΔW, governs every process. Holding T constant gives PV = constant and W = nRT ln(V₂/V₁) with ΔU = 0. Removing heat exchange gives PVᵞ = constant, so expansion is paid for out of internal energy and the gas cools. Since P–V work is the area under the path, a closed loop encloses the net work done per cycle.",
      why: "The isothermal work formula, the meaning of γ, the steeper adiabatic curve, and the area interpretation of work are the standard marks this model separates.",
    },
  },

  /* ── Heat determinations ── */
  "ph-3d-heat-determinations": {
    studio: "Heat experiments — Searle's bar, Lee's disc, Newton cooling, expansion",
    blurb: "The four heat-determination experiments in one studio: the bar with its lagged jacket, the disc stack, the cooling curve, and the expansion apparatus — each with the quantity it actually measures.",
    defaultView: "searles",
    parts: [
      {
        shape: { kind: "cylinder", r1: 0.45, h: 9 },
        at: [0, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0xb45309,
        views: ["searles"],
        label: { text: "Searle's bar", sub: "thermal conductivity k of the metal", at: [-3.6, 2.4, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "box", size: [5, 1.6, 1.6] },
        at: [1.6, 0, 0],
        material: "wood",
        color: 0x7c4a1e,
        views: ["searles"],
        label: { text: "Lagging jacket + steam", sub: "keeps the bar's sides adiabatic so heat flows only along it", at: [3.4, 3.0, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "cylinder", r1: 0.12, h: 1.2 },
        at: [-3.4, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0x94a3b8,
        views: ["searles"],
        label: { text: "Thermometers at x₁, x₂", sub: "temperature gradient θ₁ − θ₂ over distance", at: [-5.4, -2.6, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "cylinder", r1: 2.0, r2: 2.6, h: 0.5 },
        at: [0, -1.0, 0],
        material: "metal",
        color: 0x9ca3af,
        views: ["lees"],
        label: { text: "Lee's disc", sub: "thermal conductivity of a poor conductor", at: [-4.4, 3.0, 0], color: "#38bdf8" },
      },
      {
        shape: { kind: "cylinder", r1: 1.9, h: 0.2 },
        at: [0, -0.4, 0],
        material: "wood",
        color: 0x8b5a2b,
        views: ["lees"],
        label: { text: "Sample slab", sub: "thin disc of the material under test", at: [3.6, 2.6, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "sphere", r: 0.8 },
        at: [0, 0.6, 0],
        material: "metal",
        color: 0xdc2626,
        views: ["cooling"],
        motion: { kind: "pulse", amount: 0.02, speed: 1.0 },
        label: { text: "Hot body", sub: "cools in a steady draught", at: [-3.8, 2.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, 3.4, 0], [4, 3.4, 0], [7, -0.6, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["cooling"],
        label: { text: "Cooling curve", sub: "dθ/dt ∝ (θ − θ₀) — Newton's law of cooling", at: [5.6, 4.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "cylinder", r1: 0.16, h: 8 },
        at: [0, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0xb91c1c,
        views: ["expansion"],
        motion: { kind: "pulse", amount: 0.015, speed: 0.6 },
        label: { text: "Metal rod", sub: "linear expansivity α = ΔL/(LΔθ)", at: [-3.4, 2.6, 0], color: "#fca5a5" },
      },
      {
        shape: { kind: "torus", r: 0.9, tube: 0.05 },
        at: [4.4, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["expansion"],
        label: { text: "Spherometer / dial gauge", sub: "reads the tiny elongation directly", at: [6.6, 2.4, 0], color: "#cbd5e1" },
      },
    ],
    views: [
      {
        id: "searles",
        label: "Searle's bar (k)",
        hint: "Steady-state conduction along a lagged bar.",
        rows: [
          { name: "Searle's bar", fn: "Measures the thermal conductivity of a good conductor.", why: "The standard k-determination in the practical syllabus." },
          { name: "Lagging", fn: "Prevents sideways loss so heat flows only along the bar.", why: "Without lagging the calculation is simply invalid — and that is the mark." },
          { name: "Working relation", fn: "k = (Q/t) × x / (A(θ₁ − θ₂)) using the steady mass of condensate.", why: "Each symbol and its measurement must be identified." },
          { name: "Steady state", fn: "Readings are taken only once the thermometer columns stop moving.", why: "Explains why the experiment takes time." },
        ],
      },
      {
        id: "lees",
        label: "Lee's disc (poor conductor)",
        hint: "A slab sandwiched between a steam chamber and a disc.",
        rows: [
          { name: "Lee's disc", fn: "Measures the conductivity of a poor conductor such as cardboard or rubber.", why: "Comparison with Searle's bar is a standard question." },
          { name: "Construction", fn: "Steam chamber above, sample slab, brass disc below.", why: "Layer order is asked as a diagram label." },
          { name: "Rate of cooling", fn: "The disc's own cooling rate is used to infer its heat loss.", why: "The trick that avoids measuring heat directly." },
        ],
      },
      {
        id: "cooling",
        label: "Newton's law of cooling",
        hint: "A hot body losing heat to its surroundings.",
        shell: "ghost",
        rows: [
          { name: "Law", fn: "The rate of loss of heat is proportional to the excess temperature.", why: "Statement and proportionality are both marked." },
          { name: "Graph", fn: "The cooling curve flattens toward the ambient temperature.", why: "Interpreting its slope at a point is the numerical." },
          { name: "Validity", fn: "Holds only for a small temperature difference with no draughts.", why: "Conditions of validity are a favourite one-mark question." },
        ],
      },
      {
        id: "expansion",
        label: "Linear expansion",
        hint: "A rod heated along its length, measured to a fraction of a millimetre.",
        shell: "ghost",
        rows: [
          { name: "Real expansivity", fn: "α = ΔL/(L Δθ) for the material.", why: "The definition must be distinguished from the apparent value." },
          { name: "Apparent versus real", fn: "The container or support also expands; the correction matters.", why: "This correction is where marks are usually lost." },
          { name: "Measurement", fn: "The elongation is a fraction of a millimetre, so a spherometer or dial gauge is used.", why: "Explains the instrument choice." },
        ],
      },
    ],
    theory: {
      look: "Four set-ups side by side: a lagged metal bar with steam entering one end and two thermometers along it, a Lee's disc stack of steam chamber over a slab over a brass disc, a red hot body with its falling cooling curve, and a long rod whose elongation is read by a dial gauge.",
      principle: "Heat conduction in the steady state obeys k = (Q/t)x/(AΔθ) — which is what Searle's bar measures for good conductors and Lee's disc measures for poor ones, using the disc's own cooling rate to infer the heat flow. A body loses heat at a rate proportional to its excess temperature over the surroundings, giving a cooling curve whose slope at any point is proportional to the excess. Solids lengthen by αLΔθ, but the container expands too, so the measured (apparent) value needs a correction to give the real expansivity.",
      why: "The role of lagging, the layer order in Lee's disc, the statement and validity conditions of Newton's law, and the apparent-versus-real expansion correction are the standard practical marks.",
    },
  },

  /* ── Waves ── */
  "ph-3d-wave": {
    studio: "Wave motion — a real wave on a real string",
    blurb: "A travelling wave with its crests and troughs labelled, the wavelength and amplitude measured on the model, and the standing wave that forms when the end is fixed.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "box", size: [16, 0.3, 3] },
        at: [0, -2.6, 0],
        material: "wood",
        color: 0x6b4423,
        views: ["external", "travelling", "standing"],
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [-7.5, 0.4, 0],
        material: "metal",
        color: 0x64748b,
        views: ["external", "travelling", "standing"],
        label: { text: "Driving end", sub: "source of the disturbance", at: [-9.4, 2.2, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "tube", points: [[-7.5, 0, 0], [-5.5, 1.2, 0], [-3.5, 0, 0], [-1.5, -1.2, 0], [0.5, 0.6, 0], [2.5, -0.8, 0], [4.5, 0.9, 0], [6.5, 0, 0]], radius: 0.07 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["external", "travelling"],
        motion: { kind: "wave", amplitude: 0.35, speed: 1.6 },
        label: { text: "Transverse wave", sub: "particles move at right angles to travel", at: [-4.6, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-3.5, 0, 0], [-3.5, 1.8, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xfacc15,
        views: ["travelling"],
        label: { text: "Amplitude a", sub: "maximum displacement from the mean position", at: [-6.2, 2.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-7.5, -1.6, 0], [-3.5, -1.6, 0]], radius: 0.03 },
        material: "emissive",
        color: 0x22c55e,
        views: ["travelling"],
        label: { text: "Wavelength λ", sub: "crest to crest — the distance over which the phase repeats", at: [-5.4, -2.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.24 },
        at: [7.5, 0.4, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["standing"],
        label: { text: "Fixed end", sub: "a node must form here", at: [9.4, 2.2, 0], color: "#e2e8f0" },
      },
      {
        shape: { kind: "tube", points: [[-7.5, 0, 0], [-5.0, 1.6, 0], [-2.5, 0, 0], [0, -1.6, 0], [2.5, 0, 0], [5.0, 1.6, 0], [7.5, 0, 0]], radius: 0.07 },
        material: "emissive",
        color: 0xec4899,
        views: ["standing"],
        motion: { kind: "wave", amplitude: 0.5, speed: 2.2 },
        label: { text: "Standing wave", sub: "nodes and antinodes fixed in space", at: [-4.0, 3.4, 0], color: "#f472b6" },
      },
      {
        shape: { kind: "sphere", r: 0.14 },
        at: [-2.5, 0, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["standing"],
        repeat: { count: 3, spread: [5.0, 0, 0] },
        label: { text: "Nodes", sub: "zero displacement — λ/2 apart", at: [-2.5, -2.8, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Wave on a string",
        hint: "A transverse disturbance travelling along a stretched medium.",
        rows: [
          { name: "Transverse wave", fn: "Particle motion is perpendicular to energy transfer.", why: "Contrast with longitudinal sound is a standard question." },
          { name: "Medium", fn: "Carries the disturbance but does not travel with it.", why: "The distinction between wave speed and particle speed." },
        ],
      },
      {
        id: "travelling",
        label: "Wave quantities",
        hint: "Amplitude, wavelength, frequency and speed on the same wave.",
        rows: [
          { name: "Amplitude a", fn: "Maximum displacement from the mean position.", why: "Amplitude, not wavelength, decides loudness or brightness." },
          { name: "Wavelength λ", fn: "Crest-to-crest distance.", why: "The unit and the measurement are both asked." },
          { name: "Wave equation", fn: "v = fλ.", why: "Frequency is set by the source and never changes with the medium." },
          { name: "Phase difference", fn: "Δφ = (2π/λ)Δx.", why: "The bridge to interference." },
        ],
      },
      {
        id: "standing",
        label: "Standing wave",
        hint: "Two opposite waves on the same string.",
        shell: "ghost",
        rows: [
          { name: "Node", fn: "A point of permanently zero displacement.", why: "Nodes form at fixed ends — the boundary condition." },
          { name: "Antinode", fn: "A point of maximum displacement.", why: "Node-to-node distance is λ/2." },
          { name: "Harmonics", fn: "f_n = (n/2L)√(T/μ) for a string fixed at both ends.", why: "The nth harmonic's frequency and mode shape are both asked." },
          { name: "No energy transfer", fn: "A standing wave carries no net energy along the string.", why: "A neat conceptual discrimination from a travelling wave." },
        ],
      },
    ],
    theory: {
      look: "A blue sine train running down a stretched string from a driven left end, with the amplitude and one wavelength marked in yellow and green, and a second view where a pink standing wave sits between a driven and a fixed end with its nodes labelled.",
      principle: "A wave transfers energy through a medium without the medium itself travelling. For a travelling wave the particle motion is perpendicular to the energy flow, and the amplitude, wavelength, frequency and speed are linked by v = fλ, with frequency fixed by the source. Superposing a wave on its own reflection gives a standing wave: nodes of zero displacement, antinodes of maximum, λ/2 between adjacent nodes, and no net energy transport.",
      why: "The v = fλ relation and the constancy of frequency, the amplitude-versus-wavelength distinction, node and antinode definitions, and the harmonic frequencies of a fixed string are the recurring marks.",
    },
  },
};
