/**
 * Lab Studios — Biology A: cell, organelles, DNA, division, microbes,
 * biomolecules and human systems.
 */

import type { StudioSpec } from "./types";

export const BIOLOGY_A: Record<string, StudioSpec> = {
  /* ── Plant & animal cell ── */
  "bio-3d-cell": {
    studio: "Cell — plant and animal, side by side",
    shellWord: "Membrane",
    blurb: "A real plant cell and a real animal cell in the same frame: what only the plant has, what only the animal has, and the structures both must share.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 3.4, scale: [1, 0.85, 1], noise: 0.03 },
        at: [-4.6, 0, 0],
        material: "membrane",
        color: 0x86efac,
        views: ["external", "plant", "compare"],
        label: { text: "Cell wall (cellulose)", sub: "rigid, fully permeable — plant only", at: [-8.4, 3.6, 0], color: "#86efac" },
      },
      {
        shape: { kind: "sphere", r: 3.1, scale: [1, 0.85, 1], noise: 0.03 },
        at: [-4.6, 0, 0],
        material: "membrane",
        color: 0x22c55e,
        opacity: 0.5,
        views: ["plant", "compare"],
        label: { text: "Plasma membrane", sub: "selectively permeable — inside the wall", at: [-8.4, 1.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.9, scale: [1, 0.7, 0.7], noise: 0.04 },
        at: [-5.6, 0.2, 0],
        material: "organ",
        color: 0x16a34a,
        views: ["plant", "compare"],
        label: { text: "Large central vacuole", sub: "turgor pressure; up to 90% of the volume — plant only", at: [-9.6, -2.4, 0], color: "#22c55e" },
      },
      {
        shape: { kind: "sphere", r: 0.42, scale: [1, 0.6, 1] },
        at: [-3.4, 1.1, 0.5],
        material: "organ",
        color: 0x15803d,
        repeat: { count: 5, spread: [0.9, 0.5, 0.8] },
        views: ["plant", "compare"],
        label: { text: "Chloroplast", sub: "photosynthesis — plant only", at: [-2.0, 3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 3.2, scale: [1.1, 0.85, 1], noise: 0.06 },
        at: [4.8, 0, 0],
        material: "membrane",
        color: 0xfca5a5,
        opacity: 0.42,
        views: ["external", "animal", "compare"],
        label: { text: "Irregular plasma membrane", sub: "no wall, so the shape is not fixed — animal", at: [9.0, 3.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.62, noise: 0.05 },
        at: [4.6, 0.4, -0.4],
        material: "organ",
        color: 0x7c3aed,
        views: ["animal", "compare", "energy"],
        label: { text: "Nucleus", sub: "both cells: holds the DNA", at: [2.0, -3.6, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.05 },
        at: [5.8, -1.0, 0.6],
        material: "organ",
        color: 0xdc2626,
        repeat: { count: 4, spread: [1.2, 0.6, 0.8] },
        views: ["animal", "compare", "energy"],
        label: { text: "Mitochondria", sub: "aerobic respiration — both cells, more in active ones", at: [7.6, -3.2, 0], color: "#f87171" },
      },      {
        shape: { kind: "sphere", r: 0.55, noise: 0.06 },
        at: [4.6, 1.2, 0],
        material: "organ",
        color: 0x7c3aed,
        views: ["energy"],
        label: { text: "Nucleolus (dense)", sub: "ribosome factory inside the nucleus", at: [7.8, 2.8, 0], color: "#c084fc" },
      },
    ],
    views: [
      {

        id: "external",
        label: "Both cells (real)",
        hint: "A plant cell on the left, an animal cell on the right.",
        rows: [
          { name: "Cell theory", fn: "All living things are made of cells; the cell is the basic unit; new cells come from existing cells.", why: "The three postulates are asked verbatim." },
          { name: "Two cell types", fn: "Prokaryote lacks a true nucleus; eukaryote has one.", why: "The defining contrast, not a size claim." },
        ],
      },
      {
        id: "plant",
        label: "Plant cell only",
        hint: "The structures exclusive to plant cells.",
        rows: [
          { name: "Cell wall", fn: "Rigid cellulose layer outside the membrane; fully permeable.", why: "Fully permeable versus selectively permeable is the trap." },
          { name: "Central vacuole", fn: "One large vacuole giving turgor and storage.", why: "Turgidity and plasmolysis questions begin here." },
          { name: "Chloroplast", fn: "Contains chlorophyll for photosynthesis.", why: "Autotrophy is stated through this organelle." },
        ],
      },
      {
        id: "animal",
        label: "Animal cell only",
        hint: "What the animal cell has instead.",
        rows: [
          { name: "Centriole", fn: "Forms the spindle in animal cell division.", why: "Absent in higher plants — a standard table cell." },
          { name: "No wall, no plastid", fn: "Shape is irregular and supported only by the membrane.", why: "Explains why animal cells burst in hypotonic solutions." },
          { name: "Food vacuoles", fn: "Temporary, formed as needed.", why: "Contrast with the plant's permanent central vacuole." },
        ],
      },
      {
        id: "compare",
        label: "Shared structures",
        hint: "What both cells must have to be alive.",
        shell: "ghost",
        rows: [
          { name: "Nucleus", fn: "Holds the genetic material in eukaryotes.", why: "The one structure every eukaryotic cell needs." },
          { name: "Mitochondria", fn: "Release energy by aerobic respiration.", why: "More numerous in more active cells — a numerical reasoning point." },
          { name: "Endomembrane system", fn: "ER, Golgi, lysosome and vacuoles working as a unit.", why: "The 'why organelles form a system' question." },
        ],
      },
      {
        id: "energy",
        label: "Energy flow",
        hint: "Where the cell's energy is made.",
        shell: "ghost",
        rows: [
          { name: "Mitochondrion", fn: "Cristae give a large surface for the electron transport chain.", why: "Structure-to-function is the standard marking point." },
          { name: "ATP", fn: "The universal energy currency.", why: "Why not glucose is asked as a one-mark reason." },
          { name: "Chloroplast", fn: "Converts light energy to chemical energy in plants.", why: "Ends the chain that mitochondria then spend." },
        ],
      },
    ],
    theory: {
      look: "A green plant cell on the left with a thick outer wall, one huge clear vacuole and scattered lens-shaped chloroplasts, and a paler pink animal cell on the right with no wall and a bunch of bean-shaped mitochondria.",
      principle: "Every cell is bounded by a selectively permeable membrane and contains a nucleus, cytoplasm and mitochondria. Plant cells add a rigid cellulose wall, a single large central vacuole for turgor, and chloroplasts for photosynthesis; they lack centrioles. Animal cells have no wall or plastids, so their shape is irregular, and they divide using centrioles to form the spindle.",
      why: "The cell-theory postulates, the fully-versus-selectively permeable distinction, the plant-only and animal-only lists, and the turgor and plasmolysis consequences are the exact marks.",
    },
  },

  /* ── Organelles ── */
  "bio-3d-organelles": {
    studio: "Organelles — the endomembrane system at work",
    shellWord: "Membrane",
    blurb: "One cell opened up so the secretory pathway can be followed: nucleus → rough ER → Golgi → vesicle → membrane, with each organelle's real job named.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 3.4, noise: 0.04 },
        at: [0, 0, 0],
        material: "membrane",
        color: 0xfda4af,
        opacity: 0.34,
        views: ["external", "endo", "power"],
      },
      {
        shape: { kind: "sphere", r: 0.8, noise: 0.05 },
        at: [-1.6, 0.6, 0],
        material: "organ",
        color: 0x7c3aed,
        views: ["external", "endo"],
        label: { text: "Nucleus", sub: "houses DNA; the nucleolus makes rRNA", at: [-5.4, 3.4, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.2, noise: 0.06 },
        at: [-1.6, 0.6, 0],
        material: "organ",
        color: 0x4c1d95,
        views: ["endo"],
        label: { text: "Nucleolus", sub: "site of ribosome synthesis", at: [-6.4, 1.4, 0], color: "#a78bfa" },
      },
      {
        shape: { kind: "tube", points: [[-0.9, 0.2, 0], [0.2, 0.9, 0], [1.2, 0.2, 0], [1.9, 1.1, 0]], radius: 0.13 },
        material: "mucosa",
        color: 0x0ea5e9,
        views: ["external", "endo"],
        label: { text: "Rough ER", sub: "studded with ribosomes; makes membrane and export proteins", at: [0.4, 4.0, 0], color: "#38bdf8" },
      },
      {
        shape: { kind: "sphere", r: 0.09 },
        at: [-0.4, 1.2, 0],
        material: "emissive",
        color: 0xf59e0b,
        repeat: { count: 14, spread: [2.6, 1.0, 0.5] },
        views: ["endo"],
        label: { text: "Ribosomes", sub: "the actual protein factories", at: [2.8, 3.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[2.2, 0.6, 0], [2.8, -0.4, 0], [3.0, -1.4, 0]], radius: 0.22 },
        material: "organ",
        color: 0xdb2777,
        views: ["external", "endo"],
        label: { text: "Golgi body", sub: "modifies, packages and dispatches the proteins", at: [5.4, -2.6, 0], color: "#f472b6" },
      },
      {
        shape: { kind: "sphere", r: 0.18 },
        at: [3.4, -2.4, 0],
        material: "membrane",
        color: 0x22d3ee,
        repeat: { count: 5, spread: [-1.4, -0.9, 0.6] },
        views: ["endo"],
        label: { text: "Secretory vesicles", sub: "carry the finished product to the membrane", at: [5.8, -4.2, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.16 },
        at: [-2.4, -1.6, 0],
        material: "organ",
        color: 0x16a34a,
        views: ["external", "power"],
        label: { text: "Mitochondrion", sub: "aerobic respiration; cristae give the surface area", at: [-6.6, -3.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.32, noise: 0.08 },
        at: [2.0, -1.0, 0],
        material: "organ",
        color: 0xef4444,
        views: ["power"],
        label: { text: "Lysosome", sub: "digests with hydrolytic enzymes — 'suicide bags'", at: [2.4, -4.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.05 },
        at: [-3.0, 1.8, 0],
        material: "organ",
        color: 0x84cc16,
        views: ["power"],
        label: { text: "Peroxisome", sub: "handles oxidative reactions, breaking down peroxide", at: [-4.0, 3.6, 0], color: "#a3e635" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Cell cut open (real)",
        hint: "The main organelles in their true relative positions.",
        rows: [
          { name: "Nucleus", fn: "Enclosed by a double membrane with pores; contains chromatin and nucleolus.", why: "The nuclear pore's role in transport is a standard mark." },
          { name: "Mitochondrion", fn: "Double-membraned; the inner membrane folds into cristae.", why: "Surface-area-to-volume reasoning is what earns the mark." },
          { name: "Vacuole", fn: "Storage and, in plants, turgor.", why: "Permanent in plant cells, temporary in animal cells." },
        ],
      },
      {
        id: "endo",
        label: "Secretory pathway",
        hint: "How a protein is made and shipped out.",
        rows: [
          { name: "Rough ER", fn: "Ribosomes on its surface make proteins that enter the lumen.", why: "Why rough ER is 'rough' and what that implies." },
          { name: "Golgi body", fn: "Modifies, sorts and packages proteins into vesicles.", why: "Often confused with ER — this view separates them." },
          { name: "Vesicle", fn: "Fuses with the plasma membrane to release its contents.", why: "Exocytosis is named at this fusion." },
          { name: "Smooth ER", fn: "No ribosomes; makes lipids, detoxifies.", why: "Comparing rough and smooth ER is a routine question." },
        ],
      },
      {
        id: "power",
        label: "Energy & recycling",
        hint: "Where energy is released and debris is destroyed.",
        shell: "ghost",
        rows: [
          { name: "Mitochondrion", fn: "Releases energy as ATP by aerobic respiration.", why: "Abundant in muscle and liver — the reasoning link." },
          { name: "Lysosome", fn: "Contains hydrolytic enzymes that digest worn-out organelles.", why: "Why they are called suicide bags." },
          { name: "Peroxisome", fn: "Breaks down hydrogen peroxide using catalase.", why: "Its distinct enzyme set is one-mark material." },
        ],
      },
    ],
    theory: {
      look: "A translucent cell cut open to reveal a purple nucleus with its darker nucleolus, a blue folded rough ER studded with orange ribosome dots, a pink Golgi stack with cyan vesicles budding off, a green bean-shaped mitochondrion and a red lysosome.",
      principle: "Each organelle is a compartment whose structure serves its function. The nucleus stores the DNA and makes rRNA; ribosomes on the rough ER build proteins that pass into its lumen; the Golgi modifies and packages them into vesicles that fuse with the plasma membrane, completing the secretory pathway. Mitochondria release ATP through a cristae-folded inner membrane, lysosomes digest with hydrolytic enzymes, and peroxisomes handle oxidative breakdown.",
      why: "The structure-to-function link for each organelle, the rough-versus-smooth ER contrast, the order of the secretory pathway, cristae surface-area reasoning, and the 'suicide bag' designation are the recurring marks.",
    },
  },

  /* ── DNA ── */
  "bio-3d-dna": {
    studio: "DNA — double helix, live",
    blurb: "A real double helix you can read: the two antiparallel strands, the base pairing that holds them, the major and minor grooves, and the semiconservative copying that follows.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "tube", points: [[0, -6, 0.9], [0.9, -4, 0], [0, -2, -0.9], [-0.9, 0, 0], [0, 2, 0.9], [0.9, 4, 0], [0, 6, -0.9]], radius: 0.09 },
        material: "metal",
        color: 0x38bdf8,
        views: ["external", "bases", "replication"],
        label: { text: "Strand 1 — runs 5′ → 3′", sub: "sugar-phosphate backbone", at: [-3.6, 4.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[1.8, -6, 0], [0.9, -4, 0.9], [1.8, -2, 0], [2.7, 0, -0.9], [1.8, 2, 0], [0.9, 4, 0.9], [1.8, 6, 0]], radius: 0.09 },
        material: "metal",
        color: 0xf472b6,
        views: ["external", "bases", "replication"],
        label: { text: "Strand 2 — runs 3′ → 5′", sub: "antiparallel to strand 1", at: [4.6, 4.6, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "cylinder", r1: 0.07, h: 1.8 },
        at: [0.9, -3, 0.45],
        rot: [0, 0, 0.5],
        material: "emissive",
        color: 0xfacc15,
        views: ["external", "bases"],
        repeat: { count: 10, spread: [0.02, 1.0, 0.02] },
        label: { text: "A = T · G ≡ C", sub: "a purine always pairs with a pyrimidine", at: [-4.2, -4.6, 0], color: "#fde047" },
      },
      {
        shape: { kind: "torus", r: 1.2, tube: 0.04 },
        at: [0.9, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["external"],
        repeat: { count: 6, spread: [0, 2.0, 0] },
        label: { text: "Major & minor grooves", sub: "where proteins grip the helix", at: [4.6, -0.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.05 },
        at: [0.9, 0, 0],
        material: "organ",
        color: 0xa855f7,
        views: ["replication"],
        label: { text: "Helicase unzips the helix", sub: "breaks the hydrogen bonds between bases", at: [-3.4, 2.4, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "tube", points: [[0.2, -1.2, 0], [0.4, -2.6, 0], [1.6, -2.6, 0], [1.8, -1.2, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xef4444,
        views: ["replication"],
        label: { text: "DNA polymerase", sub: "adds nucleotides only 5′ → 3′", at: [-3.8, -1.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[1.0, 1.4, 0], [1.6, 1.4, 0], [1.8, 2.4, 0], [2.6, 2.4, 0]], radius: 0.06 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["replication"],
        label: { text: "Lagging strand fragments", sub: "rejoined later by ligase", at: [5.0, 2.6, 0], color: "#fbbf24" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Double helix (real)",
        hint: "The Watson–Crick model as a physical object.",
        rows: [
          { name: "Double helix", fn: "Two polynucleotide strands wound round a common axis.", why: "The description must include the coiling, not just 'twisted ladder'." },
          { name: "Antiparallel strands", fn: "One runs 5′→3′, the other 3′→5′.", why: "This is what makes replication asymmetric." },
          { name: "Grooves", fn: "Unequal major and minor grooves where proteins bind.", why: "Distinguishes the B-DNA model from a plain spiral." },
        ],
      },
      {
        id: "bases",
        label: "Base pairing",
        hint: "The rule that holds the two strands together.",
        shell: "ghost",
        rows: [
          { name: "Complementarity", fn: "A pairs with T by 2 hydrogen bonds; G with C by 3.", why: "The bond count is asked, and it explains GC-rich stability." },
          { name: "Purine–pyrimidine", fn: "Every pair spans the same width, keeping the helix uniform.", why: "Why a purine must pair with a pyrimidine." },
          { name: "Chargaff's rule", fn: "A = T and G = C, so A + G = T + C.", why: "The standard numerical on base percentages." },
        ],
      },
      {
        id: "replication",
        label: "Semiconservative copying",
        hint: "Unzip, copy, rejoin — one old strand per new helix.",
        shell: "ghost",
        rows: [
          { name: "Semiconservative", fn: "Each daughter helix keeps one parental strand.", why: "The Meselson–Stahl experiment is the required evidence." },
          { name: "Direction constraint", fn: "Polymerase works only 5′→3′, so one strand is discontinuous.", why: "This explains why Okazaki fragments exist at all." },
          { name: "Enzymes", fn: "Helicase unzips, polymerase extends, ligase seals.", why: "Each enzyme's single job is a one-mark item." },
        ],
      },
    ],
    theory: {
      look: "A blue sugar-phosphate strand winding up the left of a vertical axis and a pink one winding down the right — clearly antiparallel — with yellow cross-rungs of paired bases between them, green groove rings, and a replication view showing the fork being unzipped with a polymerase and lagging-strand fragments.",
      principle: "DNA is two antiparallel polynucleotide strands coiled about a common axis into a right-handed double helix. The strands are held by hydrogen bonds between complementary bases, A with T and G with C, always a purine with a pyrimidine so every pair spans the same width. Replication is semiconservative: the helix unzips, each strand acts as a template, and because polymerase can add nucleotides only in the 5′→3′ direction one new strand is built continuously while the other is made in fragments that ligase later seals.",
      why: "The antiparallel statement, the base-pairing counts and Chargaff's rule, the semiconservative evidence, and the reason Okazaki fragments are necessary are the exact examination points.",
    },
  },

  /* ── Cell division ── */
  "bio-3d-cell-division": {
    shellWord: "Membrane",
    studio: "Cell division — mitosis and meiosis on real chromosomes",
    blurb: "Real chromosomes condensing, lining up, separating and dividing: the mitotic sequence beside the two meiotic divisions that halve the chromosome number.",
    defaultView: "mitosis",
    parts: [
      {
        shape: { kind: "sphere", r: 3.2, noise: 0.05 },
        at: [0, 0, 0],
        material: "membrane",
        color: 0xfda4af,
        opacity: 0.3,
        views: ["mitosis", "meiosis"],
        label: { text: "Parent cell", sub: "diploid (2n) with homologous pairs", at: [-6.2, 4.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, -1.4, 0], [0.4, 0, 0], [0, 1.4, 0]], radius: 0.16 },
        at: [-1.4, 0, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["mitosis", "meiosis"],
        label: { text: "Chromosome (X-shaped)", sub: "two chromatids joined at the centromere", at: [-6.4, 1.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, -1.4, 0], [0.4, 0, 0], [0, 1.4, 0]], radius: 0.16 },
        at: [-1.4, 0, 0.9],
        material: "organ",
        color: 0x1d4ed8,
        views: ["mitosis", "meiosis"],
        label: { text: "Homologous partner", sub: "same genes, possibly different alleles", at: [-6.4, -1.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[0, -2.6, 0], [0, 0, 0], [0, 2.6, 0]], radius: 0.035 },
        at: [2.2, 0, 0],
        material: "emissive",
        color: 0xfbbf24,
        views: ["mitosis", "meiosis"],
        label: { text: "Spindle fibres", sub: "pull chromatids to opposite poles", at: [5.0, 2.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [3.4, 2.6, 0],
        material: "metal",
        color: 0x64748b,
        views: ["mitosis", "meiosis"],
        label: { text: "Centrosome / centriole", sub: "organises the spindle; at each pole", at: [5.6, 4.2, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "sphere", r: 0.07 },
        at: [0, 3.6, 0],
        material: "emissive",
        color: 0xffffff,
        repeat: { ring: 1, radius: 2.2 },
        views: ["mitosis"],
      },
      {
        shape: { kind: "tube", points: [[-2.2, 0, 0], [-1.0, 1.6, 0], [0, 0, 0], [1.0, -1.6, 0], [2.2, 0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x22c55e,
        views: ["mitosis"],
        label: { text: "Metaphase plate", sub: "chromosomes line up singly on the equator", at: [-4.4, -3.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[-1.6, -1.2, 0], [0, 0.6, 0], [1.2, -1.4, 0], [2.0, -0.2, 0]], radius: 0.14 },
        material: "organ",
        color: 0xa855f7,
        views: ["meiosis"],
        label: { text: "Crossing over", sub: "non-sister chromatids exchange segments at the chiasma", at: [-5.0, -4.0, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "tube", points: [[-0.4, -1.0, 0], [0.2, 0.4, 0], [0.8, -1.0, 0]], radius: 0.13 },
        at: [-1.0, 0, 0],
        material: "organ",
        color: 0xf59e0b,
        views: ["meiosis"],
        label: { text: "Bivalent / tetrad", sub: "homologues paired — four chromatids together", at: [2.4, -3.8, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[2.6, -0.4, 0], [3.2, 0.8, 0]], radius: 0.1 },
        material: "organ",
        color: 0xec4899,
        views: ["meiosis"],
        label: { text: "Independent assortment", sub: "random orientation gives 2ⁿ combinations", at: [5.2, -2.4, 0], color: "#f472b6" },
      },
    ],
    views: [
      {
        id: "mitosis",
        label: "Mitosis",
        hint: "One division, two identical diploid cells.",
        rows: [
          { name: "Purpose", fn: "Growth and repair; produces genetically identical cells.", why: "The purpose and the result are separate marks." },
          { name: "Prophase", fn: "Chromosomes condense and the spindle forms.", why: "The order of the four phases is always examined." },
          { name: "Metaphase", fn: "Chromosomes line up singly on the equator.", why: "The word 'singly' is the meiosis-distinguishing detail." },
          { name: "Anaphase", fn: "Sister chromatids separate to opposite poles.", why: "Contrast with anaphase I of meiosis, where homologues separate." },
          { name: "Result", fn: "Two cells, same chromosome number as the parent.", why: "Diploid stays diploid — the point of mitosis." },
        ],
      },
      {
        id: "meiosis",
        label: "Meiosis",
        hint: "Two divisions, four haploid cells with new gene combinations.",
        rows: [
          { name: "Purpose", fn: "Produces gametes and halving the chromosome number.", why: "Why the halving is necessary for fertilisation to restore 2n." },
          { name: "Crossing over", fn: "At pachytene; non-sister chromatids exchange segments.", why: "The source of recombinant chromosomes — a major mark." },
          { name: "Anaphase I", fn: "Homologous chromosomes separate — the actual reduction.", why: "The key contrast with mitotic anaphase." },
          { name: "Independent assortment", fn: "Random orientation of bivalents gives 2ⁿ gamete types.", why: "The 2ⁿ calculation is a standard numerical." },
          { name: "Result", fn: "Four haploid cells, each genetically unique.", why: "The 'unique' clause earns the second half of the mark." },
        ],
      },
    ],
    theory: {
      look: "A translucent parent cell holding a pair of red and blue X-shaped chromosomes with yellow spindle fibres running from two grey centrioles, and a second view where the red and blue homologues are tangled at a chiasma inside a bivalent.",
      principle: "Mitosis is one division producing two genetically identical diploid cells, with chromosomes lining up singly at metaphase and sister chromatids separating at anaphase. Meiosis is two divisions producing four haploid cells: homologous chromosomes pair as bivalents and exchange segments at chiasmata during prophase I, separate at anaphase I, and sister chromatids separate at anaphase II. Crossing over and independent assortment are what make every gamete genetically different.",
      why: "The phase order and events, the 'singly versus in pairs' distinguishing detail, the diploid-versus-haploid outcome, crossing over as a source of variation, and the 2ⁿ calculation are the standard marks.",
    },
  },

  /* ── Microorganisms ── */
  "bio-3d-micro": {
    studio: "Microorganisms — bacteria, virus and fungus in real form",
    blurb: "The three great groups at true relative scale: a bacterium with its real wall and flagellum, a virus with its capsid and nucleic acid, and a fungus with its mycelium and spores.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 1.5, scale: [1.6, 0.8, 0.8], noise: 0.02 },
        at: [-4.6, 0, 0],
        material: "membrane",
        color: 0x84cc16,
        views: ["external", "bacteria", "fungus"],
        label: { text: "Bacterium (prokaryote)", sub: "no true nucleus — the defining feature", at: [-9.0, 3.4, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "tube", points: [[-2.2, 0, 0], [-1.2, 0.6, 0], [-0.4, -0.2, 0]], radius: 0.07 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["bacteria"],
        motion: { kind: "swing", amount: 0.25, speed: 3 },
        label: { text: "Flagellum", sub: "locomotion — a rotary motor protein", at: [-1.4, 2.6, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.1 },
        at: [-5.2, 0.2, 0.3],
        material: "emissive",
        color: 0x38bdf8,
        repeat: { count: 12, spread: [1.6, 0.5, 0.4] },
        views: ["bacteria"],
        label: { text: "Plasmid DNA", sub: "extra circle of genes — carries antibiotic resistance", at: [-9.2, -2.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.04, scale: [1, 3, 1] },
        at: [-4.6, 0, 0],
        material: "emissive",
        color: 0xa78bfa,
        repeat: { count: 20, spread: [2.0, 0.03, 0.03] },
        views: ["bacteria"],
        label: { text: "Pili", sub: "attachment; the sex pilus passes plasmid DNA", at: [-6.6, -3.6, 0], color: "#c4b5fd" },
      },
      {
        shape: { kind: "sphere", r: 1.1, noise: 0.02 },
        at: [1.0, 0.6, 0],
        material: "chitin",
        color: 0x38bdf8,
        opacity: 0.55,
        views: ["external", "virus"],
        label: { text: "Virus — capsid", sub: "protein coat, not a cell at all", at: [2.4, 3.8, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.1 },
        at: [1.0, 0.6, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["virus"],
        label: { text: "Genetic material", sub: "DNA or RNA only — never both", at: [3.2, 1.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[1.6, -0.4, 0], [2.6, -1.6, 0], [2.4, -2.6, 0], [3.4, -3.4, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf472b6,
        views: ["virus"],
        repeat: { count: 6, spread: [0.2, -0.3, 0.3] },
        label: { text: "Tail fibres / spikes", sub: "recognition and attachment to the host", at: [5.4, -2.6, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "tube", points: [[4.6, -3.2, 0], [5.6, -1.6, 0], [5.2, 0.4, 0], [6.6, 1.6, 0]], radius: 0.08 },
        material: "mucosa",
        color: 0xd97706,
        views: ["external", "fungus"],
        label: { text: "Fungal hyphae", sub: "branching filaments forming a mycelium", at: [8.4, -3.4, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "sphere", r: 0.34 },
        at: [5.4, -2.2, 0],
        material: "organ",
        color: 0xdc2626,
        repeat: { count: 7, spread: [-1.4, 2.4, 0.6] },
        views: ["fungus"],
        label: { text: "Spores", sub: "asexual reproduction — carried by air", at: [8.6, 2.6, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Three groups (real)",
        hint: "Bacterium, virus and fungus to the same scale.",
        rows: [
          { name: "Bacterium", fn: "A prokaryote: no true nucleus, no membrane-bound organelles.", why: "This is what separates bacteria from all other groups." },
          { name: "Virus", fn: "Acellular — nucleic acid inside a protein capsid; not alive on its own.", why: "The living-versus-non-living argument is a standard discussion." },
          { name: "Fungus", fn: "Eukaryote with chitin walls, hyphae forming a mycelium.", why: "Saprophytic nutrition is its distinguishing mode." },
        ],
      },
      {
        id: "bacteria",
        label: "Bacterial cell",
        hint: "The prokaryotic parts and their jobs.",
        rows: [
          { name: "Plasmid", fn: "Small circular DNA carrying accessory genes.", why: "The reason antibiotic resistance spreads between species." },
          { name: "Flagellum", fn: "Rotary propeller made of flagellin.", why: "Locomotion type separates bacteria from ciliates." },
          { name: "Pili", fn: "Attachment and conjugation.", why: "How genetic material is passed sideways." },
          { name: "Nutrition", fn: "Heterotrophic and autotrophic both occur.", why: "The five-kingdom classification rests on this flexibility." },
        ],
      },
      {
        id: "virus",
        label: "Virus structure",
        hint: "Nucleic acid plus coat — nothing else.",
        shell: "ghost",
        rows: [
          { name: "Capsid", fn: "Protein coat built of repeating capsomeres.", why: "Its symmetry is asked as a structural feature." },
          { name: "Single nucleic acid", fn: "Either DNA or RNA, never both.", why: "A one-mark fact that is regularly examined." },
          { name: "Obligate parasite", fn: "Needs a host's machinery to replicate.", why: "Why a virus is not considered alive." },
        ],
      },
      {
        id: "fungus",
        label: "Fungal body",
        hint: "Filaments, spores and saprophytic feeding.",
        shell: "ghost",
        rows: [
          { name: "Hyphae and mycelium", fn: "Threads and the mass they form — huge surface for absorption.", why: "Adaptation to absorption is the marked link." },
          { name: "Spores", fn: "Asexual or sexual reproductive units.", why: "Air dispersal is the standard advantage stated." },
          { name: "Chitin wall", fn: "Not cellulose — a key difference from plants.", why: "The most common classification question." },
        ],
      },
    ],
    theory: {
      look: "An elongated green bacterial cell with a beating orange flagellum, scattered blue plasmid circles and fine violet pili; beside it a pale blue icosahedral virus holding a yellow core of nucleic acid; and to the right a branching amber mycelium studded with red spores.",
      principle: "Bacteria are prokaryotes — no true nucleus, a circular chromosome with optional plasmids, a cell wall, and a flagellum for locomotion. Viruses are acellular: a single nucleic acid type enclosed in a protein capsid, reproducing only inside a host. Fungi are eukaryotes with chitin walls, feeding saprophytically by absorbing nutrients over a mycelium and dispersing spores. Each group's anatomy explains its nutritional mode, and that link is what earns classification marks.",
      why: "The prokaryote definition, plasmid and resistance, the single-nucleic-acid rule, why a virus is called non-living, chitin versus cellulose, and saprophytic absorption are the exact points asked.",
    },
  },

  /* ── Biomolecules ── */
  "bio-3d-biomolecules": {
    studio: "Biomolecules — the four classes at molecular level",
    blurb: "Real molecular models of a sugar, a fatty acid, an amino acid chain and a nucleotide: what each is built from, the bond that joins its units, and the test that identifies it.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "torus", r: 0.9, tube: 0.22 },
        at: [-4.6, 0.4, 0],
        material: "glass",
        color: 0x22d3ee,
        views: ["external", "carbs", "build"],
        label: { text: "Carbohydrate — ring sugar", sub: "monomers join by a glycosidic bond", at: [-8.6, 3.4, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [-3.0, 0.4, 0],
        material: "emissive",
        color: 0x38bdf8,
        repeat: { count: 4, spread: [1.0, 0.02, 0.02] },
        views: ["build"],
        label: { text: "Glycosidic bond", sub: "condensation — removes one water", at: [-2.6, 2.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-1.0, 0.8, 0], [0.4, 0.2, 0], [1.7, 0.8, 0], [3.0, 0.2, 0]], radius: 0.24 },
        at: [0.4, 0, 0],
        material: "wood",
        color: 0xfacc15,
        views: ["external", "lipids"],
        label: { text: "Fatty acid — hydrocarbon tail", sub: "non-polar, so it repels water", at: [2.2, 3.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.06 },
        at: [-0.6, 0.4, 0],
        material: "organ",
        color: 0xf59e0b,
        views: ["lipids"],
        label: { text: "Glycerol head", sub: "polar — the reason a lipid straddles a membrane", at: [-4.0, 3.6, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.24 },
        at: [3.6, 0.6, 0],
        material: "emissive",
        color: 0x22c55e,
        repeat: { ring: 1, radius: 0.9 },
        views: ["external", "proteins"],
        label: { text: "Amino acid", sub: "amino group + carboxyl group + R side chain", at: [5.4, 3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[3.6, -0.4, 0], [4.6, -1.0, 0], [5.6, -0.3, 0], [6.6, -1.1, 0], [7.4, -0.3, 0]], radius: 0.09 },
        material: "emissive",
        color: 0x16a34a,
        views: ["proteins"],
        label: { text: "Polypeptide — peptide bonds", sub: "sequence of R groups decides the protein", at: [7.4, 2.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[-4.6, -2.6, 0], [-3.6, -3.4, 0], [-2.6, -2.6, 0], [-1.6, -3.4, 0]], radius: 0.16 },
        material: "metal",
        color: 0xef4444,
        views: ["external", "nucleic"],
        label: { text: "Nucleotide", sub: "sugar + phosphate + nitrogenous base", at: [-5.6, -4.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "plane", w: 9, h: 2.6 },
        at: [1.0, -4.0, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["external"],
        label: { text: "Benedict's · Iodine · Biuret · Emulsion", sub: "each class has its own identifying test", at: [1.0, -5.6, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Four classes (real)",
        hint: "Carbohydrate, lipid, protein and nucleic acid side by side.",
        rows: [
          { name: "Carbohydrate", fn: "C, H, O with H:O as 2:1; the body's first energy source.", why: "The ratio and the energy role are both marked." },
          { name: "Lipid", fn: "Non-polar, so insoluble; highest energy per gram.", why: "Why fats store more energy than sugars." },
          { name: "Protein", fn: "Built of amino acids; controls structure and catalysis.", why: "Enzymes are proteins — the functional link." },
          { name: "Nucleic acid", fn: "Built of nucleotides; stores and transmits information.", why: "Distinguish from its energy-carrying cousin ATP." },
        ],
      },
      {
        id: "build",
        label: "Bonds & synthesis",
        hint: "How monomers become polymers.",
        rows: [
          { name: "Glycosidic bond", fn: "Joins two monosaccharides by condensation.", why: "Starch, glycogen and cellulose differ only in this linkage's geometry." },
          { name: "Peptide bond", fn: "Joins the carboxyl of one amino acid to the amino of the next.", why: "The bond's name and its formation are both asked." },
          { name: "Water removal", fn: "Every condensation releases one water molecule.", why: "The reverse, hydrolysis, is how digestion works." },
        ],
      },
      {
        id: "lipids",
        label: "Lipid structure",
        hint: "Why a fat behaves the way it does in water.",
        shell: "ghost",
        rows: [
          { name: "Glycerol + fatty acids", fn: "Triglyceride = one glycerol and three fatty acids.", why: "The ester linkage is the named bond." },
          { name: "Saturated vs unsaturated", fn: "Saturated has no C=C; unsaturated has one or more.", why: "The health and melting-point consequence follows." },
          { name: "Amphipathic", fn: "Phospholipids have a polar head and non-polar tails.", why: "This is the sole reason a bilayer forms." },
        ],
      },
      {
        id: "proteins",
        label: "Protein levels",
        hint: "From chain to working machine.",
        shell: "ghost",
        rows: [
          { name: "Primary", fn: "The amino-acid sequence.", why: "Sequence determines everything above it — the key idea." },
          { name: "Secondary", fn: "α-helix and β-pleated sheet held by hydrogen bonds.", why: "The two shapes and their bond must both be named." },
          { name: "Tertiary and quaternary", fn: "3D folding, then assembly of several chains.", why: "Haemoglobin is the standard quaternary example." },
          { name: "Denaturation", fn: "Heat or pH destroys the shape, not the sequence.", why: "The precision 'loses function, keeps sequence' earns the mark." },
        ],
      },
      {
        id: "nucleic",
        label: "Nucleotide",
        hint: "The unit that carries information.",
        shell: "ghost",
        rows: [
          { name: "Three parts", fn: "Pentose sugar, phosphate, nitrogenous base.", why: "All three must be listed for full marks." },
          { name: "ATP contrast", fn: "ATP has ribose and adenine but three phosphates.", why: "Why ATP is a nucleotide used for energy, not storage." },
          { name: "Phosphodiester bond", fn: "Links nucleotides into a strand.", why: "The named backbone linkage." },
        ],
      },
    ],
    theory: {
      look: "A cyan ring sugar, a yellow hydrocarbon zig-zag with an amber glycerol head, a ring of green amino acids running into a chain, and a red nucleotide built of a sugar, a phosphate and a base — with a violet strip listing the four identifying tests.",
      principle: "Biomolecules fall into four classes by their monomers and linkages. Carbohydrates are polyhydroxy aldehydes or ketones whose units join by glycosidic bonds. Lipids combine glycerol with fatty acids through ester bonds and are non-polar, which is why phospholipids form bilayers. Proteins are amino-acid chains joined by peptide bonds, folding through four structural levels where sequence determines shape and shape determines function. Nucleic acids are nucleotide polymers linked by phosphodiester bonds, and each class has a specific identifying test.",
      why: "The monomer–linkage–function chain for each class, condensation and hydrolysis, the amphipathic reason for the bilayer, the four protein levels and denaturation, and the distinguishing tests are all regularly examined.",
    },
  },

  /* ── Human systems ── */
  "bio-3d-human": {
    shellWord: "Skin",
    studio: "Human systems — the working body",
    blurb: "Real human systems in situ: the heart with its four chambers and valves, the lungs and the breathing mechanism, and the nephron where urine is actually formed.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 1.5, scale: [1, 1.2, 1], noise: 0.05 },
        at: [-4.6, 0.4, 0],
        material: "muscle",
        color: 0xb91c1c,
        motion: { kind: "pulse", amount: 0.03, speed: 1.4 },
        views: ["external", "heart", "nephron"],
        label: { text: "Heart", sub: "four chambers; two pumps in series", at: [-8.4, 3.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.06 },
        at: [-5.2, 1.2, 0],
        material: "organ",
        color: 0x7f1d1d,
        views: ["heart"],
        label: { text: "Right atrium", sub: "receives deoxygenated blood from the body", at: [-9.0, 0.8, 0], color: "#fca5a5" },
      },
      {
        shape: { kind: "sphere", r: 0.6, noise: 0.06 },
        at: [-4.2, -0.6, 0],
        material: "muscle",
        color: 0xdc2626,
        views: ["heart"],
        label: { text: "Left ventricle", sub: "thickest wall — pumps to the whole body", at: [-8.6, -2.0, 0], color: "#ef4444" },
      },
      {
        shape: { kind: "tube", points: [[-5.2, 0.6, 0], [-4.4, 1.0, 0], [-4.2, 0.0, 0]], radius: 0.16 },
        material: "membrane",
        color: 0xfacc15,
        views: ["heart"],
        label: { text: "Atrioventricular valves", sub: "prevent backflow into the atria", at: [-5.0, -3.6, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-5.6, 1.6, 0], [-6.2, 3.0, 0]], radius: 0.16 },
        material: "metal",
        color: 0x60a5fa,
        views: ["heart"],
        label: { text: "Vena cava → pulmonary artery", sub: "right side carries deoxygenated blood", at: [-8.6, 4.4, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 1.3, scale: [1, 0.9, 0.8], noise: 0.06 },
        at: [1.0, 1.4, 0],
        material: "mucosa",
        color: 0xf9a8d4,
        opacity: 0.6,
        repeat: { count: 2, spread: [1.9, 0, 0] },
        views: ["external", "respiration"],
        label: { text: "Lungs — alveoli", sub: "surface area for gas exchange", at: [3.4, 4.2, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "cylinder", r1: 0.3, h: 3.0 },
        at: [2.0, -1.8, 0],
        rot: [0.35, 0, 0.2],
        material: "membrane",
        color: 0xa5b4fc,
        views: ["respiration"],
        label: { text: "Trachea → bronchi", sub: "supported by C-shaped cartilage rings", at: [0.4, -3.6, 0], color: "#a5b4fc" },
      },
      {
        shape: { kind: "cone", r: 1.5, h: 2.2 },
        at: [1.0, -1.4, 0],
        material: "muscle",
        color: 0xea580c,
        views: ["respiration"],
        label: { text: "Diaphragm", sub: "contracts and flattens to draw air in", at: [-2.2, -3.6, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "tube", points: [[5.0, 3.0, 0], [5.6, 1.4, 0], [5.0, 0.2, 0], [5.9, -1.2, 0], [5.2, -2.4, 0]], radius: 0.16 },
        material: "emissive",
        color: 0x22d3ee,
        views: ["external", "nephron"],
        label: { text: "Nephron", sub: "the functional unit of the kidney", at: [8.4, 3.4, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.06 },
        at: [5.0, 2.6, 0],
        material: "organ",
        color: 0xdc2626,
        opacity: 0.7,
        views: ["nephron"],
        label: { text: "Glomerulus + Bowman's capsule", sub: "ultrafiltration under pressure", at: [8.0, 0.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[5.6, -1.2, 0], [6.6, -2.4, 0]], radius: 0.06 },
        material: "emissive",
        color: 0xfacc15,
        views: ["nephron"],
        label: { text: "Collecting duct → urine", sub: "reabsorption has already reclaimed the useful solutes", at: [8.6, -3.4, 0], color: "#fde047" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Digestive & circulatory (real)",
        hint: "The transport and absorption systems in place.",
        rows: [
          { name: "Gut wall", fn: "Villi with a rich capillary network absorb digested food.", why: "Surface area plus blood supply is the two-part answer." },
          { name: "Blood", fn: "Plasma, red cells, white cells and platelets.", why: "Each component's function is separately marked." },
          { name: "Double circulation", fn: "Blood passes the heart twice per circuit.", why: "Why the left ventricle wall is the thickest." },
        ],
      },
      {
        id: "heart",
        label: "Heart",
        hint: "Four chambers, two pumps, valves that enforce direction.",
        shell: "ghost",
        rows: [
          { name: "Four chambers", fn: "Two thin-walled atria receive; two thick-walled ventricles pump.", why: "Atrium-versus-ventricle wall thickness is asked." },
          { name: "Valves", fn: "Atrioventricular and semilunar valves prevent backflow.", why: "The consequence of valve failure must be stated." },
          { name: "Conduction", fn: "SA node sets the rhythm; the AV node relays it.", why: "Why the heart beats without nervous input." },
          { name: "Coronary supply", fn: "The heart muscle feeds itself through its own arteries.", why: "Basis of the heart-attack explanation." },
        ],
      },
      {
        id: "respiration",
        label: "Breathing mechanism",
        hint: "How air is drawn in and exchanged.",
        shell: "ghost",
        rows: [
          { name: "Inspiration", fn: "Diaphragm contracts and flattens; external intercostals lift the ribs.", why: "The pressure change must be stated as the reason." },
          { name: "Expiration", fn: "Muscles relax, volume falls, air is pushed out.", why: "Normally passive — a commonly missed detail." },
          { name: "Alveoli", fn: "Thin, moist, richly supplied with capillaries.", why: "Each of the three features is a mark." },
          { name: "Transport of O₂", fn: "Mostly as oxyhaemoglobin; CO₂ mostly as bicarbonate.", why: "The two carriers are always asked together." },
        ],
      },
      {
        id: "nephron",
        label: "Urine formation",
        hint: "Filter, reabsorb, secrete.",
        shell: "ghost",
        rows: [
          { name: "Ultrafiltration", fn: "Pressure in the glomerulus forces water and small solutes into the capsule.", why: "Why proteins and cells stay in the blood." },
          { name: "Selective reabsorption", fn: "Mostly in the proximal tubule — glucose, amino acids, salts and water.", why: "The 'selective' clause is required." },
          { name: "Loop of Henle", fn: "Creates the salt gradient that concentrates urine.", why: "The counter-current mechanism is the standard extension." },
          { name: "Tubular secretion", fn: "Adds wastes such as H⁺, K⁺ and drugs back into the filtrate.", why: "The third step is often forgotten." },
        ],
      },
    ],
    theory: {
      look: "A dark red beating heart with its chambers and yellow valves exposed, two translucent pink lungs above a violet trachea and orange diaphragm, and beside them a cyan tubule looping from a red glomerulus into a collecting duct.",
      principle: "Human systems work by maintaining gradients. The heart is a double pump whose thick-walled left ventricle drives blood round the whole body, with valves enforcing one-way flow and the SA node setting the rhythm. Breathing is a pressure mechanism: the diaphragm and intercostals change thoracic volume, so air moves down the pressure gradient into alveoli built for exchange. Each kidney's nephrons make urine in three steps — ultrafiltration in the glomerulus, selective reabsorption along the tubule, and tubular secretion — with the loop of Henle creating the gradient that concentrates it.",
      why: "The double circulation and wall-thickness link, valve direction, the SA node, the pressure basis of breathing with alveoli features, and the three named steps of urine formation are the recurring examination marks.",
    },
  },
};
