/**
 * Lab Studios — Physics B: quantum, modern physics, mechanics-II,
 * magnetism & EMI, elasticity & gas, and the measurement/vector suites.
 */

import type { StudioSpec } from "./types";

export const PHYSICS_B: Record<string, StudioSpec> = {
  /* ── Quantum ── */
  "ph-3d-quantum": {
    studio: "Quantum ideas — photons, thresholds and waves of matter",
    blurb: "A real photoelectric surface being struck by light, the threshold that stops emission, and a beam of electrons showing its own wave nature.",
    defaultView: "photoelectric",
    parts: [
      {
        shape: { kind: "box", size: [3.2, 2.4, 0.5] },
        at: [-3.4, 0, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["photoelectric", "threshold"],
        label: { text: "Metal surface", sub: "ejects electrons only above the threshold frequency", at: [-6.2, 3.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "tube", points: [[2.6, 1.2, 0], [0.6, 0.6, 0], [-1.8, 0.2, 0]], radius: 0.07, endRadius: 0.02 },
        material: "emissive",
        color: 0x8b5cf6,
        repeat: { count: 5, spread: [0, -0.7, 0.9] },
        views: ["photoelectric", "threshold"],
        label: { text: "Incident photons (hf)", sub: "energy arrives in packets, not continuously", at: [2.4, 3.4, 0], color: "#c4b5fd" },
      },
      {
        shape: { kind: "sphere", r: 0.14 },
        at: [-2.6, 1.0, 0],
        material: "emissive",
        color: 0x22d3ee,
        repeat: { count: 7, spread: [0.5, 1.4, 0.6] },
        views: ["photoelectric"],
        label: { text: "Photoelectrons", sub: "E_k = hf − φ — one photon frees one electron", at: [-2.4, 4.2, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "plane", w: 4.4, h: 2.2 },
        at: [4.6, 0, 0],
        material: "metal",
        color: 0x334155,
        views: ["photoelectric"],
        label: { text: "Collector (stopping potential)", sub: "eV₀ = E_k(max) — the classical way to read energy", at: [4.6, 3.2, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "tube", points: [[2.6, -1.4, 0], [0.4, -0.8, 0]], radius: 0.07, endRadius: 0.02 },
        material: "emissive",
        color: 0xf97316,
        repeat: { count: 4, spread: [0, 0.5, 0.8] },
        views: ["threshold"],
        label: { text: "Below threshold: nothing", sub: "intensity cannot substitute for frequency", at: [2.2, -3.0, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "tube", points: [[-6, 0, 0], [-3, 0.5, 0], [0, -0.5, 0], [3, 0.5, 0], [6, 0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x22c55e,
        views: ["matter"],
        motion: { kind: "wave", amplitude: 0.3, speed: 1.4 },
        label: { text: "Matter wave (de Broglie)", sub: "λ = h/mv — electrons diffract like light", at: [0, 3.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 1.2, scale: [1, 1, 0.4], noise: 0.03 },
        at: [0, 0, 0],
        material: "emissive",
        color: 0x38bdf8,
        opacity: 0.35,
        views: ["orbital"],
        label: { text: "Electron cloud", sub: "probability density, not a fixed path", at: [0, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.16 },
        at: [0, 0, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["orbital"],
        label: { text: "Nucleus", sub: "energy levels En = −13.6/n² eV (hydrogen)", at: [-3.8, -2.6, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "photoelectric",
        label: "Photoelectric effect",
        hint: "Light knocking electrons out of a metal.",
        rows: [
          { name: "Photon energy", fn: "E = hf; emission needs hf ≥ φ, the work function.", why: "The threshold frequency follows directly and is asked numerically." },
          { name: "Instant emission", fn: "No time lag even at low intensity.", why: "The observation that killed the wave-only theory." },
          { name: "Stopping potential", fn: "eV₀ = hf − φ.", why: "The experimental route to Planck's constant." },
        ],
      },
      {
        id: "threshold",
        label: "Threshold & intensity",
        hint: "Why brightness cannot compensate for low frequency.",
        shell: "ghost",
        rows: [
          { name: "One photon, one electron", fn: "Energy per photon depends on frequency, not intensity.", why: "The single most examined conceptual point." },
          { name: "Intensity's role", fn: "Intensity changes only the number of electrons, never their energy.", why: "Distinguishes classical and quantum predictions." },
          { name: "Graph", fn: "E_k(max) against f is a straight line of slope h.", why: "The line's intercepts are interpreted in numericals." },
        ],
      },
      {
        id: "matter",
        label: "Matter waves",
        hint: "Electrons carrying their own wavelength.",
        shell: "ghost",
        rows: [
          { name: "de Broglie relation", fn: "λ = h/p = h/mv.", why: "The formula and its numerical use are both asked." },
          { name: "Electron diffraction", fn: "Electrons form ring patterns through thin crystals.", why: "The experimental proof of wave nature." },
          { name: "Speed dependence", fn: "Faster particles have shorter wavelengths.", why: "Explains why everyday objects show no wave nature." },
        ],
      },
      {
        id: "orbital",
        label: "Atomic levels",
        hint: "Where the electron is allowed to be.",
        shell: "ghost",
        rows: [
          { name: "Stationary states", fn: "En = −13.6/n² eV for hydrogen.", why: "The basis of all energy-level numericals." },
          { name: "Photon emission", fn: "hf = E_high − E_low on falling to a lower level.", why: "Links spectra to the level diagram." },
          { name: "Ionisation", fn: "13.6 eV frees the electron from the ground state.", why: "The n = ∞ limit is asked directly." },
        ],
      },
    ],
    theory: {
      look: "A grey metal slab being struck by violet photon rays, cyan electrons flying off to a dark collector plate, an orange beam below the threshold surface showing no emission at all, and a green wavy electron trail stretched along the axis.",
      principle: "Light of frequency f delivers energy in quanta E = hf. A surface emits electrons only when hf exceeds the work function φ; the maximum kinetic energy is hf − φ, independent of intensity, which sets only how many electrons leave. Electrons themselves have wavelength λ = h/mv and diffract accordingly. In an atom the electron occupies stationary states of energy En = −13.6/n² eV, emitting a photon hf = E_high − E_low when it falls.",
      why: "The threshold-frequency argument, the intensity-versus-frequency distinction, the stopping-potential relation, the de Broglie wavelength, and the hydrogen level formula are the standard marks.",
    },
  },

  /* ── Mechanics II ── */
  "ph-3d-mechanics-i": {
    studio: "Mechanics II — momentum, collisions and rotation",
    blurb: "A real collision you can pause in your head: momentum conserved, energy maybe not, plus the rotating disc that defines moment of inertia.",
    defaultView: "collision",
    parts: [
      {
        shape: { kind: "box", size: [14, 0.4, 5] },
        at: [0, -1.8, 0],
        material: "stone",
        color: 0x1e293b,
        views: ["collision", "rotation"],
      },
      {
        shape: { kind: "sphere", r: 0.6 },
        at: [-3.4, 0.4, 0],
        material: "metal",
        color: 0xef4444,
        motion: { kind: "flow", from: [-4.4, 0.4, 0], to: [3.4, 0.4, 0], speed: 0.5, count: 3 },
        views: ["collision"],
        label: { text: "m₁ moving at u₁", sub: "momentum p = mu before contact", at: [-4.4, 3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.6 },
        at: [2.8, 0.4, 0],
        material: "metal",
        color: 0x3b82f6,
        views: ["collision"],
        label: { text: "m₂ at rest", sub: "u₂ = 0 — the standard set-up", at: [3.6, 2.8, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[-2.4, 0.4, 0], [2.2, 0.4, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xfacc15,
        views: ["collision"],
        label: { text: "Contact forces", sub: "equal and opposite — Newton's third law for the pair", at: [-0.2, 3.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "cylinder", r1: 2.0, h: 0.5 },
        at: [0, 0.2, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["rotation"],
        motion: { kind: "spin", axis: "y", speed: 1.2 },
        label: { text: "Rotating disc", sub: "I = ½MR² — mass at the rim costs most energy", at: [-4.0, 3.2, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [1.6, 0.7, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["rotation"],
        label: { text: "Mass near the axis", sub: "small I — easy to spin", at: [3.2, 3.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [-1.6, 0.7, 0],
        material: "organ",
        color: 0xf59e0b,
        views: ["rotation"],
        label: { text: "Mass at the rim", sub: "I = mr² — twice the radius, four times the inertia", at: [-4.4, 0.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "torus", r: 1.4, tube: 0.05 },
        at: [0, 0.7, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x38bdf8,
        views: ["rotation"],
        label: { text: "L = Iω conserved", sub: "the skater's spin speeds up as I falls", at: [0, -3.4, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "collision",
        label: "Collision",
        hint: "Two bodies meeting along a line.",
        rows: [
          { name: "Momentum conservation", fn: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂, always (no external force).", why: "The universal equation for every collision numerical." },
          { name: "Elastic collision", fn: "Kinetic energy also conserved; e = 1.", why: "Both conservation laws give two equations for two unknowns." },
          { name: "Inelastic collision", fn: "KE is lost to heat and deformation; e < 1.", why: "Why the bodies may move together after impact." },
          { name: "Perfectly inelastic", fn: "e = 0; the bodies stick and move with a common velocity.", why: "The maximum-loss case, asked as a limit." },
        ],
      },
      {
        id: "rotation",
        label: "Rotation",
        hint: "The disc, its inertia and its conserved angular momentum.",
        shell: "ghost",
        rows: [
          { name: "Moment of inertia", fn: "I = Σmr²; depends on where the mass sits, not just how much.", why: "The r² dependence is the reasoning mark." },
          { name: "Rotational KE", fn: "½Iω², the rotational analogue of ½mv².", why: "Rolling problems combine both forms." },
          { name: "Angular momentum", fn: "L = Iω is conserved when no external torque acts.", why: "Explains the spinning skater and the collapsing star alike." },
          { name: "Torque", fn: "τ = Iα is the rotational second law.", why: "The bridge from linear to rotational dynamics." },
        ],
      },
    ],
    theory: {
      look: "A dark bench with a red sphere rolling toward a resting blue one, a yellow contact band at the meeting point, and — beside the collision — a spinning metal disc carrying a green mass near its axis and an amber one at the rim, ringed by a blue angular-momentum circle.",
      principle: "In any collision the total momentum is conserved because the contact forces are equal and opposite; kinetic energy is conserved only when the collision is perfectly elastic, and is lost as heat and deformation otherwise, completely so when the bodies move off together. For rotation the moment of inertia I = Σmr² plays the role of mass: rotational kinetic energy is ½Iω², torque is τ = Iα, and with no external torque the angular momentum Iω stays constant.",
      why: "The momentum-first strategy, the coefficient-of-restitution cases, the r² meaning of moment of inertia, and conservation of angular momentum are the exact points examined.",
    },
  },

  /* ── Magnetism & EMI ── */
  "ph-3d-magnetism-emi": {
    studio: "Magnetism & EMI — from field to induced current",
    blurb: "A magnet plunging into a coil: the flux change, Lenz's direction rule, and Faraday's law that turns all of it into an emf you can calculate.",
    defaultView: "induction",
    parts: [
      {
        shape: { kind: "torus", r: 1.1, tube: 0.09 },
        at: [0, 0, 0],
        rot: [0, Math.PI / 2, 0],
        material: "metal",
        color: 0xb45309,
        repeat: { count: 8, spread: [0, 0, 3.2] },
        views: ["induction", "lenz"],
        label: { text: "Coil", sub: "N turns — the emf multiplies by N", at: [-3.6, 3.2, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "cylinder", r1: 0.35, h: 2.4 },
        at: [0, 1.6, 1.4],
        material: "metal",
        color: 0xdc2626,
        rot: [Math.PI / 2, 0, 0],
        views: ["induction", "lenz"],
        motion: { kind: "flow", from: [0, 1.6, 4.4], to: [0, 1.6, 0.8], speed: 0.3, count: 2 },
        label: { text: "Bar magnet (N leading)", sub: "moving in changes the flux through the coil", at: [3.6, 3.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "plane", w: 3.4, h: 3.4 },
        at: [0, 0, 0.4],
        rot: [0, 0, 0],
        material: "emissive",
        color: 0x22c55e,
        opacity: 0.35,
        views: ["induction"],
        label: { text: "Flux Φ = BA", sub: "field × area it threads", at: [-4.6, -3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[1.6, 0, 0], [3.4, 0, 0], [3.4, -2.4, 0], [1.4, -2.4, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["induction"],
        label: { text: "Induced current", sub: "flows only while the magnet moves", at: [5.2, -1.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "cylinder", r1: 0.9, h: 0.2 },
        at: [0, 0, 0],
        rot: [0, 0, Math.PI / 2],
        material: "emissive",
        color: 0xef4444,
        views: ["lenz"],
        label: { text: "Induced pole: N facing N", sub: "opposes the approach — Lenz's law in one picture", at: [-4.4, -2.8, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, 2.4, 1.2], [0, 0.2, 0.4]], radius: 0.03 },
        material: "emissive",
        color: 0xfacc15,
        views: ["lenz"],
        label: { text: "Back-push (work done)", sub: "you must push against the induced field — that work becomes electrical energy", at: [2.6, 4.2, 0], color: "#fde047" },
      },
      {
        shape: { kind: "torus", r: 1.2, tube: 0.1 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "metal",
        color: 0x94a3b8,
        motion: { kind: "spin", axis: "y", speed: 2.0 },
        views: ["generator"],
        label: { text: "Rotating coil in a field", sub: "the AC generator: flux varies sinusoidally", at: [-4.2, 3.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "plane", w: 5, h: 5 },
        at: [0, -0.2, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x8b5cf6,
        opacity: 0.25,
        repeat: { count: 3, spread: [0, 0.9, 0] },
        views: ["generator"],
        label: { text: "Uniform field B between poles", sub: "flux through the coil = BA cos ωt", at: [4.4, -2.6, 0], color: "#c4b5fd" },
      },
      {
        shape: { kind: "tube", points: [[-1.8, 0.2, 0], [-1.8, 2.8, 0]], radius: 0.06 },
        material: "emissive",
        color: 0x22d3ee,
        views: ["generator"],
        label: { text: "Brushes + slip rings", sub: "take the alternating emf out", at: [-4.4, -2.2, 0], color: "#67e8f9" },
      },
    ],
    views: [
      {
        id: "induction",
        label: "Faraday's law",
        hint: "A moving magnet threading a coil.",
        rows: [
          { name: "Faraday's law", fn: "ε = −N dΦ/dt — emf is proportional to the rate of flux change.", why: "The minus sign and the N factor are both marked." },
          { name: "Flux", fn: "Φ = BA cos θ; flux changes when B, A or θ changes.", why: "Three separate routes to an emf, each examined." },
          { name: "Current only while moving", fn: "A stationary magnet induces nothing.", why: "The classic conceptual discriminator." },
        ],
      },
      {
        id: "lenz",
        label: "Lenz's law",
        hint: "The direction of the induced current.",
        shell: "ghost",
        rows: [
          { name: "Lenz's law", fn: "The induced current opposes the change producing it.", why: "Needed for every direction question." },
          { name: "Energy conservation", fn: "The opposition is why work must be done to generate electricity.", why: "The 'why the minus sign' explanation earns the mark." },
          { name: "Eddy currents", fn: "The same rule in bulk metal — basis of magnetic braking.", why: "The standard application extension." },
        ],
      },
      {
        id: "generator",
        label: "AC generator",
        hint: "The coil spinning in a uniform field.",
        shell: "ghost",
        rows: [
          { name: "Sinusoidal emf", fn: "ε = NBAω sin ωt from the rotating coil.", why: "The amplitude expression is asked directly." },
          { name: "Peak emf", fn: "ε₀ = NBAω — larger coils, stronger fields, faster rotation.", why: "Each factor's effect is a short numerical." },
          { name: "Slip rings vs commutator", fn: "Slip rings give AC; a commutator rectifies to DC.", why: "The distinguishing hardware question." },
        ],
      },
    ],
    theory: {
      look: "An amber coil of eight rings facing a red bar magnet dropping toward it, a translucent green flux disc inside the coil, a blue current loop round the circuit, and — in the generator view — a silver coil spinning between violet field plates with cyan brushes.",
      principle: "A changing magnetic flux through a coil induces an emf ε = −N dΦ/dt. The induced current flows in whatever direction opposes the change (Lenz's law), which is why generating electricity always requires work. In an AC generator the coil rotates in a uniform field, so the flux varies as cos ωt and the emf is sinusoidal with peak value NBAω; slip rings deliver the alternating output while a commutator would rectify it.",
      why: "Faraday's law with its minus sign, the three ways flux can change, Lenz's law as energy conservation, and the peak-emf expression for the generator are the recurring marks.",
    },
  },

  /* ── Elasticity & gas ── */
  "ph-3d-elasticity-gas": {
    studio: "Elasticity & gas laws — springs, wires and pistons",
    blurb: "A stretched wire obeying Hooke's law up to its elastic limit, beside a gas column whose P, V and T relations can each be seen at constant others.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cylinder", r1: 0.14, h: 5.0 },
        at: [-3.6, 0.6, 0],
        material: "metal",
        color: 0xb45309,
        views: ["external", "hooke"],
        label: { text: "Stretched wire", sub: "stress = F/A, strain = ΔL/L", at: [-6.4, 3.2, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "tube", points: [[-3.6, -1.9, 0], [-3.6, -3.4, 0]], radius: 0.1, endRadius: 0.04 },
        material: "emissive",
        color: 0xef4444,
        views: ["hooke"],
        label: { text: "Load F", sub: "within the elastic limit, F ∝ extension", at: [-6.0, -3.8, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[-2.4, -1.0, 0], [-1.4, 0.2, 0], [-0.2, -1.0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x22c55e,
        views: ["hooke"],
        label: { text: "Elastic limit", sub: "beyond it the wire never regains its length", at: [0.8, -3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "cylinder", r1: 1.1, h: 4.4 },
        at: [2.6, 0, 0],
        material: "glass",
        color: 0xdbeafe,
        views: ["external", "gas"],
        label: { text: "Gas column", sub: "fixed n — the state is (P, V, T)", at: [5.6, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "cylinder", r1: 1.05, h: 0.4 },
        at: [2.6, 1.6, 0],
        material: "metal",
        color: 0x64748b,
        views: ["gas"],
        label: { text: "Piston", sub: "Boyle's law: P ∝ 1/V at constant T", at: [5.4, 1.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "cone", r: 1.0, h: 1.6 },
        at: [2.6, -2.6, 0],
        material: "emissive",
        color: 0xf97316,
        views: ["gas"],
        label: { text: "Heater", sub: "Charles's law: V ∝ T at constant P", at: [5.4, -3.6, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "plane", w: 6, h: 3.4 },
        at: [-3.4, -4.6, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["external"],
        label: { text: "PV = nRT", sub: "one equation, three named special cases", at: [-3.4, -6.0, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Apparatus (real)",
        hint: "A loaded wire beside a piston of gas.",
        rows: [
          { name: "Elasticity", fn: "The body regains its shape when the load is removed.", why: "Distinguishes elastic from plastic behaviour." },
          { name: "Gas state", fn: "Fixed by pressure, volume and temperature together.", why: "State variables versus path variables." },
        ],
      },
      {
        id: "hooke",
        label: "Hooke's law & elasticity",
        hint: "Stress, strain and the elastic limit.",
        shell: "ghost",
        rows: [
          { name: "Hooke's law", fn: "F = kx within the elastic limit.", why: "The spring constant and its units are asked." },
          { name: "Young's modulus", fn: "Y = stress/strain = (F/A)/(ΔL/L).", why: "The definition plus its numerical use." },
          { name: "Elastic limit", fn: "Beyond it the deformation is permanent.", why: "The boundary on every stress–strain graph." },
          { name: "Elastic PE", fn: "Energy stored = ½kx² = ½ × stress × strain × volume.", why: "The energy form is asked in work–energy numericals." },
        ],
      },
      {
        id: "gas",
        label: "Gas laws",
        hint: "Each law holds the other two variables fixed.",
        shell: "ghost",
        rows: [
          { name: "Boyle's law", fn: "PV = constant at constant T.", why: "The isothermal case of the ideal-gas equation." },
          { name: "Charles's law", fn: "V/T = constant at constant P.", why: "Leads directly to absolute zero." },
          { name: "Pressure law", fn: "P/T = constant at constant V.", why: "The isochoric case — why sealed containers burst." },
          { name: "Ideal-gas equation", fn: "PV = nRT combines all three.", why: "The general law every numerical reduces to." },
        ],
      },
    ],
    theory: {
      look: "A copper wire hanging with a red load stretching it and a green strain curve, beside a glass cylinder of blue gas with a grey piston above an orange heater, and a violet strip carrying the combined gas equation.",
      principle: "Within the elastic limit a wire obeys Hooke's law: extension is proportional to load, or stress proportional to strain, with Young's modulus Y as the constant; energy ½kx² is stored and recovered, but past the elastic limit the deformation becomes permanent. For a fixed amount of gas, PV = nRT governs the state, and holding all but two variables fixed recovers Boyle's law (PV constant), Charles's law (V ∝ T) and the pressure law (P ∝ T).",
      why: "Stress–strain vocabulary, Young's modulus and stored energy, the elastic limit, and each gas law with the variable held constant are the standard marks.",
    },
  },

  /* ── Measurement & vectors suites ── */
  "ph-3d-measurement": {
    studio: "Measurement — precision you can hold",
    blurb: "Vernier calipers, micrometer screw gauge, spherometer and a travelling microscope: the instrument, the reading it gives, and the least count that decides how good the reading is.",
    defaultView: "vernier",
    parts: [
      {
        shape: { kind: "box", size: [6.5, 0.35, 0.8] },
        at: [-2.6, 0, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["vernier"],
        label: { text: "Vernier calipers", sub: "main scale + vernier scale", at: [-2.6, 2.4, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "box", size: [1.1, 0.22, 0.55] },
        at: [-4.4, -0.15, 0],
        material: "metal",
        color: 0x64748b,
        views: ["vernier"],
        label: { text: "Vernier scale (n divisions)", sub: "LC = 1 MSD − 1 VSD, typically 0.1 mm", at: [-4.6, -2.4, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "cylinder", r1: 0.5, h: 3.2 },
        at: [3.0, 0.2, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0xb45309,
        views: ["micrometer"],
        label: { text: "Micrometer screw gauge", sub: "LC = pitch / number of circular divisions", at: [3.0, 3.0, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "cylinder", r1: 0.85, h: 0.3 },
        at: [4.6, 0.2, 0],
        rot: [0, 0, Math.PI / 2],
        material: "metal",
        color: 0x475569,
        views: ["micrometer"],
        label: { text: "Thimble (circular scale)", sub: "one full turn advances exactly one pitch", at: [4.4, -2.6, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "cylinder", r1: 0.12, h: 4.4 },
        at: [0, 0.2, 0],
        material: "metal",
        color: 0x38bdf8,
        views: ["travelling"],
        label: { text: "Travelling microscope", sub: "reads to 0.01 mm along a vertical scale", at: [2.6, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "plane", w: 8, h: 3 },
        at: [0, -2.8, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["travelling"],
        label: { text: "Thickness of a hair / wire diameter", sub: "count divisions between the reference marks", at: [-2.6, -4.2, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "cylinder", r1: 0.55, r2: 0.55, h: 0.16 },
        at: [3.4, 2.4, 0],
        material: "metal",
        color: 0xa3a3a3,
        views: ["spherometer"],
        label: { text: "Spherometer (3 legs + central screw)", sub: "measures the sagitta h of a curved surface", at: [3.4, 5.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[3.4, 2.32, 0], [3.4, 0.7, 0]], radius: 0.05 },
        material: "metal",
        color: 0x737373,
        views: ["spherometer"],
        label: { text: "Central screw", sub: "R = a²/6h + h/2", at: [6.2, 0.7, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "tube", points: [[3.4, 2.32, 0], [2.72, 1.0, 0]], radius: 0.045 },
        material: "metal",
        color: 0x8b8b8b,
        views: ["spherometer"],
      },
      {
        shape: { kind: "tube", points: [[3.4, 2.32, 0], [4.08, 1.0, 0]], radius: 0.045 },
        material: "metal",
        color: 0x8b8b8b,
        views: ["spherometer"],
      },
      {
        shape: { kind: "tube", points: [[3.4, 2.32, 0], [3.4, 1.0, -1.12]], radius: 0.045 },
        material: "metal",
        color: 0x8b8b8b,
        views: ["spherometer"],
        label: { text: "Three legs, mean spacing a", sub: "set on a plane glass slab for zero error", at: [0.6, 3.4, 0], color: "#86efac" },
      },
    ],
    views: [
      {
        id: "vernier",
        label: "Vernier calipers",
        hint: "Reading to a tenth of a millimetre.",
        rows: [
          { name: "Least count", fn: "LC = 1 main-scale division − 1 vernier division.", why: "The formula and its value (0.1 mm or 0.01 cm) are asked." },
          { name: "Zero error", fn: "Correct the reading if the jaws close off the zero mark.", why: "Positive and negative zero errors are distinguished in numericals." },
          { name: "Reading", fn: "Main scale + (vernier coincidence × LC).", why: "The two-step reading procedure is examined directly." },
        ],
      },
      {
        id: "micrometer",
        label: "Screw gauge",
        hint: "Reading to a hundredth of a millimetre.",
        rows: [
          { name: "Pitch", fn: "Distance the screw advances per full turn — the standard 0.5 mm.", why: "Pitch divided by head divisions gives the least count." },
          { name: "Least count", fn: "LC = pitch ÷ number of circular-scale divisions.", why: "The standard 0.5 mm pitch / 50 divisions = 0.01 mm." },
          { name: "Reading", fn: "Main (pitch) scale + circular-scale reading × LC.", why: "Same structure as vernier, different scales." },
          { name: "Backlash error", fn: "Approach every reading turning the same way.", why: "The practical precaution is a one-mark item." },
        ],
      },
      {
        id: "spherometer",
        label: "Spherometer",
        hint: "The sagitta relation for a curved surface.",
        rows: [
          { name: "Least count", fn: "Pitch ÷ circular divisions, typically 0.01 mm.", why: "Same logic as the screw gauge, different numbers." },
          { name: "Radius formula", fn: "R = a²/6h + h/2, with a the mean leg spacing.", why: "The formula and the meaning of a and h are both asked." },
          { name: "Sign convention", fn: "h is positive for a convex surface, negative for concave.", why: "Decides which face of a lens you are measuring." },
        ],
      },
      {
        id: "travelling",
        label: "Travelling microscope",
        hint: "For very small vertical separations.",
        rows: [
          { name: "Use", fn: "Refractive index of a glass slip, capillary bore, wire diameter.", why: "The standard experiments it serves are asked." },
          { name: "Vernier on a vertical scale", fn: "Same LC logic, mounted to slide vertically.", why: "Shows it is a vernier, not a new principle." },
        ],
      },
    ],
    theory: {
      look: "A silver caliper with its sliding vernier jaw, an amber screw gauge with its dark knurled thimble, a three-legged spherometer with its central screw, and a slender blue travelling microscope over a violet reference plate — each instrument carrying a label naming its least count.",
      principle: "Every measurement instrument is defined by its least count: the smallest interval it can resolve. A vernier calipers reaches a tenth of a millimetre by subtracting one vernier division from one main-scale division; a screw gauge reaches a hundredth by dividing the screw's pitch by the number of circular-scale divisions; a spherometer relates the sagitta h of a curved surface to its radius by R = a²/6h + h/2; and a travelling microscope is a vertical vernier used for very small separations. Correct readings also need zero-error correction, taken with the jaws just closed.",
      why: "The least-count formulas, the reading procedure, zero error with its sign, the sagitta formula, and which instrument suits which experiment are the exact practical marks.",
    },
  },

  "ph-3d-vectors-full": {
    studio: "Vectors — addition you can walk around",
    blurb: "Two real forces on a ring, their parallelogram completed in space, and the resolution into components that turns every vector problem into arithmetic.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.3 },
        at: [0, 0, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["external", "parallelogram", "components"],
        label: { text: "Point O", sub: "where all vectors act", at: [-2.6, -2.6, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [4.2, 1.6, 0]], radius: 0.1, endRadius: 0.03 },
        material: "emissive",
        color: 0xef4444,
        views: ["external", "parallelogram", "components"],
        label: { text: "Vector A", sub: "magnitude + direction — nothing else", at: [4.6, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [1.6, 3.4, 0]], radius: 0.1, endRadius: 0.03 },
        material: "emissive",
        color: 0x3b82f6,
        views: ["external", "parallelogram", "components"],
        label: { text: "Vector B", sub: "the second effect on the same point", at: [-3.6, 3.4, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [5.8, 5.0, 0]], radius: 0.1, endRadius: 0.03 },
        material: "emissive",
        color: 0x22c55e,
        views: ["parallelogram"],
        label: { text: "Resultant R", sub: "the diagonal of the parallelogram they span", at: [5.4, 5.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[4.2, 1.6, 0], [5.8, 5.0, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x64748b,
        views: ["parallelogram"],
      },
      {
        shape: { kind: "tube", points: [[1.6, 3.4, 0], [5.8, 5.0, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x64748b,
        views: ["parallelogram"],
      },
      {
        shape: { kind: "tube", points: [[4.2, 0, 0], [4.2, 1.6, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["components"],
        label: { text: "A cos θ and A sin θ", sub: "resolve along the axes — then add separately", at: [4.8, -2.6, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[0, 1.6, 0], [4.2, 1.6, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xa855f7,
        views: ["components"],
        label: { text: "R = √(Ax² + Bx²) , tan θ = ΣFy/ΣFx", sub: "the two formulas every resultant reduces to", at: [-0.6, 4.6, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Two vectors (real)",
        hint: "Two arrows from one point.",
        rows: [
          { name: "Vector", fn: "Has magnitude and direction; scalars have only magnitude.", why: "Classifying quantities is the opening mark of every vector question." },
          { name: "Representation", fn: "Length gives magnitude, arrowhead-free line gives direction.", why: "The house rule: direction is read from the line, never from an arrow decoration." },
        ],
      },
      {
        id: "parallelogram",
        label: "Parallelogram law",
        hint: "The diagonal is the resultant.",
        shell: "ghost",
        rows: [
          { name: "Parallelogram law", fn: "R = √(A² + B² + 2AB cos θ).", why: "The formula and its maximum/minimum limits are asked." },
          { name: "Special cases", fn: "θ = 0 gives A + B; θ = 180° gives A − B; θ = 90° gives √(A² + B²).", why: "The three limits are standard one-liners." },
          { name: "Equilibrium", fn: "Three concurrent forces in equilibrium give Lami's theorem.", why: "The standard extension for a point at rest." },
        ],
      },
      {
        id: "components",
        label: "Resolution",
        hint: "Split along the axes, then recombine.",
        shell: "ghost",
        rows: [
          { name: "Components", fn: "A cos θ along x, A sin θ along y.", why: "The reverse (recombination) uses the same pair." },
          { name: "Adding vectors", fn: "Add x-components together, then y-components, then recombine.", why: "The universal algorithm for many-force problems." },
          { name: "Unit vectors", fn: "A = Ax î + Ay ĵ + Az k̂.", why: "The notation in which all 3D problems are written." },
        ],
      },
    ],
    theory: {
      look: "A yellow point where a red and a blue vector spring out, grey completion lines drawing the parallelogram with its green diagonal resultant, and amber/purple drops showing how each vector resolves onto the axes.",
      principle: "A vector carries magnitude and direction and must be added geometrically. Two vectors from one point span a parallelogram whose diagonal is their resultant, R = √(A² + B² + 2AB cos θ), with the special cases of θ = 0°, 90° and 180°. Equivalently, each vector is resolved into perpendicular components — A cos θ and A sin θ — summed separately along each axis, and recombined by Pythagoras.",
      why: "The parallelogram formula, its three limiting cases, the resolution algorithm, and Lami's theorem for equilibrium are the recurring marks.",
    },
  },

  "ph-3d-vectors-classic": {
    studio: "Vectors — the classic board",
    blurb: "The traditional vector board: forces in equilibrium on a ring, the triangle they close, and the unit-vector notation that organises it all.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "plane", w: 12, h: 8 },
        at: [0, 0, -0.3],
        material: "stone",
        color: 0x1e293b,
        views: ["external", "equilibrium", "triangle"],
      },
      {
        shape: { kind: "torus", r: 0.4, tube: 0.09 },
        at: [0, 0, 0],
        material: "metal",
        color: 0xfacc15,
        views: ["external", "equilibrium"],
        label: { text: "Ring in equilibrium", sub: "zero resultant — the ring does not move", at: [-3.6, 3.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [3.6, 2.0, 0]], radius: 0.08, endRadius: 0.03 },
        material: "emissive",
        color: 0xef4444,
        views: ["external", "equilibrium", "triangle"],
        label: { text: "Tension T₁", sub: "one of three pulls on the ring", at: [4.4, 3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [-2.8, 2.8, 0]], radius: 0.08, endRadius: 0.03 },
        material: "emissive",
        color: 0x3b82f6,
        views: ["external", "equilibrium", "triangle"],
        label: { text: "Tension T₂", sub: "at a different angle — the direction matters", at: [-4.6, 3.6, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [0, -3.4, 0]], radius: 0.08, endRadius: 0.03 },
        material: "emissive",
        color: 0x22c55e,
        views: ["external", "equilibrium", "triangle"],
        label: { text: "Weight W", sub: "the third force, straight down", at: [2.4, -3.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[3.6, 2.0, 0], [-2.8, 2.8, 0], [0, -3.4, 0], [3.6, 2.0, 0]], radius: 0.045 },
        material: "emissive",
        color: 0xa855f7,
        views: ["triangle"],
        label: { text: "Closed triangle", sub: "forces in equilibrium form a closed head-to-tail loop", at: [0.2, 4.8, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "tube", points: [[-5.4, -2.6, 0], [-4.2, -2.6, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["triangle"],
        label: { text: "î, ĵ, k̂ notation", sub: "every vector as a sum of unit vectors", at: [-4.4, -4.2, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Three forces (real)",
        hint: "The ring pulled three ways at once.",
        rows: [
          { name: "Equilibrium", fn: "The resultant of all forces on the ring is zero.", why: "The condition is the first line of every solution." },
          { name: "Concurrent forces", fn: "All three act through one point.", why: "Concurrence is what allows Lami's theorem." },
        ],
      },
      {
        id: "equilibrium",
        label: "Lami's theorem",
        hint: "Each force over the sine of the angle between the other two.",
        shell: "ghost",
        rows: [
          { name: "Lami's theorem", fn: "T₁/sin α = T₂/sin β = W/sin γ.", why: "The fastest route to three-force equilibrium numbers." },
          { name: "Angle identification", fn: "Each angle is between the other two forces.", why: "Misreading the angle is the classic lost mark." },
        ],
      },
      {
        id: "triangle",
        label: "Triangle & components",
        hint: "Head-to-tail closure and the unit-vector form.",
        shell: "ghost",
        rows: [
          { name: "Triangle law", fn: "Vectors in equilibrium close a head-to-tail triangle.", why: "The graphic statement of zero resultant." },
          { name: "Unit vectors", fn: "F = Fx î + Fy ĵ + Fz k̂.", why: "The notation every 3D numerical is written in." },
          { name: "Checking", fn: "ΣFx = 0, ΣFy = 0, ΣFz = 0.", why: "The algebraic test that earns the verification mark." },
        ],
      },
    ],
    theory: {
      look: "A dark board with a yellow ring pulled by red, blue and green lines, a violet triangle joining the three force heads, and a blue unit-vector legend at the corner.",
      principle: "When three concurrent forces hold a point in equilibrium, their resultant is zero: the forces close a head-to-tail triangle, and each force divided by the sine of the angle between the other two is the same constant (Lami's theorem). Component-wise the condition is ΣFx = ΣFy = ΣFz = 0, written compactly with unit vectors î, ĵ, k̂.",
      why: "The equilibrium condition, Lami's theorem with correct angle identification, the triangle law, and the component check are the standard marks.",
    },
  },
};
