/**
 * Lab Studios — Biology B: ecology, evolution, floral diversity,
 * conservation and the syllabus/theory suites.
 */

import type { StudioSpec } from "./types";

export const BIOLOGY_B: Record<string, StudioSpec> = {
  /* ── Ecology ── */
  "bio-3d-ecology": {
    studio: "Ecology — energy flowing through a real ecosystem",
    blurb: "A pond ecosystem with its trophic levels stacked in place: light entering, producers fixing it, herbivores eating them, and the decomposers closing the loop.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cylinder", r1: 6.5, h: 2.4 },
        at: [0, -1.8, 0],
        material: "glass",
        color: 0x22d3ee,
        opacity: 0.28,
        views: ["external", "foodchain", "nutrient"],
        label: { text: "Pond ecosystem", sub: "producers → consumers → decomposers", at: [0, 2.6, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "plane", w: 10, h: 1 },
        at: [0, 3.6, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["foodchain"],
        label: { text: "Solar energy — the only input", sub: "all energy enters here, one way", at: [0, 5.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.1 },
        at: [-3.0, -0.8, 0],
        material: "organ",
        color: 0x22c55e,
        repeat: { count: 4, spread: [1.2, 0.3, 0.8] },
        views: ["external", "foodchain"],
        label: { text: "Producers (phytoplankton)", sub: "fix light into chemical energy — trophic level 1", at: [-4.6, -3.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.06 },
        at: [-0.6, -0.6, 0],
        material: "organ",
        color: 0xf59e0b,
        repeat: { count: 3, spread: [1.0, 0.3, 0.6] },
        views: ["external", "foodchain"],
        label: { text: "Primary consumers (zooplankton)", sub: "eat the producers — level 2", at: [0.2, -3.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.55, scale: [1.4, 0.7, 0.5], noise: 0.05 },
        at: [2.4, -0.4, 0],
        material: "wetSkin",
        color: 0x3b82f6,
        repeat: { count: 2, spread: [1.4, 0.2, 0.6] },
        views: ["external", "foodchain"],
        label: { text: "Secondary consumers (fish)", sub: "eat the herbivores — level 3", at: [3.0, 2.2, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "tube", points: [[-3.0, -0.2, 0], [-0.6, 0, 0], [1.6, -0.2, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf97316,
        views: ["foodchain"],
        label: { text: "Food chain", sub: "only ~10% of energy passes each level", at: [-0.4, 2.0, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "sphere", r: 0.4, noise: 0.2 },
        at: [4.6, -1.4, 0],
        material: "wood",
        color: 0x7c4a1e,
        repeat: { count: 3, spread: [1.0, 0.4, 0.8] },
        views: ["external", "nutrient"],
        label: { text: "Decomposers (bacteria, fungi)", sub: "return nutrients — without them the cycle stops", at: [4.6, -3.8, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "torus", r: 2.2, tube: 0.05 },
        at: [0, -1.6, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0xa855f7,
        views: ["nutrient"],
        label: { text: "Nutrient cycle", sub: "matter cycles; energy only flows through", at: [-2.6, 1.6, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Ecosystem (real)",
        hint: "A pond with all its living and non-living parts.",
        rows: [
          { name: "Ecosystem", fn: "All organisms in an area plus their physical environment.", why: "The definition must include both parts." },
          { name: "Biotic components", fn: "Producers, consumers and decomposers.", why: "Classifying each organism is the opening mark." },
          { name: "Abiotic components", fn: "Light, temperature, water, minerals.", why: "These set the carrying capacity." },
        ],
      },
      {
        id: "foodchain",
        label: "Energy flow",
        hint: "Why food chains are short.",
        shell: "ghost",
        rows: [
          { name: "10% law", fn: "Roughly a tenth of the energy passes each trophic level.", why: "Explains why top predators are rare." },
          { name: "Trophic levels", fn: "Producer → primary → secondary → tertiary consumer.", why: "The numbering is asked directly." },
          { name: "Food web", fn: "Interconnected chains give stability.", why: "Why monocultures are fragile." },
        ],
      },
      {
        id: "nutrient",
        label: "Nutrient cycling",
        hint: "Matter cycles while energy escapes as heat.",
        shell: "ghost",
        rows: [
          { name: "Decomposers", fn: "Break dead matter into usable minerals.", why: "The step that closes every cycle." },
          { name: "Carbon cycle", fn: "Photosynthesis fixes CO₂; respiration returns it.", why: "The balance and its human disturbance." },
          { name: "Nitrogen cycle", fn: "Fixation, nitrification, assimilation, denitrification.", why: "Each step's microbes are asked." },
        ],
      },
    ],
    theory: {
      look: "A translucent cyan pond holding green phytoplankton clusters, amber zooplankton, blue fish, brown decomposer blobs, with a yellow sunlight band above, an orange chain linking the trophic levels and a violet nutrient ring below.",
      principle: "An ecosystem consists of biotic communities — producers, consumers and decomposers — interacting with abiotic factors. Energy enters once as sunlight, is fixed by producers, and passes upward with roughly 90% lost at each step, which is why chains rarely exceed four levels. Unlike energy, matter cycles: decomposers return the elements of dead matter to the soil, closing the carbon and nitrogen cycles.",
      why: "The 10% law, trophic-level numbering, the role of decomposers, and the one-way-energy-versus-cycling-matter contrast are the recurring marks.",
    },
  },

  /* ── Evolution ── */
  "bio-3d-evolution": {
    studio: "Evolution — variation, selection and descent",
    blurb: "A real population of varied individuals: the environment removes some, the survivors breed, and the frequency of traits shifts — natural selection made visible.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "plane", w: 13, h: 7 },
        at: [0, -1.8, 0],
        material: "stone",
        color: 0x3f3f2e,
        views: ["external", "selection"],
        label: { text: "Environment — the selector", sub: "decides which variations survive", at: [0, -3.6, 0], color: "#a3a380" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.08 },
        at: [-3.6, 0.2, 0],
        material: "wetSkin",
        color: 0x84cc16,
        repeat: { count: 6, spread: [0.9, 0.4, 0.7] },
        views: ["external", "selection"],
        label: { text: "Variation within the population", sub: "no two individuals identical — the raw material", at: [-4.4, 3.0, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.08 },
        at: [0.2, 0.4, 0],
        material: "wetSkin",
        color: 0x22c55e,
        repeat: { count: 4, spread: [0.9, 0.4, 0.7] },
        views: ["selection"],
        label: { text: "Better-adapted survivors", sub: "reproduce more — differential survival", at: [1.0, 3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.24, noise: 0.08 },
        at: [3.8, 0.0, 0],
        material: "wetSkin",
        color: 0x94a3b8,
        opacity: 0.4,
        repeat: { count: 4, spread: [0.9, 0.4, 0.7] },
        views: ["selection"],
        label: { text: "Less-adapted removed", sub: "not destroyed — just out-reproduced", at: [4.4, 3.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "tube", points: [[-3.6, 1.4, 0], [-1.8, 2.2, 0], [0.2, 1.4, 0], [2.4, 2.2, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["external"],
        label: { text: "Descent with modification", sub: "species change over generations — Darwin's phrase", at: [0, 4.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.34, noise: 0.06 },
        at: [-4.8, -0.6, 1.6],
        material: "organ",
        color: 0x78716c,
        views: ["fossils"],
        repeat: { count: 3, spread: [1.6, 0.2, 1.0] },
        label: { text: "Fossils", sub: "the direct record that life has changed", at: [-4.8, -2.8, 1.6], color: "#d6d3d1" },
      },
      {
        shape: { kind: "tube", points: [[-1.2, 0.2, 1.2], [0, 1.0, 1.2], [1.4, 0.2, 1.2], [2.8, 1.2, 1.2]], radius: 0.14 },
        material: "organ",
        color: 0xf472b6,
        views: ["fossils"],
        label: { text: "Homologous organs", sub: "same structure, different function — common ancestry", at: [1.0, 3.4, 1.2], color: "#f9a8d4" },
      },
      {
        shape: { kind: "tube", points: [[3.0, -0.4, 1.2], [3.6, 0.8, 1.2]], radius: 0.14 },
        material: "organ",
        color: 0x22d3ee,
        views: ["fossils"],
        label: { text: "Analogous organs", sub: "different structure, same function — convergent evolution", at: [4.8, 2.2, 1.2], color: "#67e8f9" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Population (real)",
        hint: "A varied population in its environment.",
        rows: [
          { name: "Variation", fn: "Individuals differ in traits, generated by mutation and recombination.", why: "Without variation selection has nothing to act on." },
          { name: "Overproduction", fn: "More offspring are produced than survive.", why: "Darwin's first observation." },
          { name: "Struggle for existence", fn: "Resources are finite, so competition follows.", why: "The logical link between the observations." },
        ],
      },
      {
        id: "selection",
        label: "Natural selection",
        hint: "Differential survival changes the gene pool.",
        shell: "ghost",
        rows: [
          { name: "Survival of the fittest", fn: "'Fit' means best-reproducing, not strongest.", why: "The misread word — defining it correctly earns the mark." },
          { name: "Directional change", fn: "Allele frequencies shift generation by generation.", why: "Selection acts on phenotypes, evolution is the genetic change." },
          { name: "Adaptation", fn: "Accumulated selected traits suit the organism to its niche.", why: "Distinguish adaptation from acclimatisation." },
        ],
      },
      {
        id: "fossils",
        label: "Evidence",
        hint: "Fossils, homology and analogy.",
        shell: "ghost",
        rows: [
          { name: "Palaeontology", fn: "Fossils show succession — older forms are simpler.", why: "The direct historical evidence." },
          { name: "Homology", fn: "Same basic structure, different use (forelimbs).", why: "Points to common ancestry — divergent evolution." },
          { name: "Analogy", fn: "Different structure, same use (wings).", why: "Points to convergent evolution under similar selection." },
        ],
      },
    ],
    theory: {
      look: "A muted stony terrain carrying a scatter of green individuals — some bright and solid, some faded and translucent — an amber lineage curve rising across the generations, and beside them grey fossils with pink homologous and cyan analogous forelimbs.",
      principle: "Evolution proceeds because populations vary, more offspring are produced than can survive, and the environment therefore selects those whose variations suit it best; the survivors reproduce, shifting allele frequencies — descent with modification. Evidence comes from the fossil record and from comparative anatomy: homologous organs share structure but differ in function (divergence from common ancestry), while analogous organs share function but not structure (convergence).",
      why: "Darwin's observations in order, the correct meaning of 'fitness', and the homology-versus-analogy distinction with the divergence/convergence labels are the exact marks.",
    },
  },

  /* ── Floral diversity ── */
  "bio-3d-floral": {
    studio: "Floral diversity — the flowering plant in real form",
    shellWord: "Skin",
    blurb: "A real flower opened up: the four whorls in place, the male and female organs labelled, and pollination to fertilisation traced on the actual structures.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "torus", r: 1.6, tube: 0.5, arc: Math.PI },
        at: [0, 0.4, 0],
        rot: [1.1, 0, 0],
        material: "organ",
        color: 0xf472b6,
        repeat: { count: 5, spread: [0.2, 0.2, 0] },
        views: ["external", "flower"],
        label: { text: "Petals (corolla)", sub: "attract pollinators — the second whorl", at: [-4.6, 3.4, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "torus", r: 2.1, tube: 0.32, arc: Math.PI },
        at: [0, 0.2, 0],
        rot: [1.1, 0, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["flower"],
        label: { text: "Sepals (calyx)", sub: "protect the bud — the outermost whorl", at: [4.4, 3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[-0.8, 0.8, 0], [-1.0, 2.2, 0]], radius: 0.07 },
        material: "emissive",
        color: 0xfacc15,
        repeat: { count: 4, spread: [0.5, 0, 0.4] },
        views: ["external", "flower", "pollination"],
        label: { text: "Stamen: filament + anther", sub: "the male organ — anther makes pollen", at: [-3.2, 4.6, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[0.3, 0.8, 0], [0.5, 2.8, 0]], radius: 0.09 },
        material: "emissive",
        color: 0xa855f7,
        views: ["external", "flower", "pollination", "fertilisation"],
        label: { text: "Carpel: stigma, style, ovary", sub: "the female organ — ovules inside the ovary", at: [2.8, 5.0, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.14, noise: 0.1 },
        at: [-0.9, 2.4, 0],
        material: "emissive",
        color: 0xfb923c,
        repeat: { count: 6, spread: [2.4, 0.3, 0.8] },
        views: ["pollination"],
        label: { text: "Pollen grains", sub: "the male gametophytes, carried by wind or insect", at: [-2.6, 5.6, 0], color: "#fdba74" },
      },
      {
        shape: { kind: "tube", points: [[0.5, 2.6, 0], [0.55, 1.4, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["fertilisation"],
        label: { text: "Pollen tube", sub: "grows down the style to the ovule", at: [3.4, 2.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.22, noise: 0.08 },
        at: [0.4, 0.0, 0],
        material: "organ",
        color: 0x15803d,
        views: ["fertilisation"],
        label: { text: "Ovule → seed", sub: "fertilised ovule becomes the seed", at: [-2.6, -1.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.6, scale: [1.2, 0.9, 0.9], noise: 0.06 },
        at: [3.6, -0.8, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["fruit"],
        label: { text: "Ovary → fruit", sub: "the ripened ovary wall, protecting the seeds", at: [3.6, -3.2, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Flower (real)",
        hint: "The reproductive shoot of an angiosperm.",
        rows: [
          { name: "Four whorls", fn: "Calyx, corolla, androecium, gynoecium — outside in.", why: "The order and the collective terms are both marked." },
          { name: "Complete flower", fn: "All four whorls present.", why: "Classifying a given flower is routine." },
          { name: "Inflorescence", fn: "The arrangement of flowers on a shoot.", why: "Names like raceme and cyme are asked." },
        ],
      },
      {
        id: "flower",
        label: "Whorls",
        hint: "Each layer's structure and job.",
        shell: "ghost",
        rows: [
          { name: "Calyx", fn: "Green sepals protecting the bud.", why: "Outermost — sometimes colourful (choripetalous exceptions)." },
          { name: "Corolla", fn: "Petals attracting pollinators.", why: "Colour, scent and nectar work together." },
          { name: "Androecium", fn: "Stamens of filament and anther.", why: "Where pollen is produced by meiosis." },
          { name: "Gynoecium", fn: "Carpels of stigma, style and ovary.", why: "The only female structure in the flower." },
        ],
      },
      {
        id: "pollination",
        label: "Pollination",
        hint: "Pollen reaching the stigma.",
        shell: "ghost",
        rows: [
          { name: "Self vs cross", fn: "Same flower or a different plant of the same species.", why: "Cross-pollination's advantage: variation." },
          { name: "Agents", fn: "Wind, water, insects, birds.", why: "The adaptations for each agent are asked." },
          { name: "Double fertilisation", fn: "One male gamete + egg, another + two polar nuclei.", why: "The unique angiosperm event — always examined." },
        ],
      },
      {
        id: "fertilisation",
        label: "Fertilisation → seed & fruit",
        hint: "From pollen tube to seed and fruit.",
        shell: "ghost",
        rows: [
          { name: "Pollen tube", fn: "Grows through the style carrying the male gametes.", why: "Chemotropic guidance is a one-mark detail." },
          { name: "Seed", fn: "Fertilised ovule with embryo and food store.", why: "Endosperm's origin is part of the double-fertilisation mark." },
          { name: "Fruit", fn: "Ripened ovary; aids seed dispersal.", why: "Fruit vs vegetable confusion is settled by this definition." },
        ],
      },
    ],
    theory: {
      look: "A pink-petalled flower with green sepals behind it, yellow stamens standing around a taller purple carpel, orange pollen drifting toward the stigma, a blue pollen tube running down the style into a green ovule, and a red ripened fruit beside the stem.",
      principle: "A flower carries four whorls — calyx, corolla, androecium, gynoecium. Pollen made in the anther reaches the stigma by self- or cross-pollination through wind, water or animal agents; a pollen tube then grows down the style, and double fertilisation — one gamete fusing with the egg, the other with the two polar nuclei — produces the embryo and endosperm. The ovule becomes the seed and the ovary the fruit, which protects and disperses the seeds.",
      why: "Whorl names in order, the agents and adaptations of pollination, double fertilisation, and the ovule→seed / ovary→fruit transformations are the recurring marks.",
    },
  },

  /* ── Conservation & biota ── */
  "bio-3d-biota-conservation": {
    studio: "Conservation — why species vanish and how they are saved",
    blurb: "A habitat shrinking at its edge, the species squeezed inside it, and the two responses: protect it in place, or take it out of danger.",
    defaultView: "threats",
    parts: [
      {
        shape: { kind: "cylinder", r1: 4.2, h: 1.6 },
        at: [0, 0, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["threats", "insitu"],
        label: { text: "Intact habitat", sub: "large and connected — species persist", at: [-4.6, 3.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "box", size: [3.4, 1.4, 3.4] },
        at: [5.2, 0.2, 0],
        material: "wood",
        color: 0x7c4a1e,
        views: ["threats"],
        label: { text: "Deforestation / farmland", sub: "habitat loss — the number-one cause of extinction", at: [5.2, 3.2, 0], color: "#b45309" },
      },
      {
        shape: { kind: "sphere", r: 0.32, noise: 0.06 },
        at: [1.2, 1.0, 0],
        material: "wetSkin",
        color: 0xf97316,
        repeat: { count: 5, spread: [1.6, 0.3, 1.2] },
        views: ["threats"],
        label: { text: "Squeezed population", sub: "small, isolated populations lose variation fast", at: [1.4, 3.4, 0], color: "#fdba74" },
      },
      {
        shape: { kind: "sphere", r: 0.9, scale: [1, 0.5, 1] },
        at: [-5.0, 1.4, 0],
        material: "glass",
        color: 0x38bdf8,
        opacity: 0.4,
        views: ["threats"],
        label: { text: "Invasive species & pollution", sub: "competitors and toxins — other major threats", at: [-5.2, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "torus", r: 3.0, tube: 0.14 },
        at: [0, 0.8, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "metal",
        color: 0x22c55e,
        views: ["insitu"],
        label: { text: "In-situ: national parks, reserves", sub: "protect the species inside its ecosystem", at: [0, 3.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "box", size: [2.2, 2.2, 2.2] },
        at: [4.6, 1.1, 0],
        material: "glass",
        color: 0xa855f7,
        opacity: 0.45,
        views: ["exsitu"],
        label: { text: "Ex-situ: zoo, seed bank, tissue culture", sub: "protect the species outside its habitat", at: [4.6, 3.8, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.06 },
        at: [-4.4, 0.4, 0],
        material: "organ",
        color: 0x22c55e,
        repeat: { count: 4, spread: [1.2, 0.5, 0.8] },
        views: ["exsitu"],
        label: { text: "Reintroduction", sub: "bred stock returns to protected habitat", at: [-4.4, -2.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 6, h: 2.6 },
        at: [0, -2.6, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["threats"],
        label: { text: "Biodiversity hotspot", sub: "high endemism + high threat = priority", at: [0, -4.0, 0], color: "#fde047" },
      },
    ],
    views: [
      {
        id: "threats",
        label: "Threats",
        hint: "What drives species toward extinction.",
        rows: [
          { name: "Habitat loss", fn: "Clearing, fragmentation and degradation.", why: "The leading cause — naming it correctly is the mark." },
          { name: "Invasive species", fn: "Introduced competitors, predators and diseases.", why: "Second after habitat loss." },
          { name: "Overexploitation", fn: "Harvesting faster than populations recover.", why: "Includes logging, fishing and the wildlife trade." },
          { name: "Hotspots", fn: "Regions of high endemism under high threat.", why: "Prioritisation logic is asked directly." },
        ],
      },
      {
        id: "insitu",
        label: "In-situ conservation",
        hint: "Protection where the species lives.",
        shell: "ghost",
        rows: [
          { name: "Protected areas", fn: "National parks, wildlife reserves, biosphere reserves.", why: "Nepal's examples (Chitwan, Sagarmatha) are asked." },
          { name: "Why in-situ first", fn: "The ecosystem and its processes are saved along with the species.", why: "The reasoning that ranks it above ex-situ." },
        ],
      },
      {
        id: "exsitu",
        label: "Ex-situ conservation",
        hint: "Protection away from the habitat.",
        shell: "ghost",
        rows: [
          { name: "Methods", fn: "Zoos, botanical gardens, seed banks, cryopreservation, tissue culture.", why: "Listing with one example each is the standard mark." },
          { name: "When used", fn: "For species whose habitat is already gone or too dangerous.", why: "The complement, not the substitute, to in-situ." },
          { name: "Reintroduction", fn: "Captive-bred stock is returned to protected habitat.", why: "The step that reconnects the two strategies." },
        ],
      },
    ],
    theory: {
      look: "A green habitat dome being eaten away by brown farmland blocks, orange animals pressed inside it, a translucent blue pressure bubble of invaders and pollution, a green reserve ring around the habitat, and a violet glass box standing for the zoo and seed bank.",
      principle: "Biodiversity is lost mainly through habitat destruction, then invasive species, overexploitation and pollution; small isolated populations lose genetic variation and face inbreeding. Conservation answers in two ways: in-situ, protecting whole habitats in national parks and reserves so species persist in functioning ecosystems, and ex-situ, keeping species alive in zoos, seed banks and tissue culture until they can be reintroduced. Hotspots — high endemism plus high threat — set the priorities.",
      why: "The ranked list of threats, in-situ versus ex-situ with examples, and the hotspot definition are the exact marks.",
    },
  },
};
