/**
 * Lab Studios — E: the last 3D suites. These pages are themselves suites of
 * many scenes, so each spec covers the suite's core visual idea — the one
 * idea every scene inside shares.
 */

import type { StudioSpec } from "./types";

export const SUITES_B: Record<string, StudioSpec> = {
  /* ── Chemistry suites ── */
  "ch-3d-advanced": {
    studio: "Advanced chemistry — orbital overlap and reaction energy",
    blurb: "Real hybrid orbitals reaching out to overlap, and the energy hill a reaction must climb — the two ideas the advanced suite keeps returning to.",
    defaultView: "orbitals",
    parts: [
      {
        shape: { kind: "sphere", r: 0.7, scale: [1, 0.55, 0.55], noise: 0.03 },
        at: [-3.0, 0, 0],
        material: "emissive",
        color: 0x3b82f6,
        opacity: 0.5,
        rot: [0, 0, 0.6],
        views: ["orbitals"],
        label: { text: "sp³ hybrid orbital", sub: "one s + three p → four identical lobes at 109.5°", at: [-4.6, 3.0, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 0.7, scale: [1, 0.55, 0.55], noise: 0.03 },
        at: [-1.2, 0.8, 0],
        material: "emissive",
        color: 0xf97316,
        opacity: 0.5,
        rot: [0, 0, -0.6],
        views: ["orbitals"],
        label: { text: "Overlapping lobe of H", sub: "head-on σ overlap makes the covalent bond", at: [0.6, 3.4, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.04 },
        at: [-2.1, 0.4, 0],
        material: "organ",
        color: 0xe2e8f0,
        views: ["orbitals"],
        label: { text: "Bonding pair region", sub: "electron density between the nuclei", at: [-1.4, -2.8, 0], color: "#e2e8f0" },
      },
      {
        shape: { kind: "sphere", r: 0.9, noise: 0.12 },
        at: [3.4, 0, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["energy"],
        label: { text: "Reactants", sub: "bonds must first be broken — uphill", at: [1.6, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.55, noise: 0.16 },
        at: [4.6, 1.8, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["energy"],
        label: { text: "Activated complex", sub: "the top of the hill — Ea is its height", at: [6.0, 4.2, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.8, noise: 0.12 },
        at: [5.8, 0.2, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["energy"],
        label: { text: "Products (lower energy)", sub: "ΔH is the net drop — exothermic here", at: [5.8, -2.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[3.4, 0.4, 0], [4.0, 1.5, 0], [4.6, 2.2, 0], [5.4, 1.0, 0], [5.8, 0.5, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xa855f7,
        views: ["energy"],
        label: { text: "Energy profile", sub: "catalyst lowers the hill, never changes ΔH", at: [3.0, -3.2, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "orbitals",
        label: "Hybridisation",
        hint: "Why bonds have the angles they do.",
        rows: [
          { name: "sp³", fn: "Four identical lobes at 109.5° — methane's geometry.", why: "Mixing s and p orbitals explains observed shapes." },
          { name: "σ overlap", fn: "Head-on overlap of lobes along the bond axis.", why: "The strongest covalent linkage." },
          { name: "Lone-pair lobes", fn: "Unbonded hybrids occupy space and squeeze bond angles.", why: "Connects hybridisation to VSEPR directly." },
        ],
      },
      {
        id: "energy",
        label: "Reaction energy",
        hint: "The hill between reactants and products.",
        shell: "ghost",
        rows: [
          { name: "Activation energy", fn: "The height the reactants must climb to react.", why: "Explains why stable mixtures still need a spark." },
          { name: "Exothermic vs endothermic", fn: "Products lower or higher than reactants — sign of ΔH.", why: "Reading ΔH off a profile is the standard mark." },
          { name: "Catalyst", fn: "Provides a lower-energy path without changing ΔH.", why: "The most-tested distinction on the profile." },
        ],
      },
    ],
    theory: {
      look: "Two translucent hybrid lobes — blue and orange — meeting at a white electron-pair cloud, and beside them a red reactant sphere climbing a violet energy path over a yellow activated complex down to a green product sphere.",
      principle: "Covalent bonds form by orbital overlap: mixing s and p orbitals gives hybrids (sp³ at 109.5°, sp² at 120°, sp at 180°) whose lobes overlap head-on to concentrate electron density between the nuclei. Reactions, meanwhile, must climb an activation-energy hill to reach the activated complex before falling to the products; the net height difference is ΔH, and a catalyst lowers the hill — speeding the reaction — without changing ΔH.",
      why: "The hybrid geometries and their angles, σ overlap, reading Ea and ΔH off a profile, and the catalyst's exact role are the recurring marks.",
    },
  },

  "ch-3d-molecules": {
    studio: "Molecules — geometry from electron pairs",
    blurb: "Real models of the examinable set: linear CO₂, bent H₂O, tetrahedral CH₄, pyramidal NH₃ — each shape read straight off its electron-pair count.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.04 },
        at: [-4.6, 0.4, 0],
        material: "metal",
        color: 0x64748b,
        views: ["external", "pairs"],
        label: { text: "CO₂ — linear, 180°", sub: "two double bonds, no lone pairs on carbon", at: [-4.6, 3.0, 0], color: "#94a3b8" },
      },
      {
        shape: { kind: "sphere", r: 0.26 },
        at: [-5.8, 0.4, 0],
        material: "organ",
        color: 0xef4444,
        repeat: { count: 2, spread: [2.4, 0, 0] },
        views: ["external", "pairs"],
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.04 },
        at: [-0.4, 0.4, 0],
        material: "organ",
        color: 0xef4444,
        views: ["external", "pairs"],
        label: { text: "H₂O — bent, 104.5°", sub: "two lone pairs compress the tetrahedron", at: [-0.4, 3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [0.7, 1.2, 0.3],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 2, spread: [1.4, -0.7, 0.4] },
        views: ["external", "pairs"],
      },
      {
        shape: { kind: "sphere", r: 0.52, noise: 0.04 },
        at: [3.6, 0.4, 0],
        material: "metal",
        color: 0x94a3b8,
        views: ["external", "pairs"],
        label: { text: "CH₄ — tetrahedral, 109.5°", sub: "four bond pairs, zero lone pairs", at: [3.6, 3.0, 0], color: "#cbd5e1" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [4.7, 1.2, 0.4],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 4, spread: [2.0, 1.4, 1.6] },
        views: ["external", "pairs"],
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.04 },
        at: [7.0, 0.4, 0],
        material: "organ",
        color: 0x3b82f6,
        views: ["external", "pairs"],
        label: { text: "NH₃ — pyramidal, 107°", sub: "one lone pair — between water and methane", at: [7.4, 3.0, 0], color: "#60a5fa" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [8.0, 1.1, 0.3],
        material: "emissive",
        color: 0xe2e8f0,
        repeat: { count: 3, spread: [1.5, 0.9, 1.1] },
        views: ["external", "pairs"],
      },
      {
        shape: { kind: "sphere", r: 0.18, noise: 0.05 },
        at: [-2.6, -2.2, 0],
        material: "emissive",
        color: 0xa855f7,
        repeat: { count: 2, spread: [1.2, 0, 0] },
        views: ["pairs"],
        label: { text: "Lone pairs (counted, not bonded)", sub: "they take space and squeeze angles", at: [-2.6, -3.8, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The set (real)",
        hint: "Four molecules, four classic shapes.",
        rows: [
          { name: "Linear", fn: "2 electron domains, 180° — CO₂, BeCl₂.", why: "The reference for all other angles." },
          { name: "Bent", fn: "4 domains, 2 lone pairs, 104.5° — H₂O.", why: "Lone-pair compression is the reasoning mark." },
          { name: "Tetrahedral", fn: "4 domains, 0 lone pairs, 109.5° — CH₄.", why: "The parent geometry of the sequence." },
          { name: "Pyramidal", fn: "4 domains, 1 lone pair, 107° — NH₃.", why: "Sits exactly between the previous two." },
        ],
      },
      {
        id: "pairs",
        label: "Counting domains",
        hint: "The procedure that predicts any shape.",
        shell: "ghost",
        rows: [
          { name: "Count domains", fn: "Bond pairs + lone pairs on the central atom.", why: "A double bond still counts as one domain." },
          { name: "Repulsion order", fn: "LP–LP > LP–BP > BP–BP.", why: "This ordering produces every angle reduction." },
          { name: "Predicting unseen", fn: "Apply the same count to a molecule never seen before.", why: "The transfer skill the exam actually tests." },
        ],
      },
    ],
    theory: {
      look: "Four molecular models in a row — grey linear CO₂, red bent H₂O, grey tetrahedral CH₄ and blue pyramidal NH₃ — with violet lone-pair spheres floating beneath the bent and pyramidal ones.",
      principle: "Molecular shape follows from electron-pair geometry: counting bond and lone pairs on the central atom gives the domain count, and lone pairs — repelling more than bond pairs — compress the angles from 109.5° (CH₄) through 107° (NH₃) to 104.5° (H₂O), while two domains give the 180° linear geometry of CO₂.",
      why: "The four shapes with their angles, the domain-counting procedure, and the lone-pair compression sequence are the exact marks.",
    },
  },

  "ch-3d-syllabus-suite": {
    studio: "Chemistry syllabus suite — the shared core",
    blurb: "Every scene in this suite is built on one idea: structure decides properties — atomic structure, bonding, equilibrium and energy all shown the same way.",
    defaultView: "atom",
    parts: [
      {
        shape: { kind: "sphere", r: 0.45, noise: 0.1 },
        at: [0, 0, 0],
        material: "organ",
        color: 0xef4444,
        views: ["atom", "bonding"],
        label: { text: "Nucleus — Z protons", sub: "electron shells fill outward: 2, 8, 8…", at: [-3.8, 3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "torus", r: 1.6, tube: 0.04 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x38bdf8,
        repeat: { count: 3, spread: [0, 0.7, 0] },
        views: ["atom"],
        label: { text: "Electron shells", sub: "valence electrons decide all chemistry", at: [3.4, 3.0, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.14 },
        at: [1.6, 0, 0],
        material: "emissive",
        color: 0x22d3ee,
        repeat: { ring: 1, radius: 1.6 },
        views: ["atom"],
        motion: { kind: "spin", axis: "y", speed: 2.0 },
      },
      {
        shape: { kind: "sphere", r: 0.34, noise: 0.05 },
        at: [-1.0, 0, 0],
        material: "metal",
        color: 0xfacc15,
        views: ["bonding"],
        repeat: { count: 2, spread: [2.0, 0, 0] },
        label: { text: "Ion formation", sub: "metal loses → cation; non-metal gains → anion", at: [0, -3.0, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[1.0, -2.2, 0], [1.8, -1.6, 0], [2.6, -2.2, 0]], radius: 0.07 },
        material: "emissive",
        color: 0x22c55e,
        views: ["bonding"],
        label: { text: "Bond strength ladder", sub: "ionic > covalent network > metallic > molecular", at: [3.4, -3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 6, h: 3.2 },
        at: [0, 2.4, 0],
        material: "glass",
        color: 0xa855f7,
        opacity: 0.3,
        views: ["equilibrium"],
        label: { text: "Dynamic equilibrium", sub: "forward rate = backward rate; concentrations constant", at: [0, 4.6, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "torus", r: 1.7, tube: 0.05 },
        at: [0, 0.4, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x22d3ee,
        views: ["equilibrium"],
        label: { text: "Le Chatelier", sub: "the system shifts to oppose any change imposed", at: [-3.6, -2.8, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.12 },
        at: [-2.2, 0, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["energy"],
        label: { text: "Exothermic: ΔH < 0", sub: "bonds formed release more than breaking cost", at: [-3.6, 3.2, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.12 },
        at: [2.2, 0, 0],
        material: "organ",
        color: 0x3b82f6,
        views: ["energy"],
        label: { text: "Endothermic: ΔH > 0", sub: "products hold more energy than reactants", at: [3.4, 3.2, 0], color: "#60a5fa" },
      },
    ],
    views: [
      {
        id: "atom",
        label: "Atomic structure",
        hint: "Shells, valence and the periodic logic.",
        rows: [
          { name: "Shell filling", fn: "2, 8, 8 pattern across the first three periods.", why: "Explains valency and group behaviour." },
          { name: "Valence electrons", fn: "The outermost shell's electrons do the reacting.", why: "Links position in the table to bonding." },
          { name: "Isotopes", fn: "Same protons, different neutrons.", why: "Mass differs, chemistry does not." },
        ],
      },
      {
        id: "bonding",
        label: "Bonding",
        hint: "Why each bond type gives its properties.",
        shell: "ghost",
        rows: [
          { name: "Ionic", fn: "Transfer of electrons; giant lattice; high melting point.", why: "Conducts when molten or dissolved — the test." },
          { name: "Covalent", fn: "Shared pairs; molecular or giant network.", why: "Explains low melting points of molecular solids." },
          { name: "Metallic", fn: "Cations in a sea of delocalised electrons.", why: "Conductivity and malleability both follow." },
        ],
      },
      {
        id: "equilibrium",
        label: "Equilibrium",
        hint: "Reversible reactions settling into balance.",
        shell: "ghost",
        rows: [
          { name: "Dynamic equilibrium", fn: "Rates equal, concentrations constant, both reactions still running.", why: "'Dynamic' must be stated, not just 'equal'." },
          { name: "Le Chatelier", fn: "Shifts oppose changes in concentration, pressure, temperature.", why: "Predicting the shift direction is the examined skill." },
          { name: "Kc", fn: "Products over reactants, powers from the equation.", why: "Writing Kc correctly is the numerical's first mark." },
        ],
      },
      {
        id: "energy",
        label: "Energy changes",
        hint: "Where the heat comes from or goes.",
        shell: "ghost",
        rows: [
          { name: "Exothermic", fn: "ΔH negative; bond-making outweighs bond-breaking.", why: "Combustion and neutralisation are the examples." },
          { name: "Endothermic", fn: "ΔH positive; energy absorbed from surroundings.", why: "Photosynthesis and thermal decomposition." },
          { name: "Hess's law", fn: "ΔH is path-independent.", why: "The route to indirect enthalpy calculations." },
        ],
      },
    ],
    theory: {
      look: "A red nucleus ringed by blue shell rings carrying cyan electrons, a yellow ion pair joined by a green bond ladder, a translucent violet equilibrium panel over a cyan cycle ring, and red/blue energy spheres facing each other.",
      principle: "Chemistry's syllabus suite rests on one chain: electron shells determine valence, valence determines bonding type, bonding type determines properties, and reaction conditions decide whether systems sit in equilibrium and release or absorb energy. Ionic bonding transfers electrons, covalent shares them, metallic delocalises them; dynamic equilibrium balances opposing rates and answers change per Le Chatelier; exothermic reactions end lower on the energy scale (ΔH < 0) and endothermic ones higher.",
      why: "Shell-to-valence-to-bonding reasoning, the three bond types with their property tests, dynamic equilibrium, Le Chatelier's principle and ΔH signs are the recurring marks.",
    },
  },

  /* ── Biology suites ── */
  "bio-3d-advanced": {
    studio: "Advanced biology — genetics and the code",
    shellWord: "Skin",
    blurb: "A real transcription readout: DNA opening, mRNA copying, and the codon table translating three bases at a time into protein.",
    defaultView: "central",
    parts: [
      {
        shape: { kind: "tube", points: [[-3.2, -3, 0], [-2.4, -1.5, 0], [-3.0, 0, 0], [-2.2, 1.5, 0], [-3.0, 3, 0]], radius: 0.08 },
        material: "metal",
        color: 0x38bdf8,
        views: ["central", "code"],
        label: { text: "DNA (template)", sub: "stays in the nucleus — the master copy", at: [-4.8, 3.4, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-1.6, -3, 0], [-1.0, -1.5, 0], [-1.8, 0, 0], [-0.8, 1.5, 0], [-1.6, 3, 0]], radius: 0.07 },
        material: "emissive",
        color: 0xfacc15,
        views: ["central", "code"],
        label: { text: "mRNA transcript", sub: "U replaces T — the working copy sent out", at: [-1.4, -3.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.08 },
        at: [1.8, 0, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["central", "code"],
        label: { text: "Ribosome", sub: "reads the mRNA three bases at a time", at: [1.8, 3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[2.0, -0.4, 0], [3.2, -0.9, 0], [4.4, -0.4, 0], [5.6, -1.1, 0]], radius: 0.1 },
        material: "emissive",
        color: 0xf472b6,
        views: ["central", "code"],
        label: { text: "Polypeptide → protein", sub: "sequence decided entirely by the codons", at: [3.6, 2.6, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "sphere", r: 0.14, noise: 0.08 },
        at: [1.2, -1.2, 0],
        material: "emissive",
        color: 0xa855f7,
        repeat: { count: 4, spread: [1.2, 0.6, 0.6] },
        views: ["code"],
        label: { text: "tRNA (adaptors)", sub: "anticodon on one end, amino acid on the other", at: [-1.2, -2.6, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "plane", w: 4.5, h: 3 },
        at: [4.6, 1.4, 0],
        material: "emissive",
        color: 0x38bdf8,
        views: ["code"],
        label: { text: "Codon table", sub: "64 codons, 20 amino acids, 3 stop signals — degenerate but unambiguous", at: [4.6, 3.8, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.05 },
        at: [-4.4, 0, 0],
        material: "metal",
        color: 0xef4444,
        views: ["central"],
        label: { text: "Mutation", sub: "a base change — silent, missense or nonsense", at: [-6.0, -2.8, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "central",
        label: "Central dogma",
        hint: "DNA → RNA → protein.",
        rows: [
          { name: "Transcription", fn: "One DNA strand is copied into mRNA.", why: "U pairing with A is the distinguishing detail." },
          { name: "Translation", fn: "Ribosome reads mRNA codons into amino acids.", why: "The order DNA → RNA → protein is the dogma itself." },
          { name: "Mutation", fn: "Base substitution or frameshift in the sequence.", why: "Its protein consequence is the examined extension." },
        ],
      },
      {
        id: "code",
        label: "The code",
        hint: "Triplet, degenerate, unambiguous.",
        shell: "ghost",
        rows: [
          { name: "Triplet code", fn: "Three bases specify one amino acid.", why: "64 codons for 20 amino acids — the arithmetic." },
          { name: "Degeneracy", fn: "Several codons can specify the same amino acid.", why: "Explains why some mutations are silent." },
          { name: "tRNA role", fn: "Anticodon pairs the codon; carries its amino acid.", why: "The adaptor concept ties the whole system together." },
        ],
      },
    ],
    theory: {
      look: "A blue DNA strand beside a yellow mRNA copy, a green ribosome threading the transcript into a pink growing polypeptide, violet tRNA adaptors nearby, a blue codon table, and a red mutation marker at the DNA's start.",
      principle: "Information flows from DNA to RNA to protein. Transcription copies one DNA strand into mRNA (U pairing with A); translation has the ribosome read the mRNA in three-base codons, each matched by a tRNA anticodon carrying its amino acid. The code is triplet, degenerate (multiple codons per amino acid) and unambiguous, and a mutation — a base change — may be silent, alter one amino acid, or introduce a stop signal.",
      why: "The central dogma order, the triplet/degenerate/unambiguous properties, tRNA's adaptor role, and mutation types are the exact marks.",
    },
  },

  "bio-3d-suite": {
    studio: "Biology suite — the shared core",
    shellWord: "Skin",
    blurb: "Cell → tissue → organ → system: one organisational ladder the whole suite climbs, with transport and control running through every level.",
    defaultView: "levels",
    parts: [
      {
        shape: { kind: "sphere", r: 0.5, noise: 0.06 },
        at: [-4.8, 0, 0],
        material: "membrane",
        color: 0x22c55e,
        views: ["levels", "transport"],
        label: { text: "Cell", sub: "the smallest living unit", at: [-4.8, 2.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "tube", points: [[-3.6, 0, 0], [-2.2, 0.4, 0]], radius: 0.09 },
        material: "organ",
        color: 0x38bdf8,
        views: ["levels"],
        repeat: { count: 4, spread: [0.5, 0.5, 0.5] },
        label: { text: "Tissue", sub: "similar cells doing one job together", at: [-2.4, 2.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.7, scale: [1.3, 0.8, 0.8], noise: 0.05 },
        at: [-0.2, 0, 0],
        material: "organ",
        color: 0xef4444,
        views: ["levels"],
        label: { text: "Organ", sub: "different tissues combined for a task", at: [-0.2, 2.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[1.4, -0.6, 0], [2.2, 0.4, 0], [3.0, -0.6, 0], [3.8, 0.4, 0]], radius: 0.07 },
        material: "emissive",
        color: 0xb91c1c,
        views: ["levels", "transport"],
        label: { text: "Organ system", sub: "organs cooperating — circulatory, digestive…", at: [2.6, 2.6, 0], color: "#fca5a5" },
      },
      {
        shape: { kind: "sphere", r: 1.2, noise: 0.03 },
        at: [5.8, 0, 0],
        material: "wetSkin",
        color: 0xfbbf24,
        views: ["levels"],
        label: { text: "Organism", sub: "all systems coordinated as one individual", at: [5.8, 2.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-4.8, -1.6, 0], [-2.0, -2.0, 0], [0.8, -1.6, 0], [3.4, -2.0, 0], [5.8, -1.6, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xa855f7,
        views: ["transport"],
        label: { text: "Transport links every level", sub: "blood carries what each level needs and removes waste", at: [0.6, -3.6, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "levels",
        label: "Levels of organisation",
        hint: "The ladder from cell to organism.",
        rows: [
          { name: "Cell → tissue", fn: "Similar cells aggregate into a working tissue.", why: "The order of the ladder is itself examined." },
          { name: "Tissue → organ → system", fn: "Tissues combine; organs cooperate.", why: "Each level gains an ability the level below lacks." },
          { name: "Emergence", fn: "Each level has properties none of its parts show alone.", why: "The conceptual point behind the ladder." },
        ],
      },
      {
        id: "transport",
        label: "Transport & control",
        hint: "What connects all levels.",
        shell: "ghost",
        rows: [
          { name: "Circulation", fn: "Blood links every cell to food, oxygen and waste removal.", why: "The reason transport is a system-level service." },
          { name: "Coordination", fn: "Nerves (fast) and hormones (slow) direct the systems.", why: "Comparing the two mechanisms is standard." },
          { name: "Homeostasis", fn: "Steady internal conditions despite external change.", why: "The purpose the coordination serves." },
        ],
      },
    ],
    theory: {
      look: "A green cell, blue tissue strands, a red organ, a crimson system loop and a golden whole organism arranged along one line, with a violet transport ribbon running beneath every level.",
      principle: "Biology is organised in ascending levels — cell, tissue, organ, organ system, organism — where each level combines the ones below into a new capability. What connects all levels is transport and control: blood carries materials between every cell and every organ, while nervous and hormonal coordination keeps the whole system in homeostasis.",
      why: "The level order, the emergence idea, and transport-plus-coordination as the connecting services are the exact marks.",
    },
  },

  "bio-3d-diversity": {
    studio: "Diversity — the five kingdoms at a glance",
    shellWord: "Skin",
    blurb: "Monera, Protista, Fungi, Plantae, Animalia arranged as real body plans, each placed by the features that define its kingdom.",
    defaultView: "kingdoms",
    parts: [
      {
        shape: { kind: "sphere", r: 0.8, scale: [1.5, 0.7, 0.7], noise: 0.03 },
        at: [-5.4, 0, 0],
        material: "membrane",
        color: 0x84cc16,
        views: ["kingdoms"],
        label: { text: "Monera — prokaryotes", sub: "no true nucleus; bacteria and cyanobacteria", at: [-5.4, 3.0, 0], color: "#a3e635" },
      },
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.04 },
        at: [-2.8, 0.2, 0],
        material: "membrane",
        color: 0x22d3ee,
        opacity: 0.6,
        views: ["kingdoms"],
        label: { text: "Protista — unicellular eukaryotes", sub: "Amoeba, Paramecium, Euglena", at: [-2.6, 3.2, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "tube", points: [[-0.8, -0.6, 0], [-0.4, 0.4, 0], [-0.9, 1.2, 0], [0.0, 1.8, 0]], radius: 0.08 },
        material: "mucosa",
        color: 0xd97706,
        views: ["kingdoms"],
        repeat: { count: 3, spread: [0.8, 0.2, 0.6] },
        label: { text: "Fungi — saprophytic eukaryotes", sub: "chitin walls; absorb dead matter", at: [0.2, 3.2, 0], color: "#f59e0b" },
      },
      {
        shape: { kind: "cone", r: 0.6, h: 2.2 },
        at: [2.4, 0.2, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["kingdoms"],
        label: { text: "Plantae — autotrophs", sub: "cellulose walls; make food by photosynthesis", at: [2.6, 3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.65, scale: [1.3, 0.8, 0.8], noise: 0.05 },
        at: [5.2, 0, 0],
        material: "wetSkin",
        color: 0xf59e0b,
        views: ["kingdoms"],
        label: { text: "Animalia — heterotrophs", sub: "no cell walls; ingest food and move", at: [5.2, 3.0, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[-5.4, -2.2, 0], [5.2, -2.2, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xa855f7,
        views: ["kingdoms"],
        label: { text: "Placed by: nucleus · cell wall · nutrition", sub: "the three questions that sort every organism", at: [0, -3.8, 0], color: "#c084fc" },
      },

      /* ── Levels of biodiversity ── */
      {
        shape: { kind: "tube", points: [[-6.6, -1.8, 0], [-6.0, -0.9, 0.5], [-6.4, 0.1, -0.5], [-5.8, 1.1, 0.4], [-6.2, 2.0, 0]], radius: 0.07 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["levels"],
        label: { text: "Genetic diversity", sub: "allele variation inside one species", at: [-6.2, 3.6, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-6.6, -1.8, 0], [-5.8, -0.9, -0.5], [-6.4, 0.1, 0.5], [-5.8, 1.1, -0.4], [-6.2, 2.0, 0]], radius: 0.07 },
        material: "emissive",
        color: 0x22d3ee,
        views: ["levels"],
      },
      {
        shape: { kind: "sphere", r: 0.5 },
        at: [-1.9, 0.5, 0],
        material: "organ",
        color: 0x4ade80,
        views: ["levels"],
      },
      {
        shape: { kind: "sphere", r: 0.34 },
        at: [-0.8, 1.1, 0.3],
        material: "wetSkin",
        color: 0xf59e0b,
        views: ["levels"],
      },
      {
        shape: { kind: "cone", r: 0.28, h: 1.2 },
        at: [0.1, 1.0, -0.3],
        material: "organ",
        color: 0x22c55e,
        views: ["levels"],
      },
      {
        shape: { kind: "sphere", r: 0.22, scale: [1.6, 0.7, 0.7] },
        at: [-1.2, -1.0, 0.2],
        material: "membrane",
        color: 0x84cc16,
        views: ["levels"],
        label: { text: "Species diversity", sub: "how many species share one area", at: [-0.7, 3.6, 0], color: "#86efac" },
      },
      {
        shape: { kind: "box", size: [3.6, 0.3, 2.4] },
        at: [5.8, -1.2, 0],
        material: "stone",
        color: 0x57534e,
        views: ["levels"],
      },
      {
        shape: { kind: "box", size: [3.6, 0.3, 2.4] },
        at: [5.8, -0.5, 0],
        material: "wood",
        color: 0x166534,
        views: ["levels"],
      },
      {
        shape: { kind: "box", size: [3.6, 0.3, 2.4] },
        at: [5.8, 0.2, 0],
        material: "glass",
        color: 0x3b82f6,
        views: ["levels"],
        label: { text: "Ecosystem diversity", sub: "forest, pond, grassland — different habitats", at: [5.8, 3.4, 0], color: "#93c5fd" },
      },
      {
        shape: { kind: "tube", points: [[-7.0, -3.0, 0], [7.0, -3.0, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xa855f7,
        views: ["levels"],
        label: { text: "Three levels, one idea", sub: "genes → species → habitats, each level nests in the next", at: [0, -4.2, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "kingdoms",
        label: "Five kingdoms",
        hint: "Whittaker's classification.",
        rows: [
          { name: "Monera", fn: "Prokaryotic, unicellular, cell wall present.", why: "The only prokaryotic kingdom — its definition is the mark." },
          { name: "Protista", fn: "Eukaryotic, mostly unicellular.", why: "The first eukaryotes — a bridge kingdom." },
          { name: "Fungi", fn: "Eukaryotic, chitin walls, saprophytic absorption.", why: "Chitin vs cellulose distinguishes it from plants." },
          { name: "Plantae", fn: "Eukaryotic, cellulose walls, autotrophic.", why: "Photosynthesis is the defining nutrition." },
          { name: "Animalia", fn: "Eukaryotic, no cell walls, heterotrophic ingestion.", why: "Absence of a wall is itself the classification feature." },
        ],
      },
      {
        id: "levels",
        label: "Levels of diversity",
        hint: "Genetic · species · ecosystem.",
        rows: [
          { name: "Genetic diversity", fn: "Variation in alleles and genes within a single species.", why: "It is the raw material of natural selection and of a species' survival." },
          { name: "Species diversity", fn: "The number and relative abundance of species in one area.", why: "Species richness and evenness are the two words examiners want." },
          { name: "Ecosystem diversity", fn: "The range of habitats, communities and ecological processes.", why: "It spans forest, pond and grassland as distinct systems." },
          { name: "Nesting", fn: "Genes sit inside species, species inside ecosystems.", why: "Losing a habitat removes every level at once — the conservation link." },
        ],
      },
    ],
    theory: {
      look: "Five kingdom models in a row — a green bacterial rod, a cyan unicell, amber fungal hyphae, a green plant cone and an amber animal form — over a violet baseline naming the three sorting questions.",
      principle: "Whittaker's five kingdoms sort organisms by three questions: is there a true nucleus (prokaryote Monera versus the eukaryotic kingdoms), is there a cell wall and of what (fungi chitin, plants cellulose, animals none), and how is food obtained (photosynthesis in Plantae, absorption in Fungi, ingestion in Animalia), with Protista holding the unicellular eukaryotes.",
      why: "The five kingdom names with one defining feature each, and the three sorting questions, are the exact marks.",
    },
  },

  "bio-3d-syllabus-suite": {
    studio: "Biology syllabus suite — the shared core",
    shellWord: "Skin",
    blurb: "Life's single recipe repeated at every scale: membrane compartments, genetic information, energy transformation and response to the environment.",
    defaultView: "core",
    parts: [
      {
        shape: { kind: "sphere", r: 1.4, noise: 0.04 },
        at: [0, 0, 0],
        material: "membrane",
        color: 0x86efac,
        opacity: 0.4,
        views: ["core", "energy"],
        label: { text: "Membrane-bound life", sub: "every living thing is compartments in a membrane", at: [-4.0, 3.0, 0], color: "#86efac" },
      },
      {
        shape: { kind: "tube", points: [[-0.6, -1.2, 0], [0.2, -0.4, 0], [-0.4, 0.4, 0], [0.4, 1.2, 0]], radius: 0.07 },
        material: "metal",
        color: 0x7c3aed,
        views: ["core", "information"],
        label: { text: "Genetic information", sub: "DNA → RNA → protein in every organism", at: [2.8, 3.0, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.35, noise: 0.06 },
        at: [0.6, 0, 0],
        material: "organ",
        color: 0xdc2626,
        views: ["energy"],
        label: { text: "Mitochondrion", sub: "respiration releases the energy all life spends", at: [0.6, -3.0, 0], color: "#f87171" },
      },
      {
        shape: { kind: "cone", r: 0.5, h: 1.2 },
        at: [-0.6, 0, 0],
        material: "organ",
        color: 0x22c55e,
        views: ["energy"],
        label: { text: "Chloroplast (where present)", sub: "photosynthesis re-enters the energy", at: [-3.2, -3.0, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "torus", r: 1.8, tube: 0.04 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0x38bdf8,
        views: ["information"],
        label: { text: "Reproduction & inheritance", sub: "information copied at division, passed to offspring", at: [-3.4, -2.8, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-3.4, 2.0, 0], [-1.4, 1.2, 0], [1.0, 1.8, 0], [3.2, 1.0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xf59e0b,
        views: ["core"],
        label: { text: "Response & adaptation", sub: "stimulus → response; selection adapts populations", at: [0.4, 3.4, 0], color: "#fbbf24" },
      },
    ],
    views: [
      {
        id: "core",
        label: "The shared core",
        hint: "What every living thing does.",
        rows: [
          { name: "Compartmentalisation", fn: "Membranes create the controlled interiors life needs.", why: "The one structure every organism shares." },
          { name: "Response", fn: "All organisms detect and react to stimuli.", why: "One of the defining characteristics of life." },
          { name: "Adaptation", fn: "Populations become suited to their environment over generations.", why: "Links daily function to evolutionary change." },
        ],
      },
      {
        id: "information",
        label: "Information",
        hint: "Storage, copying, expression.",
        shell: "ghost",
        rows: [
          { name: "DNA", fn: "Stores the instructions in base sequence.", why: "The universal molecule of heredity." },
          { name: "Expression", fn: "Genes are transcribed and translated into proteins.", why: "The central dogma in syllabus terms." },
          { name: "Inheritance", fn: "Copies pass to the next generation at reproduction.", why: "Why offspring resemble parents." },
        ],
      },
      {
        id: "energy",
        label: "Energy",
        hint: "Where it enters and where it is spent.",
        shell: "ghost",
        rows: [
          { name: "Photosynthesis", fn: "Light energy fixed into glucose.", why: "The entry point for nearly all ecosystems." },
          { name: "Respiration", fn: "Glucose broken down to release ATP.", why: "The universal energy currency." },
          { name: "Enzymes", fn: "Protein catalysts control every step.", why: "Named as the regulators of both processes." },
        ],
      },
    ],
    theory: {
      look: "A green translucent membrane sphere holding a violet DNA ribbon, a red mitochondrion and a green chloroplast cone, ringed by a blue inheritance loop and an amber response curve.",
      principle: "Every living thing performs the same core functions: it is compartmentalised by membranes, it stores information in DNA and expresses it through RNA into proteins, it transforms energy — photosynthesis to capture, respiration to release as ATP — and it responds to stimuli, with adaptation accumulating across generations. Every scene in the syllabus suite is one of these four functions seen at a different scale.",
      why: "Membrane compartmentalisation, the information chain, the two energy processes, and stimulus–response with adaptation are the exact marks.",
    },
  },

  "bio-3d-faunal": {
    studio: "Faunal diversity — the animal body plans",
    shellWord: "Skin",
    blurb: "From asymmetric sponge to backboned chordate: nine phyla arranged by increasing complexity — germ layers, body cavity and symmetry all advancing in step.",
    defaultView: "ladder",
    parts: [
      {
        shape: { kind: "sphere", r: 0.7, noise: 0.25 },
        at: [-5.6, 0, 0],
        material: "wax",
        color: 0x86efac,
        views: ["ladder", "features"],
        label: { text: "Porifera", sub: "asymmetric, pores, no tissues — spicule skeleton", at: [-5.6, 3.0, 0], color: "#86efac" },
      },
      {
        shape: { kind: "cylinder", r1: 0.4, h: 1.6 },
        at: [-3.8, 0.2, 0],
        material: "membrane",
        color: 0x22d3ee,
        opacity: 0.5,
        views: ["ladder", "features"],
        repeat: { count: 6, spread: [0, 1.2, 0.5] },
        label: { text: "Cnidaria", sub: "diploblastic, radial — hydra and jellyfish", at: [-3.6, 3.2, 0], color: "#67e8f9" },
      },
      {
        shape: { kind: "sphere", r: 0.5, scale: [1.8, 0.35, 0.8], noise: 0.04 },
        at: [-1.8, 0, 0],
        material: "wetSkin",
        color: 0xf472b6,
        views: ["ladder", "features"],
        label: { text: "Platyhelminthes", sub: "flat, triploblastic, no body cavity — flukes", at: [-1.6, 3.0, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "cylinder", r1: 0.3, r2: 0.08, h: 1.4 },
        at: [0.0, 0, 0],
        material: "wetSkin",
        color: 0xfbbf24,
        views: ["ladder", "features"],
        label: { text: "Aschelminthes", sub: "round body, false coelom — Ascaris", at: [0.2, 3.0, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[1.2, -0.4, 0], [1.6, 0.4, 0], [1.2, 1.2, 0], [1.8, 2.0, 0]], radius: 0.22 },
        material: "wetSkin",
        color: 0x8b5a2b,
        views: ["ladder", "features"],
        label: { text: "Annelida", sub: "true coelom, segmented — earthworm", at: [1.6, 3.2, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.4, scale: [1.5, 0.7, 0.7], noise: 0.04 },
        at: [3.2, 0, 0],
        material: "chitin",
        color: 0x22c55e,
        views: ["ladder", "features"],
        repeat: { count: 2, spread: [1.2, 0, 0] },
        label: { text: "Arthropoda", sub: "jointed legs, chitin exoskeleton — insects", at: [3.4, 3.2, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "torus", r: 0.7, tube: 0.3 },
        at: [5.0, 0, 0],
        material: "glass",
        color: 0xf59e0b,
        views: ["ladder", "features"],
        label: { text: "Mollusca", sub: "soft body, muscular foot, shell — snail", at: [5.0, 3.0, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.55, scale: [1, 0.4, 0.4], noise: 0.06 },
        at: [6.8, 0, 0],
        material: "organ",
        color: 0xf97316,
        views: ["ladder", "features"],
        repeat: { count: 2, spread: [0, 0.9, 0.9] },
        label: { text: "Echinodermata", sub: "spiny skin, water vascular system — starfish", at: [6.8, 3.2, 0], color: "#fb923c" },
      },
      {
        shape: { kind: "sphere", r: 0.6, scale: [1.6, 0.6, 0.6], noise: 0.04 },
        at: [8.4, 0, 0],
        material: "wetSkin",
        color: 0x38bdf8,
        views: ["ladder", "features"],
        label: { text: "Chordata", sub: "notochord, dorsal nerve cord — vertebrates", at: [8.2, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-5.6, -2.2, 0], [8.4, -2.2, 0]], radius: 0.03 },
        material: "emissive",
        color: 0xa855f7,
        views: ["ladder"],
        label: { text: "Increasing complexity →", sub: "symmetry, germ layers, coelom appear in order", at: [1.4, -3.8, 0], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "ladder",
        label: "The ladder",
        hint: "Nine phyla from simple to complex.",
        rows: [
          { name: "Order", fn: "Porifera → Cnidaria → Platyhelminthes → Aschelminthes → Annelida → Arthropoda → Mollusca → Echinodermata → Chordata.", why: "The sequence itself is examined." },
          { name: "Trend", fn: "Specialised cells, then tissues, then organs as phyla advance.", why: "The pattern behind the order." },
        ],
      },
      {
        id: "features",
        label: "Distinguishing features",
        hint: "What separates each phylum.",
        shell: "ghost",
        rows: [
          { name: "Germ layers", fn: "Diploblastic (Cnidaria) versus triploblastic (all above).", why: "The layer count is a standard identification mark." },
          { name: "Body cavity", fn: "None (flatworms), false (roundworms), true coelom (annelids on).", why: "Coelom type separates the middle phyla." },
          { name: "Symmetry", fn: "Radial in cnidarians, bilateral from flatworms up.", why: "Symmetry type is asked for each phylum." },
          { name: "Notochord", fn: "Present at some stage in Chordata only.", why: "The defining chordate feature." },
        ],
      },
    ],
    theory: {
      look: "Nine animal models in a line — green sponge, cyan hydra, pink flatworm, yellow roundworm, brown segmented worm, green chitinous insect, amber shelled mollusc, orange starfish and blue chordate — over a violet complexity arrow.",
      principle: "The animal kingdom climbs a ladder of increasing complexity: Porifera with no true tissues, radial diploblastic Cnidaria, triploblastic flatworms without a body cavity, roundworms with a false coelom, segmented Annelida with a true coelom, Arthropoda with jointed limbs and chitin, soft Mollusca with shells, spiny water-vascular Echinodermata, and Chordata with the notochord and dorsal nerve cord. Symmetry, germ layers and body cavity each advance in step along the ladder.",
      why: "The phylum order, germ-layer counts, coelom types, symmetry, and the chordate notochord are the exact marks.",
    },
  },

  /* ── Math suites ── */
  "math-3d-perpendicular": {
    studio: "Perpendicularity — the right angle everywhere",
    blurb: "Perpendicular axes, a line meeting a plane at right angles, and the tangent-as-perpendicular idea that links geometry to calculus.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "tube", points: [[-4, 0, 0], [4, 0, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xef4444,
        views: ["external", "plane"],
        label: { text: "Line ⊥ line", sub: "meet at 90° — the defining test", at: [4.4, 1.8, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, -3.4, 0], [0, 3.4, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x22c55e,
        views: ["external", "plane"],
        label: { text: "Gradient product = −1", sub: "m₁m₂ = −1 for perpendicular lines", at: [-2.8, 3.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 6, h: 5 },
        at: [2.4, -0.6, 0],
        material: "glass",
        color: 0x8b5cf6,
        opacity: 0.3,
        views: ["external", "plane"],
        label: { text: "Line ⊥ plane", sub: "perpendicular to every line through the foot", at: [2.4, 3.4, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "tube", points: [[2.4, -0.6, 0], [2.4, 2.6, 0]], radius: 0.05 },
        material: "emissive",
        color: 0xfacc15,
        views: ["plane"],
        label: { text: "The normal line", sub: "direction = the plane's normal vector (a, b, c)", at: [-0.4, 2.2, 0], color: "#fde047" },
      },
      {
        shape: { kind: "sphere", r: 1.4, noise: 0.02 },
        at: [-3.0, -1.2, 0],
        material: "glass",
        color: 0x38bdf8,
        opacity: 0.45,
        views: ["external"],
        label: { text: "Tangent ⊥ radius", sub: "the circle's tangent is perpendicular to the radius at contact", at: [-3.0, 1.8, 0], color: "#7dd3fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Perpendiculars",
        hint: "Line–line, line–circle, line–plane.",
        rows: [
          { name: "Line ⊥ line", fn: "Intersect at 90°; in coordinates m₁m₂ = −1.", why: "The gradient rule is the standard numerical." },
          { name: "Tangent", fn: "Perpendicular to the radius at the point of contact.", why: "The source of every circle-theorem angle." },
          { name: "Line ⊥ plane", fn: "Perpendicular to all lines in the plane through its foot.", why: "The 3D strengthening of the 2D idea." },
        ],
      },
      {
        id: "plane",
        label: "Normals",
        hint: "The perpendicular as a direction vector.",
        shell: "ghost",
        rows: [
          { name: "Normal vector", fn: "(a, b, c) for the plane ax + by + cz = d.", why: "Angles between planes use their normals." },
          { name: "Shortest distance", fn: "Measured along the normal.", why: "Why the point-plane formula divides by the normal's length." },
          { name: "Direction of steepest change", fn: "The normal points where the function increases fastest.", why: "The bridge to gradient in calculus." },
        ],
      },
    ],
    theory: {
      look: "A red and a green line crossing at right angles, a violet glass plane with a yellow normal line standing out of it, and a blue sphere whose tangent meets its radius at 90°.",
      principle: "Perpendicularity is the right-angle relationship in every guise: two lines meet at 90° (gradients multiplying to −1), a tangent meets its circle's radius at 90°, and a line perpendicular to a plane is perpendicular to every line through its foot, its direction matching the plane's normal vector. In calculus the tangent to a curve is perpendicular to the normal at that point, tying geometry to rates of change.",
      why: "The gradient product rule, the tangent–radius theorem, line-plane perpendicularity and normal vectors are the exact marks.",
    },
  },

  "math-3d-advanced": {
    studio: "Advanced geometry — cones, spheres and section formulae",
    blurb: "The sphere inscribed in a cone, the section formula placing a point between two others, and the direction cosines that orient any line in space.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cone", r: 1.8, h: 3.4 },
        at: [0, 0, 0],
        material: "metal",
        color: 0xf59e0b,
        views: ["external", "cone"],
        label: { text: "Cone", sub: "slant height l² = r² + h²", at: [-4.0, 3.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "sphere", r: 0.8, noise: 0.02 },
        at: [0, 1.1, 0],
        material: "glass",
        color: 0x38bdf8,
        opacity: 0.55,
        views: ["cone"],
        label: { text: "Inscribed sphere", sub: "tangent to base and to every generator", at: [3.2, 3.0, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.2 },
        at: [-2.8, -1.8, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["external", "sections"],
        label: { text: "Point A(x₁, y₁, z₁)", sub: "section formula begins here", at: [-4.6, 0.6, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.2 },
        at: [2.8, 1.8, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["external", "sections"],
        label: { text: "Point B(x₂, y₂, z₂)", sub: "…and ends here", at: [3.6, 3.6, 0], color: "#f87171" },
      },
      {
        shape: { kind: "sphere", r: 0.16 },
        at: [0, 0, 0],
        material: "emissive",
        color: 0xfacc15,
        views: ["sections"],
        label: { text: "Division point", sub: "internal m:n → weighted average of A and B", at: [-0.6, -2.4, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[0, 0, 0], [3.0, 1.8, 1.2]], radius: 0.05 },
        material: "emissive",
        color: 0xa855f7,
        views: ["external", "sections"],
        label: { text: "Direction cosines", sub: "l² + m² + n² = 1 for any line", at: [3.4, 1.0, 1.6], color: "#c084fc" },
      },
    ],
    views: [
      {
        id: "external",
        label: "The set",
        hint: "Cone, sphere and a line in space.",
        rows: [
          { name: "Pythagorean families", fn: "l² = r² + h² on the cone; distance formula in space.", why: "The same right-triangle logic at both scales." },
          { name: "Direction cosines", fn: "Cosines of the angles a line makes with the axes.", why: "Their identity l² + m² + n² = 1 is the checked fact." },
        ],
      },
      {
        id: "cone",
        label: "Cone & insphere",
        hint: "Tangency inside a solid.",
        shell: "ghost",
        rows: [
          { name: "Slant height", fn: "l = √(r² + h²).", why: "Substituted into curved surface area πrl." },
          { name: "Insphere", fn: "Touches the base and each generator line.", why: "The tangency condition fixes its radius." },
        ],
      },
      {
        id: "sections",
        label: "Sections & ratios",
        hint: "Points between points.",
        shell: "ghost",
        rows: [
          { name: "Section formula", fn: "Internal division m:n weights each coordinate.", why: "Midpoint is the 1:1 special case." },
          { name: "Centroid", fn: "Average of the vertices' coordinates.", why: "The most-used application." },
        ],
      },
    ],
    theory: {
      look: "An amber cone holding a translucent blue inscribed sphere, a green and a red point with a yellow division point between them, and a violet direction line carrying its direction cosines.",
      principle: "Advanced geometry reuses one idea — the right triangle — at every scale: a cone's slant height satisfies l² = r² + h², the distance formula in space is its 3D form, and an inscribed sphere is fixed by tangency to the base and every generator. Points between points are placed by the section formula, a weighted average that gives the midpoint at ratio 1:1 and the centroid as the vertices' average, while a line's orientation is fixed by direction cosines satisfying l² + m² + n² = 1.",
      why: "Slant-height and surface-area substitutions, tangency conditions, the section formula with its midpoint special case, and the direction-cosine identity are the exact marks.",
    },
  },

  "math-3d-labeled": {
    studio: "Labeled geometry — every part named in place",
    blurb: "A labelled pyramid with its slant edge, apothem and height distinguished, and a labelled circle with chord, sector and segment — vocabulary pinned to real geometry.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "cone", r: 1.7, h: 2.6 },
        at: [-2.8, 0, 0],
        material: "glass",
        color: 0x38bdf8,
        opacity: 0.4,
        views: ["external", "solid"],
        label: { text: "Height h", sub: "apex straight above the centre — not the slant", at: [-4.8, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-2.8, 0.1, 0], [-1.4, 0.1, 0]], radius: 0.045 },
        material: "emissive",
        color: 0xfacc15,
        views: ["solid"],
        label: { text: "Radius r", sub: "centre to rim of the circular base", at: [-1.0, 1.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "tube", points: [[-2.8, 0.1, 0], [-1.35, 2.6, 0]], radius: 0.045 },
        material: "emissive",
        color: 0xf472b6,
        views: ["solid"],
        label: { text: "Slant height l", sub: "apex to rim — √(r² + h²), never confused with h", at: [0.6, 3.4, 0], color: "#f9a8d4" },
      },
      {
        shape: { kind: "cylinder", r1: 1.5, h: 2.6 },
        at: [2.8, 0, 0],
        material: "glass",
        color: 0x22c55e,
        opacity: 0.4,
        views: ["external", "solid"],
        label: { text: "Cylinder", sub: "V = πr²h · CSA = 2πrh", at: [2.8, 3.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "torus", r: 1.4, tube: 0.04 },
        at: [0, -2.8, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0xf59e0b,
        views: ["external", "circle"],
        label: { text: "Circle", sub: "chord · tangent · sector · segment", at: [-3.4, -3.6, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[-1.4, -2.8, 0], [1.4, -2.8, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["circle"],
        label: { text: "Chord", sub: "diameter when it passes through the centre", at: [0, -1.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "sphere", r: 0.12 },
        at: [1.4, -2.8, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["circle"],
        label: { text: "Sector vs segment", sub: "sector = two radii + arc; segment = chord + arc", at: [2.8, -4.2, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "external",
        label: "All labels",
        hint: "Solid and circle vocabulary together.",
        rows: [
          { name: "Terminology", fn: "Each part has one exact name.", why: "Misnaming loses the mark even with correct working." },
          { name: "Diagram habit", fn: "Label before calculating.", why: "Examiners award label marks on the diagram itself." },
        ],
      },
      {
        id: "solid",
        label: "Solid labels",
        hint: "Cone and cylinder parts.",
        shell: "ghost",
        rows: [
          { name: "Height vs slant", fn: "h is vertical; l runs along the surface.", why: "The single most confused pair in mensuration." },
          { name: "Volume & area", fn: "Cone V = ⅓πr²h; cylinder V = πr²h.", why: "The ⅓ factor is the examined distinction." },
        ],
      },
      {
        id: "circle",
        label: "Circle labels",
        hint: "Chords, sectors, segments.",
        shell: "ghost",
        rows: [
          { name: "Chord & diameter", fn: "Any chord; diameter through the centre.", why: "Perpendicular from centre bisects the chord — the theorem." },
          { name: "Sector & segment", fn: "Radii+arc versus chord+arc.", why: "Their area formulae are both asked." },
        ],
      },
    ],
    theory: {
      look: "A blue glass cone and a green glass cylinder with yellow radius, pink slant and blue height lines, and beneath them an amber circle carrying a green chord and a red sector marker.",
      principle: "Geometry answers begin with correct vocabulary pinned to the diagram. In solids, height is vertical while slant height runs along the surface, linked by l² = r² + h²; volumes compare as cone = ⅓ of the cylinder on the same base and height. In circles, chords join rim to rim (diameter through the centre, bisected by a perpendicular from the centre), a sector is bounded by two radii and an arc, and a segment by a chord and an arc.",
      why: "Height-versus-slant distinction, the ⅓ volume relation, the chord-bisection theorem, and sector-versus-segment definitions are the exact marks.",
    },
  },

  "math-3d-syllabus-suite": {
    studio: "Math syllabus suite — the shared core",
    blurb: "Function, graph, transformation and model: one cycle that every chapter of the mathematics syllabus — algebra, trigonometry, calculus, statistics — runs through.",
    defaultView: "cycle",
    parts: [
      {
        shape: { kind: "plane", w: 5.4, h: 0.16 },
        at: [-3.0, -0.6, 0],
        material: "metal",
        color: 0x475569,
        views: ["cycle", "functions"],
      },
      {
        shape: { kind: "tube", points: [[-5.4, -0.6, 0], [-4.4, 0.4, 0], [-3.0, -0.6, 0], [-1.6, 0.8, 0], [-0.4, -0.6, 0]], radius: 0.05 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["cycle", "functions"],
        label: { text: "Function → graph", sub: "each rule draws exactly one picture", at: [-2.8, 2.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "sphere", r: 0.3, noise: 0.04 },
        at: [0.8, 0.2, 0],
        material: "emissive",
        color: 0x22c55e,
        views: ["cycle"],
        motion: { kind: "spin", axis: "y", speed: 1.6 },
        label: { text: "Transformation", sub: "shift, stretch, reflect — read from the new equation", at: [0.8, 2.4, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "torus", r: 1.6, tube: 0.05 },
        at: [3.2, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0xf59e0b,
        views: ["cycle"],
        label: { text: "Model", sub: "fit the mathematics to the situation", at: [3.4, 2.4, 0], color: "#fbbf24" },
      },
      {
        shape: { kind: "tube", points: [[-3.0, 2.0, 0], [-1.8, 2.8, 0], [0.2, 2.2, 0], [2.2, 2.8, 0], [3.4, 2.0, 0]], radius: 0.04 },
        material: "emissive",
        color: 0xa855f7,
        views: ["cycle"],
        label: { text: "Inverse & composition", sub: "undo the rule, or chain two rules", at: [0.2, 4.2, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "plane", w: 4.6, h: 2.4 },
        at: [0, -2.2, 0],
        material: "emissive",
        color: 0xef4444,
        views: ["cycle"],
        label: { text: "Domain sets the limit", sub: "no graph exists where the rule is undefined", at: [0, -3.8, 0], color: "#f87171" },
      },
    ],
    views: [
      {
        id: "cycle",
        label: "The cycle",
        hint: "Rule → picture → change → use.",
        rows: [
          { name: "Function", fn: "One output for each input.", why: "The definition is the first mark of every functions question." },
          { name: "Graph", fn: "The rule drawn as a picture.", why: "Sketching earns marks even without solving." },
          { name: "Transformation", fn: "Equation changes predict graph changes.", why: "f(x)+a, f(x+a), af(x), f(ax) — four shifts, four marks." },
          { name: "Model", fn: "The graph describes a real situation.", why: "One named application closes the loop." },
        ],
      },
      {
        id: "functions",
        label: "Functions",
        hint: "Rules, inverses and domains.",
        shell: "ghost",
        rows: [
          { name: "Domain & range", fn: "Legal inputs and resulting outputs.", why: "Domain restrictions precede every sketch." },
          { name: "Inverse", fn: "Reflects in y = x; exists when one-to-one.", why: "The existence condition is examined." },
          { name: "Composition", fn: "f(g(x)) applies g first.", why: "Order-of-application is the classic error." },
        ],
      },
    ],
    theory: {
      look: "A blue zig-zag function graph on a grey axis rail, a green transforming sphere, an amber model ring, a violet composition curve overhead and a red domain panel below.",
      principle: "The mathematics syllabus runs on one cycle: a function states a rule, its graph draws the rule as a picture, transformations shift or stretch the picture in ways read directly from the changed equation, and the result models a real situation. The inverse undoes the rule (existing only when the function is one-to-one) and composition chains two rules, with the domain — where the rule is undefined — setting the limits of every graph.",
      why: "The function definition, the four transformation families, inverse existence, composition order, and domain restriction are the exact marks.",
    },
  },

  "math-advanced": {
    studio: "Advanced mathematics — vectors and matrices as one machine",
    blurb: "A vector placed in 3D space and a matrix transforming it: the same numbers viewed two ways, joined by the determinant that measures scaling.",
    defaultView: "external",
    parts: [
      {
        shape: { kind: "tube", points: [[0, 0, 0], [3.4, 2.0, 1.2]], radius: 0.07, endRadius: 0.03 },
        material: "emissive",
        color: 0x38bdf8,
        views: ["external", "transform"],
        label: { text: "Vector v", sub: "magnitude and direction — or a column of components", at: [3.6, 3.2, 0], color: "#7dd3fc" },
      },
      {
        shape: { kind: "tube", points: [[-4.5, 0, 0], [4.5, 0, 0]], radius: 0.04 },
        material: "emissive",
        color: 0xef4444,
        views: ["external", "transform"],
        label: { text: "Basis î", sub: "matrices act on the basis vectors first", at: [-3.0, 1.8, 0], color: "#f87171" },
      },
      {
        shape: { kind: "tube", points: [[0, -3.4, 0], [0, 3.4, 0]], radius: 0.04 },
        material: "emissive",
        color: 0x22c55e,
        views: ["external", "transform"],
        label: { text: "Basis ĵ", sub: "each column of M is where a basis vector lands", at: [-2.6, 3.8, 0], color: "#4ade80" },
      },
      {
        shape: { kind: "plane", w: 4.4, h: 4.4 },
        at: [0, 0, 0],
        rot: [-Math.PI / 2, 0, 0],
        material: "glass",
        color: 0xa855f7,
        opacity: 0.25,
        views: ["transform"],
        label: { text: "Transformation matrix M", sub: "rotations, reflections and scaling in one object", at: [0, 3.6, 0], color: "#c084fc" },
      },
      {
        shape: { kind: "sphere", r: 0.22 },
        at: [3.4, 2.0, 1.2],
        material: "emissive",
        color: 0xfacc15,
        views: ["transform"],
        label: { text: "det M ≠ 0 → invertible", sub: "det = area scale factor; zero collapses the plane", at: [-0.6, -2.8, 0], color: "#fde047" },
      },
      {
        shape: { kind: "torus", r: 1.9, tube: 0.04 },
        at: [0, 0, 0],
        rot: [Math.PI / 2, 0, 0],
        material: "emissive",
        color: 0xf472b6,
        views: ["external"],
        label: { text: "Dot product & angle", sub: "a·b = |a||b| cos θ — perpendicular when zero", at: [-3.4, -3.2, 0], color: "#f9a8d4" },
      },
    ],
    views: [
      {
        id: "external",
        label: "Vectors",
        hint: "Geometry encoded as numbers.",
        rows: [
          { name: "Components", fn: "A vector as (x, y, z) or a column.", why: "The dual view that connects geometry to algebra." },
          { name: "Dot product", fn: "a·b = |a||b|cos θ; zero means perpendicular.", why: "The perpendicularity test in every numerical." },
          { name: "Magnitude & direction", fn: "|v| from Pythagoras; direction cosines for angles.", why: "Both are one-line computations." },
        ],
      },
      {
        id: "transform",
        label: "Matrices",
        hint: "Transformations as data.",
        shell: "ghost",
        rows: [
          { name: "Columns are images", fn: "Each column shows where a basis vector is sent.", why: "Reading a transformation off its matrix is the core skill." },
          { name: "Determinant", fn: "Area (or volume) scale factor; zero means collapse.", why: "Invertibility follows directly from it." },
          { name: "Composition", fn: "Applying transformations in order multiplies matrices.", why: "Order matters — AB ≠ BA in general." },
        ],
      },
    ],
    theory: {
      look: "A blue vector arrow between red and green basis axes, a violet translucent transformation plane beneath it, a yellow determinant marker at the vector's tip, and a pink ring for the dot product.",
      principle: "Vectors and matrices are two views of one machine: a vector is both a geometric arrow and a column of components; a matrix is a transformation recorded as data, its columns telling where each basis vector lands. The dot product a·b = |a||b|cos θ tests perpendicularity (zero when θ = 90°), the determinant measures the area or volume scaling a transformation applies — and det M = 0 signals collapse to a line, meaning the matrix has no inverse. Applying transformations in sequence corresponds to multiplying matrices, in order.",
      why: "The dual vector view, the dot-product perpendicularity test, reading transformations from matrix columns, determinant as scale factor, and non-commutative composition are the exact marks.",
    },
  },
};
