import { writeDual } from "./enrich-helper.mjs";

export const cap02 = {
  title: "Parallel Plate Capacitor",
  unitSlug: "capacitor",
  topicSlug: "parallel-plate-capacitor",
  topicTitle: "Parallel plate capacitor",
  relevance: 100,
  notes: [
    "**Construction & Geometry:** A parallel plate capacitor consists of two identical, parallel metallic plates of cross-sectional area $A$, held parallel at a uniform separation distance $d$, where plate dimensions are much larger than separation ($d \\ll \\sqrt{A}$). The region between the plates is filled with vacuum, air, or a dielectric material.",
    "**Uniform Electric Field Between Plates:** When plate 1 carries $+Q$ and plate 2 carries $-Q$, the surface charge density is $\\sigma = \\frac{Q}{A}$. By Gauss's Law, the electric field due to each infinite conducting sheet is $E = \\frac{\\sigma}{2\\varepsilon_0}$. In the region between plates, both fields point in the same direction (from positive to negative plate): $E = \\frac{\\sigma}{2\\varepsilon_0} + \\frac{\\sigma}{2\\varepsilon_0} = \\frac{\\sigma}{\\varepsilon_0} = \\frac{Q}{\\varepsilon_0 A}$. Outside the plates, the fields cancel to zero.",
    "**Derivation of Capacitance (Air/Vacuum):** The electric potential difference $V$ across plates separated by distance $d$ in a uniform field $E$ is $V = \\int_0^d E\\,dr = E d = \\frac{Q d}{\\varepsilon_0 A}$. Using $C = \\frac{Q}{V}$, we obtain: $C_0 = \\frac{\\varepsilon_0 A}{d}$.",
    "**Effect of Dielectric Slab:** If a dielectric slab of dielectric constant $\\kappa$ and thickness $t < d$ is inserted, the electric field inside the slab reduces to $E_d = \\frac{E_0}{\\kappa}$, while the field in remaining air $(d-t)$ remains $E_0$. The total potential difference becomes $V = E_0(d-t) + E_d t = E_0(d - t + \\frac{t}{\\kappa}) = \\frac{Q}{\\varepsilon_0 A}[d - t(1 - \\frac{1}{\\kappa})]$. Hence capacitance becomes $C = \\frac{\\varepsilon_0 A}{d - t(1 - 1/\\kappa)}$. When completely filled ($t = d$), $C = \\frac{\\kappa \\varepsilon_0 A}{d} = \\kappa C_0$.",
    "**Attractive Force Between Plates:** The charge $+Q$ on one plate experiences the electric field established solely by the charge on the other plate, $E_{other} = \\frac{\\sigma}{2\\varepsilon_0} = \\frac{Q}{2\\varepsilon_0 A}$. Therefore, the attractive electrostatic force between the plates is $F = Q E_{other} = \\frac{Q^2}{2\\varepsilon_0 A} = \\frac{1}{2} C V \\cdot \\frac{V}{d} = \\frac{1}{2}\\frac{\\varepsilon_0 A V^2}{d^2}$.",
    "**Fringing Field (Edge Effects):** Near the edges of real finite plates, the electric field lines bulge outward (fringing). Fringing slightly reduces the effective electric field in the center and slightly increases the effective area, so measured capacitance is marginally higher than the idealized formula $\\varepsilon_0 A/d$. This effect is negligible when $d \\ll \\sqrt{A}$."
  ],
  confusion: [
    "Using $E = \\sigma/\\varepsilon_0$ for force calculation: The electric field acting ON the charge $+Q$ of plate 1 is NOT the total field $E = \\sigma/\\varepsilon_0$, but only the field generated by plate 2 ($E_2 = \\sigma/2\\varepsilon_0$). Using total field leads to an erroneous factor of 2: $F = \\frac{Q^2}{2\\varepsilon_0 A}$, not $\\frac{Q^2}{\\varepsilon_0 A}$.",
    "Confusing effect of dielectric under connected vs disconnected states: If connected to a battery, voltage $V$ is fixed, so $Q = \\kappa Q_0$ and stored energy $U = \\kappa U_0$. If disconnected prior to insertion, charge $Q$ is trapped and fixed, so voltage drops to $V = V_0/\\kappa$ and energy drops to $U = U_0/\\kappa$ (the rest does mechanical work pulling the slab in).",
    "Misinterpreting plate thickness: Capacitance depends strictly on separation $d$ between facing surfaces, not the metallic thickness of the plates."
  ],
  practice: [
    "A parallel plate capacitor has circular plates of radius $8\\text{ cm}$ separated by an air gap of $1.5\\text{ mm}$. Calculate its capacitance. Solution: Area $A = \\pi r^2 = \\pi (0.08)^2 = 0.0201\\text{ m}^2$. $C = \\frac{\\varepsilon_0 A}{d} = \\frac{(8.854 \\times 10^{-12})(0.0201)}{1.5 \\times 10^{-3}} = 1.187 \\times 10^{-10}\\text{ F} = 118.7\\text{ pF}$.",
    "A parallel plate capacitor with air has $C = 20\\text{ pF}$. A dielectric slab of thickness $t = 2\\text{ mm}$ and $\\kappa = 4$ is introduced between plates separated by $d = 5\\text{ mm}$. Find new capacitance. Solution: $C = \\frac{\\varepsilon_0 A}{d - t(1 - 1/\\kappa)} = \\frac{C_0 d}{d - t(1 - 1/\\kappa)} = \\frac{20 \\times 5}{5 - 2(1 - 0.25)} = \\frac{100}{5 - 1.5} = \\frac{100}{3.5} = 28.57\\text{ pF}$.",
    "Calculate the attractive force between plates of a $100\\,\\mu\\text{F}$ capacitor charged to $500\\text{ V}$ with plate separation $1\\text{ mm}$. Solution: $F = \\frac{1}{2}\\frac{C V^2}{d} = \\frac{0.5 \\times (10^{-4}) \\times (2.5 \\times 10^5)}{10^{-3}} = \\frac{12.5}{10^{-3}} = 12500\\text{ N} = 12.5\\text{ kN}$."
  ],
  universalFacts: [
    "The attractive force between two charged parallel plates $F = \\frac{Q^2}{2\\varepsilon_0 A}$ is completely independent of the separation distance $d$ as long as fringing fields are negligible.",
    "Inserting a dielectric slab into an isolated charged capacitor creates an attractive inward fringing force that automatically pulls the dielectric into the gap.",
    "Commercial ceramic capacitors achieve ultra-compact high capacitance by using barium titanate ($BaTiO_3$) dielectrics with dielectric constants $\\kappa > 1200$."
  ],
  animation3D: "capacitor",
  motionGraphics: "capacitor"
};
