export const pd01Notes = [
  "**Electrostatic Potential & Potential Difference:** Electric potential at a point P is defined as the work done per unit positive charge in bringing a test charge q₀ from infinity to P against the electrostatic force of the source distribution, without altering the field: $V = \\frac{W}{q_0} = -\\int_\\infty^P \\vec{E} \\cdot d\\vec{r}$. Potential difference between two points A and B is $\\Delta V = V_B - V_A = -\\int_A^B \\vec{E} \\cdot d\\vec{r}$. Both V and ΔV are scalars, have SI unit volt (V), where $1\\,\\text{V} = 1\\,\\text{J/C}$, and are path-independent because the electrostatic field is conservative ($\\oint \\vec{E} \\cdot d\\vec{r} = 0$).",
  "**Potential due to an Isolated Point Charge:** For a source charge Q at the origin, the work done in bringing q₀ from infinity to distance r is $W = -\\int_\\infty^r \\frac{Q}{4\\pi\\varepsilon_0 x^2} dx = \\frac{1}{4\\pi\\varepsilon_0} \\frac{Q q_0}{r}$. Dividing by q₀ gives the potential: $V(r) = \\frac{1}{4\\pi\\varepsilon_0}\\frac{Q}{r} = k\\frac{Q}{r}$. Unlike electric field (which is a vector falling off as 1/r²), potential is a scalar that falls off only as 1/r. For an ensemble of point charges, superposition applies algebraically: $V = k \\sum_i \\frac{q_i}{r_i}$.",
  "**Relation between Electric Field and Potential Gradient:** The electric field and potential are intrinsically related. Since $V = -\\int \\vec{E}\\cdot d\\vec{r}$, we obtain $\\vec{E} = -\\vec{\\nabla}V$. For a uniform field directed along the x-axis: $E = -\\frac{dV}{dx}$. This is the foundational link that converts every electrostatic field formula into a corresponding potential formula, always by substituting $E \\propto 1/r^2$ with $V \\propto 1/r$.",
  "**Potential of Standard Charge Distributions:** (1) **Line charge:** $V = -\\frac{\\lambda}{2\\pi\\varepsilon_0}\\ln(r/r_0)$; (2) **Infinite plane sheet:** $V = -\\frac{\\sigma}{2\\varepsilon_0}x$ (linear decrease, since E is constant); (3) **Charged conducting shell (radius R, charge Q):** $V = kQ/R$ everywhere inside and on the surface, jumping to $V = kQ/r$ outside — a discontinuity of exactly $E R = \\sigma R/\\varepsilon_0$; (4) **Two parallel plates separated by d:** $E = \\frac{\\sigma}{\\varepsilon_0}$ and $V_{AB} = -Ed = -\\frac{\\sigma d}{\\varepsilon_0}$.",
  "**Potential Energy of a System of Charges:** The potential energy of a charge q brought from infinity into the field of source charge Q is $U = qV = k\\frac{qQ}{r}$. For two like charges ($qQ > 0$), U is positive, meaning work must be done against repulsion; for two unlike charges ($qQ < 0$), U is negative, indicating the system is bound and energy is released on assembly. For multiple charges, the total energy is the sum over all distinct pairs: $U = k \\sum_{i<j} \\frac{q_i q_j}{r_{ij}}$. Energy is a scalar and must never be computed by summing $\\vec{F}\\cdot d\\vec{r}$ naively over individual pairs for conservative systems.",
  "**Equivalence of Potential Energy and Force:** By the work-energy theorem, the work done by the electrostatic force in moving a charge slowly from A to B is $W = q(V_A - V_B) = -\\Delta U$. Therefore $\\Delta U = -W_{electric}$, proving that $\\Delta U = -\\int \\vec{F}\\cdot d\\vec{r}$. This means a force always acts to reduce potential energy: a positive charge accelerates toward lower V, and a negative charge accelerates toward higher V.",
  "**Electron Volt (eV) — Energy Unit Conversion:** The electron volt is the energy gained by a particle of charge e when accelerated through a potential difference of one volt: $1\\,\\text{eV} = e \\times 1\\,\\text{V} = 1.602 \\times 10^{-19}\\,\\text{C} \\times 1\\,\\text{J/C} = 1.602 \\times 10^{-19}\\,\\text{J}$. Convenient conversion factors: $1\\,\\text{eV} = 1.602 \\times 10^{-19}\\,\\text{J}$ and $1\\,\\text{J} = 6.242 \\times 10^{18}\\,\\text{eV}$. Multiples are commonly used: $1\\,\\text{keV} = 10^3\\,\\text{eV}$ (X-rays), $1\\,\\text{MeV} = 10^6\\,\\text{eV}$ (particle accelerators, nuclear binding), and $1\\,\\text{GeV} = 10^9\\,\\text{eV}$ (collider experiments). Note that electron volt is an energy unit, not a charge or potential unit."
];
