#!/usr/bin/env python3
"""Generate Biology content for NEB Class 11 entrance exam focus."""
import json
import re
from pathlib import Path

BIOLOGY_CONTENT = {
    "biomolecules-and-cell-biology": {
        "Biomolecules: Introduction and functions of carbohydrates, proteins, lipids, nucleic acids, minerals, enzymes and water": {
            "notes": [
                "### 1. Biomolecules Overview",
                "Biomolecules are organic compounds produced by living organisms. They are classified into four major groups: carbohydrates, proteins, lipids, and nucleic acids. Minerals and water are inorganic biomolecules essential for life.",
                "### 2. Carbohydrates",
                "- **Monosaccharides**: Simple sugars - glucose (C6H12O6), fructose, galactose",
                "- **Disaccharides**: Two monosaccharides - sucrose (glucose+fructose), lactose (glucose+galactose), maltose (glucose+glucose)",
                "- **Polysaccharides**: Many monosaccharides - starch (energy storage), glycogen (animal starch), cellulose (structural)",
                "- Functions: Energy source, structural support, cell recognition",
                "### 3. Proteins",
                "- Built from amino acids (20 types) linked by peptide bonds",
                "- **Primary structure**: Sequence of amino acids",
                "- **Secondary structure**: Alpha helix, beta sheet (hydrogen bonding)",
                "- **Tertiary structure**: 3D folding (disulfide bridges, hydrophobic interactions)",
                "- **Quaternary structure**: Multiple polypeptide chains (hemoglobin)",
                "- Functions: Enzymes, structural support, transport, immunity, signaling",
                "### 4. Lipids",
                "- **Fats and oils**: Triglycerides (glycerol + 3 fatty acids)",
                "- **Phospholipids**: Cell membrane component (hydrophilic head, hydrophobic tail)",
                "- **Steroids**: Cholesterol, hormones (testosterone, estrogen)",
                "- **Waxes**: Water-proofing",
                "- Functions: Energy storage (9 kcal/g), membrane structure, insulation, hormones",
                "### 5. Nucleic Acids",
                "- **DNA**: Deoxyribonucleic acid - double helix, stores genetic information",
                "- **RNA**: Ribonucleic acid - single strand, protein synthesis",
                "- Monomers: Nucleotides (sugar + phosphate + nitrogenous base)",
                "- DNA bases: Adenine, Guanine, Cytosine, Thymine",
                "- RNA bases: Adenine, Guanine, Cytosine, Uracil",
                "### 6. Enzymes",
                "- Biological catalysts (mostly proteins, some RNA = ribozymes)",
                "- Lower activation energy, not consumed in reaction",
                "- **Lock and key model**: Active site fits specific substrate",
                "- **Induced fit model**: Active site adjusts to substrate",
                "- Factors affecting enzyme activity: temperature, pH, substrate concentration, inhibitors",
                "### 7. Water",
                "- Universal solvent, high specific heat capacity, cohesion and adhesion",
                "- Essential for all metabolic reactions, transport, temperature regulation",
                "### 8. Minerals",
                "- **Macrominerals**: Ca, P, K, Na, Cl, Mg, S (needed in large amounts)",
                "- **Microminerals**: Fe, I, Zn, Cu, Mn, Se, F (trace amounts)",
                "- Functions: Bone formation, oxygen transport, nerve transmission, enzyme cofactors",
                "### 9. Entrance Exam Focus",
                "MCQs: Identify biomolecule types; Enzyme properties; Carbohydrate classification; Protein structure levels.",
            ],
            "confusion": [
                "x All enzymes are proteins. x Some RNA molecules (ribozymes) also act as enzymes.",
                "x Lipids are polymers. x Lipids are not true polymers - no repeating monomer units.",
                "x DNA and RNA have the same bases. x RNA has uracil instead of thymine.",
            ],
            "practice": [
                "Differentiate between starch and cellulose.",
                "Describe the four levels of protein structure.",
                "Explain how enzymes lower activation energy.",
                "Compare saturated and unsaturated fats.",
            ],
            "formulas": [
                "Carbohydrate: Cm(H2O)n",
                "Triglyceride: glycerol + 3 fatty acids",
                "Peptide bond: -CO-NH-",
            ],
        },
        "Cell: Introduction of cell, concepts of prokaryotic and eukaryotic cells": {
            "notes": [
                "### 1. Cell Theory",
                "- All living organisms are composed of one or more cells",
                "- The cell is the basic unit of structure and function",
                "- All cells arise from pre-existing cells (Virchow: ommis cellula e cellula)",
                "### 2. Prokaryotic Cells",
                "- No nucleus (DNA in nucleoid region)",
                "- No membrane-bound organelles",
                "- Smaller (1-10 micrometers)",
                "- Cell wall present (peptidoglycan in bacteria)",
                "- Ribosomes (70S)",
                "- Examples: Bacteria, Archaea, Cyanobacteria",
                "### 3. Eukaryotic Cells",
                "- True nucleus with nuclear envelope",
                "- Membrane-bound organelles",
                "- Larger (10-100 micrometers)",
                "- Cell wall in plants (cellulose), absent in animals",
                "- Ribosomes (80S in cytoplasm, 70S in mitochondria/chloroplasts)",
                "- Examples: Plants, Animals, Fungi, Protists",
                "### 4. Key Organelles and Functions",
                "- **Nucleus**: Controls cell activities, contains DNA",
                "- **Mitochondria**: Powerhouse - ATP production (cellular respiration)",
                "- **Ribosomes**: Protein synthesis",
                "- **Endoplasmic reticulum**: Protein (RER) and lipid (SER) synthesis",
                "- **Golgi apparatus**: Packaging and secretion",
                "- **Lysosomes**: Digestion (contain hydrolytic enzymes)",
                "- **Chloroplasts**: Photosynthesis (plants only)",
                "- **Cell membrane**: Selectively permeable barrier",
                "### 5. Differences Summary",
                "| Feature | Prokaryotic | Eukaryotic |",
                "| Nucleus | Absent | Present |",
                "| Organelles | None | Present |",
                "| Size | Small | Large |",
                "| Division | Binary fission | Mitosis/Meiosis |",
                "### 6. Entrance Exam Focus",
                "MCQs: Identify prokaryotic vs eukaryotic; Match organelle to function; Cell theory statements.",
            ],
            "confusion": [
                "x Prokaryotes have no DNA. x They have DNA but not enclosed in a nucleus.",
                "x All cells have a nucleus. x Prokaryotic cells lack a true nucleus.",
                "x Ribosomes are only in eukaryotes. x Both have ribosomes (different sizes).",
            ],
            "practice": [
                "Compare prokaryotic and eukaryotic cells with a table.",
                "Label and describe the functions of 5 organelles.",
                "Why are mitochondria called the powerhouse of the cell?",
                "Explain the significance of cell theory.",
            ],
            "formulas": [],
        },
    },
    "heredity-and-evolution": {
        "Mendel's laws of inheritance": {
            "notes": [
                "### 1. Gregor Mendel - Father of Genetics",
                "Mendel conducted experiments on pea plants (Pisum sativum) from 1856-1863. He studied 7 pairs of contrasting characters.",
                "### 2. Key Terms",
                "- **Gene**: Unit of heredity, determines a trait",
                "- **Allele**: Alternative form of a gene",
                "- **Dominant**: Expressed when present (capital letter)",
                "- **Recessive**: Expressed only when homozygous (lowercase)",
                "- **Genotype**: Genetic makeup (e.g., TT, Tt, tt)",
                "- **Phenotype**: Physical appearance",
                "- **Homozygous**: Same alleles (TT or tt)",
                "- **Heterozygous**: Different alleles (Tt)",
                "- **Monohybrid cross**: Cross involving one trait",
                "- **Dihybrid cross**: Cross involving two traits",
                "### 3. Mendel's First Law - Law of Segregation",
                "During gamete formation, the two alleles for each gene separate (segregate) so that each gamete receives only one allele.",
                "Monohybrid cross ratio: Genotypic 1:2:1, Phenotypic 3:1",
                "### 4. Mendel's Second Law - Law of Independent Assortment",
                "Genes for different traits assort independently during gamete formation (applies to genes on different chromosomes).",
                "Dihybrid cross ratio: Phenotypic 9:3:3:1",
                "### 5. Test Cross",
                "Cross between dominant phenotype and homozygous recessive to determine genotype.",
                "### 6. Entrance Exam Focus",
                "Solve Punnett squares; Calculate ratios; Distinguish between laws.",
            ],
            "confusion": [
                "x Dominant traits are more common. x Dominant just means expressed when present.",
                "x Independent assortment applies to all genes. x Only applies to genes on different chromosomes.",
                "x 3:1 ratio always means homozygous dominant. x Could be heterozygous.",
            ],
            "practice": [
                "Cross TT x tt - find F1 and F2 genotypic and phenotypic ratios.",
                "In peas, tall (T) is dominant to short (t). Cross Tt x Tt. What fraction is homozygous?",
                "A dihybrid cross TtRr x TtRr gives what phenotypic ratio?",
                "How do you determine if a tall plant is TT or Tt?",
            ],
            "formulas": [
                "Monohybrid phenotypic ratio: 3:1",
                "Dihybrid phenotypic ratio: 9:3:3:1",
                "Test cross ratio: 1:1",
            ],
        },
        "Incomplete dominance and codominance": {
            "notes": [
                "### 1. Beyond Mendel - Non-Mendelian Inheritance",
                "Not all traits follow simple dominant-recessive patterns.",
                "### 2. Incomplete Dominance",
                "- Neither allele is completely dominant",
                "- Heterozygote shows intermediate phenotype",
                "- Example: Snapdragon flowers - Red (RR) x White (WW) -> Pink (RW)",
                "- Phenotypic ratio matches genotypic ratio: 1:2:1",
                "### 3. Codominance",
                "- Both alleles are fully expressed in heterozygote",
                "- Neither masks the other",
                "- Example: ABO blood groups - IA and IB are codominant",
                "- Example: Roan cattle - red and white hairs both appear",
                "### 4. Multiple Alleles",
                "- More than two alleles exist for a gene in the population",
                "- Individual still has only two alleles",
                "- Example: ABO blood groups - IA, IB, i (three alleles)",
                "### 5. Blood Group Inheritance",
                "- IAIA or IAi = Group A",
                "- IBIB or IBi = Group B",
                "- IAIB = Group AB (codominance)",
                "- ii = Group O (recessive)",
                "- Anti-A antibodies in type B and O; Anti-B antibodies in type A and O",
                "### 6. Entrance Exam Focus",
                "Distinguish incomplete dominance vs codominance; Solve blood group crosses.",
            ],
            "confusion": [
                "x Incomplete dominance = blending. x It's not permanent blending - alleles remain distinct.",
                "x Codominance = incomplete dominance. x In codominance both show fully, not intermediate.",
                "x Type AB can donate to anyone. x Type AB can ONLY receive, not donate.",
            ],
            "practice": [
                "Cross red snapdragon (RR) with white (WW). What are F1 and F2 ratios?",
                "A type A father and type B mother have a type O child. What are parent genotypes?",
                "Can a type AB parent and type O parent have a type O child? Why/why not?",
                "Explain why codominance differs from incomplete dominance.",
            ],
            "formulas": [],
        },
    },
    "human-health-and-diseases": {
        "Pathogens and diseases": {
            "notes": [
                "### 1. Pathogens Overview",
                "Pathogens are disease-causing microorganisms: bacteria, viruses, fungi, protozoa, helminths.",
                "### 2. Bacterial Diseases",
                "- **Tuberculosis**: Mycobacterium tuberculosis, airborne, affects lungs",
                "- **Cholera**: Vibrio cholerae, waterborne, causes severe diarrhea",
                "- **Typhoid**: Salmonella typhi, fecal-oral, fever, abdominal pain",
                "- **Diphtheria**: Corynebacterium diphtheriae, respiratory, pseudomembrane",
                "- **Pertussis (Whooping Cough)**: Bordetella pertussis, highly contagious",
                "### 3. Viral Diseases",
                "- **Influenza**: Influenza virus, airborne, respiratory",
                "- **Common Cold**: Rhinovirus, nasal congestion",
                "- **Dengue**: Dengue virus, mosquito-borne (Aedes aegypti)",
                "- **Chikungunya**: Chikungunya virus, mosquito-borne, joint pain",
                "- **Hepatitis B**: Hepatitis B virus, blood/body fluids, liver",
                "- **HIV/AIDS**: Human Immunodeficiency Virus, destroys CD4+ T cells",
                "- **Rabies**: Rabies virus, animal bite, affects nervous system",
                "### 4. Protozoan Diseases",
                "- **Malaria**: Plasmodium (P. falciparum, P. vivax), Anopheles mosquito",
                "- **Amoebiasis**: Entamoeba histolytica, contaminated food/water",
                "- **Sleeping Sickness**: Trypanosoma, tsetse fly",
                "- **Kala-azar**: Leishmania donovani, sandfly",
                "### 5. Worm Diseases (Helminths)",
                "- **Ascariasis**: Ascaris lumbricoides, roundworm",
                "- **Filariasis**: Wuchereria bancrofti, elephantiasis",
                "- **Taeniasis**: Taenia solium, tapeworm (pork)",
                "- **Hookworm**: Ancylostoma duodenale, soil-transmitted",
                "### 6. Fungal Diseases",
                "- **Ringworm**: Trichophyton, Microsporum, skin infections",
                "- **Athlete's foot**: Dermatophytes, foot fungus",
                "### 7. Entrance Exam Focus",
                "Match pathogen to disease; Identify vector; Distinguish bacterial vs viral treatments.",
            ],
            "confusion": [
                "x Antibiotics treat viral infections. x Antibiotics only work on bacteria.",
                "x Malaria is caused by a worm. x Malaria is caused by Plasmodium (protozoan).",
                "x All mosquitoes carry disease. x Only specific species of specific genera.",
            ],
            "practice": [
                "Match the following: Malaria-Cholera-TB-HIV with their pathogens.",
                "What vector transmits dengue? What are its symptoms?",
                "Why are antibiotics ineffective against viral diseases?",
                "Describe the life cycle of Plasmodium.",
            ],
            "formulas": [],
        },
        "Immune system and immunity": {
            "notes": [
                "### 1. Immune System Overview",
                "The immune system protects the body against pathogens and foreign substances.",
                "### 2. Innate Immunity (Non-specific)",
                "- Present from birth",
                "- First line of defense",
                "- **Physical barriers**: Skin, mucous membranes",
                "- **Chemical barriers**: Stomach acid, lysozyme in tears",
                "- **Phagocytes**: Neutrophils, macrophages engulf pathogens",
                "- **Inflammation**: Redness, swelling, heat, pain",
                "- **Fever**: Elevated temperature inhibits pathogen growth",
                "- **Natural Killer cells**: Destroy infected host cells",
                "### 3. Adaptive Immunity (Specific)",
                "- Develops over lifetime",
                "- Specific to particular pathogens",
                "- Has memory (immunological memory)",
                "- **Humoral immunity**: B cells produce antibodies",
                "- **Cell-mediated immunity**: T cells destroy infected cells",
                "### 4. Antibodies (Immunoglobulins)",
                "- **IgG**: Most abundant, crosses placenta, long-term immunity",
                "- **IgM**: First responder, large pentamer",
                "- **IgA**: Mucosal immunity (tears, saliva, breast milk)",
                "- **IgE**: Allergic reactions, parasitic infections",
                "- **IgD**: B cell receptor",
                "### 5. Active vs Passive Immunity",
                "- **Active**: Body produces its own antibodies (infection or vaccination)",
                "- **Passive**: Receives pre-made antibodies (mother to baby, antivenom)",
                "### 6. Vaccination",
                "- Introduces weakened/killed antigen to stimulate active immunity",
                "- Creates memory cells for faster response on re-exposure",
                "- Herd immunity: When enough people are immune, disease spread is limited",
                "### 7. Autoimmune Diseases",
                "- Immune system attacks body's own cells",
                "- Examples: Rheumatoid arthritis, Type 1 diabetes, Lupus, Multiple sclerosis",
                "### 8. Allergies",
                "- Hypersensitive response to harmless antigens (allergens)",
                "- Mediated by IgE, mast cells release histamine",
                "- Examples: Hay fever, asthma, food allergies, anaphylaxis",
                "### 9. Entrance Exam Focus",
                "Distinguish innate vs adaptive; Identify antibody types; Explain vaccination principle.",
            ],
            "confusion": [
                "x Innate immunity has memory. x Only adaptive immunity has immunological memory.",
                "x Antibodies kill pathogens directly. x Antibodies mark pathogens for destruction.",
                "x Vaccines cause the disease. x Vaccines use weakened/killed pathogens to build immunity.",
            ],
            "practice": [
                "Compare innate and adaptive immunity in a table.",
                "Explain how antibodies work.",
                "What is the difference between active and passive immunity?",
                "Describe the mechanism of vaccination.",
            ],
            "formulas": [],
        },
    },
    "biotechnology-principles": {
        "Principles of biotechnology": {
            "notes": [
                "### 1. What is Biotechnology?",
                "Biotechnology is the use of living organisms or their products to make or modify products for practical use. Modern biotechnology involves genetic engineering.",
                "### 2. Core Techniques",
                "- **Recombinant DNA (rDNA) Technology**: Combining DNA from different sources",
                "- **PCR (Polymerase Chain Reaction)**: Amplifying DNA segments",
                "- **Gel Electrophoresis**: Separating DNA fragments by size",
                "- **Gene Cloning**: Making copies of genes",
                "### 3. Tools of Recombinant DNA Technology",
                "- **Restriction Enzymes (Molecular Scissors)**: Cut DNA at specific sequences (palindromes)",
                "- **Examples**: EcoRI (cuts at GAATTC), HindIII (cuts at AAGCTT)",
                "- **Sticky ends**: Overhanging single-stranded ends after cutting",
                "- **Blunt ends**: No overhang after cutting",
                "- **Vectors (Molecular Vehicles)**: Carry foreign DNA into host",
                "- **Examples**: Plasmids, bacteriophages, cosmids, Ti plasmid",
                "- **Competent Host**: Modified to accept foreign DNA (CaCl2 treatment for bacteria)",
                "### 4. Steps in rDNA Technology",
                "1. Isolation of genetic material (DNA extraction)",
                "2. Cutting DNA with restriction enzymes",
                "3. Separation by gel electrophoresis",
                "4. Insertion of DNA into vector",
                "5. Transformation into host cell",
                "6. Expression of desired gene",
                "### 5. PCR (Polymerase Chain Reaction)",
                "- Amplifies specific DNA segment millions of times",
                "- **Steps**: Denaturation (94°C), Annealing (50-65°C), Extension (72°C)",
                "- **Enzyme**: Taq polymerase (heat-stable from Thermus aquaticus)",
                "- **Components**: Template DNA, primers, dNTPs, Taq polymerase",
                "- **Applications**: Forensics, disease diagnosis, genetic research",
                "### 6. Gel Electrophoresis",
                "- Separates DNA fragments by size using electric field",
                "- DNA is negatively charged, moves toward positive electrode",
                "- Smaller fragments move faster through agarose gel",
                "- Visualized with ethidium bromide under UV light",
                "### 7. Entrance Exam Focus",
                "Identify restriction enzymes; Describe PCR steps; Explain vector requirements.",
            ],
            "confusion": [
                "x Any enzyme can cut DNA. x Only specific restriction enzymes recognize specific sequences.",
                "x PCR makes infinite copies. x Each cycle doubles DNA - limited by reagents.",
                "x DNA moves to positive electrode because it's positive. x DNA is NEGATIVE, moves to POSITIVE.",
            ],
            "practice": [
                "What is the function of restriction enzymes? Give an example.",
                "Describe the three steps of PCR.",
                "Why is Taq polymerase used in PCR?",
                "Explain how gel electrophoresis separates DNA fragments.",
            ],
            "formulas": [],
        },
    },
    "biotechnology-applications": {
        "Applications in agriculture and medicine": {
            "notes": [
                "### 1. Agricultural Applications",
                "- **Bt Cotton**: Contains Bacillus thuringiensis gene for insect resistance",
                "- **Bt Corn**: Pest-resistant corn expressing Bt toxin",
                "- **Golden Rice**: Enhanced with vitamin A (beta-carotene)",
                "- **Herbicide-resistant crops**: Tolerant to specific herbicides",
                "- **Delayed ripening tomatoes**: Flavr Savr tomato",
                "- **Drought-resistant crops**: Modified for water stress tolerance",
                "### 2. Medical Applications",
                "- **Insulin**: Produced by E. coli using rDNA technology (replaced animal insulin)",
                "- **Growth Hormone**: For treating dwarfism",
                "- **Vaccines**: Hepatitis B vaccine (yeast expression system)",
                "- **Gene Therapy**: Treating genetic disorders by replacing faulty genes",
                "- **Monoclonal Antibodies**: Cancer treatment, diagnostic tests",
                "- **CRISPR-Cas9**: Gene editing for therapeutic purposes",
                "### 3. Transgenic Animals",
                "- **GloFish**: Fluorescent zebrafish (research)",
                "- **Transgenic mice**: Disease models (cancer, Alzheimer's)",
                "- **Pharming**: Animals producing pharmaceutical proteins in milk",
                "- **RoboCow**: Producing human proteins in milk",
                "### 4. Biopiracy and Patents",
                "- **Biopiracy**: Unauthorized commercial use of biological resources",
                "- **Basmati rice case**: US patent on Indian basmati (later revoked)",
                                "- **Neem case**: EU patent on neem derivatives (revoked)",
                                "- **Wheat case**: US patent on Indian wheat (revoked)",
                                "- **Protected Biological Resources**: Nepal has traditional knowledge databases",
                "### 5. Bioremediation",
                "- Using microbes to clean up environmental pollutants",
                "- Oil-spill cleanup: Pseudomonas putida degrades hydrocarbons",
                "- Heavy metal removal: Bioaccumulation by certain microbes",
                "### 6. Entrance Exam Focus",
                "Applications of Bt crops; Insulin production; Biopiracy examples.",
            ],
            "confusion": [
                "x GM means genetically modified. x GWO (genetically wrought organism) is NOT the same term.",
                "x All transgenic animals are harmful. x Many provide medical benefits.",
                "x Biopiracy is legal. x It's the unauthorized exploitation of indigenous knowledge.",
            ],
            "practice": [
                "How is human insulin produced using recombinant DNA technology?",
                "What is Bt cotton and how does it work?",
                "Define biopiracy with examples from India/Nepal.",
                "What are the applications of transgenic animals?",
            ],
            "formulas": [],
        },
    },
    "environmental-issues": {
        "Air, water, and solid waste pollution": {
            "notes": [
                "### 1. Air Pollution",
                "- **Primary pollutants**: Directly emitted (SO2, NOx, CO, particulates)",
                "- **Secondary pollutants**: Formed in atmosphere (ozone, acid rain)",
                "- **Sources**: Vehicles, industries, burning fossil fuels, volcanic eruptions",
                "- **Effects**: Respiratory diseases, acid rain, smog, global warming",
                "- **Control**: Catalytic converters, scrubbers, renewable energy, afforestation",
                "### 2. Water Pollution",
                "- **Point source**: Single identifiable source (factory pipe)",
                "- **Non-point source**: Diffuse runoff (agricultural chemicals)",
                "- **Organic waste**: Sewage, food processing - increases BOD",
                "- **Eutrophication**: Excess nutrients -> algal bloom -> oxygen depletion",
                "- **Heavy metals**: Mercury (Minamata disease), Lead (neurotoxic)",
                "- **Control**: Wastewater treatment, reduce chemical use, maintain riparian zones",
                "### 3. Solid Waste Management",
                "- **Biodegradable**: Food waste, paper, garden waste - compostable",
                "- **Non-biodegradable**: Plastic, glass, metal - recycling needed",
                "- **Hazardous**: Medical waste, batteries, electronics - special disposal",
                "- **Methods**: Landfilling, incineration, composting, recycling, 3Rs (Reduce, Reuse, Recycle)",
                "- **E-waste**: Rapidly growing problem with toxic components",
                "### 4. Acid Rain",
                "- Caused by SO2 and NOx reacting with water vapor",
                "- Forms sulfuric and nitric acid in rain",
                "- Damages buildings, aquatic ecosystems, forests, soil",
                "- pH less than 5.6 is considered acid rain",
                "### 5. Greenhouse Effect and Global Warming",
                "- **Greenhouse gases**: CO2, CH4, N2O, CFCs, water vapor",
                "- **Enhanced greenhouse effect**: Human activities increase GHG concentrations",
                "- **Effects**: Rising temperatures, sea level rise, extreme weather, melting glaciers",
                "- **Kyoto Protocol (1997)**: International agreement to reduce GHG emissions",
                "- **Paris Agreement (2015)**: Limit warming to well below 2°C above pre-industrial",
                "### 6. Ozone Layer Depletion",
                "- **Ozone (O3)**: Protects Earth from harmful UV radiation",
                "- **CFCs (Chlorofluorocarbons)**: Release chlorine atoms that destroy ozone",
                "- **Ozone hole**: Over Antarctica, discovered in 1985",
                "- **Montreal Protocol (1987)**: Phased out CFCs successfully",
                "- **Effects of depletion**: Skin cancer, cataracts, immune suppression, crop damage",
                "### 7. Entrance Exam Focus",
                "Causes and effects of pollution types; Greenhouse gases; Ozone depletion mechanism.",
            ],
            "confusion": [
                "x Ozone is always bad. x Stratospheric ozone protects us; ground-level ozone is a pollutant.",
                "x Global warming = ozone depletion. x Different problems with different causes.",
                "x CO2 is the only greenhouse gas. x CH4, N2O, CFCs are also significant.",
            ],
            "practice": [
                "Explain the cause and effects of acid rain.",
                "What is the greenhouse effect? List major greenhouse gases.",
                "Describe the mechanism of ozone layer depletion.",
                "How does eutrophication affect aquatic ecosystems?",
            ],
            "formulas": [],
        },
    },
}

def generate_slug(title):
    slug = title.lower().strip()
    slug = re.sub(r'[^a-z0-9\s-]', '', slug)
    slug = re.sub(r'\s+', '-', slug)
    return slug.rstrip('-')

def main():
    base = Path('public/data/syllabus-notes/biology')
    count = 0

    for unit_slug, units in BIOLOGY_CONTENT.items():
        unit_dir = base / unit_slug
        unit_dir.mkdir(parents=True, exist_ok=True)

        for topic_title, content in units.items():
            slug = generate_slug(topic_title)
            note = {
                "title": topic_title,
                "unitSlug": unit_slug,
                "topicSlug": slug,
                "topicTitle": topic_title,
                "relevance": 100,
                "notes": content["notes"],
                "confusion": content.get("confusion", []),
                "practice": content.get("practice", []),
                "formulas": content.get("formulas", []),
            }
            path = unit_dir / f"{count+1:02d}-{slug}.json"
            with open(path, 'w', encoding='utf-8') as f:
                json.dump(note, f, indent=2, ensure_ascii=False)
            count += 1
            print(f"Created: {path}")

    print(f"\nTotal Biology files generated: {count}")

if __name__ == "__main__":
    main()
