import { z } from "zod";
import { MdList, MdString, NoteBlockSchema, ShortString, Slug } from "./atoms";
import { BlockSchema, FormulaSchema } from "./formula";

/**
 * `content/ravikishan/class-11-notes/…` → classSlug `class-11`.
 * Consumed by `scripts/content/build.ts` and the validator's path scope.
 */
export const CLASS_DIR_TO_SLUG: Record<string, string> = {
  "class-11-notes": "class-11",
  "class-12-notes": "class-12",
};

/**
 * Concept note schema — `content/ravikishan/{classSlug}-notes/{subject}/{unit}/concepts/NN-slug.json`
 *
 * The field inventory is MEASURED, not remembered. It was taken by walking the
 * corpus and listing every distinct top-level key under `concepts/`
 * (40 fields; see `scripts/enrichment/schema-gap.mjs`).
 *
 *  - Required  → `frontend/agents.md` §3 minimum for a renderable note.
 *  - Authored  → the curated note body: what a reader sees.
 *  - Extended  → fields that came in from older pipelines or other families.
 *                Present in real files, so `.strict()` must declare them.
 *
 * The three tiers are documented rather than separate schemas so that a single
 * parse still accepts every one of the ~594 concept files today. Tightening is
 * possible later by moving a tier to `.optional()` removal — deliberately NOT
 * done here, because silently dropping a field the UI reads is worse than
 * declaring it.
 */

/** Every MCQ object shape used by `mcs` (the older, consistent field). */
export const McqSchema = z
  .object({
    question: MdString,
    options: z.array(MdString).min(2).max(8),
    /** Letter matching the option index, e.g. `"C"`. */
    answer: z.string().regex(/^[A-H]$/, "answer must be a letter A–H"),
    explanation: MdString.optional(),
  })
  .strict()
  .refine((m) => m.options.length >= m.answer.charCodeAt(0) - 64, {
    message: "answer letter exceeds the number of options",
    path: ["answer"],
  });

/**
 * `mcqs` is a second, parallel MCQ convention in the corpus (217 concept files)
 * with the same intent but looser shape — most entries were generated by an
 * older pipeline. Kept distinct from `McqSchema` so the two are never confused
 * and so `hasMcqs` can be computed over BOTH.
 */
export const LegacyMcqSchema = z
  .object({
    question: z.string().min(1).max(2_000),
    options: z.array(z.string().min(1).max(500)).min(2).max(8),
    answer: z.string().min(1).max(10),
    explanation: z.string().max(2_000).optional(),
  })
  .passthrough();

/** ── Required: `frontend/agents.md` §3 ────────────────────────────────── */
const RequiredFields = z.object({
  title: ShortString,
  unitSlug: Slug,
  topicSlug: Slug,
  topicTitle: ShortString,
  notes: MdList,
});

/** ── Authored: the curated note body ─────────────────────────────────── */
const AuthoredFields = z.object({
  relevance: z.number().min(0).max(100).optional(),
  confusion: MdList.optional(),
  practice: MdList.optional(),
  universalFacts: MdList.optional(),
  examples: MdList.optional(),
  practiceQuestions: MdList.optional(),
  formulas: MdList.optional(),
  keyPoints: MdList.optional(),
  summary: z.string().max(4_000).optional(),
  specialNotes: MdList.optional(),
  importantStatements: MdList.optional(),
  importantNotes: MdList.optional(),
  examShortTricks: MdList.optional(),
  examNotes: MdList.optional(),
  importantConcepts: MdList.optional(),
  importantTasks: MdList.optional(),
  mcs: z.array(McqSchema).max(40).optional(),
  /** Hard worked numericals with full solutions (see scripts/enrichment). */
  numericals: MdList.optional(),
  // presentation metadata
  animation3D: z.string().max(200).optional(),
  motionGraphics: z.string().max(200).optional(),
  visualType: z.string().max(200).optional(),
  duplicateType: z.number().int().min(1).max(9).optional(),
  /**
   * Deliberately NOT `Slug` or a short cap, unlike the plan's sketch.
   * `tabGroup` is an opaque tab-grouping LABEL: no app code reads it (only
   * producers write it), so it never reaches a URL. Measured values run from
   * `"Atomic-Structure-Learner-Notes"` to filename-derived strings of 236
   * characters, so a slug regex or a 160-char cap rejects legitimate data.
   * The plan's constraint was an assumption; the consumer is the proof.
   */
  tabGroup: z.string().max(400).optional(),

  // ── new in this plan (PLANS.md §4.2/§6): opt-in, absent from every note today ──
  /** Structured formulas with units + solve targets (Phase 4a input). */
  formulaSpecs: z.array(FormulaSchema).optional(),
  /** Inline interactive blocks, ordered after `notes` (Phase 4b). */
  blocks: z.array(BlockSchema).optional(),
});

/**
 * ── Extended: fields inherited from older pipelines ─────────────────────
 *
 * These were NOT in PLANS.md §2, and that omission is the single largest defect
 * in the original plan: with `.strict()` applied to the plan's 27-field list,
 * these files would have been rejected (or, with `.strip()`, silently lost the
 * data they carry). Declaring them here is what makes a strict schema safe.
 *
 * Shapes are deliberately permissive for the ones the UI does not currently
 * parse field-by-field. Where the structure IS known and load-bearing
 * (`mcqs`, `mindmap`) it is typed properly.
 */
const ExtendedFields = z.object({
  // ── parallel MCQ convention (217 concept files) ──
  mcqs: z.array(LegacyMcqSchema).max(40).optional(),

  // ── problem banks (array in all 174 occurrences) ──
  exercises: z.array(z.unknown()).max(500).optional(),

  // ── embedded snapshots of the note payload before/after a round-trip.
  //    Measured as objects with `notes[]`, NOT as strings — 220 files. ──
  originalContent: NoteBlockSchema.optional(),
  enrichedContent: NoteBlockSchema.optional(),
  source: z.string().max(300).optional(),
  filename: z.string().max(300).optional(),
  /**
   * Generator timestamp on the restored legacy notes (measured: 500 concept
   * files carry `"2026-09-10T…"`). Metadata, never content — the backend corpus
   * loader already lists it in META_KEYS, so declaring it here matches how the
   * rest of the platform reads the field.
   */
  generatedAt: z.string().max(60).optional(),
  /**
   * "Bounds & Limits" strings (measured: 3–4 authored lines per note) written
   * by the same older pipeline. This is NOT dead metadata: the UI reads it —
   * `ConceptKnowledgeGrid` renders it as the "Bounds & Limits" card and the 3D
   * rig lists it in `CONCEPT_FIELD_KEYS`. Declaring it (rather than stripping
   * 500 notes) is exactly the Extended-fields doctrine above: a field the UI
   * reads must be in the schema.
   */
  bounds: MdList.optional(),

  // ── visualisation descriptors ──
  /** Measured: { type, component, desc } (105 files). */
  visualization: z
    .object({
      type: z.string().max(120).optional(),
      component: z.string().max(200).optional(),
      desc: z.string().max(600).optional(),
    })
    .passthrough()
    .optional(),
  /** Measured: a plain string (17 files) OR a full spec object (11 files). */
  simulation: z
    .union([
      z.string().max(400),
      z
        .object({
          title: z.string().max(300).optional(),
          description: z.string().max(4_000).optional(),
          parameters: z.array(z.unknown()).max(60).optional(),
          outputs: z.array(z.unknown()).max(60).optional(),
          visualElements: z.array(z.unknown()).max(60).optional(),
        })
        .passthrough(),
    ])
    .optional(),
  uiConfig: z.unknown().optional(),
  specificConditions: z.array(z.unknown()).max(200).optional(),

  // ── nested mindmap block (distinct from a standalone mindmap file) ──
  mindmap: z.unknown().optional(),

  // ── language-specific notes: measured as { notes, importantStatements } ──
  nepali: NoteBlockSchema.optional(),
  grammar: NoteBlockSchema.optional(),
});

/** The MCQ object shape used by `mcs` (the primary, consistent field). */
export type Mcq = z.infer<typeof McqSchema>;

/**
 * The full note contract. `.strict()` is deliberate: a typo'd key becomes a
 * validation failure instead of silently vanishing from the rendered note.
 */
export const ConceptNoteSchema = RequiredFields.merge(AuthoredFields)
  .merge(ExtendedFields)
  .strict();

export type ConceptNote = z.infer<typeof ConceptNoteSchema>;

/**
 * Schema coverage thresholds — a note is *complete* when it carries a body.
 * Kept here so the validator can grade completeness SEPARATELY from schema
 * validity: "valid but thin" is a real, distinct state, and collapsing it into
 * "invalid" hides the difference between a bad key and an unfinished note.
 */
export const MIN_NOTES_FOR_BODY = 4;
export const MIN_MCQ_FOR_TEST = 1;

export function hasBody(note: ConceptNote): boolean {
  return note.notes.length >= MIN_NOTES_FOR_BODY;
}

