import { describe, it, expect } from "vitest";
import { DEPLOY_VERSION } from "@/lib/deploy-version";

/**
 * Footer version badge (owner request 2026-10-01): versioning starts at
 * 0.0001 and every deployment adds exactly 0.0001. The value itself is
 * regenerated by scripts/bump-deploy-version.mjs, so these tests pin the
 * SHAPE of the scheme, never the current number.
 */
describe("deployment version (footer badge)", () => {
  it("is written with exactly four decimal places", () => {
    expect(DEPLOY_VERSION).toMatch(/^\d+\.\d{4}$/);
  });

  it("is a whole number of 0.0001 steps, at least the first version", () => {
    const steps = Number(DEPLOY_VERSION) * 10000;
    expect(Math.abs(steps - Math.round(steps))).toBeLessThan(1e-6);
    expect(Math.round(steps)).toBeGreaterThanOrEqual(1);
  });
});
