// Part 3d: remaining fields + write
const mindmap = global.mindmap, fs = global.fs, dir = global.dir;
Object.assign(mindmap, {
  confusion: [
    "❌ Memorising 30 disconnected 'chapters'. ✅ All of grammar is 6 branches off one trunk: the sentence.",
    "❌ 'My team are winning' (institution sense). ✅ Collective noun as one unit → singular 'is'.",
    "❌ 'He told that he was ill.' ✅ 'told' needs a person: 'told ME that' / 'said that'.",
    "❌ 'a university' / 'an hour' feels backwards. ✅ Sound decides: /yuː/ → 'a'; silent h → 'an'.",
    "❌ 'If I would have known...'. ✅ Type 3: 'If I HAD known, I would have come.'"
  ],
  practice: [
    "Label any newspaper sentence: subject, verb, object + word class of every remaining word.",
    "Write the 12-cell tense grid empty and fill one example per cell — from memory.",
    "Convert: She said, 'I may visit tomorrow.' → (She said that she might visit the next day.)",
    "Passivise in three tenses: 'The chef prepares the meal.' → present/past/present perfect passive.",
    "Walk the error-scan on: 'One of my friend have gone to America last year.' (friends; has/went — agreement + tense)."
  ],
  universalFacts: [
    "Every grammar question is either morphology (form changes) or syntax (combination rules).",
    "The 12 tense cells are generated by two questions — WHEN (time) and HOW it sits in time (aspect).",
    "Error-spotting is not reading: it is a fixed scan order walked mechanically."
  ],
  animation3D: "writing-and-composition",
  motionGraphics: "writing-and-composition",
  examples: [
    "One sentence, all six branches: 'Yesterday, each of the players, who had trained hard, was given a medal by the captain.' — agreement (each...was), relative pronoun, tense (had trained), voice (was given), narration, modifiers.",
    "The tense grid in one breath: I write / I am writing / I have written / I have been writing — shift all four into past and future for 12.",
    "A mindmap walk for 'spot the error': agreement ✓ → tense ✓ → preposition ✓ → article ✗ (found it)."
  ],
  practiceQuestions: [
    "Q1. Redraw the full map from memory: trunk + 6 branches + 3 sub-nodes, one example each.",
    "Q2. Where does a question-tag error live on the map? (Micro-zones.)",
    "Q3. Which two branches dominate NEB error-spotting? (Agreement + Tense.)"
  ],
  formulas: [
    "SENTENCE = SUBJECT + VERB + rest. Find the head pair first.",
    "PASSIVE = object + be (same tense) + V3 (+ by agent).",
    "BACKSHIFT = everything one step back (time, place, certainty).",
    "CONDITIONALS: 1) if+present→will; 2) if+past→would; 3) if+had V3→would have V3.",
    "AGREEMENT: verb follows the HEAD noun; each/every = singular; or/nor → nearest subject."
  ],
  keyPoints: [
    "Six branches: parts of speech, tenses, agreement, voice, narration, modals/conditions.",
    "Micro-zones decide fill-in-the-blanks: articles, prepositions, tags, non-finites, pairs.",
    "Scan order for errors: agreement → tense → preposition → article → pronoun.",
    "Voice needs a transitive verb; state verbs never passivise.",
    "Universal truths don't backshift."
  ],
  summary: "English grammar is one sentence-mechanics system with six branches — word classes, the 12-tense grid, agreement, voice, narration, modals/conditionals — plus a micro-zone layer of articles, prepositions, tags and fixed pairs that supplies most exam questions. Learn each branch as a machine, walk the error-scan in fixed order, and the whole syllabus compresses onto one revisable page.",
  specialNotes: [
    "Revise by redrawing this map from memory once a week — active recall beats re-reading.",
    "Pair with Grammar Hacks (speed) and Notice/Formal-Informal Writing (applied formats)."
  ],
  importantStatements: [
    "If you can find the subject and verb, no question can hide from you.",
    "Aspect answers HOW the action sits in time; time answers WHEN.",
    "Grammar rules are machines — feed the input, the output is fixed."
  ],
  importantNotes: [
    "This map is the index of the grammar section: every topic page hangs off one of its branches."
  ],
  examShortTricks: [
    "Cross out of-phrases before choosing the verb.",
    "Backshift everything one step: time, place, certainty move together.",
    "were for all persons in Type 2 conditionals (formal).",
    "Sound, not spelling, decides a/an.",
    "Walk the scan order; don't re-read hunting for 'feelings'."
  ]
});
fs.writeFileSync(dir + "01-grammar-master-mindmap.json", JSON.stringify(mindmap, null, 2) + "\n");
console.log("grammar-master-mindmap.json created");