var fs = require("fs");
var path = require("path");
var base = path.join(__dirname, "..", "frontend", "app", "lab");

var lines = [];
lines.push('"use client";');
lines.push("");
lines.push('import Link from "next/link";');
lines.push('import { FlaskConical, Cuboid, BookOpen, Calculator } from "lucide-react";');
lines.push("");
lines.push("const CHEM_LABS = [");
lines.push('  { id: "ch-3d-periodic", title: "Periodic Table 3D", desc: "Interactive 3D periodic table with element details, categories, and search.", type: "3D" },');
lines.push('  { id: "ch-3d-advanced", title: "Chemistry 3D Advanced", desc: "Molecular dynamics, crystallography, spectroscopy, SN1/SN2, DNA, VSEPR.", type: "3D" },');
lines.push('  { id: "ch-3d-micro", title: "Microscopy 3D", desc: "Atomic structure, electron orbitals, crystal lattice visualization.", type: "3D" },');
lines.push('  { id: "ch-th-atomic", title: "Atomic Structure Theory", desc: "Bohr model, quantum numbers, electronic configuration.", type: "Theory" },');
lines.push('  { id: "ch-th-bonding", title: "Chemical Bonding Theory", desc: "Ionic, covalent, metallic bonds, VSEPR theory.", type: "Theory" },');
lines.push('  { id: "ch-th-eq", title: "Equilibrium Theory", desc: "Chemical equilibrium, Le Chatelier-s principle.", type: "Theory" },');
lines.push('  { id: "ch-th-thermo", title: "Thermochemistry Theory", desc: "Enthalpy, entropy, Gibbs free energy.", type: "Theory" },');
lines.push('  { id: "ch-th-kinetics", title: "Chemical Kinetics Theory", desc: "Reaction rates, order of reaction, activation energy.", type: "Theory" },');
lines.push('  { id: "ch-th-acid", title: "Acid-Base Theory", desc: "pH, pOH, strong/weak acids, buffers.", type: "Theory" },');
lines.push('  { id: "ch-th-redox", title: "Redox Theory", desc: "Oxidation-reduction, electrochemical cells.", type: "Theory" },');
lines.push('  { id: "ch-th-organic", title: "Organic Chemistry Theory", desc: "Hydrocarbons, functional groups, nomenclature.", type: "Theory" },');
lines.push('  { id: "ch-calc-ph", title: "pH Calculator", desc: "Calculate pH from concentration for acids and bases.", type: "Calc" },');
lines.push('  { id: "ch-calc-titration", title: "Titration Simulator", desc: "Simulate strong acid-strong base titration and track pH changes.", type: "Calc" },');
lines.push('  { id: "ch-calc-gas", title: "Gas Laws Calc", desc: "Boyle-s, Charles-s, ideal gas law solver.", type: "Calc" },');
lines.push('  { id: "ch-calc-molarmass", title: "Molar Mass Calc", desc: "Enter a chemical formula and get molar mass.", type: "Calc" },');
lines.push('  { id: "ch-calc-stoich", title: "Stoichiometry Lab", desc: "Moles, percent composition, limiting reagent.", type: "Calc" },');
lines.push("];");
lines.push("");
lines.push("const TYPE_CONFIG = {");
lines.push('  "3D": { icon: Cuboid, color: "#10b981", bg: "bg-emerald-500/10", border: "border-emerald-200", text: "text-emerald-700 dark:text-emerald-400 dark:border-emerald-800" },');
lines.push('  "Theory": { icon: BookOpen, color: "#3b82f6", bg: "bg-blue-500/10", border: "border-blue-200", text: "text-blue-700 dark:text-blue-400 dark:border-blue-800" },');
lines.push('  "Calc": { icon: Calculator, color: "#8b5cf6", bg: "bg-violet-500/10", border: "border-violet-200", text: "text-violet-700 dark:text-violet-400 dark:border-violet-800" },');
lines.push("};");
lines.push("");
lines.push("export default function ChemistryHubPage() {");
lines.push("  return (");
lines.push('    <div className="mx-auto max-w-6xl space-y-6 py-8 md:py-14 px-4">');
lines.push("      <div>");
lines.push('        <div className="flex items-center gap-3 mb-2">');
lines.push('          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center shadow-md shadow-emerald-500/20">');
lines.push('            <FlaskConical className="h-5 w-5 text-white" />');
lines.push("          </div>");
lines.push("          <div>");
lines.push('            <h1 className="text-2xl md:text-3xl font-bold tracking-tight">Chemistry Lab</h1>');
lines.push('            <p className="text-sm text-muted-foreground">Interactive 3D visualizations, theory panels, and calculators</p>');
lines.push("          </div>");
lines.push("        </div>");
lines.push('        <Link href="/lab" className="text-xs text-muted-foreground hover:text-primary inline-flex items-center gap-1 mt-2">');
lines.push('          {"←"} Back to all labs');
lines.push("        </Link>");
lines.push("      </div>");
lines.push("");
lines.push('      <div className="flex flex-wrap gap-2">');
lines.push('        <span className="stat-pill">');
lines.push('          <span className="text-muted-foreground">Total:</span>');
lines.push('          <span className="stat-pill-value">{CHEM_LABS.length}</span>');
lines.push("        </span>");
lines.push('        <span className="stat-pill">');
lines.push('          <span className="text-muted-foreground">3D:</span>');
lines.push('          <span className="stat-pill-value text-emerald-600 dark:text-emerald-400">{CHEM_LABS.filter(l => l.type === "3D").length}</span>');
lines.push("        </span>");
lines.push('        <span className="stat-pill">');
lines.push('          <span className="text-muted-foreground">Theory:</span>');
lines.push('          <span className="stat-pill-value text-blue-600 dark:text-blue-400">{CHEM_LABS.filter(l => l.type === "Theory").length}</span>');
lines.push("        </span>");
lines.push('        <span className="stat-pill">');
lines.push('          <span className="text-muted-foreground">Calc:</span>');
lines.push('          <span className="stat-pill-value text-violet-600 dark:text-violet-400">{CHEM_LABS.filter(l => l.type === "Calc").length}</span>');
lines.push("        </span>");
lines.push("      </div>");
lines.push("");
lines.push('      <div>');
lines.push('        <h2 className="font-semibold text-base mb-3">All Chemistry Labs</h2>');
lines.push('        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">');
lines.push("          {CHEM_LABS.map((lab) => {");
lines.push("            const cfg = TYPE_CONFIG[lab.type];");
lines.push("            const Icon = cfg.icon;");
lines.push("            return (");
lines.push('              <Link key={lab.id} href={`/lab/${lab.id}`} className="block group">');
lines.push('                <div className={"elev-1 rounded-xl border border-border bg-card hover:border-primary/50 transition-all duration-200 hover:elev-2 p-4 flex items-start gap-3 h-full " + cfg.bg}>');
lines.push('                  <div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0 bg-white/50 dark:bg-black/20">');
lines.push('                    <Icon className="h-4 w-4" style={{ color: cfg.color }} />');
lines.push("                  </div>");
lines.push("                  <div className=\"min-w-0 flex-1\">");
lines.push('                    <p className="font-semibold text-sm text-foreground group-hover:text-primary transition-colors truncate">{lab.title}</p>');
lines.push('                    <p className="text-[11px] text-muted-foreground mt-0.5 line-clamp-2">{lab.desc}</p>');
lines.push("                  </div>");
lines.push('                  <span className={"text-[10px] px-1.5 py-0.5 rounded-full font-medium shrink-0 border " + cfg.border + " " + cfg.text + " " + cfg.bg}>');
lines.push("                    {lab.type}");
lines.push("                  </span>");
lines.push("                </div>");
lines.push("              </Link>");
lines.push("            );");
lines.push("          })}");
lines.push("        </div>");
lines.push("      </div>");
lines.push("    </div>");
lines.push("  );");
lines.push("}");
lines.push("");

fs.writeFileSync(path.join(base, "chemistry", "page.tsx"), lines.join("\n"), "utf8");
console.log("Created chemistry/page.tsx hub page");