// Part 3c: branches 5-6 + micro-zones + execution loop
const mindmap = global.mindmap;
mindmap.notes.push(
    "**BRANCH 5 — NARRATION (direct ↔ indirect speech):** two operations: (a) remove quotes, add 'that'/to-infinitive/connector; (b) BACKSHIFT — reporting verb in past shifts everything one step back: present→past, past→past perfect, will/can/may→would/could/might, this→that, now→then, today→that day, ago→before, here→there, tomorrow→the next day. Statements → that +; yes-no questions → if/whether with statement word-order; wh-questions → wh-word + statement order; commands → to + V1 ('told him to go'); requests → requested + to; exclamations → exclaimed with joy/sorrow that.",
    "**BRANCH 5 sub-node — no-backshift cases:** universal truths stay present ('the earth revolves...'); if the reporting verb is present/future ('says'), nothing shifts.",
    "**BRANCH 6 — MODALS & CONDITIONS:** modals (can, could, may, might, shall, should, will, would, must, ought to) never take to/s/-ing and are followed by V1. Meanings: can=ability, may=permission/possibility, must=obligation/certainty, should=advice, would=past habit/politeness/unreal. The conditional ladder: Type 1 (if + present, will + V1) real future; Type 2 (if + past, would + V1) unreal present — 'were' for all persons; Type 3 (if + had + V3, would have + V3) unreal past — regret/replay.",
    "**CROSS-BRANCH MICRO-ZONES (the marks-savers):** ARTICLES (a/an by SOUND — 'an hour', 'a university'; the = specific/second mention/unique; zero before meals, languages, games). PREPOSITIONS (IN/ON/AT for place and time scales). QUESTION TAGS (copy the auxiliary, flip polarity; none → do/does/did). NON-FINITES (infinitive = purpose; gerund = noun; participle = adjective). DEGREES (comparative + than; superlative + the; 'than that of' for like-with-like). FIXED PAIRS (no sooner...than; hardly...when; not only...but also — never mixed).",
    "**EXAM EXECUTION LOOP:** 1) identify the branch the question lives on; 2) apply that branch's machine (the rules are mechanical); 3) in error-spotting walk the scan order: agreement → tense → preposition → article → pronoun; 4) after writing, re-check the five most-tested zones."
);
require("./gen-part3d.js");