@echo off
cd /d "%~dp0educational-platform-global"
echo Starting backend server...
start "Backend" cmd /c "npm run dev:backend"
echo Starting frontend server...
start "Frontend" cmd /c "npm run dev"
echo Both servers starting...
ping 127.0.0.1 -n 15 >nul
echo Opening browser...
start http://localhost:5173
