{
  "build": {
    "command": "npm run build",
    "commandOrigin": "config",
    "publish": {
      "publishOrigin": "config",
      "directory": "frontend/.next"
    }
  },
  "functions": {
    "frontend/.netlify/functions-internal/**": {
      "runtime": "nodejs20.x"
    }
  }
}
