/**
 * Chemistry theorem / concept bank — NEB Che. 201 (Grade 11).
 * Entries are authored in official syllabus (unit) order and each is wired to
 * an EXISTING DerivationVisual `visualType` so it renders on the theorems page.
 */
import type { DerivationOrTheorem } from "@/lib/derivations-data";

export const CHEMISTRY_THEOREMS: DerivationOrTheorem[] = [
  // ── Unit 2: Stoichiometry ────────────────────────────────────────────────
  {
    id: "chem-avogadro-deduction",
    slug: "avogadros-law-deduction",
    title: "Avogadro's Law and Its Deductions",
    subject: "chemistry",
    unit: "Stoichiometry",
    unitId: "stoichiometry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Equal volumes of all gases at the same temperature and pressure contain equal numbers of molecules; from this, molecular mass and vapour density can be deduced.",
    coreFormula: "V \\propto N \\ (T,P\\ constant); M = 2 \\times VD",
    concernedTerms: [
      { term: "Vapour density", symbol: "VD", definition: "Mass of a gas occupying the same volume as an equal mass of H2." },
      { term: "Mole", symbol: "mol", definition: "6.022\\times10^{23} entities of a substance." },
      { term: "Molar volume", symbol: "22.4 L", definition: "Volume of 1 mole of a gas at STP." },
    ],
    assumptions: ["The gas behaves ideally and T, P are constant."],
    proofSteps: [
      { stepNumber: 1, title: "Law statement", latex: "V_1/N_1 = V_2/N_2", explanation: "At fixed T and P, volume is directly proportional to molecule count." },
      { stepNumber: 2, title: "Deduce molecular mass", latex: "M = \\text{mass of } 6.022\\times10^{23} \\text{ molecules} = \\text{mass of 22.4 L at STP}", explanation: "1 mole occupies 22.4 L at STP, so molar mass = gas density × 22.4." },
      { stepNumber: 3, title: "Deduce vapour density relation", latex: "VD = \\frac{\\rho}{\\rho_{H_2}} = \\frac{M}{2} \\implies M = 2 \\times VD", explanation: "Hydrogen (M=2) is the reference." },
    ],
    conclusion: "Avogadro's law lets us convert between gas volumes and molecular amounts — the bridge of gas stoichiometry.",
    keyTakeaways: ["M = 2 × VD; 1 mole of any gas = 22.4 L at STP."],
    examTraps: ["Vapour density uses H2 as the standard, not H or He."],
    visualType: "avogadros-law-deduction",
    solvedProblems: [
      {
        id: "chem-avog-1",
        question: "Find the molecular mass of a gas whose vapour density is 16.",
        given: "VD = 16.",
        stepByStep: ["M = 2 × VD.", "M = 2 × 16 = 32."],
        finalAnswer: "M = 32 (oxygen)",
        visualType: "avogadros-law-deduction",
        tipOrTrap: "Always double the vapour density.",
      },
    ],
  },

  // ── Unit 3: Atomic Structure ────────────────────────────────────────────
  {
    id: "chem-quantum-numbers",
    slug: "quantum-numbers-rules",
    title: "Quantum Numbers and Their Rules",
    subject: "chemistry",
    unit: "Atomic Structure",
    unitId: "atomic-structure",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Each electron in an atom is described by four quantum numbers: n (energy level), l (subshell shape), m_l (orientation) and m_s (spin).",
    coreFormula: "n = 1,2,3,\\dots;\\ l = 0\\dots n-1;\\ m_l = -l\\dots +l;\\ m_s = \\pm \\tfrac{1}{2}",
    concernedTerms: [
      { term: "Principal quantum number", symbol: "n", definition: "Energy shell; number of orbitals = n²." },
      { term: "Azimuthal quantum number", symbol: "l", definition: "Subshell shape: s(0), p(1), d(2), f(3)." },
      { term: "Magnetic quantum number", symbol: "m_l", definition: "Orbital orientation; gives 2l+1 orbitals." },
      { term: "Spin quantum number", symbol: "m_s", definition: "Electron spin; ±½, allowing 2 electrons per orbital." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Count orbitals per shell", latex: "\\#\\ \\text{orbitals} = n^2, \\quad \\#\\ \\text{electrons} = 2n^2", explanation: "Each orbital holds two opposite-spin electrons." },
      { stepNumber: 2, title: "Count orbitals per subshell", latex: "s:1, p:3, d:5, f:7", explanation: "Follows 2l+1." },
      { stepNumber: 3, title: "Validate a set", latex: "(3,2,-2,\\tfrac12) \\checkmark;\\ (3,3,0,\\tfrac12) \\times", explanation: "l must be < n; l=3 is forbidden for n=3." },
    ],
    conclusion: "The quantum-number rules define every valid electron state and the capacity of each shell and subshell.",
    keyTakeaways: ["n=3 holds 18 electrons (2n²); p subshell always has 3 orbitals."],
    examTraps: ["l=3 (f) first appears at n=4."],
    visualType: "quantum-numbers",
    solvedProblems: [
      {
        id: "chem-qn-1",
        question: "How many orbitals and electrons does the third shell contain?",
        given: "n = 3.",
        stepByStep: ["Orbitals = n² = 9.", "Electrons = 2n² = 18."],
        finalAnswer: "9 orbitals, 18 electrons",
        visualType: "quantum-numbers",
      },
    ],
  },
  {
    id: "chem-heisenberg-uncertainty",
    slug: "heisenberg-uncertainty-principle",
    title: "Heisenberg's Uncertainty Principle",
    subject: "chemistry",
    unit: "Atomic Structure",
    unitId: "atomic-structure",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "The position and momentum of a particle cannot both be known with arbitrary precision: \\(\\Delta x\\,\\Delta p \\ge h/4\\pi\\).",
    coreFormula: "\\Delta x \\, \\Delta p \\ge \\frac{h}{4\\pi}",
    concernedTerms: [
      { term: "Planck's constant", symbol: "h", definition: "6.626\\times10^{-34} J·s." },
      { term: "Probability density", symbol: "\\Psi^2", definition: "Chance of finding the electron in a small volume." },
      { term: "Orbital", definition: "Region of high probability, not a fixed path." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Numerical check", latex: "m_e = 9.1\\times10^{-31}\\,kg, v \\sim 10^6\\,m/s \\Rightarrow \\Delta x \\ge \\frac{h}{4\\pi m v}", explanation: "For an electron this lower bound is ~atomic scale; for macroscopic bodies it is negligible." },
      { stepNumber: 2, title: "Consequence", latex: "\\text{orbit} \\times \\; \\text{probability} \\checkmark", explanation: "Bohr's fixed orbits are replaced by probability orbitals." },
    ],
    conclusion: "Quantum mechanics replaces particle orbits with probability clouds; the uncertainty principle is the formal limit of measurement.",
    keyTakeaways: ["The principle matters only for very small masses."],
    examTraps: ["Δp is the uncertainty in momentum, not the whole momentum."],
    visualType: "heisenberg-uncertainty",
    solvedProblems: [
      {
        id: "chem-heis-1",
        question: "If an electron's position is known to ±1 pm, estimate the minimum uncertainty in its velocity.",
        given: "Δx = 10⁻¹² m, mₑ = 9.1×10⁻³¹ kg.",
        stepByStep: ["Δv ≥ h/(4π m Δx).", "≈ 6.6×10⁻³⁴ / (4π × 9.1×10⁻³¹ × 10⁻¹²) ≈ 5.8×10⁴ m/s."],
        finalAnswer: "Δv ≈ 6×10⁴ m/s",
        visualType: "heisenberg-uncertainty",
      },
    ],
  },

  // ── Unit 5: Chemical Bonding and Shapes of Molecules ───────────────────
  {
    id: "chem-vsepr-shapes",
    slug: "vsepr-theory-molecular-shapes",
    title: "VSEPR Theory and Molecular Shapes",
    subject: "chemistry",
    unit: "Chemical Bonding and Shapes of Molecules",
    unitId: "chemical-bonding-and-shapes-of-molecules",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Electron pairs around a central atom repel and arrange themselves as far apart as possible; lone pairs repel more strongly than bond pairs, distorting ideal angles.",
    coreFormula: "\\text{AX}_n\\text{E}_m \\Rightarrow \\text{shape}",
    concernedTerms: [
      { term: "Bond pair", symbol: "B", definition: "Shared pair in a covalent bond." },
      { term: "Lone pair", symbol: "E", definition: "Non-bonding electron pair on the central atom." },
      { term: "Steric number", definition: "Number of electron domains (B+E); sets the electron geometry." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Predict CH4", latex: "C: 4B,0E \\Rightarrow \\text{tetrahedral}, 109.5^{\\circ}", explanation: "Four equivalent domains." },
      { stepNumber: 2, title: "Predict NH3 and H2O", latex: "N: 3B,1E \\Rightarrow \\text{trigonal-pyramidal}, 107^{\\circ}; O: 2B,2E \\Rightarrow \\text{bent}, 104.5^{\\circ}", explanation: "Lone pairs compress bond angles." },
      { stepNumber: 3, title: "Predict BeF2 / BF3", latex: "Be: 2B \\Rightarrow \\text{linear}, 180^{\\circ}; B: 3B \\Rightarrow \\text{trigonal-planar}, 120^{\\circ}", explanation: "No lone pairs → ideal angles." },
    ],
    conclusion: "Molecular shape = electron geometry bent by lone-pair repulsion (E > E–B > B–B).",
    keyTakeaways: ["H2O is bent at 104.5°, NH3 pyramidal at 107°."],
    examTraps: ["The shape is named for ATOM positions; H2O's electron geometry is tetrahedral but its molecular shape is bent."],
    visualType: "vsepr-theory",
    solvedProblems: [
      {
        id: "chem-vsepr-1",
        question: "Predict the shape and bond angle of SF6.",
        given: "S: 6 bond pairs, 0 lone pairs.",
        stepByStep: ["Steric number 6, octahedral.", "All 90° and 180° angles."],
        finalAnswer: "Octahedral, 90°",
        visualType: "vsepr-theory",
      },
    ],
  },
  {
    id: "chem-hybridization-sp-sp2-sp3",
    slug: "hybridization-spspsp2spp3",
    title: "Hybridization of s and p Orbitals (sp, sp², sp³)",
    subject: "chemistry",
    unit: "Chemical Bonding and Shapes of Molecules",
    unitId: "chemical-bonding-and-shapes-of-molecules",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Valence orbitals mix into equivalent hybrid orbitals whose number and geometry explain molecular shapes: sp (linear), sp² (trigonal planar), sp³ (tetrahedral).",
    coreFormula: "sp:\\,180^{\\circ};\\ sp^2:\\,120^{\\circ};\\ sp^3:\\,109.5^{\\circ}",
    concernedTerms: [
      { term: "Hybrid orbital", definition: "Mix of atomic orbitals of comparable energy and compatible symmetry." },
      { term: "σ bond", definition: "Head-on overlap of hybrid orbitals." },
      { term: "s-character", symbol: "50/33/25%", definition: "sp has 50% s; sp² 33%; sp³ 25%." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "BeCl2 / CO2", latex: "sp \\Rightarrow \\text{linear}", explanation: "Two hybrids form two σ bonds." },
      { stepNumber: 2, title: "BF3 / C2H4", latex: "sp^2 \\Rightarrow \\text{planar}, \\pi \\text{ bond from unhybridised p}", explanation: "The leftover p orbital gives the π system." },
      { stepNumber: 3, title: "CH4 / NH3", latex: "sp^3 \\Rightarrow \\text{tetrahedral}", explanation: "Four hybrids; lone pairs occupy one in NH3." },
    ],
    conclusion: "Hybridization rationalizes bond angles and the π bonds of double/triple bonds.",
    keyTakeaways: ["A triple bond = 1 σ (sp) + 2 π; a double bond = 1 σ (sp²) + 1 π."],
    examTraps: ["Hybridization is judged by steric number, not by the number of bonds alone."],
    visualType: "hybridization-spspsp2spp3",
    solvedProblems: [
      {
        id: "chem-hyb-1",
        question: "Give the hybridization and shape of CO2.",
        given: "C is the central atom.",
        stepByStep: ["Steric number 2 (two σ bonds).", "sp hybrids, linear."],
        finalAnswer: "sp, linear",
        visualType: "hybridization-spspsp2spp3",
      },
    ],
  },

  // ── Unit 6: Oxidation and Reduction ─────────────────────────────────────
  {
    id: "chem-redox-half-reaction",
    slug: "redox-balancing-half-reaction",
    title: "Balancing Redox Reactions by the Half-Reaction Method",
    subject: "chemistry",
    unit: "Oxidation and Reduction",
    unitId: "oxidation-and-reduction",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "A redox equation is balanced by separating the oxidation and reduction half-reactions, balancing mass and charge in each, then combining them so electrons cancel.",
    coreFormula: "\\text{ox} + e^- \\rightarrow \\text{red};\\ \\sum e^-=\\sum e^-",
    concernedTerms: [
      { term: "Oxidation number", definition: "Hypothetical ionic charge used to track electron transfer." },
      { term: "Half-reaction", definition: "One side of the electron transfer (oxidation or reduction)." },
      { term: "Electrode potential", definition: "Tendency of a half-cell to gain/lose electrons." },
    ],
    assumptions: ["Acidic medium shown (H+/H2O used for O and H balancing)."],
    proofSteps: [
      { stepNumber: 1, title: "Split the reaction", latex: "MnO_4^- \\rightarrow Mn^{2+}\\ (\\text{reduction}); Fe^{2+} \\rightarrow Fe^{3+}\\ (\\text{oxidation})", explanation: "Mn: +7→+2 (gains 5e⁻); Fe: +2→+3 (loses 1e⁻)." },
      { stepNumber: 2, title: "Balance O and H (acidic)", latex: "MnO_4^- + 8H^+ + 5e^- \\rightarrow Mn^{2+} + 4H_2O", explanation: "Water balances O; H⁺ balances H; electrons balance charge." },
      { stepNumber: 3, title: "Equalize and add", latex: "MnO_4^- + 8H^+ + 5Fe^{2+} \\rightarrow Mn^{2+} + 4H_2O + 5Fe^{3+}", explanation: "5 Fe²⁺ supply the 5 electrons; charges: +8−1−5=+2 both sides." },
    ],
    conclusion: "The half-reaction method guarantees mass and charge balance in any redox equation.",
    keyTakeaways: ["Multiply the half-reactions to equalize electron count."],
    examTraps: ["In basic medium, neutralize H⁺ with OH⁻ afterwards."],
    visualType: "redox-balancing-half-reaction",
    solvedProblems: [
      {
        id: "chem-redox-1",
        question: "Balance: Cr2O7²⁻ + Fe²⁺ + H⁺ → Cr³⁺ + Fe³⁺ + H2O.",
        given: "Acidic permanganate-style method.",
        stepByStep: ["Cr: +6→+3, gains 3e⁻ per Cr, 6e⁻ total.", "Fe²⁺→Fe³⁺ loses 1e⁻; ×6 Fe²⁺.", "Cr2O7²⁻ + 14H⁺ + 6Fe²⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H2O."],
        finalAnswer: "1,14,6 → 2,6,7",
        visualType: "redox-balancing-half-reaction",
      },
    ],
  },
  {
    id: "chem-electrolysis-faradays-law",
    slug: "electrolysis-faraday-laws",
    title: "Faraday's Laws of Electrolysis",
    subject: "chemistry",
    unit: "Oxidation and Reduction",
    unitId: "oxidation-and-reduction",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "The mass of substance deposited/ liberated at an electrode is proportional to (i) the charge passed and (ii) its equivalent weight.",
    coreFormula: "m = \\frac{M\\, I\\, t}{n\\,F},\\quad F = 96485\\,\\text{C mol}^{-1}",
    concernedTerms: [
      { term: "Faraday constant", symbol: "F", definition: "Charge of 1 mole of electrons (≈ 96485 C)." },
      { term: "Equivalent weight", symbol: "M/n", definition: "Molar mass per mole of electrons exchanged." },
      { term: "Electrode reaction", definition: "Oxidation at anode, reduction at cathode in an electrolytic cell." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "First law", latex: "m \\propto Q \\Rightarrow m = zQ = zIt", explanation: "z is the electrochemical equivalent." },
      { stepNumber: 2, title: "Second law", latex: "m \\propto \\text{equivalent weight} \\Rightarrow m = \\frac{M}{nF}Q", explanation: "Same charge deposits equal equivalents of different substances." },
      { stepNumber: 3, title: "Apply", latex: "\\text{Cu}^{2+} + 2e^- \\rightarrow \\text{Cu}: m = \\frac{63.5\\,It}{2F}", explanation: "n=2 for Cu²⁺." },
    ],
    conclusion: "Faraday's laws connect charge, time and current to the mass of electrode products.",
    keyTakeaways: ["1 F deposits 1 equivalent of any substance."],
    examTraps: ["Use the correct n (electrons per ion): Ag⁺→Ag has n=1, Cu²⁺→Cu has n=2."],
    visualType: "electrolysis-faraday",
    solvedProblems: [
      {
        id: "chem-faraday-1",
        question: "How much silver (Ag, M=108) is deposited by 2 A for 1 hour?",
        given: "Ag⁺ + e⁻ → Ag, n=1.",
        stepByStep: ["Q = It = 2×3600 = 7200 C.", "m = MQ/F = 108×7200/96485 ≈ 8.07 g."],
        finalAnswer: "≈ 8.1 g Ag",
        visualType: "electrolysis-faraday",
      },
    ],
  },

  // ── Unit 7: States of Matter ────────────────────────────────────────────
  {
    id: "chem-combined-gas-law",
    slug: "combined-gas-law",
    title: "Combined Gas Law",
    subject: "chemistry",
    unit: "States of Matter",
    unitId: "states-of-matter",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "For a fixed amount of gas, pressure, volume and temperature are linked: \\(P_1V_1/T_1 = P_2V_2/T_2\\).",
    coreFormula: "\\frac{P_1 V_1}{T_1} = \\frac{P_2 V_2}{T_2}",
    concernedTerms: [
      { term: "Boyle's law", symbol: "PV = const", definition: "At constant T, P∝1/V." },
      { term: "Charles' law", symbol: "V/T = const", definition: "At constant P, V∝T (K)." },
      { term: "Kelvin scale", definition: "Absolute temperature; T(K)=t(°C)+273." },
    ],
    assumptions: ["Fixed moles; ideal-gas behaviour."],
    proofSteps: [
      { stepNumber: 1, title: "Combine Boyle + Charles + Gay-Lussac", latex: "\\frac{P_1 V_1}{T_1} = \\frac{P_2 V_2}{T_2}", explanation: "Each pair of variables relates through the same constant." },
      { stepNumber: 2, title: "Solve example", latex: "\\frac{1\\times V}{298} = \\frac{2\\times 0.5}{350} \\Rightarrow V = 0.85\\,L", explanation: "Compressed and heated gas keeps P·V/T constant." },
    ],
    conclusion: "The combined law relates a gas between any two equilibrium states.",
    keyTakeaways: ["Always use kelvin temperatures."],
    examTraps: ["Using °C instead of K silently breaks the ratio."],
    visualType: "combined-gas-law",
    solvedProblems: [
      {
        id: "chem-cgl-1",
        question: "A gas at 1 atm, 2 L, 27 °C is compressed to 0.5 L at 35 °C. Find the final pressure.",
        given: "Combined gas law.",
        stepByStep: ["T1=300K, T2=308K.", "P2 = P1·V1·T2/(V2·T1) = 1×2×308/(0.5×300) ≈ 4.11 atm."],
        finalAnswer: "≈ 4.1 atm",
        visualType: "combined-gas-law",
      },
    ],
  },
  {
    id: "chem-real-gas-compressibility",
    slug: "real-gas-compressibility",
    title: "Real Gases and the Compressibility Factor",
    subject: "chemistry",
    unit: "States of Matter",
    unitId: "states-of-matter",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Real gases deviate from ideality at low T and high P; the van der Waals equation and the compressibility factor Z capture the correction.",
    coreFormula: "\\left(P + a\\frac{n^2}{V^2}\\right)(V - nb) = nRT;\\quad Z = \\frac{PV}{nRT}",
    concernedTerms: [
      { term: "Compressibility factor", symbol: "Z", definition: "Ratio of actual to ideal PV; Z=1 for an ideal gas." },
      { term: "van der Waals constants", symbol: "a, b", definition: "a = intermolecular attraction; b = excluded volume." },
      { term: "Critical point", definition: "Above it, no liquid exists; Z = 0.5 region signals strong attraction." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Volume correction", latex: "V_{\\text{free}} = V - nb", explanation: "Molecules themselves occupy volume b per mole." },
      { stepNumber: 2, title: "Pressure correction", latex: "P_{\\text{meas}} + a\\frac{n^2}{V^2}", explanation: "Attraction near the walls reduces measured pressure." },
      { stepNumber: 3, title: "Read Z", latex: "Z > 1:\\ \\text{repulsion};\\ Z < 1: \\text{attraction}", explanation: "Deviations vanish at high T / low P." },
    ],
    conclusion: "The Z-factor diagnosis tells whether attraction or excluded volume dominates.",
    keyTakeaways: ["At low T, H2 shows Z>1 even at moderate pressure."],
    examTraps: ["Z<1 does not mean 'harder to compress' — it means attractions hold molecules in."],
    visualType: "real-gas-compressibility",
    solvedProblems: [
      {
        id: "chem-rz-1",
        question: "A gas occupies 0.95 L at 1 atm, 273 K (n = 0.042 mol). Find Z.",
        given: "Z = PV/nRT.",
        stepByStep: ["Z = (1×0.95)/(0.042×0.082×273) ≈ 0.95/0.94 ≈ 1.01."],
        finalAnswer: "Z ≈ 1.01 (nearly ideal)",
        visualType: "real-gas-compressibility",
      },
    ],
  },

  // ── Unit 8: Chemical Equilibrium ────────────────────────────────────────
  {
    id: "chem-law-of-mass-action",
    slug: "law-of-mass-action-equilibrium-constant",
    title: "Law of Mass Action and the Equilibrium Constant",
    subject: "chemistry",
    unit: "Chemical Equilibrium",
    unitId: "chemical-equilibrium",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "At equilibrium, the rate of a chemical reaction is proportional to the product of the molar concentrations of the reactants, each raised to its stoichiometric power.",
    coreFormula: "K_c = \\frac{[C]^c[D]^d}{[A]^a[B]^b}",
    concernedTerms: [
      { term: "Reaction quotient", symbol: "Q", definition: "Same expression as K but with current concentrations; Q<K → forward." },
      { term: "Equilibrium constant", symbol: "K", definition: "Concentration ratio at equilibrium; large K favors products." },
      { term: "Dynamic equilibrium", definition: "Forward and reverse rates equal; concentrations constant." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Write the expression", latex: "N_2 + 3H_2 \\rightleftharpoons 2NH_3: K = \\frac{[NH_3]^2}{[N_2][H_2]^3}", explanation: "Coefficients become exponents; pure solids/liquids are omitted." },
      { stepNumber: 2, title: "Direction of shift", latex: "Q < K \\Rightarrow \\text{forward}", explanation: "The system responds to re-establish K." },
    ],
    conclusion: "K fixes the composition at equilibrium; Q predicts which direction a disturbed system moves.",
    keyTakeaways: ["K is temperature-dependent only."],
    examTraps: ["Omit H2O (liquid) and solids from Kc expressions."],
    visualType: "mass-action-equilibrium",
    solvedProblems: [
      {
        id: "chem-lma-1",
        question: "For 2SO2 + O2 ⇌ 2SO3 with [SO2]=0.2, [O2]=0.1, [SO3]=0.6, find Kc.",
        given: "Concentrations at equilibrium.",
        stepByStep: ["Kc = [SO3]²/([SO2]²[O2]).", "Kc = 0.36/(0.04×0.1) = 90."],
        finalAnswer: "Kc = 90",
        visualType: "mass-action-equilibrium",
      },
    ],
  },
  {
    id: "chem-buffer-henderson",
    slug: "buffer-henderson-hasselbalch",
    title: "Buffers and the Henderson–Hasselbalch Equation",
    subject: "chemistry",
    unit: "Chemical Equilibrium",
    unitId: "chemical-equilibrium",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "A weak acid plus its salt resists pH change; the buffer pH is given by pH = pKa + log([A⁻]/[HA]).",
    coreFormula: "\\text{pH} = \\text{p}K_a + \\log\\frac{[A^-]}{[HA]}",
    concernedTerms: [
      { term: "Buffer capacity", definition: "Moles of acid/base the buffer can absorb before failure." },
      { term: "Conjugate pair", definition: "HA/A⁻ whose ratio sets pH near pKa." },
      { term: "pKa", definition: "The pH where [A⁻] = [HA]; buffer works best within ±1 pH unit." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Derive from Ka", latex: "K_a = \\frac{[H^+][A^-]}{[HA]} \\Rightarrow [H^+] = K_a\\frac{[HA]}{[A^-]}", explanation: "Take −log on both sides." },
      { stepNumber: 2, title: "Henderson form", latex: "\\text{pH} = \\text{p}K_a + \\log\\frac{[A^-]}{[HA]}", explanation: "Ratio of base to acid fixes pH." },
      { stepNumber: 3, title: "Apply", latex: "\\text{pH} = 4.76 + \\log\\frac{0.5}{0.5} = 4.76", explanation: "Equal concentrations give pH = pKa." },
    ],
    conclusion: "Buffers pin pH to the pKa of the acid pair; they fail when the acid (or base) is consumed.",
    keyTakeaways: ["pH of a buffer ≈ pKa ± 1."],
    examTraps: ["[A\u207b] is the conjugate BASE — it goes in the numerator."],
    visualType: "buffer-henderson",
    solvedProblems: [
      {
        id: "chem-buffer-1",
        question: "A buffer has 0.1 M acetic acid and 0.2 M acetate. pKa = 4.76. Find pH.",
        given: "Henderson–Hasselbalch.",
        stepByStep: ["pH = 4.76 + log(0.2/0.1).", "log(2) = 0.30."],
        finalAnswer: "pH = 5.06",
        visualType: "buffer-henderson",
      },
    ],
  },

  // ── Unit 12: Fundamental Principles of Organic Chemistry ────────────────
  {
    id: "chem-inductive-resonance-effects",
    slug: "inductive-resonance-effect",
    title: "Inductive and Resonance Effects in Organic Chemistry",
    subject: "chemistry",
    unit: "Fundamental Principles of Organic Chemistry",
    unitId: "fundamental-principles-of-organic-chemistry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "The inductive effect shifts σ-electron density through a chain (+I/−I); resonance delocalizes electrons through π-systems (+R/−R); together they govern acidity, reactivity and stability.",
    coreFormula: "-I \\downarrow pH;\\ +R \\uparrow \\text{stability}",
    concernedTerms: [
      { term: "Inductive effect", symbol: "±I", definition: "Permanent σ polarization by electronegative groups; decays fast with distance." },
      { term: "Resonance", symbol: "±R", definition: "Delocalization of π electrons; gives multiple valid structures." },
      { term: "Electrophile / nucleophile", definition: "Electron-poor / electron-rich reactive species." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Acidity via −I", latex: "CH_3COOH < ClCH_2COOH < Cl_2CHCOOH < Cl_3CCOOH", explanation: "More −I (Cl) stabilizes the conjugate base → stronger acid." },
      { stepNumber: 2, title: "Stability via +R", latex: "\\text{CH}_2=\\text{CH}-OH: +R \\Rightarrow O-lone-pair} \\rightarrow \\pi", explanation: "Lone pairs donated into the π system." },
      { stepNumber: 3, title: "Compare ranges", latex: "-I:\\,\\text{chain};\\ \\pm R:\\,\\pi\\text{-system}", explanation: "Induction is strong over 2–3 bonds; resonance needs conjugation." },
    ],
    conclusion: "Electron effects are the 'why' behind relative stabilities and reactivities.",
    keyTakeaways: ["NO2 and CHO are −M (−R) groups; OMe and NH2 are +R."],
    examTraps: ["A lone pair conjugated with a π system is +R, but an electronegative atom attached to a σ chain is −I."],
    visualType: "inductive-resonance-effect",
    solvedProblems: [
      {
        id: "chem-effect-1",
        question: "Arrange in increasing acidity: phenol, p-nitrophenol, p-methoxyphenol.",
        given: "−I/−R stabilizes phenoxide.",
        stepByStep: ["p-NO2 (−M) most stabilizing → strongest acid.", "p-OMe (+R) most destabilizing → weakest."],
        finalAnswer: "p-OMe-phenol < phenol < p-NO2-phenol",
        visualType: "inductive-resonance-effect",
      },
    ],
  },

  // ── Unit 17: Modern Chemical Manufactures ───────────────────────────────
  {
    id: "chem-haber-process",
    slug: "haber-process-ammonia",
    title: "Haber–Bosch Process: Manufacture of Ammonia",
    subject: "chemistry",
    unit: "Modern Chemical Manufactures",
    unitId: "modern-chemical-manufactures",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Ammonia is produced industrially by N2 + 3H2 ⇌ 2NH3 at ~450 °C, 200 atm, on an Fe catalyst; high pressure and low temperature favor yield, but kinetics force the compromise.",
    coreFormula: "N_2 + 3H_2 \\rightleftharpoons 2NH_3,\\ \\Delta H = -92\\,kJ",
    concernedTerms: [
      { term: "Le Chatelier compromise", definition: "Yield wants low T; rate wants high T → 450 °C." },
      { term: "Recycle loop", definition: "Unreacted N2/H2 are re-compressed back to the reactor." },
      { term: "Catalyst", symbol: "Fe + K2O/P2O5", definition: "Speeds equilibrium attainment without changing K." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Equilibrium direction", latex: "\\Delta H < 0: T\\uparrow \\Rightarrow K\\downarrow", explanation: "Cooling improves yield (exothermic)." },
      { stepNumber: 2, title: "Pressure choice", latex: "4\\,mol \\rightarrow 2\\,mol: P\\uparrow \\Rightarrow \\text{NH}_3\\uparrow", explanation: "High pressure pushes toward fewer moles." },
      { stepNumber: 3, title: "Rate compromise", latex: "450^{\\circ}C + 200\\,atm + Fe", explanation: "Enough rate while keeping decent conversion." },
    ],
    conclusion: "Haber's process is the classic industrial equilibrium optimization — yield vs rate vs cost.",
    keyTakeaways: ["About 15–25% of feed converts per pass; the rest is recycled."],
    examTraps: ["Raising temperature LOWERS NH3 yield (endothermic side favored)."],
    visualType: "haber-process-flow",
    solvedProblems: [
      {
        id: "chem-haber-1",
        question: "Why is 450 °C used instead of 200 °C despite exothermicity?",
        given: "ΔH = −92 kJ.",
        stepByStep: ["Low T gives high K but negligible rate.", "450 °C is the kinetic/thermodynamic compromise."],
        finalAnswer: "Rate would be too slow at low T",
        visualType: "haber-process-flow",
      },
    ],
  },
  {
    id: "chem-contact-process-h2so4",
    slug: "contact-process-sulphuric-acid",
    title: "Contact Process: Manufacture of Sulphuric Acid",
    subject: "chemistry",
    unit: "Modern Chemical Manufactures",
    unitId: "modern-chemical-manufactures",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Sulphuric acid is made by oxidizing SO2 to SO3 over a V2O5 catalyst, then absorbing SO3 into H2SO4 to form oleum, which is diluted to the acid.",
    coreFormula: "S \\rightarrow SO_2 \\rightarrow SO_3 \\rightarrow H_2SO_4",
    concernedTerms: [
      { term: "V2O5 catalyst", definition: "Oxidizes SO2 to SO3; regenerated by O2." },
      { term: "Oleum", symbol: "H2S2O7", definition: "SO3 absorbed in H2SO4; used to avoid direct H2O mixing." },
      { term: "98% H2SO4", definition: "Absorbs SO3 efficiently, unlike dilute acid." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Sulfur burn", latex: "S + O_2 \\rightarrow SO_2", explanation: "Raw material: native sulfur or pyrite." },
      { stepNumber: 2, title: "Catalytic oxidation", latex: "2SO_2 + O_2 \\xrightarrow{V_2O_5} 2SO_3", explanation: "~450 °C, ~1–2 atm; K is large but kinetics slow without catalyst." },
      { stepNumber: 3, title: "Absorption", latex: "SO_3 + H_2SO_4 \\rightarrow H_2S_2O_7;\\ H_2S_2O_7 + H_2O \\rightarrow 2H_2SO_4", explanation: "Oleum avoids the smoke of SO3–water direct contact." },
    ],
    conclusion: "The contact process is a catalytic, reversible exothermic equilibrium optimized by temperature, pressure and recycle.",
    keyTakeaways: ["SO3 is NOT absorbed in water — acid mists form."],
    examTraps: ["V2O5 replaces older As2O3 (toxic)."],
    visualType: "contact-process-h2so4",
    solvedProblems: [
      {
        id: "chem-contact-1",
        question: "Why is SO3 absorbed in conc. H2SO4 rather than water?",
        given: "Process design.",
        stepByStep: ["Direct water contact forms a mist of H2SO4 (dangerous, low absorption).", "Oleum then dilutes cleanly."],
        finalAnswer: "Oleum route avoids misting",
        visualType: "contact-process-h2so4",
      },
    ],
  },
  {
    id: "chem-solvay-process-na2co3",
    slug: "solvay-process-sodium-carbonate",
    title: "Solvay (Ammonia Soda) Process: Na2CO3",
    subject: "chemistry",
    unit: "Modern Chemical Manufactures",
    unitId: "modern-chemical-manufactures",
    gradeTrack: "grade-11",
    nebCode: "Che. 201",
    isExtra: false,
    statement:
      "Sodium carbonate is produced by saturating a brine/ammonia solution with CO2; NaHCO3 precipitates (low solubility), then is calcined.",
    coreFormula: "NaCl + NH_3 + CO_2 + H_2O \\rightarrow NaHCO_3\\downarrow + NH_4Cl;\\; 2NaHCO_3 \\xrightarrow{\\Delta} Na_2CO_3 + CO_2 + H_2O",
    concernedTerms: [
      { term: "Solvay cycle", definition: "NH3 and CaO are regenerated, making the process 'ammonia soda'." },
      { term: "NaHCO3 precipitation", definition: "NaHCO3 has low solubility; NaCl does not precipitate." },
      { term: "Calcination", definition: "Heating bicarbonate gives the carbonate product." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Saturate brine with NH3", latex: "NH_3 \\rightarrow NH_4^+ + OH^- \\Rightarrow CO_2 \\rightarrow HCO_3^- \\rightarrow NaHCO_3", explanation: "Basic medium absorbs CO2 as bicarbonate." },
      { stepNumber: 2, title: "Precipitate and heat", latex: "2NaHCO_3 \\xrightarrow{300^{\\circ}C} Na_2CO_3 + H_2O + CO_2", explanation: "CO2 is reused; NH4Cl reacts with lime to recover NH3." },
      { stepNumber: 3, title: "Recovery", latex: "2NH_4Cl + Ca(OH)_2 \\rightarrow CaCl_2 + 2NH_3\\uparrow", explanation: "Ammonia returns to the carbonation tower." },
    ],
    conclusion: "The Solvay process turns cheap NaCl, limestone and recycle ammonia into Na2CO3.",
    keyTakeaways: ["NaHCO3 precipitates; NaCl stays in solution."],
    examTraps: ["KCl brine does NOT work — KNaCO3 is too soluble; the trick is the low-solubility NaHCO3."],
    visualType: "solvay-process-na2co3",
    solvedProblems: [
      {
        id: "chem-solvay-1",
        question: "Why does NaHCO3 precipitate but NaCl does not in the Solvay process?",
        given: "Solubility comparison.",
        stepByStep: ["NaHCO3 solubility ≈ 9.6 g/100 mL at 15 °C.", "NaCl solubility ≈ 36 g/100 mL; solution is not saturated."],
        finalAnswer: "NaHCO3 solubility is much lower",
        visualType: "solvay-process-na2co3",
      },
    ],
  },
];
