/**
 * Mathematics theorem bank — NEB Mat. 007 (Grade 11) + Mat. 201 (Grade 12).
 * Entries are authored in official syllabus (unit) order and each is wired to
 * an EXISTING DerivationVisual `visualType` so it renders on the theorems page.
 */
import type { DerivationOrTheorem } from "@/lib/derivations-data";

export const MATH_THEOREMS: DerivationOrTheorem[] = [
  // ── Unit 1: Algebra ──────────────────────────────────────────────────────
  {
    id: "math-am-gm-hm-relation",
    slug: "am-gm-hm-relation",
    title: "AM–GM–HM Relation",
    subject: "mathematics",
    unit: "Algebra",
    unitId: "algebra",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Algebra)",
    isExtra: false,
    statement:
      "For positive real numbers, the arithmetic mean dominates the geometric mean which dominates the harmonic mean: \\(AM \\ge GM \\ge HM\\), with equality iff all numbers are equal.",
    coreFormula: "\\frac{a+b}{2} \\ge \\sqrt{ab} \\ge \\frac{2}{\\frac1a+\\frac1b}",
    concernedTerms: [
      { term: "Arithmetic mean", symbol: "AM", definition: "The ordinary average of the numbers." },
      { term: "Geometric mean", symbol: "GM", definition: "Root of the product of the numbers." },
      { term: "Harmonic mean", symbol: "HM", definition: "Reciprocal of the mean of the reciprocals." },
    ],
    assumptions: ["a, b > 0."],
    proofSteps: [
      { stepNumber: 1, title: "AM ≥ GM", latex: "\\left(\\frac{a+b}{2}\\right)^2 - ab = \\frac{(a-b)^2}{4} \\ge 0", explanation: "Square of a real number is non-negative; the AM−GM inequality follows." },
      { stepNumber: 2, title: "GM ≥ HM", latex: "\\sqrt{ab} \\ge \\frac{2ab}{a+b} \\iff (a+b)^2 \\ge 4ab \\iff (a-b)^2 \\ge 0", explanation: "Same identity under the reciprocal transformation." },
      { stepNumber: 3, title: "Equality case", latex: "a = b \\Rightarrow AM = GM = HM", explanation: "Equality throughout the chain holds only when all values coincide." },
    ],
    conclusion: "The three classical means obey a strict total order for positive reals, with equality only at uniformity.",
    keyTakeaways: ["For a fixed sum, the product is maximized when the numbers are equal."],
    examTraps: ["GM is undefined for negative inputs; the inequality needs positivity."],
    visualType: "amgm-relation",
    solvedProblems: [
      {
        id: "math-amgm-1",
        question: "Find the minimum of x + 1/x for x > 0.",
        given: "AM–GM.",
        stepByStep: ["x + 1/x ≥ 2√(x·1/x) = 2.", "Equality when x = 1/x → x = 1."],
        finalAnswer: "Minimum = 2",
        visualType: "amgm-relation",
      },
    ],
  },
  {
    id: "math-quadratic-equation-nature",
    slug: "quadratic-equation-nature-of-roots",
    title: "Nature of Roots of a Quadratic Equation",
    subject: "mathematics",
    unit: "Algebra",
    unitId: "algebra",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Algebra)",
    isExtra: false,
    statement:
      "The roots of \\(ax^2 + bx + c = 0\\) are real/distinct, real/equal or complex/conjugate according as the discriminant \\(D = b^2 - 4ac\\) is positive, zero or negative.",
    coreFormula: "x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a},\\quad D = b^2 - 4ac",
    concernedTerms: [
      { term: "Discriminant", symbol: "D", definition: "The quantity b² − 4ac deciding the root type." },
      { term: "Sum of roots", symbol: "α + β = −b/a", definition: "Roots relate to coefficients by Vieta's relations." },
      { term: "Product of roots", symbol: "αβ = c/a", definition: "The second Vieta relation." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "D > 0", latex: "b^2 > 4ac \\Rightarrow \\sqrt{D} \\in \\mathbb{R},\\ \\alpha \\ne \\beta", explanation: "Two distinct real roots." },
      { stepNumber: 2, title: "D = 0", latex: "b^2 = 4ac \\Rightarrow \\alpha = \\beta = -b/2a", explanation: "Repeated real root (graph touches the x-axis)." },
      { stepNumber: 3, title: "D < 0", latex: "b^2 < 4ac \\Rightarrow \\alpha,\\beta = \\frac{-b}{2a} \\pm i\\frac{\\sqrt{-D}}{2a}", explanation: "A complex conjugate pair; no real intersection." },
    ],
    conclusion: "The discriminant is the single test that classifies the root behaviour of every real quadratic.",
    keyTakeaways: ["Use Vieta to find expressions in the roots without solving."],
    examTraps: ["If a, b, c are rational and D is a non-square, the roots are irrational."],
    visualType: "quadratic-equation-nature-roots",
    solvedProblems: [
      {
        id: "math-quad-1",
        question: "For x² − 3x + 2 = 0, find the sum and product of the roots.",
        given: "Vieta's relations.",
        stepByStep: ["Sum = −b/a = 3.", "Product = c/a = 2."],
        finalAnswer: "Sum 3, product 2",
        visualType: "quadratic-equation-nature-roots",
      },
    ],
  },
  {
    id: "math-logarithm-properties",
    slug: "logarithm-properties-proof",
    title: "Properties of Logarithms",
    subject: "mathematics",
    unit: "Algebra",
    unitId: "algebra",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Algebra)",
    isExtra: false,
    statement:
      "Logarithms turn multiplication into addition, powers into multiplication and reciprocals into sign changes: \\(\\log_b(xy) = \\log_b x + \\log_b y\\), \\(\\log_b x^n = n\\log_b x\\), \\(\\log_b(1/x) = -\\log_b x\\).",
    coreFormula: "\\log_b M + \\log_b N = \\log_b MN;\\ \\log_b M - \\log_b N = \\log_b\\tfrac{M}{N};\\ \\log_b M^n = n\\log_b M",
    concernedTerms: [
      { term: "Change of base", symbol: "log_b x = log_a x / log_a b", definition: "Rewrites a logarithm in another base." },
      { term: "Natural log", symbol: "ln", definition: "Log base e ≈ 2.718." },
      { term: "Domain", definition: "Arguments of logs must be > 0." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Product rule", latex: "\\log_b M + \\log_b N = \\log_b(MN)", explanation: "Follows from the exponential definition: b^p M · b^p N = b^{p+q}." },
      { stepNumber: 2, title: "Power rule", latex: "\\log_b M^n = n \\log_b M", explanation: "Repeated application of the product rule." },
      { stepNumber: 3, title: "Reciprocal", latex: "\\log_b(1/M) = -\\log_b M", explanation: "M · 1/M = 1 → log 1 = 0." },
    ],
    conclusion: "These identities let you expand and compress logarithmic expressions and solve equations.",
    keyTakeaways: ["log_b(b) = 1 and log_b(1) = 0 are the anchor values."],
    examTraps: ["log(x+y) ≠ log x + log y — the log of a sum is not a sum of logs."],
    visualType: "logarithm-properties-proof",
    solvedProblems: [
      {
        id: "math-log-1",
        question: "Express log 15 − log 3 as a single logarithm.",
        given: "Quotient rule.",
        stepByStep: ["log 15 − log 3 = log(15/3) = log 5."],
        finalAnswer: "log 5",
        visualType: "logarithm-properties-proof",
      },
    ],
  },
  {
    id: "math-complex-number-properties",
    slug: "complex-number-properties",
    title: "Complex Numbers: Modulus, Conjugate and Algebra",
    subject: "mathematics",
    unit: "Algebra",
    unitId: "algebra",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Algebra)",
    isExtra: false,
    statement:
      "For \\(z = a + ib\\), the modulus is \\(|z| = \\sqrt{a^2+b^2}\\) and the conjugate \\(\\bar z = a - ib\\); the product \\(z\\bar z = |z|^2\\).",
    coreFormula: "|z| = \\sqrt{a^2+b^2};\\ \\ z\\bar z = a^2+b^2;\\ \\ |z_1 z_2| = |z_1||z_2|",
    concernedTerms: [
      { term: "Modulus", symbol: "|z|", definition: "Distance of z from the origin in the complex plane." },
      { term: "Argument", symbol: "θ", definition: "Angle from the positive real axis." },
      { term: "Conjugate", symbol: "z̄", definition: "Reflection of z across the real axis." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Product with conjugate", latex: "z\\bar z = (a+ib)(a-ib) = a^2+b^2 = |z|^2", explanation: "i² = −1 cancels the imaginary part." },
      { stepNumber: 2, title: "Multiplicative modulus", latex: "|z_1 z_2| = |z_1||z_2|", explanation: "Both sides square to (|z1|²)(|z2|²) = (a1²+b1²)(a2²+b2²)." },
    ],
    conclusion: "The modulus is multiplicative and the conjugate removes the imaginary part.",
    keyTakeaways: ["|z| = 1 places z on the unit circle."],
    examTraps: ["The conjugate of z1 + z2 is the sum of the conjugates: z̄1 + z̄2."],
    visualType: "complex-number-properties",
    solvedProblems: [
      {
        id: "math-complex-1",
        question: "Find |3 + 4i| and its conjugate.",
        given: "Modulus and conjugate definitions.",
        stepByStep: ["|3+4i| = √(9+16) = 5.", "Conjugate = 3 − 4i."],
        finalAnswer: "5; 3 − 4i",
        visualType: "complex-number-properties",
      },
    ],
  },

  // ── Unit 3: Analytic Geometry ───────────────────────────────────────────
  {
    id: "math-line-equation-forms",
    slug: "line-equation-forms",
    title: "Equations of a Straight Line (All Forms)",
    subject: "mathematics",
    unit: "Analytic Geometry",
    unitId: "analytic-geometry",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Analytic Geometry)",
    isExtra: false,
    statement:
      "A line can be written in slope-intercept, point-slope, two-point, intercept, normal and general forms; each is suited to a different set of given data.",
    coreFormula: "y = mx + c;\\ \\ y - y_1 = m(x - x_1);\\ \\ \\frac{x}{a}+\\frac{y}{b}=1;\\ \\ Ax+By+C=0",
    concernedTerms: [
      { term: "Slope", symbol: "m", definition: "Rise over run; m = tan θ." },
      { term: "Intercept form", definition: "x/a + y/b = 1 with x-intercept a and y-intercept b." },
      { term: "Normal form", symbol: "x cosα + y sinα = p", definition: "p is the perpendicular distance from the origin; α the angle of the normal." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Point-slope", latex: "m = \\frac{y-y_1}{x-x_1} \\Rightarrow y-y_1 = m(x-x_1)", explanation: "Slope definition through a known point." },
      { stepNumber: 2, title: "Perpendicular condition", latex: "m_1 m_2 = -1", explanation: "Product of perpendicular slopes is −1." },
      { stepNumber: 3, title: "Intercept form", latex: "\\frac{x}{a}+\\frac{y}{b}=1", explanation: "Set y=0 → x=a; set x=0 → y=b." },
    ],
    conclusion: "Choose the form that matches the data; all are algebraically interconvertible.",
    keyTakeaways: ["Parallel lines share slope; perpendicular slopes multiply to −1."],
    examTraps: ["Vertical lines have undefined slope — use x = c instead."],
    visualType: "line-equation-forms",
    solvedProblems: [
      {
        id: "math-line-1",
        question: "Find the equation of the line through (1,2) with slope 3.",
        given: "Point-slope form.",
        stepByStep: ["y − 2 = 3(x − 1).", "y = 3x − 1."],
        finalAnswer: "y = 3x − 1",
        visualType: "line-equation-forms",
      },
    ],
  },
  {
    id: "math-pair-of-lines-condition",
    slug: "pair-of-straight-lines-condition",
    title: "Pair of Straight Lines: Second Degree",
    subject: "mathematics",
    unit: "Analytic Geometry",
    unitId: "analytic-geometry",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Analytic Geometry)",
    isExtra: false,
    statement:
      "The general second-degree equation \\(ax^2 + 2hxy + by^2 + 2gx + 2fy + c = 0\\) represents a pair of straight lines iff \\(h^2 - abc\\) conditions on the determinant hold.",
    coreFormula: "\\begin{vmatrix} a & h & g \\\\ h & b & f \\\\ g & f & c \\end{vmatrix} = 0",
    concernedTerms: [
      { term: "Homogeneous second degree", definition: "Only the ax² + 2hxy + by² terms; the lines pass through the origin." },
      { term: "Angle between lines", symbol: "tanθ = 2√(h²−ab)/(a+b)", definition: "The angle formula for the pair." },
      { term: "Joint equation", definition: "Product of the two individual line equations." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Homogeneous pair", latex: "ax^2 + 2hxy + by^2 = 0", explanation: "Factor into two lines through the origin when h² ≥ ab." },
      { stepNumber: 2, title: "Angle formula", latex: "\\tan\\theta = \\frac{2\\sqrt{h^2-ab}}{a+b}", explanation: "Derived from the two slopes m1, m2." },
      { stepNumber: 3, title: "Parallel condition", latex: "h^2 = ab \\Rightarrow \\theta = 0", explanation: "Zero angle → the pair is parallel (or coincident)." },
    ],
    conclusion: "The second-degree coefficients encode the two lines, their angle and their concurrence.",
    keyTakeaways: ["Equal slopes from h² = ab → parallel pair."],
    examTraps: ["A 'pair' can also be a point, a real line, or complex lines — check discriminants."],
    visualType: "pair-of-lines-condition",
    solvedProblems: [
      {
        id: "math-pair-1",
        question: "Show that 6x² + 11xy + 6y² = 0 represents two lines and find their slopes.",
        given: "Homogeneous pair.",
        stepByStep: ["Set y = mx → 6m² + 11m + 6 = 0.", "m = (−11 ± 1)/12 → m = −2/3, −3/2."],
        finalAnswer: "m = −2/3 and −3/2",
        visualType: "pair-of-lines-condition",
      },
    ],
  },

  // ── Unit 5: Statistics and Probability ──────────────────────────────────
  {
    id: "math-probability-basic-theorems",
    slug: "probability-basic-theorems",
    title: "Basic Laws and Definitions of Probability",
    subject: "mathematics",
    unit: "Statistics and Probability",
    unitId: "statistics-and-probability",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Statistics)",
    isExtra: false,
    statement:
      "For events A and B: \\(P(A \\cup B) = P(A) + P(B) - P(A \\cap B)\\); the multiplication and complement rules follow from this.",
    coreFormula: "P(A\\cap B) = P(A)P(B|A);\\ P(\\bar A) = 1 - P(A)",
    concernedTerms: [
      { term: "Conditional probability", symbol: "P(A|B)", definition: "Probability of A given B has occurred." },
      { term: "Independent events", definition: "P(A|B) = P(A); the occurrence of B does not alter A." },
      { term: "Sample space", definition: "The set of all outcomes of an experiment." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Addition rule", latex: "P(A \\cup B) = P(A) + P(B) - P(A\\cap B)", explanation: "Subtract the double-counted intersection." },
      { stepNumber: 2, title: "Multiplication rule", latex: "P(A \\cap B) = P(A)P(B|A)", explanation: "The chain rule of probability." },
      { stepNumber: 3, title: "Independence", latex: "P(A\\cap B) = P(A)P(B)", explanation: "The special case where P(B|A) = P(B)." },
    ],
    conclusion: "These laws handle any question about unions, intersections and complements of events.",
    keyTakeaways: ["For independent events, drop the conditional."],
    examTraps: ["'Mutually exclusive' (A∩B=∅) and 'independent' are NOT the same — exclusive events are in fact dependent."],
    visualType: "probability-basic-theorems",
    solvedProblems: [
      {
        id: "math-prob-1",
        question: "P(A)=0.4, P(B)=0.3, P(A∪B)=0.6. Find P(A∩B).",
        given: "Addition rule.",
        stepByStep: ["P(A∩B) = P(A)+P(B)−P(A∪B) = 0.4+0.3−0.6 = 0.1."],
        finalAnswer: "0.1",
        visualType: "probability-basic-theorems",
      },
    ],
  },
  {
    id: "math-pearson-skewness",
    slug: "pearson-coefficient-of-skewness",
    title: "Karl Pearson's Coefficient of Skewness",
    subject: "mathematics",
    unit: "Statistics and Probability",
    unitId: "statistics-and-probability",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Statistics)",
    isExtra: false,
    statement:
      "Karl Pearson's skewness is \\(\\text{Sk} = \\dfrac{3(Med - Mean)}{\\sigma}\\); it measures the asymmetry of a distribution around its mean.",
    coreFormula: "\\text{Sk}_{Pearson} = \\frac{3(M - \\bar x)}{\\sigma}",
    concernedTerms: [
      { term: "Median", symbol: "Med", definition: "The middle value; robust to outliers." },
      { term: "Standard deviation", symbol: "σ", definition: "The typical spread of the data." },
      { term: "Coefficient of variation", symbol: "CV = σ/mean × 100%", definition: "Relative dispersion." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Symmetry test", latex: "Med = \\bar x \\Rightarrow \\text{Sk} = 0", explanation: "A symmetric distribution is unskewed." },
      { stepNumber: 2, title: "Right vs left tail", latex: "Med < \\bar x \\Rightarrow \\text{Sk} > 0\\ (\\text{right-skewed})", explanation: "The long right tail pulls the mean above the median." },
      { stepNumber: 3, title: "Range of values", latex: "-1 \\le \\text{Sk} \\le 1\\ (\\text{Pearson bound})", explanation: "Within three standard deviations of the median." },
    ],
    conclusion: "Pearson's coefficient summarizes skewness as a normalized difference between median and mean.",
    keyTakeaways: ["For a strongly skewed set, replace the mean by the median."],
    examTraps: ["The coefficient of SKEWNESS is not the same as the coefficient of VARIATION."],
    visualType: "pearson-skewness",
    solvedProblems: [
      {
        id: "math-skew-1",
        question: "Mean = 40, Median = 35, σ = 10. Find Pearson's skewness.",
        given: "Sk = 3(Med − Mean)/σ.",
        stepByStep: ["Sk = 3(35−40)/10 = 3(−5)/10 = −1.5."],
        finalAnswer: "Sk = −1.5 (left-skewed)",
        visualType: "pearson-skewness",
      },
    ],
  },

  // ── Unit 6: Calculus ────────────────────────────────────────────────────
  {
    id: "math-limits-continuity-ftc",
    slug: "fundamental-theorem-calculus",
    title: "Fundamental Theorem of Calculus (Both Parts)",
    subject: "mathematics",
    unit: "Calculus",
    unitId: "calculus",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Calculus)",
    isExtra: false,
    statement:
      "If \\(F\\) is an antiderivative of a continuous \\(f\\) on \\([a,b]\\), then \\(\\int_a^b f\\,dx = F(b) - F(a)\\); and \\(\\frac{d}{dx}\\int_a^x f\\,dt = f(x)\\).",
    coreFormula: "\\int_a^b f\\,dx = F(b)-F(a);\\quad \\frac{d}{dx}\\int_a^x f\\,dt = f(x)",
    concernedTerms: [
      { term: "Antiderivative", symbol: "F", definition: "F′ = f." },
      { term: "Indefinite integral", symbol: "∫f dx = F + C", definition: "The family of antiderivatives." },
      { term: "Definite integral", symbol: "∫a b f dx", definition: "The signed area under f." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "FTC Part 2", latex: "\\int_a^b f\\,dx = F(b) - F(a)", explanation: "Evaluate an antiderivative at the endpoints." },
      { stepNumber: 2, title: "FTC Part 1", latex: "\\frac{d}{dx}\\int_a^x f\\,dt = f(x)", explanation: "Derivative of the accumulated-area function recovers f." },
      { stepNumber: 3, title: "Apply", latex: "\\int_0^1 2x\\,dx = x^2\\big|_0^1 = 1", explanation: "The area under y = 2x on [0,1] is 1." },
    ],
    conclusion: "The FTC connects differentiation and integration as inverse operations — the heart of the calculus.",
    keyTakeaways: ["Definite integrals need no '+C'."],
    examTraps: ["The FTC requires f to be continuous on the interval."],
    visualType: "ftc-calculus",
    solvedProblems: [
      {
        id: "math-ftc-1",
        question: "Evaluate ∫₀² x² dx.",
        given: "FTC.",
        stepByStep: ["Antiderivative of x² is x³/3.", "F(2) − F(0) = 8/3 − 0 = 8/3."],
        finalAnswer: "8/3",
        visualType: "ftc-calculus",
      },
    ],
  },
  {
    id: "math-lhospitals-rule",
    slug: "l-hospitals-rule",
    title: "L'Hôpital's Rule",
    subject: "mathematics",
    unit: "Calculus",
    unitId: "calculus",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Calculus)",
    isExtra: false,
    statement:
      "If \\(\\lim_{x\\to c} f/g\\) gives \\(0/0\\) or \\(\\infty/\\infty\\) and \\(g'\\neq 0\\) near c, then \\(\\lim f/g = \\lim f'/g'\\) provided the latter exists.",
    coreFormula: "\\lim_{x\\to c}\\frac{f}{g} = \\lim_{x\\to c}\\frac{f'}{g'}",
    concernedTerms: [
      { term: "Indeterminate form", symbol: "0/0, ∞/∞", definition: "The cases where l'Hôpital applies." },
      { term: "Derivative ratio", definition: "Differentiate numerator and denominator separately." },
      { term: "Recurring rule", definition: "If the new form is still indeterminate, apply the rule again." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "0/0 case", latex: "\\frac{0}{0} \\Rightarrow \\frac{f'}{g'}", explanation: "Mean value theorem justifies the step." },
      { stepNumber: 2, title: "Apply", latex: "\\lim_{x\\to 0}\\frac{\\sin x}{x} = \\lim_{x\\to 0}\\frac{\\cos x}{1} = 1", explanation: "The classic trigonometric limit." },
      { stepNumber: 3, title: "Iterate", latex: "\\lim_{x\\to 0}\\frac{x - \\sin x}{x^3} \\xrightarrow{l'H} \\frac{1 - \\cos x}{3x^2} \\xrightarrow{l'H} \\frac{\\sin x}{6x} = \\frac16", explanation: "Repeated application removes successive indeterminate layers." },
    ],
    conclusion: "L'Hôpital resolves 0/0 and ∞/∞ limits by replacing the original ratio with the derivative ratio.",
    keyTakeaways: ["Check the form first — l'Hôpital does NOT apply to 0·∞ directly (convert it)." ],
    examTraps: ["A limit that is not 0/0 or ∞/∞ is illegal for l'Hôpital."],
    visualType: "lhospitals-rule",
    solvedProblems: [
      {
        id: "math-lh-1",
        question: "Evaluate lim_{x→0} (eˣ − 1 − x)/x².",
        given: "0/0 form.",
        stepByStep: ["1st l'H: (eˣ − 1)/(2x) → 0/0.", "2nd l'H: eˣ/2 → 1/2."],
        finalAnswer: "1/2",
        visualType: "lhospitals-rule",
      },
    ],
  },
  {
    id: "math-monotonicity-extrema",
    slug: "monotonicity-extrema",
    title: "Monotonicity and Extrema of a Function",
    subject: "mathematics",
    unit: "Calculus",
    unitId: "calculus",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Calculus)",
    isExtra: false,
    statement:
      "A differentiable function is increasing on an interval where \\(f' > 0\\), decreasing where \\(f' < 0\\); local extrema occur at critical points \\(f'=0\\) or undefined, tested by the second-derivative test.",
    coreFormula: "f'(x) > 0 \\Rightarrow \\text{increasing};\\ f'(c)=0,\\ f''(c)<0 \\Rightarrow \\text{local max}",
    concernedTerms: [
      { term: "Critical point", definition: "Where f′ = 0 or is undefined." },
      { term: "Second-derivative test", symbol: "f''", definition: "Sign of f'' at a critical point tells max/min." },
      { term: "Point of inflection", definition: "Where f'' changes sign; concavity flips." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Find critical points", latex: "f'(x) = 0 \\Rightarrow x = c_i", explanation: "Only critical points can be extrema." },
      { stepNumber: 2, title: "Classify", latex: "f''(c) < 0 \\Rightarrow \\text{max};\\ f''(c) > 0 \\Rightarrow \\text{min};\\ f''(c) = 0 \\Rightarrow \\text{inconclusive}", explanation: "Use the sign chart of f′ for the inconclusive case." },
      { stepNumber: 3, title: "Intervals", latex: "\\text{sign chart of } f'", explanation: "Read increasing/decreasing intervals off the f′ signs." },
    ],
    conclusion: "The sign of the first derivative gives monotonicity; the sign of the second at critical points gives the type of extremum.",
    keyTakeaways: ["Maxima on a closed interval also include the endpoints."],
    examTraps: ["f'' = 0 does not mean 'not an extremum' — it means 'test again'."],
    visualType: "monotonicity-extrema",
    solvedProblems: [
      {
        id: "math-extrema-1",
        question: "Classify the critical points of f(x) = x³ − 3x.",
        given: "f′ = 3x² − 3.",
        stepByStep: ["f′ = 0 → x = ±1.", "f″ = 6x: f″(1)=6>0 (min), f″(−1)=−6<0 (max)."],
        finalAnswer: "x=1 min, x=−1 max",
        visualType: "monotonicity-extrema",
      },
    ],
  },
  {
    id: "math-integration-by-parts",
    slug: "integration-by-parts",
    title: "Integration by Parts",
    subject: "mathematics",
    unit: "Calculus",
    unitId: "calculus",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Calculus)",
    isExtra: false,
    statement:
      "For \\(u, v\\), \\(\\int u\\,dv = uv - \\int v\\,du\\); the choice of u follows the LIATE priority (Log, Inverse-trig, Algebraic, Trig, Exponential).",
    coreFormula: "\\int u\\,dv = uv - \\int v\\,du",
    concernedTerms: [
      { term: "LIATE order", definition: "u = the leftmost of Log, Inverse, Algebraic, Trig, Exponential." },
      { term: "Cyclic integral", definition: "Some ∫u dv come back to ∫u dv; solve for it." },
      { term: "Reduction formula", definition: "∫f^n dx expressed in terms of ∫f^{n−1} dx." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Choose u, dv", latex: "\\int x e^x\\,dx: u=x,\\ dv=e^x dx", explanation: "Algebraic before Exponential → u = x." },
      { stepNumber: 2, title: "Integrate and differentiate", latex: "v = e^x,\\ du = dx", explanation: "Standard antiderivatives." },
      { stepNumber: 3, title: "Apply formula", latex: "\\int x e^x\\,dx = x e^x - \\int e^x\\,dx = e^x(x - 1) + C", explanation: "Simplify." },
    ],
    conclusion: "By parts converts a hard integral into an easier one by shifting the differentiation onto the chosen u.",
    keyTakeaways: ["Repeated parts handle ∫xⁿ eˣ; cyclic parts handle ∫eˣ sin x."],
    examTraps: ["A wrong LIATE choice leads to a longer or harder integral — pick the 'most differentiated' u."],
    visualType: "integration-by-parts",
    solvedProblems: [
      {
        id: "math-ibp-1",
        question: "Evaluate ∫ x ln x dx.",
        given: "LIATE → u = ln x.",
        stepByStep: ["u = ln x, dv = x dx → du = 1/x dx, v = x²/2.", "∫x ln x = (x²/2)ln x − ∫(x²/2)(1/x) dx = (x²/2)ln x − x²/4 + C."],
        finalAnswer: "(x²/2) ln x − x²/4 + C",
        visualType: "integration-by-parts",
      },
    ],
  },
  {
    id: "math-trapezoidal-rule",
    slug: "trapezoidal-rule-numerical",
    title: "Numerical Integration: Trapezoidal Rule",
    subject: "mathematics",
    unit: "Calculus / Computational Methods",
    unitId: "computational-methods-or-mechanics",
    gradeTrack: "grade-11",
    nebCode: "Mat. 007 (Computational Methods)",
    isExtra: false,
    statement:
      "The trapezoidal rule approximates \\(\\int_a^b f\\,dx\\) as \\(h\\left[\\frac12 y_0 + y_1 + \\cdots + y_{n-1} + \\frac12 y_n\\right]\\) with \\(h = (b-a)/n\\).",
    coreFormula: "\\int_a^b f\\,dx \\approx h\\left(\\frac{y_0 + y_n}{2} + \\sum_{i=1}^{n-1} y_i\\right)",
    concernedTerms: [
      { term: "Step size", symbol: "h", definition: "Uniform sub-interval width." },
      { term: "Node values", symbol: "y_i", definition: "f evaluated at the grid points." },
      { term: "Simpson's rule", definition: "Higher-order: parabolic segments; ~5th order." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Trapezoid on each sub-interval", latex: "\\int_{x_i}^{x_{i+1}} f\\,dx \\approx \\frac{h}{2}(y_i + y_{i+1})", explanation: "The area of a trapezoid." },
      { stepNumber: 2, title: "Sum over all sub-intervals", latex: "\\approx \\frac{h}{2}(y_0 + 2y_1 + 2y_2 + \\cdots + 2y_{n-1} + y_n)", explanation: "Inner nodes appear twice." },
      { stepNumber: 3, title: "Apply", latex: "\\int_0^1 x^2\\,dx \\approx \\frac{1}{2}\\left(0 + 2(0.25) + 1\\right) = 0.75", explanation: "True value 1/3 ≈ 0.333; with more steps accuracy rises." },
    ],
    conclusion: "The trapezoidal rule is the simplest composite quadrature; it is 2nd-order accurate.",
    keyTakeaways: ["Simpson's rule (if you use it) must have an even number of intervals."],
    examTraps: ["The endpoints appear with weight ½, all interior points with weight 1, times h."],
    visualType: "trapezoidal-rule",
    solvedProblems: [
      {
        id: "math-trap-1",
        question: "Approximate ∫₀² x dx by the trapezoidal rule with n = 2.",
        given: "h = 1.",
        stepByStep: ["y₀ = 0, y₁ = 1, y₂ = 2.", "T = 1·(0/2 + 1 + 2/2) = 2."],
        finalAnswer: "T = 2 (exact)",
        visualType: "trapezoidal-rule",
      },
    ],
  },

  // ── Grade-12 Calculus Extras ────────────────────────────────────────────
  {
    id: "extra-math-newton-raphson",
    slug: "newton-raphson-method",
    title: "Newton–Raphson Root-Finding",
    subject: "mathematics",
    unit: "Calculus / Computational Methods",
    unitId: "computational-methods-or-mechanics",
    gradeTrack: "extra-grade-12",
    nebCode: "Mat. 007 (Numerical)",
    isExtra: true,
    statement:
      "To find a root of f(x) = 0, start from x₀ and iterate \\(x_{n+1} = x_n - f(x_n)/f'(x_n)\\); it converges quadratically near a simple root.",
    coreFormula: "x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}",
    concernedTerms: [
      { term: "Iteration", symbol: "x_{n+1}", definition: "The next better estimate." },
      { term: "Convergence", definition: "The estimate sequence approaching the root." },
      { term: "Quadratic convergence", definition: "Number of correct digits doubles per step near the root." },
    ],
    assumptions: ["f differentiable; x₀ sufficiently close to a simple root."],
    proofSteps: [
      { stepNumber: 1, title: "Linearisation", latex: "f(x_n + \\Delta) \\approx f(x_n) + f'(x_n)\\Delta = 0", explanation: "The tangent at x_n crosses the x-axis at x_n − f/f′." },
      { stepNumber: 2, title: "Iterate", latex: "x_{n+1} = x_n - \\frac{f(x_n)}{f'(x_n)}", explanation: "Repeat until |x_{n+1} − x_n| < tol." },
      { stepNumber: 3, title: "Example", latex: "x^2 - 2 = 0,\\ x_0 = 1: x_1 = 1.5, x_2 = 1.4167, x_3 = 1.41421\\ldots", explanation: "In three steps reaches √2." },
    ],
    conclusion: "Newton–Raphson is the workhorse for non-linear root finding; it is fast but sensitive to x₀.",
    keyTakeaways: ["Near a multiple root, convergence slows to linear."],
    examTraps: ["A bad x₀ can diverge — always bracket the root first if possible."],
    visualType: "newton-raphson-method",
    solvedProblems: [
      {
        id: "math-nr-1",
        question: "Use one Newton step from x₀ = 2 to approximate √3.",
        given: "f(x) = x² − 3, f′ = 2x.",
        stepByStep: ["x₁ = 2 − (4−3)/(4) = 2 − 0.25 = 1.75."],
        finalAnswer: "x₁ = 1.75",
        visualType: "newton-raphson-method",
      },
    ],
  },
  {
    id: "extra-math-bayes-theorem-proof",
    slug: "bayes-theorem-proof",
    title: "Bayes' Theorem (with a worked proof)",
    subject: "mathematics",
    unit: "Calculus / Probability (Grade 12)",
    unitId: "calculus",
    gradeTrack: "extra-grade-12",
    nebCode: "Mat. 201 (Probability)",
    isExtra: true,
    statement:
      "For mutually exclusive hypotheses H₁…Hₙ with prior P(Hᵢ) and likelihood P(E|Hᵢ), the posterior probability is \\(P(H_i|E) = P(H_i)P(E|H_i) / \\sum_j P(H_j)P(E|H_j)\\).",
    coreFormula: "P(H_i|E) = \\frac{P(H_i)P(E|H_i)}{P(E)},\\ P(E) = \\sum_j P(H_j)P(E|H_j)",
    concernedTerms: [
      { term: "Prior", symbol: "P(H)", definition: "Probability before seeing the evidence." },
      { term: "Likelihood", symbol: "P(E|H)", definition: "Probability of the evidence under H." },
      { term: "Posterior", symbol: "P(H|E)", definition: "Probability after seeing the evidence." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Conditional probability", latex: "P(H|E) = \\frac{P(E|H)P(H)}{P(E)}", explanation: "By the definition of conditional probability." },
      { stepNumber: 2, title: "Total probability", latex: "P(E) = \\sum_j P(E|H_j)P(H_j)", explanation: "Partition the evidence space over the hypotheses." },
      { stepNumber: 3, title: "Combine", latex: "P(H|E) = \\frac{P(E|H)P(H)}{\\sum_j P(E|H_j)P(H_j)}", explanation: "Bayes' theorem." },
    ],
    conclusion: "Bayes' theorem updates a prior with new evidence to yield a posterior.",
    keyTakeaways: ["The base-rate matters: P(H) often dominates."],
    examTraps: ["Confusing P(E|H) with P(H|E) — the 'prosecutor's fallacy'."],
    visualType: "bayes-theorem",
    solvedProblems: [
      {
        id: "math-bayes-1",
        question: "A disease has 1% prevalence. A test is 99% sensitive and 95% specific. What is P(disease | positive)?",
        given: "Bayes' theorem.",
        stepByStep: ["P(D) = 0.01, P(+|D) = 0.99, P(+|D̄) = 0.05.", "P(D|+) = 0.99×0.01 / (0.99×0.01 + 0.05×0.99) ≈ 0.99 / 0.99 × (0.01/(0.01+0.05)) ≈ 0.166."],
        finalAnswer: "≈ 16.6%",
        visualType: "bayes-theorem",
        tipOrTrap: "Low base rates dominate — most positives are false.",
      },
    ],
  },

  // ── Grade-12 Discrete-Geometry / Complex Extras ─────────────────────────
  {
    id: "extra-math-demoivres-theorem",
    slug: "de-moivres-theorem",
    title: "De Moivre's Theorem",
    subject: "mathematics",
    unit: "Calculus / Complex Numbers (Grade 12)",
    unitId: "calculus",
    gradeTrack: "extra-grade-12",
    nebCode: "Mat. 201 (Complex Numbers)",
    isExtra: true,
    statement:
      "For any integer n, \\(\\bigl(\\cos\\theta + i\\sin\\theta\\bigr)^n = \\cos(n\\theta) + i\\sin(n\\theta)\\); it yields powers, roots and trigonometric identities.",
    coreFormula: "(\\cos\\theta + i\\sin\\theta)^n = \\cos n\\theta + i\\sin n\\theta",
    concernedTerms: [
      { term: "Polar form", symbol: "z = r e^{iθ}", definition: "Complex number in modulus-argument form." },
      { term: "n-th root", symbol: "z^{1/n}", definition: "All n roots of a complex number are spaced by 2π/n." },
      { term: "Trigonometric identity", definition: "Expansion of powers of cos θ, sin θ via De Moivre." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Inductive step", latex: "(re^{iθ})^{n+1} = r^{n+1} e^{i(n+1)θ}", explanation: "Assuming it holds for n." },
      { stepNumber: 2, title: "n-th root", latex: "z = re^{iθ} \\Rightarrow z^{1/n} = r^{1/n} e^{i(θ + 2kπ)/n},\\ k=0\\dots n-1", explanation: "n distinct roots." },
      { stepNumber: 3, title: "Chebyshev", latex: "\\cos n\\theta = \\Re\\bigl(e^{inθ}\\bigr)", explanation: "Expansion gives cos nθ as a polynomial in cos θ." },
    ],
    conclusion: "De Moivre's theorem turns powers of complex numbers into trigonometric powers and gives root formulas.",
    keyTakeaways: ["The cube roots of 1 are 1, e^{2πi/3}, e^{4πi/3}."],
    examTraps: ["For fractional exponents, take all branches (k = 0 … n−1)."],
    visualType: "de-moivres-theorem",
    solvedProblems: [
      {
        id: "math-demoivre-1",
        question: "Find the cube roots of 1.",
        given: "z³ = 1 = e^{i·0} = e^{i·3π} etc.",
        stepByStep: ["z = e^{i·0/3}, e^{i·2π/3}, e^{i·4π/3}."],
        finalAnswer: "1, −1/2 ± i√3/2",
        visualType: "de-moivres-theorem",
      },
    ],
  },
];
