/**
 * Biology theorem / concept bank — NEB Bio. 201 (Grade 11).
 * Entries are authored in official syllabus (unit) order and each is wired to
 * an EXISTING DerivationVisual `visualType` so it renders on the theorems page.
 */
import type { DerivationOrTheorem } from "@/lib/derivations-data";

export const BIOLOGY_THEOREMS: DerivationOrTheorem[] = [
  // ── Unit 1: Biomolecules and Cell Biology ───────────────────────────────
  {
    id: "bio-biomolecule-functions",
    slug: "biomolecules-functions",
    title: "Classes of Biomolecules and Their Functions",
    subject: "biology",
    unit: "Biomolecules and Cell Biology",
    unitId: "biomolecules-and-cell-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement:
      "Living cells are built from four core biomolecule families — carbohydrates, proteins, lipids and nucleic acids — each performing a distinct structural or regulatory role.",
    coreFormula: "Cell ≈ Carbs (energy/structure) + Proteins (enzymes) + Lipids (membranes) + Nucleic acids (genetic info)",
    concernedTerms: [
      { term: "Carbohydrate", definition: "Energy source (glucose) and structural polysaccharides (cellulose, starch, glycogen)." },
      { term: "Protein", definition: "Polymer of amino acids; enzymes, transport, structural and immune roles." },
      { term: "Lipid", definition: "Hydrophobic molecules; membrane structure (phospholipids) and long-term energy storage." },
      { term: "Nucleic acid", definition: "DNA and RNA; store and transmit genetic information." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Energy biomolecules", latex: "C_6H_{12}O_6 + 6O_2 \\rightarrow 6CO_2 + 6H_2O + \\text{ATP}", explanation: "Carbohydrate oxidation via respiration releases energy captured as ATP." },
      { stepNumber: 2, title: "Structural biomolecules", latex: "\\text{cellulose} \\rightarrow \\text{cell wall}, \\quad \\text{keratin} \\rightarrow \\text{hair/nails}", explanation: "Polysaccharides and proteins provide structural support." },
      { stepNumber: 3, title: "Information biomolecules", latex: "DNA \\xrightarrow{transcription} RNA \\xrightarrow{translation} Protein", explanation: "The central flow of genetic information." },
    ],
    conclusion: "Each biomolecule family is indispensable; carbohydrates and lipids handle energy, proteins handle work, nucleic acids handle information, lipids build membranes.",
    keyTakeaways: ["Enzymes are proteins — not carbohydrates.", "Lipids are the main membrane component (phospholipid bilayer)."],
    examTraps: ["ATP is NOT a lipid even though it is an energy molecule — it is a nucleotide."],
    visualType: "biomolecule-types-diagram",
    solvedProblems: [
      {
        id: "bio-biomol-1",
        question: "Name the bond that links amino acids in a protein and the bond that links monosaccharides in a disaccharide.",
        given: "Peptide and glycosidic bond definitions.",
        stepByStep: ["Amino acids join via condensation forming a peptide bond (-CO-NH-).", "Monosaccharides join via condensation forming a glycosidic bond."],
        finalAnswer: "Peptide bond; glycosidic bond",
        visualType: "biomolecule-types-diagram",
        visualDescription: "Condensation links across the four biomolecule families.",
      },
    ],
  },
  {
    id: "bio-cell-prokaryotic-eukaryotic",
    slug: "prokaryotic-vs-eukaryotic-cell",
    title: "Prokaryotic vs Eukaryotic Cells",
    subject: "biology",
    unit: "Biomolecules and Cell Biology",
    unitId: "biomolecules-and-cell-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Prokaryotic cells lack a membrane-bound nucleus and organelles; eukaryotic cells contain a nucleus and membrane-bound organelles.",
    coreFormula: "Prokaryote (no nucleus, 70S ribosomes) vs Eukaryote (nucleus, 80S ribosomes)",
    concernedTerms: [
      { term: "Nucleoid", definition: "Un organised DNA region in prokaryotes; not enclosed by a membrane." },
      { term: "Membrane-bound organelle", definition: "Compartments (mitochondria, ER, Golgi) present only in eukaryotes." },
      { term: "Cell wall", definition: "Rigid layer; chitin in fungi, cellulose in plants, peptidoglycan in bacteria." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Genetic organisation", latex: "\\text{Prokaryote: circular DNA, no histones}", explanation: "Eukaryotes use linear DNA packaged with histones into chromosomes." },
      { stepNumber: 2, title: "Ribosome size", latex: "70S (prokaryote) vs 80S (eukaryote)", explanation: "Sedimentation coefficient distinguishes the two ribosome types." },
    ],
    conclusion: "The presence or absence of a nucleus is the fundamental dividing line between the two cell types.",
    keyTakeaways: ["Bacteria are prokaryotes; all eukaryotes (plants, animals, fungi, protists) have a nucleus."],
    examTraps: ["Mitochondria and chloroplast have their own DNA — evidence of endosymbiosis, not a prokaryote."],
    visualType: "prokaryotic-vs-eukaryotic-cell",
    solvedProblems: [
      {
        id: "bio-prok-euk-1",
        question: "A unicellular organism has a nucleus and mitochondria but no cell wall. Is it prokaryotic or eukaryotic? Why?",
        given: "Presence of nucleus + mitochondria.",
        stepByStep: ["A membrane-bound nucleus defines eukaryotic identity.", "Mitochondria are eukaryotic organelles.", "Absence of a wall is consistent with an animal or protist cell."],
        finalAnswer: "Eukaryotic — it has a nucleus and mitochondria.",
        visualType: "prokaryotic-vs-eukaryotic-cell",
      },
    ],
  },
  {
    id: "bio-plant-animal-cell",
    slug: "plant-vs-animal-cell",
    title: "Plant Cell vs Animal Cell",
    subject: "biology",
    unit: "Biomolecules and Cell Biology",
    unitId: "biomolecules-and-cell-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Plant cells possess a cell wall, central vacuole and chloroplasts; animal cells possess centrioles and lack a cell wall.",
    coreFormula: "Plant: wall + central vacuole + chloroplast; Animal: centrioles + lysosomes",
    concernedTerms: [
      { term: "Central vacuole", definition: "Large membrane-bound sac storing water and turgor in plant cells." },
      { term: "Centriole", definition: "Cylindrical structure involved in animal cell division; absent in most plants." },
      { term: "Chloroplast", definition: "Organelle of photosynthesis, present only in plant (and algal) cells." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Rigidity source", latex: "\\text{plant cell wall (cellulose)} \\rightarrow \\text{turgor support}", explanation: "The wall limits expansion; the central vacuole maintains turgor." },
    ],
    conclusion: "Structural differences explain why plant cells are rigid and photoautotrophic while animal cells are mobile and heterotrophic.",
    keyTakeaways: ["Only plant cells fix CO2 via chloroplasts."],
    examTraps: ["Not all plant cells have chloroplasts — root cells do not."],
    visualType: "animal-vs-plant-cell",
    solvedProblems: [
      {
        id: "bio-pa-cell-1",
        question: "List one structure present in a plant cell but absent in a typical animal cell.",
        given: "Comparative cell anatomy.",
        stepByStep: ["Cell wall, chloroplast and large central vacuole are plant-specific."],
        finalAnswer: "Cell wall / chloroplast / central vacuole",
        visualType: "animal-vs-plant-cell",
      },
    ],
  },
  {
    id: "bio-organelle-structure-function",
    slug: "organelle-functions",
    title: "Structure and Function of Eukaryotic Organelles",
    subject: "biology",
    unit: "Biomolecules and Cell Biology",
    unitId: "biomolecules-and-cell-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Each membrane-bound organelle performs a specialised function that collectively sustains the eukaryotic cell.",
    coreFormula: "Mitochondria (ATP), ER (folding/transport), Golgi (packaging), Lysosome (digestion), Ribosome (translation)",
    concernedTerms: [
      { term: "Mitochondrion", definition: "Site of aerobic respiration and ATP synthesis." },
      { term: "Ribosome", definition: "RNA-protein complex where translation occurs; free or rough-ER bound." },
      { term: "Golgi apparatus", definition: "Modifies, sorts and packages proteins for secretion." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Protein pathway", latex: "Ribosome \\rightarrow RER \\rightarrow Golgi \\rightarrow Secretory vesicle", explanation: "The secretory pathway shows functional interdependence of organelles." },
    ],
    conclusion: "Organelles are specialised compartments that increase the efficiency of cellular metabolism.",
    keyTakeaways: ["Both mitochondria and chloroplast carry their own DNA."],
    examTraps: ["Smooth ER does not have ribosomes — it synthesises lipids and detoxifies."],
    visualType: "organelle-functions",
    solvedProblems: [
      {
        id: "bio-organelle-1",
        question: "Which organelle would be abundant in a cell that secretes large amounts of protein?",
        given: "Secretory cell, e.g. pancreatic acinar cell.",
        stepByStep: ["High secretory demand raises demand for protein processing.", "Rough ER and Golgi handle folding and packaging."],
        finalAnswer: "Rough endoplasmic reticulum and Golgi apparatus",
        visualType: "organelle-functions",
      },
    ],
  },
  {
    id: "bio-cell-division-mitosis-meiosis",
    slug: "mitosis-vs-meiosis",
    title: "Mitosis vs Meiosis",
    subject: "biology",
    unit: "Biomolecules and Cell Biology",
    unitId: "biomolecules-and-cell-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Mitosis yields two genetically identical diploid daughter cells; meiosis yields four genetically distinct haploid gametes.",
    coreFormula: "Mitosis: 2N \\rightarrow 2\\times 2N; Meiosis: 2N \\rightarrow 4\\times N",
    concernedTerms: [
      { term: "Crossing over", definition: "Reciprocal exchange of chromatids in meiosis I, generating genetic variation." },
      { term: "Independent assortment", definition: "Random orientation of bivalents at metaphase I increases variation." },
      { term: "Sister chromatid", definition: "Two identical copies of a chromosome joined at the centromere." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Reduction of chromosome number", latex: "2N \\xrightarrow{\\text{meiosis I}} N", explanation: "Homologues separate in meiosis I, halving ploidy." },
      { stepNumber: 2, title: "Variation sources", latex: "\\text{LOH + IA} \\Rightarrow 2^{\\,n} \\text{combinations}", explanation: "With n bivalents, independent assortment yields up to 2^n gamete types." },
    ],
    conclusion: "Mitosis maintains chromosome number for growth and repair; meiosis halves it and shuffles alleles for sexual reproduction.",
    keyTakeaways: ["Anaphase II of meiosis resembles anaphase of mitosis."],
    examTraps: ["Crossing over occurs in prophase I, NOT in mitosis."],
    visualType: "mitosis-vs-meiosis",
    solvedProblems: [
      {
        id: "bio-mito-meio-1",
        question: "How many chromosome combinations can a diploid organism with 23 pairs of chromosomes produce via independent assortment alone?",
        given: "n = 23.",
        stepByStep: ["Each bivalent has 2 orientations.", "Total = 2^23."],
        finalAnswer: "2^{23} = 8{,}388{,}608 combinations",
        visualType: "mitosis-vs-meiosis",
      },
    ],
  },

  // ── Unit 2: Floral Diversity ─────────────────────────────────────────────
  {
    id: "bio-fungi-mucor-yeast",
    slug: "fungi-life-cycles-mucor-yeast",
    title: "Fungi: Mucor and Yeast Life Cycles",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Mucor (zygomycete) reproduces asexually by sporangiospores and sexually via zygosporangia; yeast reproduces by budding and forms ascospores under stress.",
    coreFormula: "Mucor: hyphae + sporangium \\rightarrow spores; Yeast: bud + ascospore",
    concernedTerms: [
      { term: "Sporangium", definition: "Structure at the tip of a sporangiophore bearing conidial spores." },
      { term: "Zygospore", definition: "Thick-walled sexual spore formed by fusion of gametangia." },
      { term: "Budding", definition: "Asexual reproduction of yeast by outgrowth of a daughter cell." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Asexual phase", latex: "\\text{sporangium} \\rightarrow \\text{sporangiospores}", explanation: "Wind disperses spores for rapid colonisation." },
    ],
    conclusion: "Fungi switch between asexual spore production and sexual zygospore/ascospore formation depending on nutrients and stress.",
    keyTakeaways: ["Mucor is a mould with a mycelium; yeast is a unicellular fungus."],
    examTraps: ["Zygomycetes form zygospores, not ascospores."],
    visualType: "fungi-life-cycles",
    solvedProblems: [
      {
        id: "bio-fungi-1",
        question: "Identify the fungus that is unicellular and reproduces by budding.",
        given: "Yeast morphology.",
        stepByStep: ["Unicellular + budding + ascospores under starvation point to yeast."],
        finalAnswer: "Yeast (Saccharomyces)",
        visualType: "fungi-life-cycles",
      },
    ],
  },
  {
    id: "bio-algae-spirogyra",
    slug: "algae-types-spirogyra",
    title: "Algae: Types and Spirogyra",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Algae are photosynthetic protists grouped into green, brown and red types; Spirogyra is a filamentous green alga reproducing by fragmentation and conjugation.",
    coreFormula: "Green algae: chlorophyll a+b, product stored as starch",
    concernedTerms: [
      { term: "Spirogyra", definition: "Unicellular chain (filament) green alga with spiral chloroplasts and statocytes." },
      { term: "Conjugation", definition: "Sexual reproduction where two filaments exchange haploid contents via a conjugation bridge." },
      { term: "Red algae", definition: "Mostly marine; store floridean starch." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Reproduction", latex: "\\text{fragmentation (asexual)} + \\text{conjugation (sexual)}", explanation: "Spirogyra produces zygospores after conjugation." },
    ],
    conclusion: "Algal diversity spans three major groups distinguished by pigments and stored food; Spirogyra exemplifies green algae.",
    keyTakeaways: ["Green algae store food as starch, like higher plants."],
    examTraps: ["Spirogyra is not a plant — it lacks true tissue differentiation."],
    visualType: "algae-types-diagram",
    solvedProblems: [
      {
        id: "bio-algae-1",
        question: "State the method by which Spirogyra reproduces sexually.",
        given: "Spirogyra life history.",
        stepByStep: ["Two adjacent filaments form a conjugation tube.", "Protoplasts exchange, forming zygospores."],
        finalAnswer: "Conjugation",
        visualType: "algae-types-diagram",
      },
    ],
  },
  {
    id: "bio-bryophyta-marchantia",
    slug: "bryophyte-life-cycle-marchantia",
    title: "Bryophyta: Marchantia Life Cycle",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Marchantia is a liverwort (bryophyte) in which the dominant, independent phase is the haploid gametophyte; the short-lived diploid sporophyte is dependent on it.",
    coreFormula: "2N sporophyte \\xrightarrow{meiosis} N spores \\rightarrow N gametophyte (dominant)",
    concernedTerms: [
      { term: "Gametophyte", definition: "Dominant haploid generation producing archegonium (female) and antheridium (male)." },
      { term: "Sporophyte", definition: "Short-lived diploid generation on a stalk (seta) producing spores." },
      { term: "Alternation of generations", definition: "Succession of haploid and diploid phases." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Dominance of gametophyte", latex: "\\text{independent 2N? No} \\Rightarrow \\text{independent N}", explanation: "In bryophytes the plant body we see is the haploid gametophyte." },
    ],
    conclusion: "Bryophytes represent the earliest land plants, still dependent on water for fertilisation.",
    keyTakeaways: ["Marchantia is dioecious — male and female cones on separate plants."],
    examTraps: ["The dominant phase in bryophytes is the GAMETOPHYTE, unlike pteridophytes."],
    visualType: "bryophyte-life-cycle",
    solvedProblems: [
      {
        id: "bio-bryo-1",
        question: "Name the dominant generation in Marchantia.",
        given: "Alternation of generations.",
        stepByStep: ["The free-living plant body is haploid.", "Therefore the gametophyte is dominant."],
        finalAnswer: "Gametophyte (N)",
        visualType: "bryophyte-life-cycle",
      },
    ],
  },
  {
    id: "bio-pteridophyta-dryopteris",
    slug: "pteridophyte-life-cycle-dryopteris",
    title: "Pteridophyta: Dryopteris Life Cycle",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "In Dryopteris the dominant phase is the diploid sporophyte; the gametophyte (prothallus) is small and short-lived.",
    coreFormula: "2N sporophyte (dominant) \\rightarrow N prothallus \\rightarrow 2N zygote",
    concernedTerms: [
      { term: "Prothallus", definition: "Heart-shaped haploid gametophyte bearing archegonia and antheridia." },
      { term: "Sori", definition: "Clusters of sporangia on the underside of the frond that produce spores." },
      { term: "Vascular tissue", definition: "Xylem and phloem; present in pteridophytes, absent in bryophytes." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Sporophyte dominance", latex: "\\text{sori} \\rightarrow \\text{spores} \\rightarrow \\text{prothallus}", explanation: "The independent plant is the sporophyte." },
    ],
    conclusion: "Pteridophytes show reversal of dominance versus bryophytes: the sporophyte is now the dominant, independent phase.",
    keyTakeaways: ["Dryopteris has true roots, stems and leaves (vascular plant)."],
    examTraps: ["In pteridophytes the SPOROPHYTE is dominant — the opposite of bryophytes."],
    visualType: "pteridophyte-life-cycle",
    solvedProblems: [
      {
        id: "bio-pterido-1",
        question: "Which generation is dominant in Dryopteris?",
        given: "Pteridophyte life cycle.",
        stepByStep: ["The free vascular plant is 2N.", "Hence the sporophyte is dominant."],
        finalAnswer: "Sporophyte (2N)",
        visualType: "pteridophyte-life-cycle",
      },
    ],
  },
  {
    id: "bio-gymnosperm-pinus",
    slug: "gymnosperm-life-cycle-pinus",
    title: "Gymnosperm: Pinus Life Cycle",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Pinus (gymnosperm) produces microspores on pollen (male) cones and megaspores in ovules on seed cones; seeds are exposed (not fruits).",
    coreFormula: "2N sporophyte \\rightarrow N pollen (male) + N egg (female) \\rightarrow 2N zygote",
    concernedTerms: [
      { term: "Strobilus", definition: "Cone structure bearing sporangia on scales." },
      { term: "Pollen grain", definition: "Male gametophyte carrying two male nuclei." },
      { term: "Exposed seed", definition: "Gymnosperm seeds do not develop in a fruit (no carpel)." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Pollen tube growth", latex: "\\text{pollen} \\rightarrow \\text{pollen tube} \\rightarrow \\text{ovule}", explanation: "Wind-carried pollen delivers male gametes to the ovule." },
    ],
    conclusion: "Gymnosperms are the first to form pollen and seeds but lack flowers and fruits.",
    keyTakeaways: ["Pinus is the archetypal gymnosperm studied in NEB."],
    examTraps: ["Gymnosperm 'seeds' are not enclosed in a fruit."],
    visualType: "gymnosperm-life-cycle",
    solvedProblems: [
      {
        id: "bio-gymno-1",
        question: "Give two features that distinguish gymnosperms from angiosperms.",
        given: "Comparative reproduction.",
        stepByStep: ["No true flowers/fruits.", "Seeds are naked (exposed) rather than enclosed."],
        finalAnswer: "No flowers; naked seeds",
        visualType: "gymnosperm-life-cycle",
      },
    ],
  },
  {
    id: "bio-angiosperm-flower-fruit",
    slug: "angiosperm-flower-fruit-anatomy",
    title: "Angiosperm: Flower and Fruit Morphology",
    subject: "biology",
    unit: "Floral Diversity",
    unitId: "floral-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Angiosperms possess flowers (sepals, petals, stamens, carpels) and fruits; double fertilisation produces both the embryo and endosperm.",
    coreFormula: "\\text{microspore} \\rightarrow \\text{sperm}_{1,2}; \\text{sperm}_1+\\text{egg} \\rightarrow \\text{zygote}, \\text{sperm}_2+\\text{PP} \\rightarrow \\text{endosperm}",
    concernedTerms: [
      { term: "Carpel", definition: "Female reproductive organ (ovary + style + stigma); its ovules become seeds." },
      { term: "Stamen", definition: "Male organ: anther (microspores) and filament." },
      { term: "Double fertilisation", definition: "Two male nuclei fertilise the egg and the polar nuclei respectively." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Fruit origin", latex: "\\text{ovary} \\xrightarrow{\\text{after fertilisation}} \\text{fruit}", explanation: "The fruit is the mature, modified ovary." },
    ],
    conclusion: "Angiosperms are the most successful plants, characterised by flowers, fruits and double fertilisation.",
    keyTakeaways: ["Endosperm is triploid (3N) — unique to angiosperms."],
    examTraps: ["Fruit develops from the ovary; the seed develops from the fertilised ovule."],
    visualType: "flower-anatomy-diagram",
    solvedProblems: [
      {
        id: "bio-angio-1",
        question: "What structure gives rise to the fruit in an angiosperm?",
        given: "Post-fertilisation development.",
        stepByStep: ["The ovary matures into the fruit.", "Ovules within become seeds."],
        finalAnswer: "Ovary",
        visualType: "flower-anatomy-diagram",
      },
    ],
  },

  // ── Unit 3: Introductory Microbiology ────────────────────────────────────
  {
    id: "bio-bacterial-cell-structure",
    slug: "bacterial-cell-structure",
    title: "Structure of the Bacterial Cell",
    subject: "biology",
    unit: "Introductory Microbiology",
    unitId: "introductory-microbiology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Bacteria are prokaryotes: a cell wall (peptidoglycan), plasma membrane, nucleoid, 70S ribosomes, and optional capsules, pili and flagella.",
    coreFormula: "\\text{wall} + \\text{membrane} + \\text{nucleoid} + \\text{cytoplasm} \\rightarrow \\text{bacterium}",
    concernedTerms: [
      { term: "Peptidoglycan", definition: "Mural layer of the bacterial cell wall." },
      { term: "Plasmid", definition: "Small circular DNA carrying selectable or accessory genes." },
      { term: "Mesosome", definition: "Infolded membrane region involved in growth." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Gram classification", latex: "\\text{thick PG} \\rightarrow \\text{Gram}^{+}; \\text{thin PG} \\rightarrow \\text{Gram}^{-}", explanation: "Wall structure determines Gram staining result." },
    ],
    conclusion: "Bacterial structure defines their classification, nutrition and ecological roles.",
    keyTakeaways: ["Cyanobacteria are photosynthetic bacteria ('blue-green algae')."],
    examTraps: ["Bacteria have a cell wall but NO nuclear membrane."],
    visualType: "bacterial-cell-structure",
    solvedProblems: [
      {
        id: "bio-bacteria-1",
        question: "State one structural difference between Gram-positive and Gram-negative bacteria.",
        given: "Cell wall structure.",
        stepByStep: ["Gram-positive: thick peptidoglycan, no outer membrane.", "Gram-negative: thin peptidoglycan + outer membrane."],
        finalAnswer: "Thickness of peptidoglycan / outer membrane",
        visualType: "bacterial-cell-structure",
      },
    ],
  },
  {
    id: "bio-virus-structure-bacteriophage",
    slug: "virus-structure-bacteriophage",
    title: "Virus: Structure and the Bacteriophage",
    subject: "biology",
    unit: "Introductory Microbiology",
    unitId: "introductory-microbiology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Viruses are non-cellular infective particles (protein capsid + nucleic acid) that can only replicate inside a host; bacteriophages infect bacteria.",
    coreFormula: "\\text{capsid} + \\text{N.A.} \\rightarrow \\text{virion}",
    concernedTerms: [
      { term: "Capsid", definition: "Protein coat protecting the nucleic acid; composed of capsomeres." },
      { term: "Envelope", definition: "Lipid membrane derived from the host, present in some animal viruses." },
      { term: "Bacteriophage", definition: "Virus that infects bacteria, e.g. T4." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Phage replication", latex: "\\text{injection} \\rightarrow \\text{replication} \\rightarrow \\text{assembly} \\rightarrow \\text{lysis}", explanation: "The lytic cycle bursts the host releasing new phages." },
    ],
    conclusion: "Viruses sit at the border between living and non-living; they lack their own metabolism.",
    keyTakeaways: ["Only one type of nucleic acid (DNA or RNA) is present per virus."],
    examTraps: ["A virion is the complete, intact particle; 'naked' viruses lack an envelope."],
    visualType: "virion-structure",
    solvedProblems: [
      {
        id: "bio-virus-1",
        question: "Why are viruses not considered living cells?",
        given: "Criteria of life.",
        stepByStep: ["No ribosomes, no independent metabolism.", "Replication needs a host cell."],
        finalAnswer: "They cannot metabolise or replicate independently",
        visualType: "virion-structure",
      },
    ],
  },
  {
    id: "bio-biotechnology-microbes",
    slug: "biotechnology-microbe-applications",
    title: "Biotechnology: Microbial Applications",
    subject: "biology",
    unit: "Introductory Microbiology",
    unitId: "introductory-microbiology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Microorganisms are exploited industrially and medically to produce foods, antibiotics, enzymes and to treat pollutants.",
    coreFormula: "\\text{strain} \\xrightarrow{\\text{fermentation/bioreactor}} \\text{product}",
    concernedTerms: [
      { term: "Fermentation", definition: "Metabolism of sugars by microbes to yield products (alcohol, lactic acid)." },
      { term: "Bioreactor", definition: "Vessel where microbes are cultured under controlled conditions." },
      { term: "Biofertiliser", definition: "Living microbe preparation enriching soil nitrogen." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Industrial example", latex: "C_{6}H_{12}O_6 \\xrightarrow{\\text{S. cerevisiae}} 2C_2H_5OH + 2CO_2", explanation: "Yeast fermentation produces ethanol." },
    ],
    conclusion: "Biotechnology harnesses microbial metabolism for food, medicine and environment.",
    keyTakeaways: ["Lactobacillus produces lactic acid in curd; Rhizobium fixes nitrogen."],
    examTraps: ["Alcohol fermentation by yeast is anaerobic; lactic-acid fermentation in muscles is also anaerobic."],
    visualType: "biotech-microbe-applications",
    solvedProblems: [
      {
        id: "bio-biotech-1",
        question: "Name the microbe used in curd (yogurt) production and the product it makes.",
        given: "Lactic acid fermentation.",
        stepByStep: ["Lactobacillus ferments lactose.", "Product is lactic acid which coagulates milk."],
        finalAnswer: "Lactobacillus; lactic acid",
        visualType: "biotech-microbe-applications",
      },
    ],
  },

  // ── Unit 4: Ecology ──────────────────────────────────────────────────────
  {
    id: "bio-food-chain-web-trophic",
    slug: "food-chain-web-trophic-levels",
    title: "Food Chains, Food Webs and Trophic Levels",
    subject: "biology",
    unit: "Ecology",
    unitId: "ecology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Energy and matter flow through trophic levels; a food chain is linear, a food web is a network, and pyramids represent this flow.",
    coreFormula: "\\text{Producer} \\rightarrow \\text{P1} \\rightarrow \\text{P2} \\rightarrow \\text{Decomposer}",
    concernedTerms: [
      { term: "Trophic level", definition: "Functional position in the food chain (producer, primary/secondary consumer)." },
      { term: "Ecological pyramid", definition: "Diagram of numbers, biomass or energy across trophic levels." },
      { term: "Net Primary Productivity", definition: "Energy retained by producers after respiration." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Energy flow", latex: "\\text{10\\% rule}: E_{n+1} \\approx 0.1 E_n", explanation: "Most energy is lost as heat at each transfer." },
    ],
    conclusion: "Ecosystems transfer energy unidirectionally with large losses, limiting trophic length.",
    keyTakeaways: ["Only the energy pyramid is always upright."],
    examTraps: ["Numbers and biomass pyramids can be inverted (e.g. an oak supporting many insects)."],
    visualType: "food-chain-web",
    solvedProblems: [
      {
        id: "bio-trophic-1",
        question: "If a producer level has 1000 kcal, approximately how much reaches the second-level consumer?",
        given: "10% rule.",
        stepByStep: ["P1 = 100 kcal, P2 = 10 kcal."],
        finalAnswer: "≈ 10 kcal",
        visualType: "food-chain-web",
      },
    ],
  },
  {
    id: "bio-biogeochemical-cycles",
    slug: "carbon-nitrogen-cycles",
    title: "Biogeochemical Cycles: Carbon and Nitrogen",
    subject: "biology",
    unit: "Ecology",
    unitId: "ecology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Essential elements such as carbon and nitrogen circulate between biotic and abiotic pools through biological and physical processes.",
    coreFormula: "CO_2 \\leftrightarrow \\text{organic C} \\leftrightarrow reservoirs; N_2 \\rightarrow NH_4^+ \\rightarrow NO_3^- \\rightarrow N_2",
    concernedTerms: [
      { term: "Nitrogen fixation", definition: "Conversion of N2 to ammonia (nitrifying bacteria, Rhizobium)." },
      { term: "Denitrification", definition: "Conversion of nitrates back to N2 (Denitrobacter)." },
      { term: "Sedimentary pool", definition: "Reservoir where an element cycles through rocks." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Nitrogen cycle", latex: "N_2 \\xrightarrow{fixers} NH_4^+ \\xrightarrow{nitrifiers} NO_3^- \\xrightarrow{denitrifiers} N_2", explanation: "The cycle recloses the atmospheric pool." },
    ],
    conclusion: "Cycles keep essential elements in continuous motion between organisms and the environment.",
    keyTakeaways: ["Only microbes (and lightning) fix nitrogen."],
    examTraps: ["Ammonification (nitrification) is a separate step from denitrification."],
    visualType: "carbon-nitrogen-cycles",
    solvedProblems: [
      {
        id: "bio-cycles-1",
        question: "Name the microbe that converts nitrate to N2 in the soil.",
        given: "Nitrogen cycle.",
        stepByStep: ["Denitrifiers reduce nitrates to N2.", "e.g. Pseudomonas / Denitrobacter."],
        finalAnswer: "Denitrifying bacteria",
        visualType: "carbon-nitrogen-cycles",
      },
    ],
  },
  {
    id: "bio-ecological-adaptation",
    slug: "hydrophyte-xerophyte-adaptations",
    title: "Ecological Adaptation: Hydrophytes and Xerophytes",
    subject: "biology",
    unit: "Ecology",
    unitId: "ecology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Plants adapt structurally to water availability: hydrophytes thrive in water, xerophytes conserve it in arid habitats.",
    coreFormula: "\\text{hydrophyte}: \\text{aerenchyma + sunken stomata}; \\text{xerophyte}: \\text{thick cuticle + reduced leaves}",
    concernedTerms: [
      { term: "Aerenchyma", definition: "Air-filled tissue giving buoyancy and gas exchange to aquatic plants." },
      { term: "Xerophytic adaptation", definition: "Reduced/stomatal leaves, thick cuticle, deep roots (e.g. cactus)." },
      { term: "Morphological adaptation", definition: "Structural adjustment to an environment." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Water relation", latex: "\\text{high water} \\Rightarrow \\text{aerenchyma}; \\text{low water} \\Rightarrow \\text{stomatal closure}", explanation: "Opposite pressures shape opposite tissues." },
    ],
    conclusion: "Adaptation is the match between an organism's traits and its habitat.",
    keyTakeaways: ["Xerophytes keep stomata open only at night (CAM in many)."],
    examTraps: ["Hydrophytes have few thick-cuticle; xerophytes have prominent cuticles."],
    visualType: "hydrophyte-xerophyte-adaptations",
    solvedProblems: [
      {
        id: "bio-ec-adapt-1",
        question: "Name two adaptations of a xerophyte to a dry environment.",
        given: "Water conservation.",
        stepByStep: ["Thick waxy cuticle reduces transpiration.", "Reduced or spiny leaves reduce surface area."],
        finalAnswer: "Thick cuticle; reduced/spiny leaves",
        visualType: "hydrophyte-xerophyte-adaptations",
      },
    ],
  },
  {
    id: "bio-ecological-imbalance",
    slug: "ecological-imbalance-climate-change",
    title: "Ecological Imbalance and Climate Change",
    subject: "biology",
    unit: "Ecology",
    unitId: "ecology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Human activity drives ecological imbalances — greenhouse effect, ozone depletion, acid rain and biological invasion.",
    coreFormula: "GHGs \\uparrow + \\text{ozone-depleting} \\uparrow \\Rightarrow \\text{global imbalance}",
    concernedTerms: [
      { term: "Greenhouse gases", definition: "CO2, CH4, N2O, CFCs trapping infrared radiation." },
      { term: "Ozone depletion", definition: "Loss of stratospheric O3 by CFCs, increasing UV." },
      { term: "Acid rain", definition: "Precipitation of SOx/NOx acids damaging ecosystems." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Feedback loop", latex: "CO_2 \\uparrow \\Rightarrow T \\uparrow \\Rightarrow \\text{permafrost} \\rightarrow CH_4 \\uparrow \\Rightarrow T \\uparrow", explanation: "Warming releases more greenhouse gases." },
    ],
    conclusion: "Ecological imbalances disrupt biogeochemical cycles and biodiversity, and feed back on climate.",
    keyTakeaways: ["CFCs are the chief ozone-depleting agents."],
    examTraps: ["Ozone depletion is distinct from global warming (different gases)."],
    visualType: "pollution-climate-change",
    solvedProblems: [
      {
        id: "bio-eco-imb-1",
        question: "Name two effects of ozone layer depletion.",
        given: "UV-B increase.",
        stepByStep: ["Increased UV-B raises skin cancer and cataracts.", "UV-B damages phytoplankton and crop DNA."],
        finalAnswer: "Higher UV-B; ecosystem damage",
        visualType: "pollution-climate-change",
      },
    ],
  },

  // ── Unit 5: Vegetation ───────────────────────────────────────────────────
  {
    id: "bio-nepal-vegetation",
    slug: "vegetation-zones-nepal",
    title: "Types of Vegetation in Nepal",
    subject: "biology",
    unit: "Vegetation",
    unitId: "vegetation",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Nepal's extreme altitude and moisture gradients support distinct vegetation zones from subtropical to alpine.",
    coreFormula: "Altitude + Moisture + Climate \\Rightarrow \\text{vegetation type}",
    concernedTerms: [
      { term: "Terai / Churia", definition: "Lowland (terai) and mid-hill (churia) broadleaf forests." },
      { term: "Rhododendron forest", definition: "Temperate evergreen forest of the mid-hills." },
      { term: "Alpine vegetation", definition: "Short herbs and cushion plants above the tree line." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Zonation", latex: "T \\downarrow \\text{with alt.} \\Rightarrow \\text{zone succession}", explanation: "A lapse rate shifts each 100 m up the mountain." },
    ],
    conclusion: "Nepal's vertical relief packs many climate zones into a small area, giving high vegetation diversity.",
    keyTakeaways: ["Conservation of each zone is part of ex-situ and in-situ protection."],
    examTraps: ["'Churia' is a folk term for the mid-hills, not a formal zone."],
    visualType: "nepal-vegetation-zones",
    solvedProblems: [
      {
        id: "bio-nepal-veg-1",
        question: "Name two plant zones of Nepal with an example of one species each.",
        given: "Zonation.",
        stepByStep: ["Temperate: Rhododendron arboreum.", "Alpine: Sedum or Dianthus."],
        finalAnswer: "Temperate zone; alpine zone",
        visualType: "nepal-vegetation-zones",
      },
    ],
  },

  // ── Unit 6: Introduction to Biology ──────────────────────────────────────
  {
    id: "bio-scope-fields",
    slug: "biology-scope-fields",
    title: "Scope and Fields of Biology",
    subject: "biology",
    unit: "Introduction to Biology",
    unitId: "introduction-to-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Biology is the study of living organisms; it divides into botany and zoology and has many sub-disciplines.",
    coreFormula: "\\text{Biology} = \\text{Botany} + \\text{Zoology} + \\text{Microbiology} + \\cdots",
    concernedTerms: [
      { term: "Botany", definition: "Study of plants." },
      { term: "Zoology", definition: "Study of animals." },
      { term: "Biodiversity", definition: "Variation at gene, species and ecosystem levels." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Disciplinary tree", latex: "\\text{Biology} \\rightarrow \\{ \\text{botany, zoology, ...} \\}", explanation: "Each field studies one class of life." },
    ],
    conclusion: "Biology is interdisciplinary and underpins agriculture, medicine and ecology.",
    keyTakeaways: ["Biotechnology and genomics are modern applied branches."],
    examTraps: ["Microbiology studies microbes, not a single kingdom."],
    visualType: "biology-scope-branches",
    solvedProblems: [
      {
        id: "bio-scope-1",
        question: "Name the field that studies the relationships between organisms and their environment.",
        given: "Disciplinary definitions.",
        stepByStep: ["The study of interactions = ecology."],
        finalAnswer: "Ecology",
        visualType: "biology-scope-branches",
      },
    ],
  },

  // ── Unit 7: Evolutionary Biology ────────────────────────────────────────
  {
    id: "bio-origin-of-life",
    slug: "origin-of-life-experiment",
    title: "Origin of Life: Oparin-Haldane and Miller-Urey",
    subject: "biology",
    unit: "Evolutionary Biology",
    unitId: "evolutionary-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Oparin-Haldane proposed that life began from non-living chemicals; Miller-Urey demonstrated that amino acids form from inorganic gases under prebiotic conditions.",
    coreFormula: "\\text{CH}_4, NH_3, H_2O, H_2 \\xrightarrow{\\text{discharge}} \\text{amino acids}",
    concernedTerms: [
      { term: "Protobiont", definition: "Colloidal system regarded as a precursor to the first cell." },
      { term: "Prebiotic soup", definition: "Hypothetical early-ocean mixture of organic monomers." },
      { term: "Oparin-Haldane hypothesis", definition: "Life arose from inorganic precursors under early-Earth conditions." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Miller-Urey result", latex: "\\text{amino acids} \\in \\text{condensate}", explanation: "Amino acids formed spontaneously from simple gases and spark." },
    ],
    conclusion: "The origin of life is plausibly abiotic; the Miller-Urey experiment provides the classical support.",
    keyTakeaways: ["Miller-Urey proved organic synthesis, not that life arose."],
    examTraps: ["The experiment did NOT reproduce a living cell — only monomers."],
    visualType: "origin-of-life-experiment",
    solvedProblems: [
      {
        id: "bio-origin-1",
        question: "What did Miller-Urey's apparatus produce that supported Oparin's theory?",
        given: "Prebiotic gas mixture.",
        stepByStep: ["Discharge + recondensation yielded amino acids.", "Amino acids are monomers of proteins."],
        finalAnswer: "Amino acids",
        visualType: "origin-of-life-experiment",
      },
    ],
  },
  {
    id: "bio-evidences-of-evolution",
    slug: "evidences-of-evolution",
    title: "Evidences of Evolution",
    subject: "biology",
    unit: "Evolutionary Biology",
    unitId: "evolutionary-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Morphological, anatomical, palaeontological, embryological and biochemical evidence all indicate common ancestry.",
    coreFormula: "\\text{homology} + \\text{vestigia} + \\text{fossils} + \\text{DNA} \\Rightarrow \\text{evolution}",
    concernedTerms: [
      { term: "Homologous organs", definition: "Similar structure, different function — common origin (e.g. pentadactyl limb)." },
      { term: "Analogous organs", definition: "Similar function, different structure — convergent evolution." },
      { term: "Vestigial organ", definition: "Reduced structure from a lost function (e.g. human tailbone)." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Common origin from homology", latex: "\\text{same skeleton} \\Rightarrow \\text{common ancestor}", explanation: "Ancestral plan persists across vertebrate limbs." },
    ],
    conclusion: "Independent lines of evidence converge on the fact of evolution.",
    keyTakeaways: ["DNA similarities are the strongest evidence."],
    examTraps: ["Analogous organs are evidence of CONVERGENCE, not descent."],
    visualType: "evidences-of-evolution",
    solvedProblems: [
      {
        id: "bio-evol-evid-1",
        question: "Classify the forelimbs of a bat and a human: homologous or analogous?",
        given: "Anatomical comparison.",
        stepByStep: ["Same underlying bone plan.", "Different function (flight vs locomotion)."],
        finalAnswer: "Homologous (divergent evolution)",
        visualType: "evidences-of-evolution",
      },
    ],
  },
  {
    id: "bio-theories-of-evolution",
    slug: "theories-of-evolution-comparison",
    title: "Theories of Evolution: Lamarckism, Darwinism, Neo-Darwinism",
    subject: "biology",
    unit: "Evolutionary Biology",
    unitId: "evolutionary-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Lamarckism (inheritance of acquired characters), Darwinism (natural selection) and Neo-Darwinism (synthetic theory with genetics) explain evolution differently.",
    coreFormula: "Lamarck: UG \\rightarrow \\text{acquired} \\rightarrow \\text{inherit}; Darwin: \\Delta p \\propto s",
    concernedTerms: [
      { term: "Natural selection", definition: "Differential survival/reproduction of the fittest (Darwin)." },
      { term: "Neo-Darwinism", definition: "Synthetic theory: mutation + selection + drift." },
      { term: "Pangenesis", definition: "Lamarck's mechanism of 'particules' carrying acquired traits." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Test Lamarckism", latex: "\\text{guinea-pig tail} \\rightarrow \\text{descendants with tails}", explanation: "Experiments show acquired characters are NOT inherited — falsifying Lamarck." },
    ],
    conclusion: "Modern evolutionary biology = Darwin's selection + Mendelian genetics + molecular data.",
    keyTakeaways: ["Neo-Darwinism is the current framework."],
    examTraps: ["Lamarckism was disproved (Weismann's guinea-pig)."],
    visualType: "evolution-theories-comparison",
    solvedProblems: [
      {
        id: "bio-evol-theo-1",
        question: "Why was Weismann's guinea-pig experiment a blow to Lamarckism?",
        given: "Lamarck's pangenesis.",
        stepByStep: ["Trimmed tails on successive generations.", "Offspring always had normal tails."],
        finalAnswer: "Acquired characters are not inherited",
        visualType: "evolution-theories-comparison",
      },
    ],
  },
  {
    id: "bio-human-evolution",
    slug: "human-evolution-tree",
    title: "Human Evolution",
    subject: "biology",
    unit: "Evolutionary Biology",
    unitId: "evolutionary-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Modern humans descend from an anthropoid ancestor through successive hominid stages with increasing brain size and bipedalism.",
    coreFormula: "\\text{anthropoid} \\rightarrow \\text{Australopithecus} \\rightarrow H.\\ erectus \\rightarrow H.\\ sapiens",
    concernedTerms: [
      { term: "Hominid", definition: "Bipedal great-ape lineage leading to humans." },
      { term: "Encephalisation", definition: "Increase in brain size over evolution." },
      { term: "Bipedalism", definition: "Upright walking; an early human distinguishing trait." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Progressive trend", latex: "V_{brain} \\uparrow, H_{bipedal} \\uparrow", explanation: "Brain volume and upright posture increase through the fossil record." },
    ],
    conclusion: "Human evolution is a tree (not a ladder) with branching and extinction.",
    keyTakeaways: ["Bipedalism preceded encephalisation."],
    examTraps: ["Humans did not evolve from 'monkeys' as currently living — we share a common ancestor."],
    visualType: "human-evolution-tree",
    solvedProblems: [
      {
        id: "bio-human-evo-1",
        question: "State one distinguishing feature of hominids over apes.",
        given: "Anatomical comparison.",
        stepByStep: ["Hominids are obligate bipeds with S-shaped spine.", "Apes retain knuckle-walking."],
        finalAnswer: "Obligate bipedalism",
        visualType: "human-evolution-tree",
      },
    ],
  },

  // ── Unit 8: Faunal Diversity ────────────────────────────────────────────
  {
    id: "bio-protist-classification",
    slug: "protist-diversity-classification",
    title: "Protista: Outline Classification",
    subject: "biology",
    unit: "Faunal Diversity",
    unitId: "faunal-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Protists are mostly unicellular eukaryotes, classified into protozoa (animal-like), algae (plant-like) and slime moulds (fungus-like).",
    coreFormula: "\\text{Protista} = \\text{protozoa} + \\text{algae} + \\text{slime mould}",
    concernedTerms: [
      { term: "Protozoa", definition: "Animal-like protists (Amoeba, Paramecium, Plasmodium)." },
      { term: "Ciliate", definition: "Flagellate or ciliate protozoan." },
      { term: "Slime mould", definition: "Sessile, fungus-like protist." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Classification rule", latex: "\\text{motile animal-like} \\rightarrow \\text{protozoa}", explanation: "By nutrition and mode of locomotion." },
    ],
    conclusion: "Protista is a 'dumping' group for unicellular eukaryotes that don't fit other kingdoms.",
    keyTakeaways: ["Paramecium and Plasmodium are classic protozoa studied in NEB."],
    examTraps: ["Algae (green, red, brown) are protists, not plants."],
    visualType: "protist-diversity",
    solvedProblems: [
      {
        id: "bio-protist-1",
        question: "Classify Plasmodium: kingdom and protozoan group.",
        given: "Classification.",
        stepByStep: ["P. vivax is a unicellular eukaryote (protist).", "It is a parasitic spiroplasm."],
        finalAnswer: "Protista; sporozoan",
        visualType: "protist-diversity",
      },
    ],
  },
  {
    id: "bio-animal-phyla-diagnosis",
    slug: "animal-phyla-diagnostic-features",
    title: "Diagnostic Features of Animal Phyla",
    subject: "biology",
    unit: "Faunal Diversity",
    unitId: "faunal-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Each animal phylum has a set of diagnostic features (body plan, symmetry, body cavity, germ layers) used to place an organism.",
    coreFormula: "\\text{body cavity + symmetry + germ layers} \\Rightarrow \\text{phylum}",
    concernedTerms: [
      { term: "Coelom", definition: "True body cavity lined with mesoderm (triploblastic coelomates)." },
      { term: "Metamerism", definition: "Segmentation of the body into repeated units." },
      { term: "Bilateral symmetry", definition: "Left and right halves mirror each other." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Classify by cavity", latex: "\\text{diploblastic} + \\text{acoelomate} \\Rightarrow \\text{Platyhelminthes}", explanation: "Flatworms have two germ layers and no cavity." },
    ],
    conclusion: "Phylum-level diagnosis uses germ layers, body cavity and symmetry.",
    keyTakeaways: ["Arthropods are the largest phylum (insects)."],
    examTraps: ["Nemathelminthes (roundworms) are pseudocoelomates, not true coelomates."],
    visualType: "animal-phyla-key-features",
    solvedProblems: [
      {
        id: "bio-phyla-1",
        question: "Why is an earthworm a coelomate?",
        given: "Annelid diagnosis.",
        stepByStep: ["It has a fluid-filled true coelom (chaetae in it).", "Triploblastic body plan."],
        finalAnswer: "True coelom present",
        visualType: "animal-phyla-key-features",
      },
    ],
  },
  {
    id: "bio-earthworm-pheretima",
    slug: "earthworm-external-anatomy",
    title: "Earthworm (Pheretima posthuma)",
    subject: "biology",
    unit: "Faunal Diversity",
    unitId: "faunal-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Pheretima posthuma is a segmented annelid with a clitellum, metanephric nephridia, a dorsal nerve cord and a gel tube for respiration.",
    coreFormula: "\\text{metamerism} + \\text{coelom} + \\text{clitellum} \\Rightarrow \\text{annelid}",
    concernedTerms: [
      { term: "Clitellum", definition: "Thickened segment producing the cocoon in which fertilised eggs develop." },
      { term: "Nephridium", definition: "Excretory tubule; Pheretima has septal (metanephric) nephridia." },
      { term: "Typhlosole", definition: "Internal dorsal fold of the alimentary canal increasing absorptive area." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Cocoon formation", latex: "\\text{clitellum} \\rightarrow \\text{mucus cocoon} \\rightarrow \\text{eggs} + \\text{spermen}", explanation: "Sexual reproduction is by copulation via clitellum." },
    ],
    conclusion: "Earthworms are model invertebrates for studying annelid anatomy and physiology.",
    keyTakeaways: ["They respire through the skin — which is why they stay moist."],
    examTraps: ["The 'heart' of an earthworm is replaced by dorsal vessels, not a true heart."],
    visualType: "earthworm-external-anatomy",
    solvedProblems: [
      {
        id: "bio-worm-1",
        question: "Name the pair of structures that produce the cocoon in an earthworm.",
        given: "Reproduction.",
        stepByStep: ["The clitellum is the specialised band.", "It secretes the mucus cocoon."],
        finalAnswer: "Clitellum",
        visualType: "earthworm-external-anatomy",
      },
    ],
  },
  {
    id: "bio-frog-rana",
    slug: "frog-anatomy-overview",
    title: "Frog (Rana tigrina)",
    subject: "biology",
    unit: "Faunal Diversity",
    unitId: "faunal-diversity",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Rana tigrina is a model amphibian for studying the 3-chambered heart, moist-skin respiration and the complete digestive tract.",
    coreFormula: "\\text{3-chambered heart} + \\text{dual respiration} + \\text{metamorphosis} \\Rightarrow \\text{amphibian}",
    concernedTerms: [
      { term: "Ventriculus", definition: "Frogs have one atrium-less ventricle mixing oxygenated and deoxygenated blood." },
      { term: "Metamorphosis", definition: "Tadpole to frog; thyroid hormone (T3/T4) regulates." },
      { term: "Cutaneous respiration", definition: "Gas exchange through moist skin." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Circulatory system", latex: "\\text{3 chambers} \\Rightarrow \\text{mixing in ventricle}", explanation: "A partial septum divides the ventricle." },
    ],
    conclusion: "Rana tigrina exemplifies the major amphibian body systems.",
    keyTakeaways: ["Frogs are tetrapods with a 3-chambered heart."],
    examTraps: ["Amphibians have a partial septum, not a complete one."],
    visualType: "frog-anatomy-overview",
    solvedProblems: [
      {
        id: "bio-frog-1",
        question: "How many chambers does the frog heart have?",
        given: "Comparative anatomy.",
        stepByStep: ["Frogs have 2 atria + 1 ventricle = 3 chambers."],
        finalAnswer: "Three",
        visualType: "frog-anatomy-overview",
      },
    ],
  },

  // ── Unit 10: Conservation Biology ───────────────────────────────────────
  {
    id: "bio-biodiversity-conservation",
    slug: "biodiversity-conservation",
    title: "Biodiversity and Conservation",
    subject: "biology",
    unit: "Conservation Biology",
    unitId: "conservation-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Biodiversity (genetic, species and ecosystem) is protected by in-situ (protected areas) and ex-situ (botanical garden, seed bank) strategies.",
    coreFormula: "\\text{biodiversity} = \\text{genes} + \\text{species} + \\text{ecosystems}",
    concernedTerms: [
      { term: "In-situ", definition: "Conservation in the natural habitat (parks, reserves)." },
      { term: "Ex-situ", definition: "Conservation outside the habitat (botanical garden, seed bank, zoo)." },
      { term: "Hotspot", definition: "Region of high endemic richness and threat." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Complementary strategies", latex: "\\text{in-situ} + \\text{ex-situ} \\Rightarrow \\text{survival}", explanation: "In-situ preserves ecosystems; ex-situ buffers against extinction." },
    ],
    conclusion: "Biodiversity loss is accelerated by habitat destruction, poaching, pollution and invasive species.",
    keyTakeaways: ["Nepal's IUCN Red List is a key reference for national conservation."],
    examTraps: ["In-situ is preferred because it protects whole ecosystems, not just species."],
    visualType: "biodiversity-conservation",
    solvedProblems: [
      {
        id: "bio-bio-cons-1",
        question: "Name one in-situ and one ex-situ conservation method.",
        given: "Conservation strategies.",
        stepByStep: ["In-situ: national park, wildlife reserve.", "Ex-situ: botanical garden, seed bank."],
        finalAnswer: "National park; seed bank",
        visualType: "biodiversity-conservation",
      },
    ],
  },
  {
    id: "bio-conservation-strategies-nepal",
    slug: "conservation-strategies-nepal",
    title: "Conservation Strategies in Nepal",
    subject: "biology",
    unit: "Conservation Biology",
    unitId: "conservation-biology",
    gradeTrack: "grade-11",
    nebCode: "Bio. 201",
    isExtra: false,
    statement: "Nepal's national parks (Chitwan, Bardia, Annapurna), wildlife reserves and Ramsar sites (Kathmandu, Bara) protect flora and fauna.",
    coreFormula: "\\text{parks} + \\text{reserves} + \\text{Ramsar sites} \\Rightarrow \\text{Nepal conservation}",
    concernedTerms: [
      { term: "Ramsar site", definition: "Wetland of international importance (WDS, Bara, etc.)." },
      { term: "IUCN categories", definition: "Extinct, Critically Endangered, Endangered, Vulnerable, NT, LC." },
      { term: "Endangered species in Nepal", definition: "Snow leopard, rhododendron arboreum, tiger, one-horned rhino, etc." },
    ],
    proofSteps: [
      { stepNumber: 1, title: "Protected-area mosaic", latex: "P + R + R_{m} \\Rightarrow \\text{network of corridors}", explanation: "Corridors allow gene flow between populations." },
    ],
    conclusion: "Nepal's conservation combines in-situ networks with ex-situ facilities.",
    keyTakeaways: ["One-horned rhino (Chitwan) is a flagship species."],
    examTraps: ["Ramsar sites are wetlands, not necessarily national parks."],
    visualType: "conservation-strategies-nepal",
    solvedProblems: [
      {
        id: "bio-cons-nepal-1",
        question: "Name two national parks of Nepal that protect large mammals.",
        given: "Protected areas.",
        stepByStep: ["Chitwan protects tiger and one-horned rhino.", "Bardia protects tiger and cheetal."],
        finalAnswer: "Chitwan, Bardia",
        visualType: "conservation-strategies-nepal",
      },
    ],
  },
];
