/**
 * Graph Bank — Chemistry & Biology.
 */

import type { GraphEntry } from "@/lib/graphs";

export const CHEM_BIO_GRAPHS: GraphEntry[] = [
  // ═══ CHEMISTRY ═══
  {
    id: "chem-order-diagnostics", slug: "order-of-reaction-graphs", name: "Order Diagnostics: ln[A] vs t and 1/[A] vs t",
    subject: "chemistry", category: "Chemical Kinetics", classLevel: "class-12",
    axes: { x: "Time t", y: "ln[A] or 1/[A]" },
    basis: "Integrated rate laws plotted for the same data until one gives a straight line.",
    meaning: "Which plot is linear reveals the order of reaction.",
    equation: "\\ln[A] = \\ln[A]_0 - kt \\ (1st), \\quad \\frac{1}{[A]} = \\frac{1}{[A]_0} + kt \\ (2nd)",
    series: [
      { shape: "linearFall", label: "ln[A] vs t (1st order)" },
      { shape: "linearRise", label: "1/[A] vs t (2nd order)", dashed: true },
    ],
    howToRead: { slope: "Rate constant k (−k for 1st, +k for 2nd)", intercept: "ln[A]₀ or 1/[A]₀" },
    output: "Straight falling line for first order; straight rising line for second order. The linear one identifies the order; slope = ±k.",
    specialCases: [
      { name: "Zero order", condition: "[A] vs t plotted", meaning: "Straight falling line; slope = −k." },
      { name: "Constant half-life", condition: "1st order", meaning: "Equal concentration halvings in equal times." },
      { name: "Doubling t½", condition: "2nd order", meaning: "Half-life grows as [A] falls." },
    ],
  },
  {
    id: "chem-rate-time", slug: "rate-vs-time", name: "Rate of Reaction vs Time",
    subject: "chemistry", category: "Chemical Kinetics", classLevel: "class-12",
    axes: { x: "Time t", y: "Rate" },
    basis: "Instantaneous rate (from tangents on the concentration–time curve) as reaction proceeds.",
    meaning: "Rate is highest at the start and falls as reactants are consumed.",
    series: [{ shape: "expDecayToFloor" }],
    marks: [{ x: 0.02, y: 0.96, label: "initial rate", type: "point" }],
    output: "Steep initial rate falling toward zero at completion (or equilibrium). Extrapolating to t = 0 gives the initial rate used in rate-law experiments.",
    specialCases: [
      { name: "Initial rate method", condition: "t → 0", meaning: "Order found before products interfere." },
      { name: "Plateau", condition: "equilibrium reached", meaning: "Forward = backward rate; no net change." },
      { name: "Catalyst curve", condition: "same Δt", meaning: "Higher curve throughout — faster completion." },
    ],
  },
  {
    id: "chem-maxwell-boltzmann", slug: "maxwell-boltzmann-distribution", name: "Maxwell–Boltzmann Energy Distribution",
    subject: "chemistry", category: "Chemical Kinetics", classLevel: "class-11",
    axes: { x: "Kinetic energy", y: "Fraction of molecules" },
    basis: "Distribution of molecular speeds/energies in a gas at temperature T.",
    meaning: "Few molecules at both extremes; the peak is the most probable energy — heating shifts it right.",
    series: [
      { shape: "bell", variant: 6, label: "low T" },
      { shape: "bell", variant: 10, label: "high T", dashed: true },
    ],
    marks: [{ x: 0.62, label: "Eₐ", type: "vline" }],
    howToRead: { area: "Fraction of molecules with E > Eₐ (can react)" },
    output: "Asymmetric bell starting at the origin with a long right tail. At higher T the peak lowers and shifts right; the tail beyond Eₐ grows — hence faster reaction.",
    specialCases: [
      { name: "Heating effect", condition: "T ↑", meaning: "More molecules exceed Eₐ — rate rises sharply." },
      { name: "Catalyst", condition: "E₃ lowered", meaning: "Eₐ line moves left into the dense region." },
      { name: "Most probable energy", condition: "peak position", meaning: "Shifts right with temperature." },
    ],
  },
  {
    id: "chem-energy-profile", slug: "energy-profile-diagram", name: "Reaction Energy Profile (with Catalyst)",
    subject: "chemistry", category: "Equilibrium & Energy", classLevel: "class-11",
    axes: { x: "Reaction progress", y: "Potential energy" },
    basis: "Energy of the reacting system tracked from reactants over the activated complex to products.",
    meaning: "Shows activation energy (the hill) and reaction enthalpy (the net drop or rise).",
    series: [
      { shape: "barrier", label: "uncatalysed" },
      { shape: "barrier", variant: 0.6, label: "catalysed", dashed: true },
    ],
    marks: [
      { x: 0.05, y: 0.1, label: "reactants", type: "point" },
      { x: 0.95, y: 0.06, label: "products", type: "point" },
    ],
    output: "Flat start, activation hill (Eₐ), flat end lower (exothermic) or higher (endothermic). Catalyst supplies a second, lower hill — ΔH unchanged.",
    specialCases: [
      { name: "Exothermic", condition: "products lower", meaning: "ΔH negative; heat released." },
      { name: "Endothermic", condition: "products higher", meaning: "ΔH positive; heat absorbed." },
      { name: "Catalyst", condition: "alternate path", meaning: "Lowers Eₐ equally for forward and back reactions." },
    ],
  },
  {
    id: "chem-k-vs-t", slug: "equilibrium-constant-vs-temperature", name: "van't Hoff: K vs Temperature",
    subject: "chemistry", category: "Equilibrium & Energy", classLevel: "class-12",
    axes: { x: "Temperature T", y: "Equilibrium constant K" },
    basis: "Equilibrium constant measured at different temperatures (Le Chatelier in numbers).",
    meaning: "K rises with T for endothermic reactions, falls for exothermic.",
    equation: "\\ln K = -\\frac{\\Delta H}{RT} + \\frac{\\Delta S}{R}",
    series: [
      { shape: "expRise", variant: 4, label: "endothermic (ΔH > 0)" },
      { shape: "expDecay", variant: 4, label: "exothermic (ΔH < 0)", dashed: true },
    ],
    output: "Exponential rise for endothermic, fall for exothermic; ln K vs 1/T is a straight line of slope −ΔH/R.",
    specialCases: [
      { name: "Haber process", condition: "exothermic", meaning: "K (yield) falls as T rises — compromise temperature needed." },
      { name: "Slope sign", condition: "van't Hoff plot", meaning: "Negative slope ⇒ exothermic." },
    ],
  },
  {
    id: "chem-titration-curve", slug: "titration-curves-ph", name: "pH Titration Curves (Strong & Weak Acid)",
    subject: "chemistry", category: "Acids & Bases", classLevel: "class-12",
    axes: { x: "Volume of base added", y: "pH" },
    basis: "pH logged while base is added to an acid sample.",
    meaning: "Reveals equivalence point, buffer region and acid strength.",
    series: [
      { shape: "sigmoid", variant: 9, label: "strong acid + strong base" },
      { shape: "sigmoid", variant: 5, label: "weak acid + strong base", dashed: true },
    ],
    marks: [{ x: 0.5, y: 0.55, label: "equivalence", type: "point" }],
    output: "Flat regions joined by a near-vertical jump at equivalence (pH 7 for strong–strong; >7 for weak acid). The weak-acid curve starts higher and shows a buffer flat before the jump.",
    specialCases: [
      { name: "Buffer region", condition: "half-neutralisation", meaning: "pH ≈ pKₐ (Henderson–Hasselbalch flat)." },
      { name: "Indicator choice", condition: "steep zone", meaning: "Indicator must change colour within the jump." },
      { name: "Weak–weak", condition: "no sharp jump", meaning: "Titration impractical — no clear endpoint." },
    ],
  },
  {
    id: "chem-vapour-pressure-t", slug: "vapour-pressure-vs-temperature", name: "Vapour Pressure vs Temperature",
    subject: "chemistry", category: "Solutions & Electrochemistry", classLevel: "class-11",
    axes: { x: "Temperature T", y: "Vapour pressure p" },
    basis: "Equilibrium vapour pressure of a liquid measured as it is heated.",
    meaning: "Exponential rise; boiling occurs when p equals atmospheric pressure.",
    equation: "\\ln p = -\\frac{\\Delta H_{vap}}{RT} + C",
    series: [{ shape: "expRise", variant: 5 }],
    marks: [{ x: 0.78, label: "b.p. (p = 1 atm)", type: "vline" }],
    output: "Slow rise then steep climb; the temperature where the curve crosses 1 atm is the normal boiling point. Clausius–Clapeyron linearises it.",
    specialCases: [
      { name: "Altitude", condition: "lower p_atm", meaning: "Crossing happens earlier — water boils cooler on mountains." },
      { name: "Volatile liquids", condition: "higher curve", meaning: "Ether/acetone reach 1 atm sooner than water." },
    ],
  },
  {
    id: "chem-solubility-t", slug: "solubility-vs-temperature", name: "Solubility vs Temperature",
    subject: "chemistry", category: "Solutions & Electrochemistry", classLevel: "class-11",
    axes: { x: "Temperature T", y: "Solubility (g/100 g water)" },
    basis: "Saturated-solution concentration measured across temperatures.",
    meaning: "Most solids dissolve more when hot; gases always dissolve less.",
    series: [
      { shape: "linearRise", label: "KNO₃ (steep)" },
      { shape: "linear", variant: 0.38, label: "NaCl (flat)", dashed: true },
    ],
    output: "Rising lines of different slopes; gas solubility falls instead. Steep curves suit recrystallisation purification.",
    specialCases: [
      { name: "Gases", condition: "dissolved gas", meaning: "Solubility FALLS with T (boiling drives gases out)." },
      { name: "Ca(OH)₂ exception", condition: "slaked lime", meaning: "Solubility decreases with temperature." },
      { name: "Recrystallisation", condition: "steep curve", meaning: "Cool a hot saturated solution to grow pure crystals." },
    ],
  },
  {
    id: "chem-atomic-radius-trend", slug: "atomic-radius-vs-z", name: "Periodic Trend: Atomic Radius vs Atomic Number",
    subject: "chemistry", category: "Periodic Trends", classLevel: "class-11",
    axes: { x: "Atomic number Z", y: "Atomic radius" },
    basis: "Covalent/metallic radii plotted across the periodic table sequence.",
    meaning: "Sawtooth: falls across a period (Z_eff rises), jumps down each new period (shell added).",
    series: [{ shape: "sawtooth", variant: 4 }],
    output: "Repeating downward slopes with sharp jumps at each alkali metal — the sawtooth signature of periodicity.",
    specialCases: [
      { name: "Across period", condition: "same shell filling", meaning: "Radius shrinks — stronger nuclear pull." },
      { name: "Down group", condition: "new shell", meaning: "Radius jumps up sharply." },
      { name: "Anions vs cations", condition: "isolectronic series", meaning: "More electrons = bigger; more protons = smaller." },
    ],
  },
  {
    id: "chem-ionization-energy-trend", slug: "ionization-energy-vs-z", name: "Periodic Trend: Ionization Energy vs Atomic Number",
    subject: "chemistry", category: "Periodic Trends", classLevel: "class-11",
    axes: { x: "Atomic number Z", y: "Ionization energy" },
    basis: "First ionization energies of the elements in sequence.",
    meaning: "Mirror of the radius trend: rises across periods, drops at each new period, with noble-gas peaks.",
    series: [{ shape: "sawtooth", variant: 5 }],
    output: "Sawtooth with noble gases at each peak and alkali metals at each valley — evidence for shell structure.",
    specialCases: [
      { name: "Noble gas peak", condition: "full shell", meaning: "Maximum IE — shells are real energy boundaries." },
      { name: "Be→B dip", condition: "subshell start", meaning: "2p electron easier to remove than 2s." },
      { name: "N→O dip", condition: "pairing repulsion", meaning: "Paired 2p electron leaves more easily." },
    ],
  },

  // ═══ BIOLOGY ═══
  {
    id: "bio-enzyme-temperature", slug: "enzyme-activity-vs-temperature", name: "Enzyme Activity vs Temperature",
    subject: "biology", category: "Enzymes & Metabolism", classLevel: "class-12",
    axes: { x: "Temperature", y: "Enzyme activity (rate)" },
    basis: "Reaction rate catalysed by an enzyme measured across temperatures.",
    meaning: "Rises with kinetic energy to an optimum, then denaturation destroys it.",
    series: [{ shape: "bell", variant: 8 }],
    marks: [{ x: 0.5, label: "optimum (~37°C human)", type: "vline" }],
    output: "Bell curve peaking at the optimum temperature; the falling side is steep because denaturation is not reversible.",
    specialCases: [
      { name: "Before optimum", condition: "Q₁₀ ≈ 2", meaning: "Rate roughly doubles per 10°C rise." },
      { name: "After optimum", condition: "denaturation", meaning: "Tertiary structure lost — activity collapses." },
      { name: "Thermophiles", condition: "bacterial enzymes", meaning: "Optimum shifted far right (70°C+)." },
    ],
  },
  {
    id: "bio-enzyme-ph", slug: "enzyme-activity-vs-ph", name: "Enzyme Activity vs pH",
    subject: "biology", category: "Enzymes & Metabolism", classLevel: "class-12",
    axes: { x: "pH", y: "Enzyme activity" },
    basis: "Same enzyme assayed across a pH range at constant temperature.",
    meaning: "Each enzyme has a narrow pH optimum from its charged-active-site chemistry.",
    series: [
      { shape: "bell", variant: 6, label: "pepsin (pH ~2)" },
      { shape: "bell", variant: 8, label: "trypsin (pH ~8)", dashed: true },
    ],
    output: "Two bells at different positions: pepsin peaks in acid (stomach), trypsin in alkali (intestine) — the pH environments of the gut.",
    specialCases: [
      { name: "Extreme pH", condition: "either side", meaning: "Ionic bonds of active site disrupted — denaturation." },
      { name: "Renaturation", condition: "mild pH return", meaning: "Some enzymes recover, unlike heat denaturation." },
    ],
  },
  {
    id: "bio-michaelis-menten", slug: "michaelis-menten-curve", name: "Michaelis–Menten: Rate vs Substrate Concentration",
    subject: "biology", category: "Enzymes & Metabolism", classLevel: "class-12",
    axes: { x: "[Substrate S]", y: "Initial rate v" },
    basis: "Initial rates measured while substrate concentration is increased at constant enzyme.",
    meaning: "Saturation kinetics: first-order in S at low S, zero-order (Vmax) at high S.",
    equation: "v = \\frac{V_{max}[S]}{K_M + [S]}",
    series: [{ shape: "saturate", variant: 7 }],
    marks: [{ x: 0.14, y: 0.5, label: "K_M (½Vmax)", type: "point" }],
    output: "Hyperbolic rise saturating at Vmax. K_M = substrate concentration giving half-Vmax — the enzyme's affinity measure (lower K_M = tighter binding).",
    specialCases: [
      { name: "Low [S]", condition: "[S] ≪ K_M", meaning: "Rate ∝ [S] — first-order region." },
      { name: "High [S]", condition: "[S] ≫ K_M", meaning: "All active sites busy — zero-order plateau." },
      { name: "Competitive inhibitor", condition: "K_M apparent ↑", meaning: "Curve shifts right; Vmax unchanged." },
    ],
  },
  {
    id: "bio-population-growth", slug: "population-growth-curves", name: "Population Growth: Exponential vs Logistic",
    subject: "biology", category: "Ecology & Populations", classLevel: "class-12",
    axes: { x: "Time t", y: "Population N" },
    basis: "Population size tracked under unlimited resources vs with a carrying capacity K.",
    meaning: "J-shaped boom vs S-shaped approach to environmental limits.",
    equation: "N_t = N_0e^{rt}, \\qquad \\frac{dN}{dt} = rN\\frac{K-N}{K}",
    series: [
      { shape: "expRise", variant: 3.2, label: "exponential (J)" },
      { shape: "sigmoid", variant: 9, label: "logistic (S)", dashed: true },
    ],
    marks: [{ x: 0.9, y: 0.85, label: "K", type: "hline" }],
    output: "J-curve climbing without limit; S-curve departing from it, decelerating and flattening at K. Steepest S-growth at K/2 (max sustainable yield).",
    specialCases: [
      { name: "Lag phase", condition: "early S-curve", meaning: "Small population still building up." },
      { name: "K/2 inflection", condition: "fisheries", meaning: "Maximum sustainable yield point." },
      { name: "Overshoot-crash", condition: "real populations", meaning: "J-curve followed by collapse when resources fail." },
    ],
  },
  {
    id: "bio-oxygen-dissociation", slug: "oxygen-haemoglobin-dissociation", name: "Oxygen–Haemoglobin Dissociation Curve",
    subject: "biology", category: "Physiology", classLevel: "class-12",
    axes: { x: "pO₂ (mm Hg)", y: "Hb saturation %" },
    basis: "Percentage saturation of haemoglobin measured against oxygen partial pressure.",
    meaning: "Sigmoid binding = cooperative loading in lungs, easy unloading in tissues.",
    series: [
      { shape: "sigmoid", variant: 8, label: "pH 7.4" },
      { shape: "sigmoid", variant: 8, label: "Bohr shift (low pH, CO₂)", dashed: true },
    ],
    marks: [
      { x: 0.85, y: 0.95, label: "lungs ~100 mm Hg", type: "point" },
      { x: 0.3, y: 0.55, label: "tissues ~40 mm Hg", type: "point" },
    ],
    output: "S-curve: shallow start, steep middle, plateau near 100%. Right-shifted curve (higher CO₂/temperature, lower pH) unloads O₂ more readily — the Bohr effect.",
    specialCases: [
      { name: "Bohr shift", condition: "active tissues", meaning: "Curve moves right — more O₂ delivered where needed." },
      { name: "Fetal Hb", condition: "left shift", meaning: "Higher affinity pulls O₂ across the placenta." },
      { name: "Myoglobin", condition: "hyperbolic", meaning: "Muscle store saturates early, releases at very low pO₂." },
    ],
  },
  {
    id: "bio-photosynthesis-light", slug: "photosynthesis-vs-light-intensity", name: "Photosynthesis vs Light Intensity",
    subject: "biology", category: "Physiology", classLevel: "class-12",
    axes: { x: "Light intensity", y: "Rate of photosynthesis" },
    basis: "Oxygen output (or CO₂ uptake) measured while light intensity is raised.",
    meaning: "Light-limited linear rise, then saturation when CO₂ or enzymes limit; crosses zero at compensation point.",
    series: [{ shape: "saturate", variant: 6 }],
    marks: [{ x: 0.16, y: 0.0, label: "compensation point", type: "point" }],
    output: "Rising curve that flattens at light saturation; extended below the axis to the compensation point where photosynthesis = respiration.",
    specialCases: [
      { name: "Compensation point", condition: "no net gas exchange", meaning: "Plant neither gains nor loses biomass — shade plants reach it at lower light." },
      { name: "CO₂ plateau", condition: "bright but CO₂-limited", meaning: "Adding CO₂ (not light) restores the rise." },
      { name: "Temperature interaction", condition: "hot + bright", meaning: "Photorespiration drags the curve down (C₃ plants)." },
    ],
  },
  {
    id: "bio-growth-curve", slug: "sigmoid-growth-curve", name: "Sigmoid Growth Curve (Organism/Culture)",
    subject: "biology", category: "Ecology & Populations", classLevel: "both",
    axes: { x: "Time", y: "Growth (size/number)" },
    basis: "Measured growth of an organism, bacterial culture or organ over time.",
    meaning: "Grand period of growth: slow start, exponential grand phase, stationary plateau.",
    series: [{ shape: "sigmoid", variant: 9 }],
    marks: [
      { x: 0.12, y: 0.12, label: "lag", type: "point" },
      { x: 0.5, y: 0.5, label: "log phase", type: "point" },
      { x: 0.9, y: 0.88, label: "stationary", type: "point" },
    ],
    output: "S-shape with three readable phases: lag (adjustment), log (fastest, constant doubling), stationary/senescence (limits reached).",
    specialCases: [
      { name: "Bacterial culture", condition: "OD measured", meaning: "Log phase used for inoculation — cells most uniform." },
      { name: "Growth rate plot", condition: "dW/dt vs t", meaning: "Bell-shaped derivative peaking in log phase." },
      { name: "Absolute vs relative", condition: "metrics", meaning: "Absolute rate peaks once; relative rate falls throughout." },
    ],
  },
];
