/**
 * Graph Bank — Mathematics: function families, conics, special functions.
 */

import type { GraphEntry } from "@/lib/graphs";

export const MATH_GRAPHS: GraphEntry[] = [
  {
    id: "math-constant", slug: "constant-function-graph", name: "Constant Function f(x) = c",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Output fixed for every input — the simplest possible function.",
    meaning: "No dependence on x; slope (derivative) is zero everywhere.",
    series: [{ shape: "constant" }],
    howToRead: { slope: "Zero — rate of change is 0" },
    output: "Horizontal line at height c. Domain ℝ, range {c}, no inverse.",
    specialCases: [
      { name: "Derivative", condition: "f'(x) = 0", meaning: "Constant functions are the stationary functions." },
      { name: "As a polynomial", condition: "degree 0", meaning: "Baseline for polynomial behaviour." },
    ],
  },
  {
    id: "math-linear", slug: "linear-function-graph", name: "Linear Function f(x) = mx + c",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Constant rate of change plotted — every straight line is a linear function.",
    meaning: "Slope m is the rate; c is the starting value.",
    series: [
      { shape: "linearRise", label: "m > 0" },
      { shape: "linearFall", label: "m < 0", dashed: true },
    ],
    howToRead: { slope: "m — rise over run", intercept: "c on the y-axis" },
    output: "Straight lines; m > 0 rises, m < 0 falls, |m| sets steepness. Lines cross at x = −c/m.",
    specialCases: [
      { name: "m = 0", condition: "horizontal", meaning: "Degenerates to a constant function." },
      { name: "Parallel lines", condition: "same m", meaning: "Equal slopes never meet." },
      { name: "Perpendicular", condition: "m₁m₂ = −1", meaning: "Negative-reciprocal slopes." },
    ],
  },
  {
    id: "math-quadratic", slug: "quadratic-parabola-graph", name: "Quadratic f(x) = ax² + bx + c (Parabola)",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Squared term dominates — the graph is a symmetric parabola.",
    meaning: "Vertex = minimum (a > 0) or maximum (a < 0); roots where it crosses the x-axis.",
    equation: "x_v = -\\frac{b}{2a}, \\quad D = b^2 - 4ac",
    series: [
      { shape: "parabola", label: "a > 0" },
      { shape: "parabolaDown", label: "a < 0", dashed: true },
    ],
    output: "U-shaped (a > 0) or ∩-shaped (a < 0); axis of symmetry x = −b/2a; discriminant decides 2/1/0 real roots.",
    specialCases: [
      { name: "D > 0", condition: "two roots", meaning: "Parabola cuts the x-axis twice." },
      { name: "D = 0", condition: "tangent", meaning: "Vertex touches the axis — repeated root." },
      { name: "Projectile link", condition: "physics", meaning: "Same shape as projectile trajectories." },
    ],
  },
  {
    id: "math-cubic", slug: "cubic-function-graph", name: "Cubic Function f(x) = ax³ + …",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Cube term dominating for large |x|.",
    meaning: "S-curve with up to two turning points and one to three real roots.",
    series: [{ shape: "cubic" }],
    output: "Reverse-S shape: from −∞ to +∞ (a > 0) with a local max and min between; always at least one real root.",
    specialCases: [
      { name: "Repeated root", condition: "touches axis", meaning: "Turning point sits ON the x-axis." },
      { name: "Point symmetry", condition: "inflection", meaning: "Cubics are symmetric about their inflection point." },
    ],
  },
  {
    id: "math-modulus", slug: "modulus-function-graph", name: "Modulus f(x) = |x|",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Absolute value flips the negative branch upward.",
    meaning: "Distance from zero — always non-negative, with a corner at the origin.",
    series: [{ shape: "vshape" }],
    output: "V-shape: slope −1 for x < 0, +1 for x > 0; non-differentiable at the corner.",
    specialCases: [
      { name: "Corner at 0", condition: "x = 0", meaning: "Left and right derivatives differ — no derivative there." },
      { name: "Shifted modulus", condition: "|x − a|", meaning: "V slides to corner at a." },
    ],
  },
  {
    id: "math-sqrt", slug: "square-root-graph", name: "Square Root f(x) = √x",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Principal square root defined for x ≥ 0.",
    meaning: "Rapid initial rise, then slowing — the mirror of the parabola's right branch.",
    series: [{ shape: "sqrt" }],
    output: "Half-parabola on its side starting at the origin; vertical tangent at x = 0 (infinite slope), domain [0, ∞).",
    specialCases: [
      { name: "Vertical tangent", condition: "x → 0⁺", meaning: "Derivative 1/2√x → ∞." },
      { name: "Inverse pairing", condition: "y = x² (x ≥ 0)", meaning: "√x is its mirror across y = x." },
    ],
  },
  {
    id: "math-reciprocal", slug: "reciprocal-function-graph", name: "Reciprocal f(x) = 1/x",
    subject: "mathematics", category: "Algebraic Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Inverse proportion plotted — product xy constant.",
    meaning: "Two branches; asymptotes are the axes themselves.",
    series: [{ shape: "hyperbola" }],
    output: "Rectangular hyperbola in quadrants I and III; x = 0 and y = 0 asymptotes — the shape of Boyle's law and capacitive reactance.",
    specialCases: [
      { name: "Never crosses axes", condition: "x ≠ 0", meaning: "No intercepts; asymptotic behaviour instead." },
      { name: "Inverse variation", condition: "xy = k", meaning: "Doubling x halves y." },
      { name: "k negative", condition: "quadrants II & IV", meaning: "Branches flip across the origin." },
    ],
  },
  {
    id: "math-exponential", slug: "exponential-function-graph", name: "Exponential f(x) = aˣ",
    subject: "mathematics", category: "Transcendental Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Growth/decay by constant multiplicative factor per unit x.",
    meaning: "The mathematics of compound growth, decay and half-life.",
    series: [
      { shape: "expRise", variant: 4, label: "a > 1" },
      { shape: "expDecay", variant: 4, label: "0 < a < 1", dashed: true },
    ],
    howToRead: { intercept: "Always passes (0, 1)" },
    output: "a > 1: explosive rise, asymptote y = 0 below. 0 < a < 1: mirror decay. Always above the x-axis, always through (0,1).",
    specialCases: [
      { name: "y = 0 asymptote", condition: "x → −∞", meaning: "Never reaches zero — half-life logic." },
      { name: "eˣ", condition: "natural base", meaning: "Slope equals value everywhere — unique property." },
      { name: "Doubling time", condition: "a = 2", meaning: "Constant doubling interval." },
    ],
  },
  {
    id: "math-logarithm", slug: "logarithmic-function-graph", name: "Logarithmic f(x) = logₐx",
    subject: "mathematics", category: "Transcendental Functions", classLevel: "class-11",
    axes: { x: "x", y: "f(x)" },
    basis: "Inverse of the exponential — answers 'what power?'",
    meaning: "Slow growth; compresses wide-ranging data (pH, decibels, Richter).",
    series: [{ shape: "log" }],
    output: "Rising curve through (1, 0) with the y-axis as vertical asymptote; defined only for x > 0; mirror of aˣ across y = x.",
    specialCases: [
      { name: "x = 1 intercept", condition: "log 1 = 0", meaning: "Every log curve passes (1, 0)." },
      { name: "Vertical asymptote", condition: "x → 0⁺", meaning: "f → −∞ — logs of tiny numbers are hugely negative." },
      { name: "Change of base", condition: "vertical stretch", meaning: "Different bases scale the same curve." },
    ],
  },
  {
    id: "math-sine", slug: "sine-graph", name: "Sine f(x) = sin x",
    subject: "mathematics", category: "Transcendental Functions", classLevel: "class-11",
    axes: { x: "x (radians)", y: "sin x" },
    basis: "Vertical coordinate of a point rotating on the unit circle.",
    meaning: "The prototype oscillation — waves, AC voltage, SHM.",
    series: [{ shape: "sine" }],
    howToRead: { slope: "cos x — the derivative" },
    output: "Periodic wave of period 2π, amplitude 1, range [−1, 1]; zero at multiples of π, peaks at π/2 + 2πn.",
    specialCases: [
      { name: "Amplitude scaling", condition: "A sin x", meaning: "Stretches vertically — wave energy ∝ A²." },
      { name: "Frequency change", condition: "sin bx", meaning: "Period 2π/b — b is the angular frequency." },
      { name: "Small-angle", condition: "sin x ≈ x", meaning: "Linear near the origin — SHM foundation." },
    ],
  },
  {
    id: "math-cosine", slug: "cosine-graph", name: "Cosine f(x) = cos x",
    subject: "mathematics", category: "Transcendental Functions", classLevel: "class-11",
    axes: { x: "x (radians)", y: "cos x" },
    basis: "Horizontal coordinate of the unit-circle point — sine shifted by π/2.",
    meaning: "Same wave, quarter-period lead; starts at maximum.",
    series: [{ shape: "cosine" }],
    output: "Identical wave to sine shifted left π/2; peaks at 2πn, zeros at π/2 + πn — the SHM velocity curve.",
    specialCases: [
      { name: "Even function", condition: "cos(−x) = cos x", meaning: "Mirror-symmetric about the y-axis." },
      { name: "Phase relation", condition: "sin(x + π/2) = cos x", meaning: "SHM velocity leads displacement." },
    ],
  },
  {
    id: "math-tangent", slug: "tangent-graph", name: "Tangent f(x) = tan x",
    subject: "mathematics", category: "Transcendental Functions", classLevel: "class-11",
    axes: { x: "x (radians)", y: "tan x" },
    basis: "Ratio sin/cos — blows up wherever cos = 0.",
    meaning: "Discontinuous periodic branches with vertical asymptotes.",
    series: [{ shape: "tangent" }],
    output: "Repeating S-branches between asymptotes at x = π/2 + πn; period π, range (−∞, ∞), no amplitude.",
    specialCases: [
      { name: "Period π", condition: "half of sine's", meaning: "tan repeats twice as often." },
      { name: "Asymptotes", condition: "cos x = 0", meaning: "Odd multiples of π/2." },
      { name: "General values", condition: "θ = nπ + α", meaning: "Basis of trig-equation solution families." },
    ],
  },
  {
    id: "math-step", slug: "step-function-graph", name: "Greatest Integer f(x) = [x] (Step)",
    subject: "mathematics", category: "Special Functions", classLevel: "class-11",
    axes: { x: "x", y: "[x]" },
    basis: "Output jumps to the greatest integer ≤ x.",
    meaning: "Quantises a continuous input into integer levels — tax slabs, postage tiers.",
    series: [{ shape: "step" }],
    output: "Staircase of horizontal segments with open/closed endpoints; discontinuous at every integer.",
    specialCases: [
      { name: "Jump discontinuities", condition: "every integer", meaning: "Function value leaps — no limits agree." },
      { name: "Applications", condition: "billing", meaning: "Any 'per completed unit' pricing is a step function." },
    ],
  },
  {
    id: "math-circle", slug: "circle-graph", name: "Circle x² + y² = r²",
    subject: "mathematics", category: "Conic Sections", classLevel: "class-11",
    axes: { x: "x", y: "y" },
    basis: "Locus of points at fixed distance r from the centre.",
    meaning: "The conic with eccentricity 0 — perfect symmetry, no focus offset.",
    series: [{ shape: "circle" }],
    output: "Closed round curve centred at origin (or (h,k) after translation); fails the vertical line test — a relation, not a function.",
    specialCases: [
      { name: "Parametric", condition: "r cosθ, r sinθ", meaning: "Bridges to trigonometry." },
      { name: "Great circles", condition: "3D", meaning: "Sections of spheres — navigation geometry." },
    ],
  },
  {
    id: "math-ellipse", slug: "ellipse-graph", name: "Ellipse x²/a² + y²/b² = 1",
    subject: "mathematics", category: "Conic Sections", classLevel: "class-11",
    axes: { x: "x", y: "y" },
    basis: "Sum of distances to two foci constant — stretched circle.",
    meaning: "Eccentricity 0 < e < 1; the orbit shape of planets.",
    series: [{ shape: "ellipse" }],
    output: "Squashed circle with semi-axes a (horizontal) and b (vertical); two foci inside; area πab.",
    specialCases: [
      { name: "a = b", condition: "becomes circle", meaning: "foci merge at the centre." },
      { name: "Kepler's first law", condition: "planetary orbits", meaning: "Sun at one focus." },
    ],
  },
  {
    id: "math-hyperbola-conic", slug: "hyperbola-graph", name: "Hyperbola x²/a² − y²/b² = 1",
    subject: "mathematics", category: "Conic Sections", classLevel: "class-11",
    axes: { x: "x", y: "y" },
    basis: "Difference of distances to two foci constant.",
    meaning: "Eccentricity e > 1; two open branches with asymptote box.",
    series: [{ shape: "sideHyperbola" }],
    output: "Left and right branches opening outward, guided by asymptotes y = ±(b/a)x; appears in lens equations and inverse-square comparisons.",
    specialCases: [
      { name: "Asymptotes", condition: "y = ±(b/a)x", meaning: "Branches approach but never touch." },
      { name: "Rectangular hyperbola", condition: "a = b", meaning: "Asymptotes perpendicular — the 1/x curve." },
      { name: "Navigation", condition: "LORAN", meaning: "Constant-difference loci are hyperbolas." },
    ],
  },
  {
    id: "math-inverse-trig", slug: "inverse-trigonometric-graphs", name: "Inverse Trigonometric: sin⁻¹x & cos⁻¹x",
    subject: "mathematics", category: "Special Functions", classLevel: "class-12",
    axes: { x: "x", y: "f(x)" },
    basis: "Trig functions restricted to principal branches, then inverted.",
    meaning: "Converts ratios back to angles — the angle-finding curves.",
    series: [
      { shape: "sigmoid", variant: 8, label: "sin⁻¹x (range −π/2..π/2)" },
      { shape: "sigmoidDown", variant: 8, label: "cos⁻¹x", dashed: true },
    ],
    output: "S-shaped curves on domain [−1, 1]; sin⁻¹ rises from −π/2 to π/2, cos⁻¹ falls from π to 0 — they sum to π/2 everywhere.",
    specialCases: [
      { name: "Principal branches", condition: "why ranges limited", meaning: "Makes the inverse a true function." },
      { name: "Complementary sum", condition: "sin⁻¹x + cos⁻¹x = π/2", meaning: "Graphs mirror around y = π/4." },
    ],
  },
];
