/**
 * Graph Bank — Physics 1: Motion, Thermodynamics, Gravitation.
 */

import type { GraphEntry } from "@/lib/graphs";

export const PHYSICS_GRAPHS: GraphEntry[] = [
  {
    id: "phy-displacement-time", slug: "displacement-time-graph", name: "Displacement–Time (s–t) Graph",
    subject: "physics", category: "Motion (Kinematics)", classLevel: "class-11",
    axes: { x: "Time t", y: "Displacement s" },
    basis: "Body's position read against a fixed origin at every instant of time.",
    meaning: "Shows WHERE the body is at every moment; its slope is the velocity.",
    equation: "s = ut + \\tfrac{1}{2}at^2",
    series: [
      { shape: "constant", label: "at rest" },
      { shape: "linearRise", label: "uniform velocity" },
      { shape: "expRise", variant: 3, label: "accelerated" },
    ],
    howToRead: { slope: "Velocity (steeper = faster; negative slope = returning)", intercept: "Initial position" },
    output: "Horizontal line (rest), straight tilted line (uniform v), upward-bending curve (acceleration). Slope at any point = instantaneous velocity.",
    specialCases: [
      { name: "Horizontal line", condition: "s constant", meaning: "Body at rest, however long the time." },
      { name: "Curved upward", condition: "a > 0", meaning: "Slope (velocity) grows with time." },
      { name: "Curve peaking then falling", condition: "upward throw", meaning: "Peak = highest point; falling branch = return." },
    ],
    traps: ["A curved s–t graph does NOT mean curved path — motion is still along a line."],
  },
  {
    id: "phy-velocity-time", slug: "velocity-time-graph", name: "Velocity–Time (v–t) Graph",
    subject: "physics", category: "Motion (Kinematics)", classLevel: "class-11",
    axes: { x: "Time t", y: "Velocity v" },
    basis: "Velocity of the body plotted against time for uniform acceleration.",
    meaning: "The master graph of kinematics: slope gives acceleration, area gives displacement.",
    equation: "v = u + at",
    series: [{ shape: "linearRise", label: "uniform acceleration" }, { shape: "constant", label: "uniform velocity" }],
    howToRead: { slope: "Acceleration", area: "Displacement", intercept: "Initial velocity u" },
    output: "Straight line of slope a starting at u. Area trapped between line and t-axis = displacement; the t-intercept of a falling line gives stopping time.",
    specialCases: [
      { name: "Line crossing t-axis", condition: "deceleration to rest", meaning: "Body reverses direction at the crossing." },
      { name: "Area below axis", condition: "v negative", meaning: "Displacement in the negative direction." },
      { name: "Two bodies, different slopes", condition: "meeting problems", meaning: "Equal areas = equal displacements; intersection = equal velocities." },
    ],
    traps: ["Area gives displacement, NOT distance, when v changes sign."],
  },
  {
    id: "phy-acceleration-time", slug: "acceleration-time-graph", name: "Acceleration–Time (a–t) Graph",
    subject: "physics", category: "Motion (Kinematics)", classLevel: "class-11",
    axes: { x: "Time t", y: "Acceleration a" },
    basis: "Rate of change of velocity plotted against time.",
    meaning: "Area under the curve gives the change in velocity.",
    equation: "\\Delta v = \\int a\\,dt",
    series: [{ shape: "constant", label: "uniform acceleration" }],
    howToRead: { area: "Change in velocity Δv" },
    output: "Flat line for constant a (area = a·t = Δv); spikes for impulsive events.",
    specialCases: [
      { name: "Zero line", condition: "a = 0", meaning: "Velocity constant (uniform motion)." },
      { name: "Rectangular pulse", condition: "brief acceleration", meaning: "Pulse area = the velocity gained." },
    ],
  },
  {
    id: "phy-projectile-trajectory", slug: "projectile-trajectory", name: "Projectile Trajectory (y–x)",
    subject: "physics", category: "Motion (Kinematics)", classLevel: "class-11",
    axes: { x: "Horizontal distance x", y: "Height y" },
    basis: "Vertical position plotted against horizontal for a body under gravity with launch angle θ.",
    meaning: "The flight path is a parabola; symmetric for equal launch/landing heights.",
    equation: "y = x\\tan\\theta - \\frac{gx^2}{2u^2\\cos^2\\theta}",
    series: [{ shape: "parabolaDown" }],
    marks: [{ x: 0.5, y: 0.75, label: "H max", type: "point" }],
    howToRead: { slope: "Direction of velocity at that point" },
    output: "Symmetric parabola; vertex at maximum height H = u²sin²θ/2g; horizontal range R = u²sin2θ/g — maximum at θ = 45°.",
    specialCases: [
      { name: "θ = 45°", condition: "maximum range", meaning: "Range = 4 × max height." },
      { name: "θ and 90°−θ", condition: "complementary angles", meaning: "Same range, different heights." },
      { name: "Horizontal launch", condition: "θ = 0 from height h", meaning: "Half-parabola starting at the tower top." },
    ],
  },
  {
    id: "phy-shm-graphs", slug: "shm-graphs", name: "SHM: Displacement, Velocity & Acceleration vs Time",
    subject: "physics", category: "Motion (Kinematics)", classLevel: "both",
    axes: { x: "Time t", y: "x, v, a" },
    basis: "Simple harmonic motion x = A sin ωt with velocity and acceleration as its derivatives.",
    meaning: "Shows the 90° phase lags: v leads x by π/2, a is antiphase with x.",
    equation: "x = A\\sin\\omega t,\\ v = A\\omega\\cos\\omega t,\\ a = -\\omega^2 x",
    series: [
      { shape: "sine", label: "x" },
      { shape: "cosine", label: "v", dashed: true },
    ],
    howToRead: { slope: "v = slope of x–t; a = slope of v–t" },
    output: "Same-period sine curves shifted by quarter periods; acceleration is the mirror (inverted) copy of displacement.",
    specialCases: [
      { name: "x = 0", condition: "mean position", meaning: "Speed maximum, acceleration zero." },
      { name: "x = ±A", condition: "extremes", meaning: "Speed zero, acceleration maximum." },
      { name: "a antiphase x", condition: "restoring nature", meaning: "Signature of SHM: a = −ω²x." },
    ],
  },
  {
    id: "phy-isothermal-adiabatic", slug: "isothermal-adiabatic-pv", name: "Isothermal vs Adiabatic (p–V)",
    subject: "physics", category: "Heat & Thermodynamics", classLevel: "both",
    axes: { x: "Volume V", y: "Pressure p" },
    basis: "Gas pressure as volume changes at constant temperature (isothermal) or with no heat exchange (adiabatic).",
    meaning: "Compression raises pressure; the adiabatic curve is steeper because temperature also rises.",
    equation: "pV = \\text{const}, \\qquad pV^{\\gamma} = \\text{const}",
    series: [
      { shape: "hyperbola", label: "isothermal" },
      { shape: "sideHyperbola", label: "adiabatic (γ > 1)", dashed: true },
    ],
    howToRead: { area: "Work done by the gas" },
    output: "Both fall as 1/V-type curves; the adiabatic (pV^γ) lies above and is steeper. Area under the curve = work done in the process.",
    specialCases: [
      { name: "Slopes at a point", condition: "comparing", meaning: "Adiabatic slope = γ × isothermal slope." },
      { name: "Work comparison", condition: "same ΔV", meaning: "Isothermal expansion does more work (larger area)." },
      { name: "Cyclic loop", condition: "engine cycle", meaning: "Enclosed area = net work per cycle." },
    ],
    traps: ["Adiabatic is steeper, not shallower — a favourite true/false trap."],
  },
  {
    id: "phy-isobaric-isochoric", slug: "isobaric-isochoric-pv", name: "Isobaric & Isochoric Processes (p–V)",
    subject: "physics", category: "Heat & Thermodynamics", classLevel: "both",
    axes: { x: "Volume V", y: "Pressure p" },
    basis: "Constant-pressure and constant-volume lines on the p–V diagram.",
    meaning: "Defines the two simplest processes and their (zero or maximal) work.",
    series: [
      { shape: "constant", label: "isobaric (p const)" },
      { shape: "resonancePeak", variant: 0.001, label: "isochoric (V const)" },
    ],
    howToRead: { area: "Isobaric: W = pΔV; isochoric: zero work" },
    output: "Isobaric = horizontal line (area under it = pΔV work). Isochoric = vertical line — zero area, zero work.",
    specialCases: [
      { name: "Isochoric", condition: "V constant", meaning: "All heat goes into internal energy (W = 0)." },
      { name: "Isobaric", condition: "p constant", meaning: "Heat splits between ΔU and work." },
    ],
  },
  {
    id: "phy-newton-cooling-graph", slug: "newtons-cooling-graph", name: "Newton's Law of Cooling (T–t)",
    subject: "physics", category: "Heat & Thermodynamics", classLevel: "class-11",
    axes: { x: "Time t", y: "Temperature T" },
    basis: "Hot body's temperature recorded as it cools in surroundings at T_s.",
    meaning: "Excess temperature decays exponentially; rate of cooling ∝ excess.",
    equation: "T = T_s + (T_0 - T_s)e^{-kt}",
    series: [{ shape: "expDecayToFloor" }],
    marks: [{ x: 0, y: 0.06, label: "T_s", type: "hline" }],
    howToRead: { slope: "Rate of cooling (steepest when hottest)" },
    output: "Steep fall flattening asymptotically onto the surroundings temperature T_s. Plot of log(T−T_s) vs t is a straight line.",
    specialCases: [
      { name: "Steep start", condition: "large excess", meaning: "Cooling fastest at the beginning." },
      { name: "Linear log plot", condition: "verification", meaning: "Confirms the exponential law; slope gives k." },
      { name: "Small excess only", condition: "validity", meaning: "Law holds for ΔT ≲ 30–40 K." },
    ],
  },
  {
    id: "phy-g-variation", slug: "g-vs-height-depth", name: "Variation of g with Height & Depth",
    subject: "physics", category: "Gravitation", classLevel: "class-11",
    axes: { x: "Distance from surface", y: "g" },
    basis: "Surface gravity compared moving upward (height h) or downward (depth d).",
    meaning: "g falls with the SQUARE of distance upward but LINEARLY with depth.",
    equation: "g_h = g\\left(\\frac{R}{R+h}\\right)^2, \\qquad g_d = g\\left(1 - \\frac{d}{R}\\right)",
    series: [
      { shape: "expDecay", variant: 2.2, label: "upward (height)" },
      { shape: "linearFall", label: "downward (depth)", dashed: true },
    ],
    output: "Upward curve: rapid inverse-square fall. Downward: straight line reaching zero at the centre (g = 0 at Earth's centre).",
    specialCases: [
      { name: "At centre", condition: "d = R", meaning: "g = 0 — Earth pulls equally in all directions." },
      { name: "h ≪ R", condition: "near surface", meaning: "Both reduce to ~g(1 − 2h/R) vs g(1 − d/R)." },
      { name: "Same fraction loss", condition: "h = d small", meaning: "g falls about TWICE as fast with height as with depth." },
    ],
  },
  {
    id: "phy-thermal-expansion-graph", slug: "length-vs-temperature", name: "Thermal Expansion: Length vs Temperature",
    subject: "physics", category: "Heat & Thermodynamics", classLevel: "class-11",
    axes: { x: "Temperature T", y: "Length L" },
    basis: "Solid rod's length measured as temperature rises uniformly.",
    meaning: "Linear expansion: length grows in direct proportion to temperature change.",
    equation: "L = L_0(1 + \\alpha\\,\\Delta T)",
    series: [{ shape: "linear" }],
    howToRead: { slope: "L₀α — proportional to the expansion coefficient" },
    output: "Straight line; steeper slope = larger coefficient α (aluminium > steel > invar ≈ 0). Extrapolating back to zero length gives −1/α (physically unreachable).",
    specialCases: [
      { name: "Slope comparison", condition: "different metals", meaning: "Steeper line = bigger α." },
      { name: "Invar alloy", condition: "α ≈ 0", meaning: "Nearly horizontal line — used in pendulum clocks." },
      { name: "Area & volume", condition: "β = 2α, γ = 3α", meaning: "Same linear graph logic scaled." },
    ],
  },
];
