// NEB (+2) lab catalog — metadata for the /lab/ visualization & measurement labs.
//
// Hierarchy:  hub  →  unit  →  concept
//   - Biology & Heat-Determinations: 2 levels (hub → unit/concept sub-labs)
//   - Physics & Chemistry: 3 levels  (hub → unit → concept)
//
// `type` tells the reader what the lab is FOR:
//   - "theory"    → 3D / concept-visualization lab
//   - "practical" → numerical measurement / wet-lab experiment (apparatus + procedure + result)

export type LabType = "theory" | "practical";
export type LabLevel = "hub" | "unit" | "concept";

export type LabRelatedLink = {
  label: string;
  href: string;
};

export type LabEntry = {
  id: string;
  title: string;
  subject: string; // "Biology" | "Physics" | "Chemistry"
  type: LabType;
  level: LabLevel;
  /** id of the parent entry (null for a hub). */
  parent: string | null;
  /** Route relative to /lab, e.g. "physics/measurement-mechanics/vernier-screw-gauge". */
  route: string;
  tagline: string;
  purpose: string;
  concepts?: string[];
  observations?: string[];
  apparatus?: string[];
  procedure?: string[];
  result?: string;
  related?: LabRelatedLink[];
};

const BIO_REL: LabRelatedLink[] = [
  { label: "Biology practical write-ups", href: "/practical/biology" },
  { label: "Biology syllabus", href: "/syllabus/biology" },
];
const PHY_REL: LabRelatedLink[] = [
  { label: "Physics practical write-ups", href: "/practical/physics" },
  { label: "Physics syllabus", href: "/syllabus/physics" },
];
const CHEM_REL: LabRelatedLink[] = [
  { label: "Chemistry practical write-ups", href: "/practical/chemistry" },
  { label: "Chemistry syllabus", href: "/syllabus/chemistry" },
];

export const LABS: Record<string, LabEntry> = {
  /* ================= BIOLOGY (hub → 10 sub-labs, all theory) ================= */
  "biology": {
    id: "biology",
    title: "Biology 3D Labs",
    subject: "Biology",
    type: "theory",
    level: "hub",
    parent: null,
    route: "biology",
    tagline: "Interactive 3D theory labs for NEB Class 11 & 12 Biology.",
    purpose:
      "A hub of concept-exploration labs — cell structure, cell division, biodiversity, ecosystems and evolution. These are visualization (theory) labs, not wet-lab practicals; pair them with the Biology practical write-ups for the experimental side.",
    related: [
      { label: "Biology practical write-ups", href: "/practical/biology" },
      { label: "Biology syllabus", href: "/syllabus/biology" },
    ],
  },

  "cell-3d": {
    id: "cell-3d",
    title: "Cell 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/cell-3d",
    tagline: "Interactive 3D explorer of eukaryotic and prokaryotic cells.",
    purpose:
      "Understand cell structure, organelle function and the plant/animal differences that NEB Biology Class 11 expects.",
    concepts: ["Nucleus & nucleolus", "Mitochondria (ATP production)", "Ribosomes (protein synthesis)", "Endoplasmic reticulum & Golgi body", "Cell wall vs cell membrane", "Prokaryote vs eukaryote"],
    observations: ["Identify each organelle by its 3D shape", "Compare a plant cell (wall, chloroplast, large vacuole) vs an animal cell", "Trace the endomembrane pathway from ER to membrane"],
    related: BIO_REL,
  },
  "cell-division-3d": {
    id: "cell-division-3d",
    title: "Cell Division 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/cell-division-3d",
    tagline: "Step-through 3D animation of mitosis and meiosis.",
    purpose: "Grasp the stages of cell division, chromosome behaviour and why meiosis produces variation — core to the NEB genetics unit.",
    concepts: ["Interphase, prophase, metaphase, anaphase, telophase", "Cytokinesis", "Mitosis vs meiosis", "Crossing over / recombination", "Chromosome : chromatid counting"],
    observations: ["Follow sister chromatids separating in mitosis", "Watch homologues pair (synapsis) in meiosis I", "Observe recombination during prophase I"],
    related: BIO_REL,
  },
  "floral-3d": {
    id: "floral-3d",
    title: "Floral Diversity 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/floral-3d",
    tagline: "3D model of flower morphology and angiosperm family characters.",
    purpose: "Learn to key plant families by floral characters — sepal/petal number, symmetry and stamen fusion — the basis of NEB floral-diversity work.",
    concepts: ["Floral symmetry (actinomorphic / zygomorphic)", "Perianth: sepals & petals", "Androecium & gynoecium", "Placentation", "Family keys: Brassicaceae, Fabaceae, Solanaceae, Liliaceae"],
    observations: ["Count the whorls; note fused vs free parts", "Match a flower to its family using the key", "Spot zygomorphic (pea-like) symmetry in Fabaceae"],
    related: BIO_REL,
  },
  "faunal-3d": {
    id: "faunal-3d",
    title: "Faunal Diversity 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/faunal-3d",
    tagline: "3D tour of animal phyla and their key identifying characters.",
    purpose: "Recognize phylum-level features used in NEB taxonomy questions — symmetry, body plan and organ systems.",
    concepts: ["Symmetry: radial, bilateral, none", "Body cavities (a-/eu-coelom)", "Metamerism / segmentation", "Skeletal systems", "Representative phyla: Porifera, Annelida, Arthropoda, Chordata"],
    observations: ["Compare a hydract (radial) vs an earthworm (bilateral)", "Locate the coelom", "Match a specimen to its phylum by character set"],
    related: BIO_REL,
  },
  "biota-3d": {
    id: "biota-3d",
    title: "Biota 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/biota-3d",
    tagline: "3D biodiversity and taxonomy framework.",
    purpose: "Build the classification hierarchy and understand biodiversity and taxonomic ranking for the NEB biodiversity unit.",
    concepts: ["Taxonomic ranks: kingdom → species", "Binomial nomenclature", "Phylogeny basics", "Biodiversity levels: genetic, species, ecosystem"],
    observations: ["Place an organism up the ranks", "Read a scientific name (genus + species)", "See how clades nest inside each other"],
    related: BIO_REL,
  },
  "biomolecules-3d": {
    id: "biomolecules-3d",
    title: "Biomolecules 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/biomolecules-3d",
    tagline: "3D structures of the four classes of biomolecules.",
    purpose: "Visualize monomer → polymer for carbohydrates, lipids, proteins and nucleic acids (Biology 301 biomolecules unit).",
    concepts: ["Monomers: monosaccharide, amino acid, fatty acid, nucleotide", "Polymerization & condensation", "Primary protein structure", "DNA vs RNA nucleotides"],
    observations: ["Watch a condensation link two monomers", "Fold an amino acid into secondary structure", "Compare deoxyribose vs ribose"],
    related: BIO_REL,
  },
  "micro-3d": {
    id: "micro-3d",
    title: "Microbiology 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/micro-3d",
    tagline: "3D look at microbes: bacteria, viruses and fungi.",
    purpose: "Understand the prokaryotic cell, viral structure and the microbial agents behind the NEB introductory-microbiology unit.",
    concepts: ["Prokaryote vs eukaryote cell", "Bacterial morphology (coccus, bacillus)", "Viral capsid & envelope", "Symbiosis & parasitism"],
    observations: ["Spot the nucleoid (no membrane-bound nucleus)", "Compare a bacterium vs a virus in size", "See the host-infection steps of a virus"],
    related: BIO_REL,
  },
  "ecology-3d": {
    id: "ecology-3d",
    title: "Ecology 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/ecology-3d",
    tagline: "3D ecosystem model: food webs, energy flow and cycles.",
    purpose: "Model producers, consumers and decomposers plus nutrient & energy flow, which underpin the NEB ecology practicals.",
    concepts: ["Trophic levels & food chains / webs", "Energy pyramid (10% rule)", "Biogeochemical cycles (C, N, H₂O)", "Biotic vs abiotic factors"],
    observations: ["Trace energy from producers to the apex", "Follow one carbon or nitrogen cycle", "Remove a species and watch the web shift"],
    related: BIO_REL,
  },
  "evolution-3d": {
    id: "evolution-3d",
    title: "Evolution 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/evolution-3d",
    tagline: "3D visualizations of natural selection and speciation.",
    purpose: "Explain the evidence and mechanisms of evolution for the NEB evolution unit.",
    concepts: ["Natural selection & adaptation", "Antibiotic resistance", "Genetic drift vs selection", "Fossils & comparative anatomy as evidence"],
    observations: ["Simulate selection on a trait over generations", "Compare homologous structures", "Track an allele frequency changing"],
    related: BIO_REL,
  },
  "conservation-3d": {
    id: "conservation-3d",
    title: "Conservation 3D",
    subject: "Biology",
    type: "theory",
    level: "unit",
    parent: "biology",
    route: "biology/conservation-3d",
    tagline: "3D model of threatened ecosystems and conservation strategies.",
    purpose: "Understand threats to biodiversity and conservation approaches for the NEB ecology / conservation themes.",
    concepts: ["Habitat loss, extinction & biodiversity value", "In-situ vs ex-situ conservation", "Endangered species & reserves"],
    observations: ["Map a threatened habitat", "Compare a sanctuary vs captive breeding", "Assess the impact of habitat fragmentation"],
    related: BIO_REL,
  },

  /* ============ HEAT DETERMINATIONS (hub → 4 sub-labs, all practical) ============ */
  "heat-determinations": {
    id: "heat-determinations",
    title: "Heat Determination Experiments",
    subject: "Physics",
    type: "practical",
    level: "hub",
    parent: null,
    route: "heat-determinations",
    tagline: "Physics measurement labs for thermal properties.",
    purpose:
      "A hub of numerical practical experiments that determine thermal constants (K, α, cooling constant). Each has apparatus, procedure and expected result; full write-ups live in the Physics practical syllabus.",
    related: [
      { label: "Physics practical write-ups", href: "/practical/physics" },
      { label: "Physics syllabus", href: "/syllabus/physics" },
    ],
  },
  "lees-disc": {
    id: "lees-disc",
    title: "Lees' Disc — Thermal Conductivity",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "heat-determinations",
    route: "heat-determinations/lees-disc",
    tagline: "Steady-state experiment to find the thermal conductivity K of a metal disc.",
    purpose: "Determine K by balancing heat flow through a disc against its radiative loss — a Class 12 heat-determination practical.",
    concepts: ["Steady state & heat flow Q/t", "Disc geometry (area A, thickness d)", "Radiative & convective losses", "Graphical determination of the cooling slope"],
    apparatus: ["Metal disc of known area A and thickness d", "Heater plate with thermometer", "Stopwatch", "Graph paper"],
    procedure: ["Heat the disc to a steady temperature above ambient", "Remove it from the heater; cool it; record T every 5 s", "Plot the cooling curve T vs t", "Find dT/dt at the steady temperature and solve the heat-balance for K"],
    result: "Thermal conductivity K reported in W m⁻¹ K⁻¹.",
    related: PHY_REL,
  },
  "linear-expansion": {
    id: "linear-expansion",
    title: "Linear Expansion — Coefficient of Expansion",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "heat-determinations",
    route: "heat-determinations/linear-expansion",
    tagline: "Find the coefficient of linear expansion α of a metal rod.",
    purpose: "Measure ΔL over a known ΔT to obtain α — a standard Class 11/12 practical.",
    concepts: ["α = ΔL / (L₀ · ΔT)", "Optical-lever / vernier magnification", "Thermal equilibrium & lag", "Correction to a reference temperature"],
    apparatus: ["Metal rod of length L₀", "Heating bath / flame", "Vernier or optical-lever arrangement", "Thermometer"],
    procedure: ["Note the initial reading L₀ at temperature T₀", "Heat steadily to T; take the final reading L₁", "Compute ΔL, correcting for any lever magnification", "Find α = ΔL / (L₀ · ΔT)"],
    result: "Coefficient of linear expansion α in K⁻¹ (order 10⁻⁵ K⁻¹ for metals).",
    related: PHY_REL,
  },
  "newton-cooling": {
    id: "newton-cooling",
    title: "Newton's Law of Cooling",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "heat-determinations",
    route: "heat-determinations/newton-cooling",
    tagline: "Verify Newton's law of cooling by plotting the cooling curve.",
    purpose: "Confirm that the rate of cooling is proportional to the excess temperature; plot θ–t and find the time constant.",
    concepts: ["dθ/dt = −k (θ − θ₀)", "Exponential decay", "Log-linear plot of ln(θ − θ₀)", "Effect of surface & air flow"],
    apparatus: ["Hot body / vessel of hot water", "Thermometer", "Stopwatch", "Ambient temperature θ₀"],
    procedure: ["Record θ at fixed intervals until near room temperature", "Plot θ vs t", "Plot ln(θ − θ₀) vs t → a straight line whose slope is −k"],
    result: "Linearity verifies Newton's law; k is the cooling constant.",
    related: PHY_REL,
  },
  "searles-bar": {
    id: "searles-bar",
    title: "Searle's Bar — Thermal Conductivity",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "heat-determinations",
    route: "heat-determinations/searles-bar",
    tagline: "Searle's method to find the thermal conductivity K of a metal rod.",
    purpose: "Measure heat conducted through a rod at steady state against end losses — a Class 12 heat-determination.",
    concepts: ["Steady-state heat flow", "Thermometer gradient along the rod", "End correction & insulation", "K = P·l / (A·ΔT·t)"],
    apparatus: ["Searle's apparatus (rod with thermometer holes)", "Water / steam bath", "Thermometers", "Balance / micrometer for dimensions"],
    procedure: ["Heat the rod end to steady state; read two thermometers (T₁, T₂)", "Collect the mass of water to find the energy input", "Measure length l, cross-sectional area A and ΔT", "Compute K = P·l / (A·ΔT·t)"],
    result: "Thermal conductivity K in W m⁻¹ K⁻¹.",
    related: PHY_REL,
  },

  /* ================= PHYSICS (hub → 6 units → 17 concepts, all practical) ================= */
  "physics": {
    id: "physics",
    title: "Physics Practical Labs",
    subject: "Physics",
    type: "practical",
    level: "hub",
    parent: null,
    route: "physics",
    tagline: "NEB Class 11 & 12 measurement experiments, organized by syllabus unit.",
    purpose:
      "Six practical units — measurement & mechanics, thermal physics, electricity, waves & optics, and electromagnetism — each holding its hands-on experiments with apparatus, procedure and expected result.",
    related: [
      { label: "Physics practical write-ups", href: "/practical/physics" },
      { label: "Physics syllabus", href: "/syllabus/physics" },
    ],
  },

  // -- Unit: Measurement & Mechanics --
  "measurement-mechanics": {
    id: "measurement-mechanics",
    title: "Measurement & Mechanics",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/measurement-mechanics",
    tagline: "Instrument reading, gravitational acceleration and rotational equilibrium.",
    purpose: "Foundational Class 11 experiments: precise measuring instruments, g by pendulum, and the principle of moments.",
    related: PHY_REL,
  },
  "vernier-screw-gauge": {
    id: "vernier-screw-gauge",
    title: "Vernier Caliper & Screw Gauge",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "measurement-mechanics",
    route: "physics/measurement-mechanics/vernier-screw-gauge",
    tagline: "Read two essential measuring instruments correctly, including zero error.",
    purpose: "Master the Vernier Caliper (2-D) and Screw Gauge (diameter) and apply the zero-error correction.",
    concepts: ["Least count & main scale", "Vernier scale", "Zero error", "Pitch of the screw gauge"],
    apparatus: ["Vernier calipers", "Screw gauge", "Metallic block / cylinder", "Graph paper"],
    procedure: ["Check for zero error on both instruments and note it", "Measure a block with the calipers (main + vernier readings)", "Measure a wire's diameter with the screw gauge over ~30 turns", "Apply the zero-error correction to get the true readings"],
    result: "Corrected length / diameter; least counts ≈ 0.01 cm (calipers) and 0.001 cm (screw gauge).",
    related: PHY_REL,
  },
  "g-simple-pendulum": {
    id: "g-simple-pendulum",
    title: "Determination of g (Simple Pendulum)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "measurement-mechanics",
    route: "physics/measurement-mechanics/g-simple-pendulum",
    tagline: "Find gravitational acceleration g from the period of a simple pendulum.",
    purpose: "A standard Class 11 practical: measure periods at several lengths and use the L–T² slope to find g.",
    concepts: ["T = 2π√(L/g)", "L² vs T² linearity", "Least count of the stopwatch", "Correcting for air drag & finite amplitude"],
    apparatus: ["Pendulum (bob + thread)", "Metre scale", "Stopwatch", "Clamp / stand"],
    procedure: ["Set the pendulum length L and time 20 oscillations", "Find T = total/20 and record L", "Repeat for 5 different lengths", "Plot L vs T²; the slope equals g/(4π²)"],
    result: "g ≈ 9.8 m s⁻² read from the slope of the L–T² graph.",
    related: PHY_REL,
  },
  "principle-of-moments": {
    id: "principle-of-moments",
    title: "Principle of Moments (Beam Balance)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "measurement-mechanics",
    route: "physics/measurement-mechanics/principle-of-moments",
    tagline: "Verify that at equilibrium the clockwise and anticlockwise moments balance.",
    purpose: "Confirm that the sum of clockwise moments equals the sum of anticlockwise moments about a pivot.",
    concepts: ["Centre of gravity", "Principle of moments", "Torque (F × d)", "Balance of forces & moments"],
    apparatus: ["Metre rule", "Pivot (knife edge)", "Slotted weights", "Strings"],
    procedure: ["Balance the rule at its centre to locate its weight acting through G", "Hang two known weights on either side at known distances", "Adjust the positions until the rule is level", "Compare Σ(clockwise moments) with Σ(anticlockwise moments)"],
    result: "The two moment sums agree within experimental error, verifying the principle.",
    related: PHY_REL,
  },

  // -- Unit: Heat & Thermal Physics --
  "heat-thermal-physics": {
    id: "heat-thermal-physics",
    title: "Heat & Thermal Physics",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/heat-thermal-physics",
    tagline: "Thermal expansion and heating-curve experiments.",
    purpose: "Class 12 thermal experiments: coefficient of linear expansion (Searle's method) and drawing a heating curve.",
    related: PHY_REL,
  },
  "linear-expansion-searle": {
    id: "linear-expansion-searle",
    title: "Coefficient of Linear Expansion (Searle's Method)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "heat-thermal-physics",
    route: "physics/heat-thermal-physics/linear-expansion-searle",
    tagline: "Find α of a metal rod by Searle's optical-lever method.",
    purpose: "Determine the coefficient of linear expansion of a metal using Searle's apparatus and the lever-magnified reading.",
    concepts: ["α = ΔL / (L₀ · ΔT)", "Searle's optical lever", "Magnification factor", "Thermal lag & steady state"],
    apparatus: ["Searle's apparatus", "Steam / water bath", "Microscope / vernier scale", "Thermometer"],
    procedure: ["Note the initial lever reading at temperature T₁", "Heat the rod to a steady T₂ and read the final position", "Compute ΔL and apply the lever magnification", "Find α = ΔL / (L₀ · ΔT)"],
    result: "α in K⁻¹ (typical metals ~10⁻⁵ K⁻¹).",
    related: PHY_REL,
  },
  "heating-curve": {
    id: "heating-curve",
    title: "Drawing a Heating Curve of a Substance",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "heat-thermal-physics",
    route: "physics/heat-thermal-physics/heating-curve",
    tagline: "Plot temperature vs time to reveal the melting & boiling plateaus.",
    purpose: "Record the temperature of a substance while it is heated, and identify the plateaus where a phase change absorbs latent heat.",
    concepts: ["Latent heat", "Melting & boiling points", "Plateau interpretation", "Specific heat"],
    apparatus: ["Test tube of a pure substance", "Water bath / flame", "Thermometer", "Stopwatch"],
    procedure: ["Heat the substance uniformly and record T at fixed intervals", "Continue past the melting and boiling plateaus", "Plot T against time"],
    result: "Flat plateaus at the melting point and boiling point, where added heat is latent heat.",
    related: PHY_REL,
  },

  // -- Unit: Electricity --
  "electricity": {
    id: "electricity",
    title: "Electricity",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/electricity",
    tagline: "Ohm's law and Kirchhoff's first law verification.",
    purpose: "Class 11 DC experiments: verifying Ohm's law with a V–I graph and Kirchhoff's junction rule.",
    related: PHY_REL,
  },
  "ohms-law": {
    id: "ohms-law",
    title: "Verification of Ohm's Law (V–I Graph)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity",
    route: "physics/electricity/ohms-law",
    tagline: "Verify V ∝ I for a fixed resistor via a V–I graph.",
    purpose: "Measure voltage and current at several settings of a fixed resistor and confirm the linear relationship.",
    concepts: ["V = IR", "Slope of V–I = R", "Constant-temperature assumption", "Internal-resistance effects"],
    apparatus: ["Fixed resistor", "Ammeter", "Voltmeter", "DC source", "Rheostat", "Switch"],
    procedure: ["Connect the circuit and vary the rheostat", "Record pairs of V and I (at least 5)", "Plot V against I", "Find the slope, which equals R"],
    result: "A straight-line V–I graph through the origin confirms Ohm's law; the slope gives R.",
    related: PHY_REL,
  },
  "kirchhoff-1st-law": {
    id: "kirchhoff-1st-law",
    title: "Verification of Kirchhoff's First Law",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity",
    route: "physics/electricity/kirchhoff-1st-law",
    tagline: "Confirm current conservation at a junction (junction rule).",
    purpose: "Verify that the total current entering a junction equals the total leaving it.",
    concepts: ["Junction rule", "Current splitting", "Parallel branches", "Ammeter placement"],
    apparatus: ["DC source", "3–4 resistors", "2–3 ammeters", "Connecting wires"],
    procedure: ["Build a junction with two parallel branches", "Measure the current in each branch and the total", "Confirm I_total = I₁ + I₂", "Repeat at different source voltages"],
    result: "The branch currents sum to the total at the junction, within experimental error.",
    related: PHY_REL,
  },

  // -- Unit: Mechanics (Grade 12) --
  "mechanics-12": {
    id: "mechanics-12",
    title: "Mechanics (Grade 12)",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/mechanics-12",
    tagline: "Surface tension and viscosity determinations.",
    purpose: "Class 12 mechanics experiments: surface tension by capillary rise and viscosity by Stokes' method.",
    related: PHY_REL,
  },
  "surface-tension-capillary": {
    id: "surface-tension-capillary",
    title: "Surface Tension by the Capillary Tube Method",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "mechanics-12",
    route: "physics/mechanics-12/surface-tension-capillary",
    tagline: "Find the surface tension of water from capillary rise.",
    purpose: "Determine the surface tension of water from the height to which it rises in a capillary tube.",
    concepts: ["Capillary rise", "h = 2T / (ρ g r)", "Surface-tension forces", "Contact angle"],
    apparatus: ["Capillary tube of known radius r", "Water", "Vertical scale", "Vernier / stand"],
    procedure: ["Note the meniscus height h in the capillary", "Measure the tube's inner radius r", "Compute T = ρ g r h / 2"],
    result: "Surface tension T of water in N m⁻¹.",
    related: PHY_REL,
  },
  "viscosity-stokes": {
    id: "viscosity-stokes",
    title: "Coefficient of Viscosity by Stoke's Method",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "mechanics-12",
    route: "physics/mechanics-12/viscosity-stokes",
    tagline: "Find the viscosity of a liquid from a falling ball's terminal velocity.",
    purpose: "Determine the coefficient of viscosity of a liquid using the terminal velocity of a falling sphere.",
    concepts: ["Terminal velocity", "Stokes' law F = 6πηrv", "Buoyancy correction", "Drag force"],
    apparatus: ["Glass cylinder of the liquid", "Small glass balls", "Stopwatch", "Metre scale", "Thermometer"],
    procedure: ["Drop a ball and time its descent over a measured distance at terminal velocity", "Find the velocity v and the ball radius r", "Apply Stokes' law with the buoyancy correction", "Repeat for 2–3 ball sizes"],
    result: "Coefficient of viscosity η in kg m⁻¹ s⁻¹ (Pa·s).",
    related: PHY_REL,
  },

  // -- Unit: Waves & Optics (Grade 12) --
  "waves-optics-12": {
    id: "waves-optics-12",
    title: "Waves & Optics (Grade 12)",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/waves-optics-12",
    tagline: "Laser wavelength, speed of sound and mains frequency.",
    purpose: "Class 12 wave/optics experiments: He–Ne wavelength via grating, speed of sound via resonance tube, mains frequency via a sonometer.",
    related: PHY_REL,
  },
  "laser-wavelength-grating": {
    id: "laser-wavelength-grating",
    title: "Wavelength of He–Ne Laser (Diffraction Grating)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "waves-optics-12",
    route: "physics/waves-optics-12/laser-wavelength-grating",
    tagline: "Measure the laser wavelength from the grating fringe positions.",
    purpose: "Determine the wavelength of He–Ne laser light using a plane diffraction grating.",
    concepts: ["Grating equation d sinθ = mλ", "Slit density (N)", "Path difference", "First-order maxima"],
    apparatus: ["He–Ne laser", "Diffraction grating", "Screen", "Metre scale"],
    procedure: ["Project the laser onto a screen through the grating", "Measure the fringe positions for orders m = 0, 1, 2", "Use d sinθ = mλ (with d = 1/N) to solve for λ"],
    result: "λ ≈ 6.3 × 10⁻⁷ m (the red He–Ne line).",
    related: PHY_REL,
  },
  "sound-velocity-resonance": {
    id: "sound-velocity-resonance",
    title: "Velocity of Sound (Resonance Tube)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "waves-optics-12",
    route: "physics/waves-optics-12/sound-velocity-resonance",
    tagline: "Find the speed of sound at NTP from resonant air-column lengths.",
    purpose: "Determine the speed of sound in air at NTP from the two resonant lengths of a tube.",
    concepts: ["Standing waves", "Resonant lengths L₁, L₂", "End correction", "L₁ − L₂ = λ/2"],
    apparatus: ["Resonance tube", "Tuning fork of known frequency", "Water trough", "Metre scale"],
    procedure: ["Find the two successive resonant lengths L₁ and L₂", "Use L₁ − L₂ = λ/2 to get λ", "Compute v = fλ and correct to NTP using v ∝ √T"],
    result: "Speed of sound at NTP ≈ 332 m s⁻¹.",
    related: PHY_REL,
  },
  "mains-frequency-sonometer": {
    id: "mains-frequency-sonometer",
    title: "Frequency of A.C. Mains (Sonometer)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "waves-optics-12",
    route: "physics/waves-optics-12/mains-frequency-sonometer",
    tagline: "Determine the supply frequency by vibrating a stretched wire resonantly.",
    purpose: "Find the mains frequency by making a stretched wire vibrate in resonance with the A.C. supply.",
    concepts: ["Standing waves on a string", "v = √(T/μ)", "f = n/(2L)", "Mains frequency"],
    apparatus: ["Sonometer (stretched wire)", "A.C. supply", "Adjustable bridge", "Force / mass-measuring tools"],
    procedure: ["Connect the wire to the A.C. supply", "Adjust the length until maximum vibration (resonance)", "Use f = (n/2L)√(T/μ)", "Solve for the mains frequency"],
    result: "Mains frequency ≈ 50 Hz.",
    related: PHY_REL,
  },

  // -- Unit: Electricity & Magnetism (Grade 12) --
  "electricity-magnetism-12": {
    id: "electricity-magnetism-12",
    title: "Electricity & Magnetism (Grade 12)",
    subject: "Physics",
    type: "practical",
    level: "unit",
    parent: "physics",
    route: "physics/electricity-magnetism-12",
    tagline: "Potentiometer, thermistor, magnetometer and diode characteristics.",
    purpose: "Class 12 E&M experiments: comparing e.m.f.s, finding internal resistance, the thermistor R–T curve, magnetometer pole strength and diode I–V characteristics.",
    related: PHY_REL,
  },
  "potentiometer-emf": {
    id: "potentiometer-emf",
    title: "Comparison of E.M.F.s of Two Cells (Potentiometer)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity-magnetism-12",
    route: "physics/electricity-magnetism-12/potentiometer-emf",
    tagline: "Compare two cells' e.m.f. without drawing current.",
    purpose: "Use a potentiometer to compare the e.m.f. of two cells from their balance lengths.",
    concepts: ["Potentiometer principle", "Balance point", "l₂/l₁ ∝ E₂/E₁", "Null point & galvanometer"],
    apparatus: ["Potentiometer wire", "Two cells + a standard cell", "Galvanometer", "Jockey", "Key"],
    procedure: ["Balance the standard cell → length l₀", "Balance each unknown cell → l₁, l₂", "Use E₂/E₁ = l₂/l₁"],
    result: "The ratio of the two cells' e.m.f.s from their balance lengths.",
    related: PHY_REL,
  },
  "potentiometer-internal-r": {
    id: "potentiometer-internal-r",
    title: "Internal Resistance of a Cell (Potentiometer)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity-magnetism-12",
    route: "physics/electricity-magnetism-12/potentiometer-internal-r",
    tagline: "Find the internal resistance r from two balance lengths.",
    purpose: "Determine the internal resistance of a cell from two potentiometer balance readings (e.m.f. vs terminal p.d.).",
    concepts: ["Terminal p.d. vs e.m.f.", "Internal resistance", "r/R = (l₁ − l₂)/l₂", "Load resistance R"],
    apparatus: ["Potentiometer", "Unknown cell", "Resistance box", "Galvanometer", "Jockey"],
    procedure: ["Balance the cell alone → l₁ (e.m.f.)", "Short-circuit it through R and balance again → l₂ (terminal p.d.)", "Compute r = R(l₁ − l₂)/l₂"],
    result: "Internal resistance r of the cell in Ω.",
    related: PHY_REL,
  },
  "thermistor-resistance": {
    id: "thermistor-resistance",
    title: "Resistance of a Thermistor vs Temperature",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity-magnetism-12",
    route: "physics/electricity-magnetism-12/thermistor-resistance",
    tagline: "Plot the R–T curve and observe the negative temperature coefficient.",
    purpose: "Trace the resistance–temperature characteristic of a thermistor and note its NTC behaviour.",
    concepts: ["NTC thermistor", "R–T curve", "Semiconductor resistance", "Resistance vs temperature"],
    apparatus: ["Thermistor", "DC source", "Ammeter / Ohm meter", "Thermometer", "Water bath"],
    procedure: ["Measure the thermistor resistance at several temperatures", "Heat gradually in a water bath, recording R and T", "Plot R against T"],
    result: "R decreases as T rises (NTC behaviour); the characteristic R–T curve is obtained.",
    related: PHY_REL,
  },
  "deflection-magnetometer": {
    id: "deflection-magnetometer",
    title: "Pole Strength & Magnetic Moment (Deflection Magnetometer)",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity-magnetism-12",
    route: "physics/electricity-magnetism-12/deflection-magnetometer",
    tagline: "Find a bar magnet's pole strength and magnetic moment from its deflection.",
    purpose: "Determine the pole strength and magnetic moment of a bar magnet using the deflection magnetometer and the tangent law.",
    concepts: ["Tangent law", "Magnetic moment M", "Pole strength m", "Earth's horizontal field H"],
    apparatus: ["Deflection magnetometer", "Small bar magnet", "Metre scale", "Compass"],
    procedure: ["Place the magnet at distance d; record the deflection θ", "Repeat at a second distance for a second θ", "Apply the tangent law to solve for M", "Find pole strength m = M/(2l)"],
    result: "Magnetic moment M (A m²) and pole strength of the magnet.",
    related: PHY_REL,
  },
  "diode-iv-characteristics": {
    id: "diode-iv-characteristics",
    title: "I–V Characteristics of a Semiconductor Diode",
    subject: "Physics",
    type: "practical",
    level: "concept",
    parent: "electricity-magnetism-12",
    route: "physics/electricity-magnetism-12/diode-iv-characteristics",
    tagline: "Trace the forward and reverse I–V curve of a p–n diode.",
    purpose: "Obtain the forward and reverse I–V characteristic of a p–n junction diode.",
    concepts: ["Forward & reverse bias", "Breakdown voltage", "Knee / turn-on voltage", "Reverse saturation current"],
    apparatus: ["p–n diode", "DC supply", "Ammeter", "Resistance box", "Potentiometer"],
    procedure: ["Wire for forward bias; record I vs V past the knee", "Reverse the diode; record the small reverse saturation current", "Sketch the full I–V curve"],
    result: "Forward conduction past ~0.7 V (Si) and a near-zero reverse current.",
    related: PHY_REL,
  },

  /* ================= CHEMISTRY (hub → 8 units → 20 concepts, all practical) ================= */
  "chemistry": {
    id: "chemistry",
    title: "Chemistry Practical Labs",
    subject: "Chemistry",
    type: "practical",
    level: "hub",
    parent: null,
    route: "chemistry",
    tagline: "NEB Class 11 & 12 wet-lab experiments, organized by syllabus unit.",
    purpose:
      "Eight practical units — lab techniques, reaction types, gas preparation, quantitative & qualitative analysis, salt recovery, titration and organic tests — each with the experiments needed for NEB practicals.",
    related: [
      { label: "Chemistry practical write-ups", href: "/practical/chemistry" },
      { label: "Chemistry syllabus", href: "/syllabus/chemistry" },
    ],
  },

  // -- Unit: Laboratory Techniques --
  "lab-techniques": {
    id: "lab-techniques",
    title: "Laboratory Techniques (Grade 11)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/lab-techniques",
    tagline: "Separation, crystallization, water of crystallization and gas molar volume.",
    purpose: "Core handling and separation skills: separating mixtures, fractional crystallization, water of crystallization and the molar volume of hydrogen.",
    related: CHEM_REL,
  },
  "separate-insoluble-mixture": {
    id: "separate-insoluble-mixture",
    title: "Separation of an Insoluble Mixture (NaCl, Sand, Camphor)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "lab-techniques",
    route: "chemistry/lab-techniques/separate-insoluble-mixture",
    tagline: "Separate salt, sand and camphor using sublimation, filtration and evaporation.",
    purpose: "Separate a mixture of salt, sand and camphor by exploiting their different physical properties.",
    concepts: ["Sublimation", "Filtration", "Evaporation / crystallization", "Solubility differences"],
    apparatus: ["Beaker", "Funnel + filter paper", "Watch glass", "Burner", "Camphor crystals"],
    procedure: ["Sublime the camphor separately (it vaporizes)", "Add water, dissolve the NaCl and filter out the sand", "Evaporate the filtrate to recover NaCl crystals"],
    result: "All three components recovered in pure form.",
    related: CHEM_REL,
  },
  "fractional-crystallization": {
    id: "fractional-crystallization",
    title: "Fractional Crystallization (KNO₃ + NaCl)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "lab-techniques",
    route: "chemistry/lab-techniques/fractional-crystallization",
    tagline: "Separate two soluble solids using their different solubility curves.",
    purpose: "Separate a mixture of KNO₃ and NaCl using the large difference in how their solubilities change with temperature.",
    concepts: ["Solubility vs temperature", "KNO₃ highly T-sensitive", "NaCl nearly constant", "Fractional crystallization"],
    apparatus: ["Hot saturated solution", "Filter paper", "Beaker", "Thermometer", "Ice bath"],
    procedure: ["Make a hot, concentrated solution of the mixture", "Cool it; KNO₃ crystallizes out first", "Filter to isolate KNO₃, then evaporate the residue to recover NaCl"],
    result: "KNO₃ and NaCl separated into distinct fractions.",
    related: CHEM_REL,
  },
  "water-crystallization": {
    id: "water-crystallization",
    title: "Number of Water of Crystallization in a Hydrated Salt",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "lab-techniques",
    route: "chemistry/lab-techniques/water-crystallization",
    tagline: "Determine the number of water molecules in a hydrated salt by heating.",
    purpose: "Find the number of water molecules (n) in a hydrated salt from the mass lost on heating.",
    concepts: ["Hydrated vs anhydrous salt", "Water of crystallization", "Mass lost %", "Finding n"],
    apparatus: ["Crucible / Gooch", "Analytical balance", "Hydrated salt sample", "Burner", "Desiccator"],
    procedure: ["Weigh the hydrated salt and heat it to constant mass", "Find the mass lost (water)", "Compute n from the mole ratio of H₂O to the anhydrous salt"],
    result: "The integer n in the salt's formula.",
    related: CHEM_REL,
  },
  "molar-volume-hydrogen": {
    id: "molar-volume-hydrogen",
    title: "Volume of 1 Mole of Hydrogen at NTP",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "lab-techniques",
    route: "chemistry/lab-techniques/molar-volume-hydrogen",
    tagline: "Find the molar volume of H₂ and correct it to NTP.",
    purpose: "Determine the volume occupied by one mole of hydrogen gas, corrected to NTP, using the gas laws.",
    concepts: ["Mole volume", "STP/NTP correction", "Gay-Lussac / gas laws", "Moles of H₂ produced"],
    apparatus: ["H₂-generation setup", "Gas cylinder / eudiometer", "Thermometer", "Barometer"],
    procedure: ["Generate a measured mass of H₂", "Measure its volume, then correct to NTP using PV = nRT", "Find the volume per mole"],
    result: "≈ 22.4 L per mole of H₂ at NTP.",
    related: CHEM_REL,
  },

  // -- Unit: Types of Chemical Reactions --
  "reactions-types": {
    id: "reactions-types",
    title: "Types of Chemical Reactions (Grade 11)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/reactions-types",
    tagline: "Precipitation, neutralization and redox (Fe²⁺/Fe³⁺).",
    purpose: "Demonstrate the main reaction types — a precipitation, a neutralization recovering NaCl, and the oxidation of ferrous to ferric ions.",
    related: CHEM_REL,
  },
  "precipitation-reaction": {
    id: "precipitation-reaction",
    title: "Precipitation: BaCl₂ + H₂SO₄",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "reactions-types",
    route: "chemistry/reactions-types/precipitation-reaction",
    tagline: "Show a double-displacement reaction forming insoluble BaSO₄.",
    purpose: "Demonstrate a precipitation (double displacement) reaction that forms the insoluble white precipitate BaSO₄.",
    concepts: ["Double displacement", "Precipitate formation", "Solubility rules", "Net ionic equation"],
    apparatus: ["BaCl₂ solution", "Dilute H₂SO₄", "Test tubes", "Filter paper"],
    procedure: ["Mix equal volumes of BaCl₂ and dilute H₂SO₄", "Observe the white precipitate of BaSO₄", "Filter and wash the precipitate"],
    result: "A white BaSO₄ precipitate confirms the reaction.",
    related: CHEM_REL,
  },
  "neutralization-nacl": {
    id: "neutralization-nacl",
    title: "Neutralization: NaOH + HCl → NaCl",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "reactions-types",
    route: "chemistry/reactions-types/neutralization-nacl",
    tagline: "Neutralize NaOH with HCl and recover NaCl crystals.",
    purpose: "Neutralize sodium hydroxide with hydrochloric acid and recover sodium-chloride crystals by evaporation.",
    concepts: ["Acid–base neutralization", "Salt formation", "Endpoint (pH 7)", "Crystallization"],
    apparatus: ["NaOH solution", "Dilute HCl", "Indicator / pH paper", "Beaker", "Burner"],
    procedure: ["Neutralize NaOH with HCl using an indicator to the endpoint", "Evaporate the solution to dryness", "Collect the NaCl crystals"],
    result: "White NaCl crystals recovered.",
    related: CHEM_REL,
  },
  "ferrous-ferric-test": {
    id: "ferrous-ferric-test",
    title: "Fe²⁺ Test and Oxidation to Fe³⁺",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "reactions-types",
    route: "chemistry/reactions-types/ferrous-ferric-test",
    tagline: "Detect ferrous ions and oxidize them to ferric ions.",
    purpose: "Detect ferrous ions in a solution and oxidize them to ferric ions, observing the characteristic colour changes.",
    concepts: ["Fe²⁺ vs Fe³⁺", "Oxidation", "Potassium ferricyanide (blue ppt)", "KSCN (blood-red) for Fe³⁺"],
    apparatus: ["FeSO₄ solution", "Oxidizing agent (e.g. brom water)", "Potassium ferricyanide", "Test tubes"],
    procedure: ["Test the solution for Fe²⁺ (e.g. with K₃[Fe(CN)₆])", "Add the oxidizing agent", "Re-test to show Fe³⁺ (yellow/brown; red with KSCN)"],
    result: "Fe²⁺ → Fe³⁺ confirmed by the reagent colour changes.",
    related: CHEM_REL,
  },

  // -- Unit: Gas Preparation --
  "gas-preparation": {
    id: "gas-preparation",
    title: "Preparation & Properties of Gases (Grade 11)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/gas-preparation",
    tagline: "Prepare and study hydrogen, ammonia and carbon dioxide.",
    purpose: "Prepare three common gases — H₂, NH₃ and CO₂ — and study their characteristic properties.",
    related: CHEM_REL,
  },
  "hydrogen-gas": {
    id: "hydrogen-gas",
    title: "Preparation & Properties of Hydrogen",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "gas-preparation",
    route: "chemistry/gas-preparation/hydrogen-gas",
    tagline: "Prepare H₂ from Zn + dilute H₂SO₄ and test its properties.",
    purpose: "Prepare hydrogen gas and study its characteristic properties (pop test, non-flame-supporting).",
    concepts: ["Zn + H₂SO₄ → H₂", "Downward delivery (lightest gas)", "Pop test", "Non-flame-supporting"],
    apparatus: ["Zinc granules", "Dilute H₂SO₄", "Gas jar", "Test tube", "Lighted splint"],
    procedure: ["Add Zn to dilute H₂SO₄; collect the gas by downward delivery", "Test with a lighted splint (sharp pop)", "Show it does not burn air's flame"],
    result: "Colorless gas with an explosive 'pop' confirms H₂.",
    related: CHEM_REL,
  },
  "ammonia-gas": {
    id: "ammonia-gas",
    title: "Preparation & Properties of Ammonia",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "gas-preparation",
    route: "chemistry/gas-preparation/ammonia-gas",
    tagline: "Prepare NH₃ and study its strongly alkaline, water-soluble nature.",
    purpose: "Prepare ammonia gas and study its strongly alkaline, water-soluble character.",
    concepts: ["NH₄⁺ + OH⁻ → NH₃ + H₂O", "Downward delivery", "Litmus test (red → blue)", "High water solubility"],
    apparatus: ["Ammonium salt", "NaOH", "Test tube", "Red litmus"],
    procedure: ["Heat the ammonium salt with NaOH; collect by downward displacement", "Test with red litmus (turns blue)", "Show its water absorption"],
    result: "Sharp alkaline smell and blue litmus confirm NH₃.",
    related: CHEM_REL,
  },
  "carbon-dioxide-gas": {
    id: "carbon-dioxide-gas",
    title: "Preparation & Properties of CO₂",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "gas-preparation",
    route: "chemistry/gas-preparation/carbon-dioxide-gas",
    tagline: "Prepare CO₂ and study its density and lime-water test.",
    purpose: "Prepare carbon dioxide and study its density, non-flame-supporting nature and the lime-water test.",
    concepts: ["CaCO₃ + HCl → CO₂", "Upward delivery (heavier than air)", "Lime-water test (milky)", "Non-flame-supporting"],
    apparatus: ["Calcium carbonate", "Dilute HCl", "Lime water", "Test tube"],
    procedure: ["Add dilute HCl to CaCO₃; collect by upward displacement", "Pass the gas through lime water (turns milky)", "Show it extinguishes a candle"],
    result: "Milky lime water and a non-flame-supporting gas confirm CO₂.",
    related: CHEM_REL,
  },

  // -- Unit: Quantitative Analysis --
  "quantitative-analysis": {
    id: "quantitative-analysis",
    title: "Quantitative Analysis (Grade 11)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/quantitative-analysis",
    tagline: "Molecular weight, solubility and drop-count surface tension.",
    purpose: "Quantitative determination experiments: molar mass of a metal carbonate, solubility of a solid, and relative surface tension by the drop-count method.",
    related: CHEM_REL,
  },
  "metal-carbonate-molarmass": {
    id: "metal-carbonate-molarmass",
    title: "Molecular Weight of a Metal Carbonate (Acid Titration)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "quantitative-analysis",
    route: "chemistry/quantitative-analysis/metal-carbonate-molarmass",
    tagline: "Find the molar mass of a metal carbonate by acid titration.",
    purpose: "Determine the molar mass of a metal carbonate by acid–base titration with a standard acid.",
    concepts: ["Acid titration", "Carbonate + acid stoichiometry", "Equivalence point", "Molar mass from moles"],
    apparatus: ["Metal carbonate sample", "Standard acid", "Pipette", "Burette", "Indicator"],
    procedure: ["Dissolve a weighed sample; titrate against the standard acid", "Record the volume at the endpoint", "Compute the molar mass from the stoichiometry"],
    result: "Molar mass of the metal carbonate in g mol⁻¹.",
    related: CHEM_REL,
  },
  "solubility-determination": {
    id: "solubility-determination",
    title: "Solubility of a Given Solid",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "quantitative-analysis",
    route: "chemistry/quantitative-analysis/solubility-determination",
    tagline: "Determine the solubility (g/100 mL) of a solid at a fixed temperature.",
    purpose: "Determine the solubility of a solid at a fixed temperature, expressed per 100 mL of water.",
    concepts: ["Solubility", "Saturated solution", "Temperature control", "g/100 mL"],
    apparatus: ["Solvent (water)", "Solid sample", "Saturated solution at T", "Filter paper", "Evaporating dish"],
    procedure: ["Prepare a saturated solution at temperature T", "Filter, then evaporate a measured aliquot to dryness", "Compute the solubility"],
    result: "Solubility in g per 100 mL at T.",
    related: CHEM_REL,
  },
  "drop-count-surface-tension": {
    id: "drop-count-surface-tension",
    title: "Relative Surface Tension (Drop-Count Method)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "quantitative-analysis",
    route: "chemistry/quantitative-analysis/drop-count-surface-tension",
    tagline: "Compare two liquids' surface tensions by counting drops.",
    purpose: "Compare the surface tensions of two liquids by the drop-count method, using water as the reference.",
    concepts: ["Drop-count method", "Surface tension ∝ mass per drop", "Capillary drop", "Relative T vs water"],
    apparatus: ["Two clean capillary tubes", "Two liquids", "Beaker", "Dropper"],
    procedure: ["Count the number of drops for a fixed volume of each liquid", "Compare T₂/T₁ = (d₂n₁)/(d₁n₂)", "Use water as the reference liquid"],
    result: "Relative surface tension of the liquid compared with water.",
    related: CHEM_REL,
  },

  // -- Unit: Qualitative Analysis --
  "qualitative-analysis": {
    id: "qualitative-analysis",
    title: "Qualitative Analysis (Grade 11)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/qualitative-analysis",
    tagline: "Detection of basic and acid radicals of an unknown salt.",
    purpose: "Identify the cation and anion of an unknown salt using standard qualitative (radical) tests.",
    related: CHEM_REL,
  },
  "acid-radical-detection": {
    id: "acid-radical-detection",
    title: "Detection of Basic & Acid Radicals of a Salt",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "qualitative-analysis",
    route: "chemistry/qualitative-analysis/acid-radical-detection",
    tagline: "Identify the cation and anion of an unknown salt.",
    purpose: "Identify the basic (cation) and acid (anion) radicals of an unknown salt and thereby the salt's identity.",
    concepts: ["Flame test", "Cation confirmation (NaOH)", "Anion (gas) tests", "Confirmatory tests"],
    apparatus: ["Unknown salt", "NaOH", "HCl", "H₂SO₄", "Test tubes", "Flame"],
    procedure: ["Do the flame test and the NaOH test for the cation", "Do acid tests for the anion (gas evolved)", "Run one confirmatory test for each radical"],
    result: "The cation and anion are identified, giving the salt's identity.",
    related: CHEM_REL,
  },

  // -- Unit: Salt Recovery --
  "salt-recovery": {
    id: "salt-recovery",
    title: "Recovery & Preparation of Salts (Grade 12)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/salt-recovery",
    tagline: "Recovering blue vitriol and calcium carbonate.",
    purpose: "Recover and prepare two salts from mixtures: blue vitriol (copper sulphate) and calcium carbonate.",
    related: CHEM_REL,
  },
  "blue-vitriol-recovery": {
    id: "blue-vitriol-recovery",
    title: "Recovery of Blue Vitriol (CuSO₄ + NaCl)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "salt-recovery",
    route: "chemistry/salt-recovery/blue-vitriol-recovery",
    tagline: "Recover copper sulphate pentahydrate crystals from a CuSO₄ + NaCl mixture.",
    purpose: "Recover blue-vitriol (copper sulphate pentahydrate) crystals from a mixture containing sodium chloride.",
    concepts: ["CuSO₄·5H₂O (blue vitriol)", "Selective solubility / crystallization", "Mother liquor"],
    apparatus: ["CuSO₄ + NaCl mixture", "Hot water", "Filter paper", "Crystallizing dish"],
    procedure: ["Dissolve the mixture in minimum hot water", "Filter the hot solution; it crystallizes on cooling", "Collect the blue crystals"],
    result: "Blue-vitriol (CuSO₄·5H₂O) crystals recovered.",
    related: CHEM_REL,
  },
  "cacoo3-recovery": {
    id: "cacoo3-recovery",
    title: "Recovery of CaCO₃ (Na₂CO₃ + CaCl₂)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "salt-recovery",
    route: "chemistry/salt-recovery/cacoo3-recovery",
    tagline: "Prepare and isolate calcium carbonate by precipitation.",
    purpose: "Prepare and isolate calcium carbonate by a precipitation reaction between sodium carbonate and calcium chloride.",
    concepts: ["Double displacement", "CaCO₃ precipitate", "Filtration & washing"],
    apparatus: ["Na₂CO₃ solution", "CaCl₂ solution", "Filter paper", "Beaker"],
    procedure: ["Mix Na₂CO₃ with CaCl₂", "The white CaCO₃ precipitates", "Filter, wash and dry the precipitate"],
    result: "Pure white CaCO₃ recovered.",
    related: CHEM_REL,
  },

  // -- Unit: Volumetric Analysis & Titration --
  "volumetric-titration": {
    id: "volumetric-titration",
    title: "Volumetric Analysis & Titration (Grade 12)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/volumetric-titration",
    tagline: "Standardizing NaOH and finding a diprotic acid's molar mass.",
    purpose: "Titration experiments: standardizing NaOH against standard HCl, and determining the molar mass of a diprotic organic acid.",
    related: CHEM_REL,
  },
  "naoh-standardization": {
    id: "naoh-standardization",
    title: "Standardization of NaOH Against Standard HCl",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "volumetric-titration",
    route: "chemistry/volumetric-titration/naoh-standardization",
    tagline: "Find the exact molarity of NaOH by titrating against standard HCl.",
    purpose: "Determine the exact molarity of a NaOH solution by titrating it against a standard HCl solution.",
    concepts: ["Titration technique", "M₁V₁ = M₂V₂", "Endpoint (phenolphthalein)", "Pipette & burette handling"],
    apparatus: ["NaOH (unknown molarity)", "Standard HCl", "Phenolphthalein", "Pipette", "Burette"],
    procedure: ["Pipette a known volume of NaOH into a flask", "Titrate with standard HCl to the endpoint", "Compute M(NaOH) = M(HCl) × V(HCl)/V(NaOH)"],
    result: "The standardized molarity of NaOH.",
    related: CHEM_REL,
  },
  "diprotic-acid-molarmass": {
    id: "diprotic-acid-molarmass",
    title: "Molar Mass of a Diprotic Organic Acid",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "volumetric-titration",
    route: "chemistry/volumetric-titration/diprotic-acid-molarmass",
    tagline: "Determine the molar mass of a diprotic acid by neutralization.",
    purpose: "Determine the molar mass of a diprotic organic acid from its neutralization with a standard NaOH solution.",
    concepts: ["Diprotic acid (2 H⁺)", "Equivalent weight", "Molar mass = 2 × Eq. weight", "Neutralization titration"],
    apparatus: ["Diprotic acid sample", "Standard NaOH", "Phenolphthalein", "Pipette", "Burette"],
    procedure: ["Weigh a known mass of the acid and dissolve it", "Titrate against standard NaOH to the endpoint", "Molar mass = (M(NaOH) × V(NaOH) × 2) / (sample mass / V)"],
    result: "Molar mass of the diprotic acid.",
    related: CHEM_REL,
  },

  // -- Unit: Organic Qualitative Tests --
  "organic-qualitative": {
    id: "organic-qualitative",
    title: "Organic Qualitative Tests (Grade 12)",
    subject: "Chemistry",
    type: "practical",
    level: "unit",
    parent: "chemistry",
    route: "chemistry/organic-qualitative",
    tagline: "Tests for a carboxylic acid and an aldehyde.",
    purpose: "Functional-group tests: confirm a carboxylic acid (NaHCO₃) and an aldehyde (Tollens' / 2,4-DNP).",
    related: CHEM_REL,
  },
  "carboxylic-acid-test": {
    id: "carboxylic-acid-test",
    title: "Test for a Carboxylic Acid (NaHCO₃)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "organic-qualitative",
    route: "chemistry/organic-qualitative/carboxylic-acid-test",
    tagline: "Confirm a carboxylic acid by CO₂ effervescence with NaHCO₃.",
    purpose: "Confirm the presence of a carboxylic acid by its reaction with sodium bicarbonate, which releases CO₂.",
    concepts: ["RCOOH + NaHCO₃ → CO₂", "Effervescence", "Limewater check for CO₂"],
    apparatus: ["Unknown acid", "NaHCO₃", "Limewater", "Test tube"],
    procedure: ["Add NaHCO₃ to the acid sample", "Observe CO₂ effervescence", "Pass the gas into limewater (turns milky)"],
    result: "CO₂ (milky limewater) confirms a carboxylic-acid group.",
    related: CHEM_REL,
  },
  "aldehyde-test": {
    id: "aldehyde-test",
    title: "Test for an Aldehyde (Tollens' / 2,4-DNP)",
    subject: "Chemistry",
    type: "practical",
    level: "concept",
    parent: "organic-qualitative",
    route: "chemistry/organic-qualitative/aldehyde-test",
    tagline: "Confirm an aldehyde using Tollens' reagent and 2,4-DNP.",
    purpose: "Confirm an aldehyde using Tollens' reagent (silver mirror) and 2,4-dinitrophenylhydrazine (orange precipitate).",
    concepts: ["Aldehyde RCHO", "Silver mirror (Tollens')", "2,4-DNP (orange ppt)", "Distinguishing aldehyde vs ketone"],
    apparatus: ["Aldehyde sample", "Tollens' reagent", "2,4-DNP reagent", "Water bath"],
    procedure: ["Warm the aldehyde with Tollens' reagent", "Observe the silver mirror", "Add 2,4-DNP for an orange precipitate"],
    result: "A silver mirror / orange precipitate confirms an aldehyde.",
    related: CHEM_REL,
  },
};

export function getLab(id: string): LabEntry | undefined {
  return LABS[id];
}

/** All children of a given entry id (used for hubs listing units, and units listing concepts). */
export function listLabs(parent: string): LabEntry[] {
  return Object.values(LABS).filter((e) => e.parent === parent);
}

/** All top-level hub entries. */
export function listHubs(): LabEntry[] {
  return Object.values(LABS).filter((e) => e.level === "hub");
}

/** All unit ids directly under a given hub id (used for /lab/[subject]/[unit]). */
export function subjectUnits(hubId: string): string[] {
  return Object.values(LABS)
    .filter((e) => e.level === "unit" && e.parent === hubId)
    .map((e) => e.id);
}

/**
 * Every (unit, concept) pair directly under a given hub id, used to
 * pre-render the /lab/[subject]/[unit]/[concept] pages.
 */
export function subjectConceptPairs(hubId: string): { unit: string; concept: string }[] {
  return Object.values(LABS)
    .filter((e) => e.level === "concept" && e.parent && getLab(e.parent)?.parent === hubId)
    .map((e) => ({ unit: e.parent!, concept: e.id }));
}
