/**
 * Lab Registry — Central mapping of lab IDs to component implementations
 * This is the single source of truth for wiring labs between pages and components
 */

import type { LabMeta } from "./types/lab";

// Component imports
import { PhysicsDynamics3D } from "@/components/lab/physics-dynamics-3d";
import { Physics3DAdvanced } from "@/components/lab/physics-advanced-3d";
import { ChemistryLab } from "@/components/lab/chemistry-lab";
import { PhysicsLab } from "@/components/lab/physics-lab";
import { BiologyLab } from "@/components/lab/biology-lab";
import {
  BiologyAdvanced3D,
  BiologyEvolution3D,
  BiologyPunnettCalculator,
  BiologyPopulationCalculator,
  BiologyPhotosynthesisCalculator,
} from "@/components/lab/biology-3d";
import {
  MathModern3D,
  MathAdvancedMotionLab,
  MathInteractive,
  MathGeometry3D,
} from "@/components/lab";
import { Class11Math3DPlus } from "@/components/lab/class11/class11-math-3d-plus";
import { Class11Physics3DPlus } from "@/components/lab/class11/class11-physics-3d-plus";
import { Class11Chemistry3DPlus } from "@/components/lab/class11/class11-chemistry-3d-plus";
import { Class11Biology3DPlus } from "@/components/lab/class11/class11-biology-3d-plus";
import { TheoryPanel } from "@/components/lab/theory-panel";
import { PremiumEquationSolver } from "@/components/lab/premium-equation-solver";
import { PremiumAdvancedCircuitSimulator } from "@/components/lab/premium-advanced-circuit";
import { PremiumPlaceholder } from "@/components/lab/premium-placeholder";

/**
 * Lab registry mapping lab IDs to their component implementations
 * Each entry includes metadata for display and routing
 */
export const LAB_REGISTRY: LabMeta[] = [
  // ===== PHYSICS LABS =====
  {
    id: "ph-3d-dynamics",
    title: "Dynamics 3D",
    description: "Inclined plane, friction, elastic collision, momentum conservation in 3D.",
    category: "physics",
    type: "3d" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Dynamics",
    component: PhysicsDynamics3D,
  },
  {
    id: "ph-3d-advanced",
    title: "Physics 3D Advanced",
    description: "Electromagnetism, wave optics, relativity, quantum orbitals, nuclear decay.",
    category: "physics",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Modern Physics",
    component: Physics3DAdvanced,
  },
  {
    id: "ph-3d-quantum",
    title: "Quantum 3D",
    description: "Quantum mechanics visualizations including orbitals, probability distributions, and spin.",
    category: "physics",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Quantum",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-wave",
    title: "Wave Simulator 3D",
    description: "Real-time 3D wave propagation with sine, cosine, and damped modes.",
    category: "physics",
    type: "3d" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Waves",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-pendulum",
    title: "Pendulum 3D",
    description: "Pendulum with trail visualization and period calculations.",
    category: "physics",
    type: "3d" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Oscillations",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-em",
    title: "EM Wave 3D",
    description: "Electromagnetic wave propagation with E and B field visualization.",
    category: "physics",
    type: "3d" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: EM Waves",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-magnetic",
    title: "Magnetic Field 3D",
    description: "Bar magnet field lines and iron filings pattern.",
    category: "physics",
    type: "3d" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Magnetism",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-vectors",
    title: "Vector Addition 3D",
    description: "Interactive 3D vectors — components, dot product, cross product.",
    category: "physics",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Vectors",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-optics",
    title: "Optics & Lens 3D",
    description: "Ray diagrams for convex/concave lenses and mirrors with live lens equation.",
    category: "physics",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Optics",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-refraction",
    title: "Refraction 3D",
    description: "Snell's law visualization with total internal reflection.",
    category: "physics",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Optics",
    component: PhysicsLab,
  },
  {
    id: "ph-3d-classic",
    title: "Physics 3D Classic",
    description: "Electric field, double pendulum, and gravitational field visualizers.",
    category: "physics",
    type: "3d" as const,
    status: "development",
    color: "#3b82f6",
    unit: "Unit: Classic",
    component: PhysicsLab,
  },
  {
    id: "ph-th-kinematics",
    title: "Kinematics Theory",
    description: "Equations of motion, projectile motion, relative velocity theory.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Kinematics",
    component: () => <TheoryPanel subject="physics" topic="kinematics" />,
  },
  {
    id: "ph-th-laws",
    title: "Laws of Motion Theory",
    description: "Newton's laws, friction, circular motion theory.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Dynamics",
    component: () => <TheoryPanel subject="physics" topic="laws-motion" />,
  },
  {
    id: "ph-th-work",
    title: "Work & Energy Theory",
    description: "Work-energy theorem, conservation of energy, power.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Work Energy",
    component: () => <TheoryPanel subject="physics" topic="work-energy" />,
  },
  {
    id: "ph-th-grav",
    title: "Gravitation Theory",
    description: "Universal gravitation, gravitational potential, satellite motion.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Gravitation",
    component: () => <TheoryPanel subject="physics" topic="gravitation" />,
  },
  {
    id: "ph-th-thermo",
    title: "Thermodynamics Theory",
    description: "Laws of thermodynamics, heat engines, entropy.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Thermo",
    component: () => <TheoryPanel subject="physics" topic="thermodynamics" />,
  },
  {
    id: "ph-th-optics",
    title: "Optics Theory",
    description: "Reflection, refraction, lens formula, mirror equation.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Optics",
    component: () => <TheoryPanel subject="physics" topic="optics" />,
  },
  {
    id: "ph-th-electro",
    title: "Electrostatics Theory",
    description: "Coulomb's law, electric field, potential, capacitance.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Electrostatics",
    component: () => <TheoryPanel subject="physics" topic="electrostatics" />,
  },
  {
    id: "ph-th-current",
    title: "Current Electricity Theory",
    description: "Ohm's law, circuits, Kirchhoff's laws.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Current",
    component: () => <TheoryPanel subject="physics" topic="current" />,
  },
  {
    id: "ph-th-emw",
    title: "EM Waves Theory",
    description: "Electromagnetic spectrum, wave properties, polarization.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: EM Waves",
    component: () => <TheoryPanel subject="physics" topic="emw" />,
  },
  {
    id: "ph-th-modern",
    title: "Modern Physics Theory",
    description: "Photoelectric effect, atomic models, nuclear physics.",
    category: "physics",
    type: "theory" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Modern",
    component: () => <TheoryPanel subject="physics" topic="modern" />,
  },
  {
    id: "ph-calc-ohms",
    title: "Ohm's Law Calculator",
    description: "Calculate V, I, R with interactive controls.",
    category: "physics",
    type: "calculator" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Electricity",
    component: PhysicsLab,
  },
  {
    id: "ph-calc-heat",
    title: "Heat Calculator",
    description: "Calorimetry, latent heat, thermal expansion.",
    category: "physics",
    type: "calculator" as const,
    status: "active",
    color: "#ef4444",
    unit: "Unit: Heat",
    component: PhysicsLab,
  },
  {
    id: "ph-calc-optics",
    title: "Optics Lab",
    description: "Reflection, refraction, lateral shift, prism dispersion.",
    category: "physics",
    type: "calculator" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Optics",
    component: PhysicsLab,
  },
  {
    id: "ph-calc-projectile",
    title: "Projectile Motion",
    description: "Launch projectiles with adjustable velocity, angle, and gravity.",
    category: "physics",
    type: "calculator" as const,
    status: "active",
    color: "#3b82f6",
    unit: "Unit: Kinematics",
    component: PhysicsLab,
  },
  {
    id: "ai-tutor",
    title: "AI Lab Tutor",
    description: "Get instant help with lab concepts. AI explains, solves, and visualizes.",
    category: "physics",
    type: "calculator" as const,
    status: "active" as const,
    color: "#f59e0b",
    component: () => (
      <PremiumPlaceholder
        title="AI Lab Tutor"
        icon={<span className="text-amber-500">🧠</span>}
        description="Get instant help with lab concepts."
      />
    ),
  },
  {
    id: "advanced-circuit",
    title: "Advanced Circuit Simulator",
    description: "Build and test complex circuits with 50+ components.",
    category: "physics",
    type: "calculator" as const,
    status: "active" as const,
    color: "#f59e0b",
    component: PremiumAdvancedCircuitSimulator,
  },

  // ===== CHEMISTRY LABS =====
  {
    id: "ch-3d-periodic",
    title: "Periodic Table 3D",
    description: "Interactive 3D periodic table with element details, categories, and search.",
    category: "chemistry",
    type: "3d" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Periodicity",
    component: ChemistryLab,
  },
  {
    id: "ch-3d-advanced",
    title: "Chemistry 3D Advanced",
    description: "Molecular dynamics, crystallography, spectroscopy, SN1/SN2, DNA, VSEPR.",
    category: "chemistry",
    type: "3d" as const,
    status: "new",
    color: "#10b981",
    unit: "Unit: Advanced",
    component: ChemistryLab,
  },
  {
    id: "ch-3d-micro",
    title: "Microscopy 3D",
    description: "Atomic structure, electron orbitals, crystal lattice visualization.",
    category: "chemistry",
    type: "3d" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Microscopy",
    component: ChemistryLab,
  },
  {
    id: "ch-th-atomic",
    title: "Atomic Structure Theory",
    description: "Bohr model, quantum numbers, electronic configuration.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Atomic",
    component: () => <TheoryPanel subject="chemistry" topic="atomic" />,
  },
  {
    id: "ch-th-bonding",
    title: "Chemical Bonding Theory",
    description: "Ionic, covalent, metallic bonds, VSEPR theory.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Bonding",
    component: () => <TheoryPanel subject="chemistry" topic="bonding" />,
  },
  {
    id: "ch-th-eq",
    title: "Equilibrium Theory",
    description: "Chemical equilibrium, Le Chatelier's principle, Kc/Kp.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Equilibrium",
    component: () => <TheoryPanel subject="chemistry" topic="equilibrium" />,
  },
  {
    id: "ch-th-thermo",
    title: "Thermochemistry Theory",
    description: "Enthalpy, entropy, Gibbs free energy, Hess's law.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Thermo",
    component: () => <TheoryPanel subject="chemistry" topic="thermo" />,
  },
  {
    id: "ch-th-kinetics",
    title: "Chemical Kinetics Theory",
    description: "Reaction rates, order of reaction, activation energy.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Kinetics",
    component: () => <TheoryPanel subject="chemistry" topic="kinetics" />,
  },
  {
    id: "ch-th-acid",
    title: "Acid-Base Theory",
    description: "pH, pOH, strong/weak acids, buffers, titration.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Acid-Base",
    component: () => <TheoryPanel subject="chemistry" topic="acid-base" />,
  },
  {
    id: "ch-th-redox",
    title: "Redox Theory",
    description: "Oxidation-reduction, electrochemical cells, corrosion.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Redox",
    component: () => <TheoryPanel subject="chemistry" topic="redox" />,
  },
  {
    id: "ch-th-organic",
    title: "Organic Chemistry Theory",
    description: "Hydrocarbons, functional groups, nomenclature.",
    category: "chemistry",
    type: "theory" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Organic",
    component: () => <TheoryPanel subject="chemistry" topic="organic" />,
  },
  {
    id: "ch-calc-ph",
    title: "pH Calculator",
    description: "Calculate pH from concentration for acids and bases.",
    category: "chemistry",
    type: "calculator" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Acid-Base",
    component: ChemistryLab,
  },
  {
    id: "ch-calc-titration",
    title: "Titration Simulator",
    description: "Simulate strong acid-strong base titration and track pH changes.",
    category: "chemistry",
    type: "calculator" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Titration",
    component: ChemistryLab,
  },
  {
    id: "ch-calc-gas",
    title: "Gas Laws Calculator",
    description: "Boyle's, Charles's, ideal gas law solver.",
    category: "chemistry",
    type: "calculator" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Gas Laws",
    component: ChemistryLab,
  },
  {
    id: "ch-calc-molarmass",
    title: "Molar Mass Calculator",
    description: "Enter a chemical formula and get molar mass.",
    category: "chemistry",
    type: "calculator" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Stoichiometry",
    component: ChemistryLab,
  },
  {
    id: "ch-calc-stoich",
    title: "Stoichiometry Lab",
    description: "Moles, percent composition, limiting reagent.",
    category: "chemistry",
    type: "calculator" as const,
    status: "active",
    color: "#10b981",
    unit: "Unit: Stoichiometry",
    component: ChemistryLab,
  },
  {
    id: "molecular-builder",
    title: "Molecular Builder 3D",
    description: "Build any molecule from scratch. Simulate reactions.",
    category: "chemistry",
    type: "3d" as const,
    status: "active" as const,
    color: "#f59e0b",
    component: () => (
      <PremiumPlaceholder
        title="Molecular Builder 3D"
        icon={<span className="text-amber-500">🔬</span>}
        description="Build molecules from scratch."
      />
    ),
  },

  // ===== BIOLOGY LABS =====
  {
    id: "bio-3d-cell",
    title: "Cell Structure 3D",
    description: "Plant and animal cell ultrastructure — organelles, membranes, nucleus in 3D.",
    category: "biology",
    type: "3d" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Cell Biology",
    component: BiologyAdvanced3D,
  },
  {
    id: "bio-3d-dna",
    title: "DNA & Genetics 3D",
    description: "Double-helix DNA structure, replication, transcription, translation.",
    category: "biology",
    type: "3d" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Genetics",
    component: BiologyAdvanced3D,
  },
  {
    id: "bio-3d-advanced",
    title: "Biology 3D Advanced",
    description: "Cell ultrastructure, molecular genetics, ecology networks, human systems.",
    category: "biology",
    type: "3d" as const,
    status: "new",
    color: "#22c55e",
    unit: "Unit: Advanced",
    component: BiologyAdvanced3D,
  },
  {
    id: "bio-3d-ecology",
    title: "Ecology & Ecosystem 3D",
    description: "Food chains, food webs, biogeochemical cycles, population dynamics.",
    category: "biology",
    type: "3d" as const,
    status: "new",
    color: "#22c55e",
    unit: "Unit: Ecology",
    component: BiologyAdvanced3D,
  },
  {
    id: "bio-3d-human",
    title: "Human Body Systems 3D",
    description: "Circulatory, respiratory, nervous, and digestive systems with interactive labels.",
    category: "biology",
    type: "3d" as const,
    status: "new",
    color: "#22c55e",
    unit: "Unit: Human Physiology",
    component: BiologyAdvanced3D,
  },
  {
    id: "bio-3d-evolution",
    title: "Evolution & Classification 3D",
    description: "Phylogenetic trees, taxonomy hierarchy, fossil record timeline.",
    category: "biology",
    type: "3d" as const,
    status: "new",
    color: "#22c55e",
    unit: "Unit: Evolution",
    component: BiologyEvolution3D,
  },
  {
    id: "bio-th-cell",
    title: "Cell Theory & Structure",
    description: "Cell theory, prokaryotic vs eukaryotic cells, organelles, membrane transport.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Cell Biology",
    component: () => <TheoryPanel subject="biology" topic="cell" />,
  },
  {
    id: "bio-th-genetics",
    title: "Genetics & Heredity",
    description: "Mendelian genetics, DNA structure, replication, transcription, translation.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Genetics",
    component: () => <TheoryPanel subject="biology" topic="genetics" />,
  },
  {
    id: "bio-th-ecology",
    title: "Ecology & Environment",
    description: "Ecosystems, biomes, biogeochemical cycles, biodiversity, conservation.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Ecology",
    component: () => <TheoryPanel subject="biology" topic="ecology" />,
  },
  {
    id: "bio-th-human",
    title: "Human Physiology",
    description: "Circulatory, respiratory, digestive, nervous, and excretory systems.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Human Physiology",
    component: () => <TheoryPanel subject="biology" topic="human" />,
  },
  {
    id: "bio-th-evolution",
    title: "Evolution & Classification",
    description: "Origin of life, natural selection, phylogenetic classification, taxonomy.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Evolution",
    component: () => <TheoryPanel subject="biology" topic="evolution" />,
  },
  {
    id: "bio-th-plant",
    title: "Plant Physiology",
    description: "Photosynthesis, transpiration, nutrition, plant hormones, transport in plants.",
    category: "biology",
    type: "theory" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Plant Biology",
    component: () => <TheoryPanel subject="biology" topic="plant" />,
  },
  {
    id: "bio-calc-punnett",
    title: "Punnett Square Solver",
    description: "Predict offspring genotypes and phenotypes from parental crosses.",
    category: "biology",
    type: "calculator" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Genetics",
    component: BiologyPunnettCalculator,
  },
  {
    id: "bio-calc-population",
    title: "Population Growth Calculator",
    description: "Exponential and logistic population growth models with carrying capacity.",
    category: "biology",
    type: "calculator" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Ecology",
    component: BiologyPopulationCalculator,
  },
  {
    id: "bio-calc-photosynthesis",
    title: "Photosynthesis Rate Calculator",
    description: "Calculate rate of photosynthesis under varying light, CO₂, and temperature.",
    category: "biology",
    type: "calculator" as const,
    status: "active",
    color: "#22c55e",
    unit: "Unit: Plant Biology",
    component: BiologyPhotosynthesisCalculator,
  },

  // ===== MATHEMATICS LABS =====
  {
    id: "math-3d-geometry",
    title: "3D Geometry",
    description: "Points, lines, planes in 3D space with interactive visualization.",
    category: "mathematics",
    type: "3d" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: 3D Geometry",
    component: MathGeometry3D,
  },
  {
    id: "math-3d-surfaces",
    title: "3D Mathematical Surfaces",
    description: "Explore saddle, wave, ripple, peak, plane, and cylinder surfaces.",
    category: "mathematics",
    type: "3d" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Calculus",
    component: MathModern3D,
  },
  {
    id: "math-3d-advanced",
    title: "Mathematics 3D Advanced",
    description: "Surfaces + contours, divergence/curl, Mandelbulb, parametric surfaces.",
    category: "mathematics",
    type: "3d" as const,
    status: "new",
    color: "#8b5cf6",
    unit: "Unit: Vector Calculus",
    component: MathModern3D,
  },
  {
    id: "math-3d-fourier",
    title: "Fourier Series 3D",
    description: "Build square, sawtooth, and triangle waves from sums of sines.",
    category: "mathematics",
    type: "3d" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Fourier",
    component: MathAdvancedMotionLab,
  },
  {
    id: "math-3d-decay",
    title: "Nuclear Decay Simulator",
    description: "Stochastic radioactive decay visualization with half-life controls.",
    category: "mathematics",
    type: "3d" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Exponential",
    component: MathAdvancedMotionLab,
  },
  {
    id: "math-th-calculus",
    title: "Calculus Theory",
    description: "Limits, derivatives, integrals, fundamental theorem.",
    category: "mathematics",
    type: "theory" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Calculus",
    component: () => <TheoryPanel subject="mathematics" topic="calculus" />,
  },
  {
    id: "math-th-trig",
    title: "Trigonometry Theory",
    description: "Identities, equations, graphs, inverse functions.",
    category: "mathematics",
    type: "theory" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Trig",
    component: () => <TheoryPanel subject="mathematics" topic="trigonometry" />,
  },
  {
    id: "math-th-algebra",
    title: "Algebra Theory",
    description: "Matrices, determinants, complex numbers, vectors.",
    category: "mathematics",
    type: "theory" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Algebra",
    component: () => <TheoryPanel subject="mathematics" topic="algebra" />,
  },
  {
    id: "math-th-stats",
    title: "Statistics Theory",
    description: "Probability, distributions, hypothesis testing.",
    category: "mathematics",
    type: "theory" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Stats",
    component: () => <TheoryPanel subject="mathematics" topic="statistics" />,
  },
  {
    id: "math-th-geo",
    title: "Coordinate Geometry Theory",
    description: "Lines, circles, conics in coordinate plane.",
    category: "mathematics",
    type: "theory" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Geometry",
    component: () => <TheoryPanel subject="mathematics" topic="geometry" />,
  },
  {
    id: "math-calc-deriv",
    title: "Derivative Calculator",
    description: "Compute derivatives and integrals numerically.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Calculus",
    component: () => <MathInteractive defaultTab="derivative" />,
  },
  {
    id: "math-calc-quad",
    title: "Quadratic Solver",
    description: "Solve ax² + bx + c = 0 and visualize the parabola.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Algebra",
    component: () => <MathInteractive defaultTab="quadratic" />,
  },
  {
    id: "math-calc-stats",
    title: "Statistics Calculator",
    description: "Mean, median, mode, standard deviation.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Stats",
    component: () => <MathInteractive defaultTab="statistics" />,
  },
  {
    id: "math-calc-matrix",
    title: "Matrix Calculator",
    description: "Add, multiply, and transpose matrices.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Algebra",
    component: () => <MathInteractive defaultTab="matrix" />,
  },
  {
    id: "math-calc-trig",
    title: "Trigonometry Lab",
    description: "Unit circle visualization and sine/cosine/tangent graphing.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Trig",
    component: () => <MathInteractive defaultTab="trigonometry" />,
  },
  {
    id: "math-calc-series",
    title: "Sequences & Series",
    description: "Arithmetic and geometric progressions.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Sequences",
    component: () => <MathInteractive defaultTab="series" />,
  },
  {
    id: "math-calc-vectors",
    title: "Vector Operations",
    description: "Add, dot product, cross product of 3D vectors.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Vectors",
    component: () => <MathInteractive defaultTab="vectors" />,
  },
  {
    id: "math-calc-limit",
    title: "Limit Calculator",
    description: "Estimate limits numerically.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Calculus",
    component: () => <MathInteractive defaultTab="limit" />,
  },
  {
    id: "math-calc-system",
    title: "System Solver",
    description: "Solve 2×2 and 3×3 systems of linear equations.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active",
    color: "#8b5cf6",
    unit: "Unit: Algebra",
    component: () => <MathInteractive defaultTab="system" />,
  },
  {
    id: "equation-solver",
    title: "Universal Equation Solver",
    description: "Solve any physics, chemistry, or math equation.",
    category: "mathematics",
    type: "calculator" as const,
    status: "active" as const,
    color: "#f59e0b",
    component: () => <PremiumEquationSolver />,
  },

  // ===== CLASS 11 LABS =====
  {
    id: "class11-physics",
    title: "Class 11 Physics 3D Plus",
    description: "Extended 3D physics visualizations for Class 11.",
    category: "class11",
    type: "3d" as const,
    status: "new",
    color: "#3b82f6",
    unit: "Unit: Class 11 Physics",
    component: Class11Physics3DPlus,
  },
  {
    id: "class11-chemistry",
    title: "Class 11 Chemistry 3D Plus",
    description: "Extended 3D chemistry visualizations for Class 11.",
    category: "class11",
    type: "3d" as const,
    status: "new",
    color: "#10b981",
    unit: "Unit: Class 11 Chemistry",
    component: Class11Chemistry3DPlus,
  },
  {
    id: "class11-math",
    title: "Class 11 Math 3D Plus",
    description: "Extended 3D math visualizations for Class 11.",
    category: "class11",
    type: "3d" as const,
    status: "new",
    color: "#8b5cf6",
    unit: "Unit: Class 11 Math",
    component: Class11Math3DPlus,
  },
  {
    id: "class11-biology",
    title: "Class 11 Biology 3D Plus",
    description: "Extended 3D biology visualizations — cells, genetics, ecology.",
    category: "class11",
    type: "3d" as const,
    status: "new",
    color: "#22c55e",
    unit: "Unit: Class 11 Biology",
    component: Class11Biology3DPlus,
  },
];

/**
 * Get a lab by its ID
 * @param id - The lab ID
 * @returns The lab metadata or undefined
 */
export function getLabById(id: string): LabMeta | undefined {
  return LAB_REGISTRY.find((lab) => lab.id === id);
}

/**
 * Get all labs for a specific category
 * @param category - The lab category
 * @returns Array of lab metadata
 */
export function getLabsByCategory(category: string): LabMeta[] {
  return LAB_REGISTRY.filter((lab) => lab.category === category);
}

/**
 * Get labs filtered by type
 * @param category - The lab category
 * @param type - The lab type (3d, theory, calculator)
 * @returns Array of lab metadata
 */
export function getLabsByType(category: string, type: string): LabMeta[] {
  return LAB_REGISTRY.filter(
    (lab) => lab.category === category && lab.type === type
  );
}

/**
 * Search labs by query
 * @param query - Search query
 * @returns Array of matching lab metadata
 */
export function searchLabs(query: string): LabMeta[] {
  const q = query.toLowerCase();
  return LAB_REGISTRY.filter(
    (lab) =>
      lab.title.toLowerCase().includes(q) ||
      lab.description.toLowerCase().includes(q)
  );
}

/**
 * Get lab statistics
 * @returns Object with lab counts by category and type
 */
export function getLabStats() {
  const stats = {
    total: LAB_REGISTRY.length,
    byCategory: {} as Record<string, number>,
    byType: { "3d": 0, theory: 0, calculator: 0 },
    byStatus: { active: 0, new: 0, premium: 0, development: 0 },
  };

  LAB_REGISTRY.forEach((lab) => {
    stats.byCategory[lab.category] = (stats.byCategory[lab.category] || 0) + 1;
    stats.byType[lab.type]++;
    stats.byStatus[lab.status]++;
  });

  return stats;
}

