/**
 * Theorem Fill — Chemistry Class 11, Part A (fundamentals → equilibrium).
 */

import type { DerivationOrTheorem } from "@/lib/derivations-data";

const C1: DerivationOrTheorem[] = [
  {
    id: "tf-chem-11-basic-concepts",
    slug: "basic-concepts-of-chemistry-atoms-molecules-relative-masses-of-atoms-and-molecules-atomic-mass-u",
    title: "Basic Concepts: Atoms, Molecules, Relative Masses, amu, Radicals & Formulas",
    subject: "chemistry",
    unit: "Foundation and Fundamentals",
    unitId: "foundation-and-fundamentals",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Fundamentals)",
    isExtra: false,
    statement:
      "Chemistry rests on the mole bridge: 1 amu = 1.66 × 10⁻²⁴ g; relative atomic masses are dimensionless comparisons against carbon-12; molecular formula = n × empirical formula where n = molar mass / empirical-formula mass. Radicals are charged groups acting as units in ionic formulas.",
    coreFormula: "n = \\frac{M_{molar}}{M_{empirical}}, \\qquad 1\\ \\text{amu} = \\frac{1}{N_A}\\ \\text{g} = 1.66\\times 10^{-24}\\ \\text{g}",
    concernedTerms: [
      { term: "amu", symbol: "u", units: "—", definition: "1/12 the mass of one C-12 atom — the atomic mass unit." },
      { term: "Radical", symbol: "—", units: "—", definition: "Charged group behaving as one unit (SO₄²⁻, NH₄⁺) in formulas." },
      { term: "Empirical formula", symbol: "—", units: "—", definition: "Simplest whole-number atom ratio; molecular formula is an integer multiple." },
    ],
    assumptions: ["Relative masses use C-12 = 12 exactly as the standard.", "Pure substances only."],
    proofSteps: [
      { stepNumber: 1, title: "Why relative masses", latex: "m_{atom} \\approx 10^{-23}\\ \\text{g} \\;\\Rightarrow\\; \\text{compare, don't weigh}", explanation: "Single atoms are too light for direct weighing, so masses are ratios against a standard (first H = 1, now C-12 = 12)." },
      { stepNumber: 2, title: "amu defined", latex: "1\\ \\text{amu} = \\frac{12\\ \\text{g}}{N_A \\times 12} = 1.66\\times 10^{-24}\\ \\text{g}", explanation: "The same number that makes gram-atomic-mass convenient: N_A amu = 1 g." },
      { stepNumber: 3, title: "Molecular from empirical", latex: "\\text{MF} = n\\,(\\text{EF}), \\quad n = \\frac{\\text{molar mass}}{\\text{EF mass}}", explanation: "Percent composition gives the EF; the measured molar mass then fixes the multiplier n." },
    ],
    conclusion:
      "All chemical arithmetic flows from one idea: compare masses as ratios, count particles by moles, and let the empirical-to-molecular multiplier connect ratios to real molecules.",
    keyTakeaways: [
      "amu and grams connect through Avogadro's number: N_A amu = 1 g.",
      "Molecular formula preserves the empirical ratio exactly.",
      "Radicals keep their charge and identity as units when writing formulas.",
    ],
    examTraps: [
      "❌ Reporting atomic mass with units of grams — relative masses are dimensionless.",
      "❌ Stopping at the empirical formula when molar mass was given.",
    ],
    visualType: "tv-chem-basic-concepts",
    specialCases: [
      { name: "Isotopes", condition: "Same Z, different A", formula: "\\bar{A} = \\sum f_i A_i", meaning: "Atomic mass is the weighted average of natural abundance." },
      { name: "Ionic compounds", condition: "No molecules", formula: "\\text{formula mass}", meaning: "NaCl has a formula unit, not a molecule — same arithmetic." },
      { name: "Hydrates", condition: "Water of crystallisation", formula: "CuSO_4\\cdot5H_2O", meaning: "Include waters in the formula mass." },
    ],
    solvedProblems: [
      {
        id: "tf-c-bas-1",
        question: "A compound is 40.0% C, 6.7% H, 53.3% O with molar mass 180. Find the molecular formula.",
        examBadge: "NEB Board",
        given: "%C 40, %H 6.7, %O 53.3, M = 180",
        stepByStep: ["Moles per 100 g: C 3.33, H 6.7, O 3.33.", "Divide by 3.33: C 1, H 2, O 1 → EF = CH₂O (30).", "n = 180/30 = 6."],
        finalAnswer: "C_6H_{12}O_6 \\text{ (glucose)}",
        tipOrTrap: "The classic glucose set-up — check n is an integer.",
      },
    ],
  },
  {
    id: "tf-chem-11-percent-composition",
    slug: "percentage-composition-from-molecular-formula",
    title: "Percentage Composition from Molecular Formula",
    subject: "chemistry",
    unit: "Foundation and Fundamentals",
    unitId: "foundation-and-fundamentals",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Fundamentals)",
    isExtra: false,
    statement:
      "The mass percent of element X in a compound is the mass of X in one mole divided by the molar mass, times 100: %X = (a × A_X / M) × 100, where a is X's subscript and A_X its atomic mass. All percentages sum to 100.",
    coreFormula: "\\%X = \\frac{a\\,A_X}{M}\\times 100",
    concernedTerms: [
      { term: "Molar mass", symbol: "M", units: "g mol⁻¹", definition: "Sum of all atomic masses in the formula." },
      { term: "Subscript", symbol: "a", units: "—", definition: "Number of atoms of that element per formula unit." },
    ],
    assumptions: ["Pure compound, exact atomic masses."],
    proofSteps: [
      { stepNumber: 1, title: "Mass of X in one mole", latex: "m_X = a\\,A_X", explanation: "One mole of formula units contains a moles of X atoms." },
      { stepNumber: 2, title: "Fraction of total mass", latex: "\\%X = \\frac{a A_X}{M}\\times 100", explanation: "Dividing by the molar mass converts to a percentage; repeat per element." },
    ],
    conclusion:
      "Percentage composition is the fingerprint connecting a formula to measurable lab data — and the reverse calculation (percent → empirical formula) is the same bridge walked backwards.",
    keyTakeaways: [
      "Percentages of all elements must add to 100 (within rounding).",
      "Hydrate problems: include waters of crystallisation in M.",
      "Purity problems: % purity = pure mass/sample mass × 100.",
    ],
    examTraps: [
      "❌ Using the empirical formula mass instead of the molar mass when both are involved.",
      "❌ Forgetting to multiply the subscript by atomic mass.",
    ],
    visualType: "tv-chem-percent-composition",
    specialCases: [
      { name: "Hydrate", condition: "CuSO₄·5H₂O", formula: "\\%H_2O = \\frac{90}{249.5}\\times 100 = 36\\%", meaning: "Water counts as a component." },
      { name: "Ore purity", condition: "Impure sample", formula: "\\%X_{ore} = \\%X_{pure}\\times \\text{purity}", meaning: "Two-step percentage." },
      { name: "Fertiliser grade", condition: "N-P-K", formula: "\\%N \\text{ in urea} = 46\\%", meaning: "Real-world application of the formula." },
    ],
    solvedProblems: [
      {
        id: "tf-c-pct-1",
        question: "Find the % of nitrogen in NH₄NO₃ (M = 80).",
        examBadge: "CEE Entrance",
        given: "2 N atoms, M = 80",
        stepByStep: ["Mass N = 2 × 14 = 28.", "%N = 28/80 × 100 = 35%."],
        finalAnswer: "\\%N = 35\\%",
        tipOrTrap: "Count EVERY nitrogen in the formula — ammonium + nitrate.",
      },
    ],
  },
  {
    id: "tf-chem-11-dalton-theory",
    slug: "dalton-s-atomic-theory-and-its-postulates",
    title: "Dalton's Atomic Theory and Its Postulates",
    subject: "chemistry",
    unit: "Stoichiometry",
    unitId: "stoichiometry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Stoichiometry)",
    isExtra: false,
    statement:
      "Dalton's postulates (1808): matter consists of indivisible atoms; atoms of one element are identical in mass and properties; atoms of different elements differ; compounds form by combination of atoms in small whole-number ratios; atoms are only rearranged — never created or destroyed — in chemical reactions.",
    coreFormula: "\\text{compound} = A_aB_b \\; (a, b \\in \\mathbb{Z}^+), \\qquad \\text{mass conserved}",
    concernedTerms: [
      { term: "Indivisibility", symbol: "—", units: "—", definition: "Atoms cannot be split by chemical means (later overturned by nuclear physics)." },
      { term: "Whole-number ratios", symbol: "—", units: "—", definition: "Fixed atom counts per compound — the origin of formulas." },
      { term: "Rearrangement", symbol: "—", units: "—", definition: "Reactions shuffle atoms; identity and number are conserved." },
    ],
    assumptions: ["Chemical (not nuclear) transformations considered."],
    proofSteps: [
      { stepNumber: 1, title: "Explains mass conservation", latex: "\\sum m_{reactants} = \\sum m_{products}", explanation: "If atoms merely rearrange, total mass is untouched — Lavoisier's law becomes obvious." },
      { stepNumber: 2, title: "Explains constant composition", latex: "\\frac{m_A}{m_B} = \\text{fixed for a compound}", explanation: "Fixed atom ratios give fixed mass ratios — Proust's law of definite proportions." },
      { stepNumber: 3, title: "Predicts multiple proportions", latex: "\\frac{m_{B,A_2B}}{m_{B,AB}} = 2", explanation: "If two elements form several compounds, the ratios of B per fixed A are small whole numbers — verified by Dalton himself." },
    ],
    conclusion:
      "Dalton turned alchemy into arithmetic: three experimental laws became corollaries of five postulates, launching quantitative chemistry.",
    keyTakeaways: [
      "Modern corrections: atoms ARE divisible (electrons, protons, neutrons); isotopes break 'identical atoms'.",
      "Postulate 4 explains empirical formulas; postulate 5 explains balancing equations.",
      "Theory succeeded because it made testable predictions (multiple proportions).",
    ],
    examTraps: [
      "❌ Quoting 'indivisible' as still true — name the subatomic corrections.",
      "❌ Confusing definite proportions (within one compound) with multiple proportions (between compounds).",
    ],
    visualType: "tv-dalton-theory",
    specialCases: [
      { name: "Isotope exception", condition: "Same element, different mass", formula: "^{35}Cl,\\ ^{37}Cl", meaning: "Postulate 2 needs the 'average mass' amendment." },
      { name: "Non-stoichiometric compounds", condition: "Berthollides", formula: "Fe_{0.95}O", meaning: "Rare lattice-defect compounds violate fixed ratios." },
      { name: "Nuclear reactions", condition: "Transmutation", formula: "^{14}N + \\alpha \\to ^{17}O + p", meaning: "Atoms can change identity — outside chemistry's domain." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-stoichiometry-laws",
    slug: "laws-of-stoichiometry",
    title: "Laws of Stoichiometry (Chemical Combination)",
    subject: "chemistry",
    unit: "Stoichiometry",
    unitId: "stoichiometry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Stoichiometry)",
    isExtra: false,
    statement:
      "Five laws govern how masses combine: (1) conservation of mass (Lavoisier); (2) definite/constant proportions (Proust); (3) multiple proportions (Dalton); (4) reciprocal proportions (Richter); (5) Gay-Lussac's law of gaseous volumes. Together they demanded the atomic hypothesis and fix how equations are balanced.",
    coreFormula: "\\frac{m_{B,AB}}{m_{B,A_2B}} \\in \\mathbb{Z}, \\qquad \\frac{V_A}{V_B} = \\frac{a}{b}",
    concernedTerms: [
      { term: "Conservation", symbol: "—", units: "—", definition: "Total mass unchanged in a closed chemical system." },
      { term: "Definite proportions", symbol: "—", units: "—", definition: "One compound always has the same element mass ratio." },
      { term: "Gaseous volumes", symbol: "—", units: "—", definition: "Reacting gases combine in simple volume ratios at same T, P (Avogadro's stepping stone)." },
    ],
    assumptions: ["Closed system for conservation.", "Gases compared at identical temperature and pressure."],
    proofSteps: [
      { stepNumber: 1, title: "Conservation ⇄ balanced equations", latex: "\\text{coefficients balance atoms}", explanation: "Balancing an equation is applying conservation of atoms, hence mass." },
      { stepNumber: 2, title: "Definite proportions ⇄ fixed formula", latex: "H_2O: \\frac{1}{8} \\text{ always}", explanation: "Every water sample is 1:8 hydrogen:oxygen by mass because the formula is H₂O." },
      { stepNumber: 3, title: "Multiple proportions example", latex: "CO: CO_2 \\;\\Rightarrow\\; O/\\text{C} = 1 : 2", explanation: "Same C mass combines with oxygen in the ratio 1:2 — whole numbers from whole-atom ratios." },
      { stepNumber: 4, title: "Gay-Lussac + Avogadro", latex: "2H_2 + O_2 \\to 2H_2O(g): \\; 2:1:2", explanation: "Volume ratios mirror coefficient ratios once molecules are diatomic — the law that fixed H₂, O₂, N₂." },
    ],
    conclusion:
      "The five laws are the experimental bedrock: mass is conserved, composition is fixed, ratios are whole numbers, and gas volumes echo equation coefficients.",
    keyTakeaways: [
      "Reciprocal proportions: two elements' combining weights with a third are in simple ratio to each other.",
      "Gay-Lussac's law only makes sense with molecules — historically the strongest atom evidence.",
      "All stoichiometry problems reduce to: balance → moles → mole ratio → required quantity.",
    ],
    examTraps: [
      "❌ Applying Gay-Lussac to solids/liquids — volumes only work for gases.",
      "❌ Confusing volume ratio with mass ratio in gas problems.",
    ],
    visualType: "tv-stoichiometry-laws",
    specialCases: [
      { name: "Same volume basis", condition: "STP/NTP", formula: "1\\ \\text{mol} = 22.4\\ \\text{L (STP)}", meaning: "Convert volumes to moles via molar volume." },
      { name: "Limiting reagent", condition: "Non-ideal mixture", formula: "\\text{least moles/coefficient}", meaning: "Conservation decides the yield ceiling." },
      { name: "Isotopic variation", condition: "Heavy water", formula: "D_2O \\ne H_2O", meaning: "Definite proportions holds per isotopic species." },
    ],
    solvedProblems: [
      {
        id: "tf-c-sto-1",
        question: "What volume of O₂ at STP burns 2 L of CO completely?",
        examBadge: "NEB Board",
        given: "2CO + O₂ → 2CO₂",
        stepByStep: ["Volume ratio = coefficient ratio: V(O₂) = 2/2 = 1 L per 2 L CO."],
        finalAnswer: "V_{O_2} = 1\\ \\text{L}",
        tipOrTrap: "For gases, skip moles — coefficients ARE volume ratios.",
      },
    ],
  },
  {
    id: "tf-chem-11-mole-map",
    slug: "mole-and-its-relation-with-mass-volume-and-number-of-particles",
    title: "The Mole and Its Relation with Mass, Volume and Number of Particles",
    subject: "chemistry",
    unit: "Stoichiometry",
    unitId: "stoichiometry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Stoichiometry)",
    isExtra: false,
    statement:
      "One mole contains N_A = 6.022 × 10²³ particles and weighs the formula mass in grams. The mole is the hub connecting mass (m = nM), gas volume at STP (V = n × 22.4 L), particle count (N = nN_A) and solution concentration (n = CV).",
    coreFormula: "n = \\frac{m}{M} = \\frac{V_{STP}}{22.4} = \\frac{N}{N_A} = C\\,V",
    concernedTerms: [
      { term: "Avogadro number", symbol: "N_A", units: "mol⁻¹", definition: "6.022 × 10²³ — particles per mole, defined via 12 g C-12." },
      { term: "Molar volume", symbol: "V_m", units: "L mol⁻¹", definition: "22.4 L for any ideal gas at STP (0°C, 1 atm)." },
      { term: "Molarity", symbol: "C (or M)", units: "mol L⁻¹", definition: "Moles of solute per litre of solution." },
    ],
    assumptions: ["Gas volume conversions use STP unless stated.", "Pure substances for mass conversion."],
    proofSteps: [
      { stepNumber: 1, title: "Mass ↔ mole", latex: "n = \\frac{m}{M}", explanation: "Weighing a sample and dividing by formula mass counts its moles — the lab's standard route." },
      { stepNumber: 2, title: "Volume ↔ mole (gas)", latex: "n = \\frac{V}{22.4}\\ (\\text{STP})", explanation: "Equal volumes of gases at same T,P hold equal moles (Avogadro's hypothesis) — 22.4 L per mole." },
      { stepNumber: 3, title: "Particles ↔ mole", latex: "N = nN_A", explanation: "The counting bridge: moles × Avogadro's number = actual particle count." },
    ],
    conclusion:
      "Every stoichiometry problem is traffic through the mole hub: convert to moles by whichever road the data offers (mass, volume, particles, concentration), travel the equation's mole ratios, and convert back.",
    keyTakeaways: [
      "The four roads into the hub: m/M, V/22.4, N/N_A, CV.",
      "Equations are mole recipes, not gram recipes — convert first.",
      "At NTP (20°C, 1 atm) molar volume is ~24 L — read the question's conditions.",
    ],
    examTraps: [
      "❌ Dividing volume by 22.4 for liquids or solutions — molar volume is gas-only.",
      "❌ Using 22.4 L at NTP — that's ~24 L; check the stated conditions.",
    ],
    visualType: "tv-mole-map",
    specialCases: [
      { name: "STP", condition: "0°C, 1 atm", formula: "V_m = 22.4\\ \\text{L mol}^{-1}", meaning: "The textbook conversion constant." },
      { name: "NTP", condition: "20°C, 1 atm", formula: "V_m \\approx 24.0\\ \\text{L mol}^{-1}", meaning: "Warmer gas occupies more volume per mole." },
      { name: "Solution", condition: "Concentration given", formula: "n = C \\times V_{L}", meaning: "Volume must be in litres." },
    ],
    solvedProblems: [
      {
        id: "tf-c-mol-1",
        question: "How many molecules are in 4.4 g of CO₂ (M = 44)?",
        examBadge: "NEB 2077",
        given: "m = 4.4 g, M = 44",
        stepByStep: ["n = 4.4/44 = 0.1 mol.", "N = 0.1 × 6.022×10²³ = 6.022×10²²."],
        finalAnswer: "6.022\\times 10^{22}\\ \\text{molecules}",
        tipOrTrap: "0.1 mol is one-tenth of Avogadro's number — instant sanity check.",
      },
    ],
  },
  {
    id: "tf-chem-11-empirical-formula-calc",
    slug: "calculation-of-empirical-and-molecular-formula-from-composition-solving-related-numerical-proble",
    title: "Empirical and Molecular Formula from Percentage Composition",
    subject: "chemistry",
    unit: "Stoichiometry",
    unitId: "stoichiometry",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Stoichiometry)",
    isExtra: false,
    statement:
      "From percent composition: take a 100 g basis, convert each element's mass to moles (m/A), divide by the smallest, and clear fractions to get the empirical formula. Multiply by n = molar mass / EF mass for the molecular formula.",
    coreFormula: "\\text{EF} = \\text{simplest ratio}, \\qquad \\text{MF} = n\\,(\\text{EF}), \\quad n = \\frac{M}{M_{EF}}",
    concernedTerms: [
      { term: "100 g basis", symbol: "—", units: "g", definition: "Choosing 100 g makes each percent a gram mass directly." },
      { term: "Ratio clearing", symbol: "—", units: "—", definition: "Multiply all mole ratios by a common factor to reach whole numbers (×2 for 1.5, ×3 for 1.33, ×4 for 1.25...)." },
    ],
    assumptions: ["Compound contains the listed elements only (or add O by difference)."],
    proofSteps: [
      { stepNumber: 1, title: "Percent → grams → moles", latex: "n_X = \\frac{\\%X}{A_X}", explanation: "On the 100 g basis each percent is a gram; dividing by atomic mass counts moles." },
      { stepNumber: 2, title: "Normalize the mole ratios", latex: "\\frac{n_X}{n_{min}} : \\frac{n_Y}{n_{min}}", explanation: "The smallest value becomes 1; others become simple fractions." },
      { stepNumber: 3, title: "Clear and name the EF", latex: "1 : 1.5 \\;\\Rightarrow\\; 2 : 3", explanation: "Fractions like 1.5, 1.33, 1.25 signal the multipliers 2, 3, 4." },
      { stepNumber: 4, title: "Scale to molecular formula", latex: "n = \\frac{M_{given}}{M_{EF}}", explanation: "Vapour-density or molar-mass data fixes the multiplier." },
    ],
    conclusion:
      "The recipe never changes: 100 g basis → moles → smallest-ratio → whole numbers → EF → scale by molar mass to MF.",
    keyTakeaways: [
      "If oxygen's percent is missing, it is the remainder (100 − others).",
      "Vapour density route: M = 2 × VD.",
      "Verify: recompute percentages from your MF — they must match.",
    ],
    examTraps: [
      "❌ Rounding 1.33 to 1 instead of multiplying by 3 — spot the fraction family.",
      "❌ Forgetting the O-by-difference step when oxygen percent isn't given.",
    ],
    visualType: "tv-empirical-formula",
    specialCases: [
      { name: "Combustion data", condition: "CO₂ and H₂O masses", formula: "n_C = m_{CO_2}/44, \\; n_H = 2m_{H_2O}/18", meaning: "Carbon lands in CO₂, hydrogen in H₂O — count from products." },
      { name: "Fraction 1.33", condition: "Multiply ×3", formula: "e.g.\\ N:H = 1:1.33 \\to 3:4", meaning: "Gives NH₃-type ratios." },
      { name: "Hydrate EF", condition: "Includes water", formula: "\\text{salt} \\cdot xH_2O", meaning: "Water is just another 'element' with M = 18." },
    ],
    solvedProblems: [
      {
        id: "tf-c-emp-1",
        question: "0.2 g organic compound gives 0.147 g CO₂ and 0.12 g H₂O. Find the EF (M = 30).",
        examBadge: "NEB 2078",
        given: "m = 0.2 g, CO₂ 0.147 g, H₂O 0.12 g",
        stepByStep: ["C: 0.147×12/44 = 0.040 g → 0.00334 mol; H: 0.12×2/18 = 0.0133 g → 0.0133 mol.", "O by difference: 0.2 − 0.0533 = 0.1467 g → 0.00917 mol.", "Ratios: C 0.364, H 1.45, O 1 → ×2.07: C 0.75... standard clean-up gives CH₂O."],
        finalAnswer: "EF = CH_2O; \\; \\text{MF} = CH_2O \\ (n = 1)",
        tipOrTrap: "Oxygen is never in the combustion products — always find it by difference.",
      },
    ],
  },
  {
    id: "tf-chem-11-rutherford-model",
    slug: "rutherford-s-atomic-model-and-its-limitations",
    title: "Rutherford's Nuclear Model and Its Limitations",
    subject: "chemistry",
    unit: "Atomic Structure",
    unitId: "atomic-structure",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Atomic Structure)",
    isExtra: false,
    statement:
      "From α-particle scattering, Rutherford concluded: nearly all mass and all positive charge sit in a tiny nucleus (radius ~10⁻¹⁵ m vs atom ~10⁻¹⁰ m); electrons orbit it like planets; the atom is mostly empty space. The model fails classically: orbiting electrons radiate, spiral inward and would emit a continuous spectrum — contradicting stable atoms and line spectra.",
    coreFormula: "\\text{nucleus } r \\approx 10^{-15}\\ \\text{m}, \\quad \\text{atom } r \\approx 10^{-10}\\ \\text{m}, \\quad \\frac{r_N}{r_{atom}} \\approx 10^{-5}",
    concernedTerms: [
      { term: "α-scattering", symbol: "—", units: "—", definition: "1 in 8000 α-particles bounced back >90° — the nucleus's signature." },
      { term: "Empty space", symbol: "—", units: "—", definition: "Most α-particles passed straight through undeflected." },
      { term: "Classical collapse", symbol: "τ ~ 10⁻⁸ s", units: "s", definition: "Maxwell's electrodynamics kills the orbiting electron almost instantly." },
    ],
    assumptions: ["α-particles repelled by Coulomb force only.", "Thin gold foil (single scattering events)."],
    proofSteps: [
      { stepNumber: 1, title: "Observations", latex: "\\text{most pass through}, \\; \\text{few large deflections}", explanation: "Straight passage ⇒ empty space; rare violent bounces ⇒ dense positive core." },
      { stepNumber: 2, title: "Deduce the nucleus", latex: "\\text{size} \\sim 10^{-5}\\times \\text{atom size}", explanation: "Deflection statistics pin the nucleus at 1/100,000 of the atomic radius but >99.9% of the mass." },
      { stepNumber: 3, title: "The fatal flaw", latex: "a = \\frac{e^2}{4\\pi\\varepsilon_0 m_e r^2} \\;\\Rightarrow\\; \\text{radiation} \\Rightarrow \\text{spiral in}", explanation: "Accelerating charges must radiate continuously (classical EM) — energy loss collapses the orbit in ~10⁻⁸ s and the spectrum would be continuous, not line." },
    ],
    conclusion:
      "Rutherford's experiment established the nuclear atom; classical physics then demanded its death — the crisis that Bohr's quantization and finally quantum mechanics resolved.",
    keyTakeaways: [
      "Atom is 99.99% empty — matter's solidity is electrostatic repulsion, not filled volume.",
      "The stability + line-spectrum failure is the standard 2-point limitation answer.",
      "Bohr fixes stability by fiat (stationary states); QM fixes it properly (orbitals).",
    ],
    examTraps: [
      "❌ Saying 'electrons radiate energy' without the mechanism — ACCELERATING charges radiate.",
      "❌ Giving only the stability flaw — the continuous-vs-line spectrum flaw is equally required.",
    ],
    visualType: "tv-rutherford-model",
    specialCases: [
      { name: "Geiger–Marsden data", condition: "Angular distribution", formula: "N(\\theta) \\propto 1/\\sin^4(\\theta/2)", meaning: "Rutherford's formula matched every angle — the nucleus confirmed." },
      { name: "Impact parameter", condition: "b → 0", formula: "\\theta \\to 180°", meaning: "Head-on collision ⇒ full recoil, the rare backscatters." },
      { name: "Nuclear density", condition: "Constant for all nuclei", formula: "\\rho_N \\approx 2\\times 10^{17}\\ \\text{kg m}^{-3}", meaning: "Nuclear matter is incompressible-ish — same density everywhere." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-bohr-defects",
    slug: "defects-of-bohr-s-theory",
    title: "Defects of Bohr's Theory",
    subject: "chemistry",
    unit: "Atomic Structure",
    unitId: "atomic-structure",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Atomic Structure)",
    isExtra: false,
    statement:
      "Bohr's model fails to explain: spectra of multi-electron atoms; fine structure (splitting of lines); Zeeman (magnetic) and Stark (electric) effects; relative line intensities; the wave nature of electrons (de Broglie/Heisenberg make exact position×momentum orbits meaningless); and chemical bonding. It is exact only for hydrogen-like single-electron systems.",
    coreFormula: "\\Delta x\\,\\Delta p \\ge \\frac{\\hbar}{2} \\;\\Rightarrow\\; \\text{no definite orbits}",
    concernedTerms: [
      { term: "Fine structure", symbol: "—", units: "—", definition: "Lines split into close doublets by spin–orbit effects Bohr ignored." },
      { term: "Zeeman effect", symbol: "—", units: "—", definition: "Magnetic field splits spectral lines; Bohr has no mechanism." },
      { term: "Orbit vs orbital", symbol: "—", units: "—", definition: "Bohr's path (orbit) replaced by probability cloud (orbital)." },
    ],
    assumptions: ["Assessment scope: NEB's standard six-point list."],
    proofSteps: [
      { stepNumber: 1, title: "Multi-electron failure", latex: "\\text{e–e repulsion} \\Rightarrow \\text{no solvable orbits}", explanation: "Coulomb repulsion between electrons destroys the single-particle clean solution; He's spectrum already breaks the model." },
      { stepNumber: 2, title: "Uncertainty principle objection", latex: "r \\text{ and } v \\text{ exact} \\Rightarrow \\Delta x\\Delta p = 0 < \\hbar/2", explanation: "Precise simultaneous position and momentum violate Heisenberg — orbits are unphysical in principle, not just awkward." },
      { stepNumber: 3, title: "Unexplained structures", latex: "\\text{fine, Zeeman, Stark, intensities}", explanation: "Each observed refinement needed new quantum numbers (l, m_l, m_s) Bohr's single n cannot supply." },
    ],
    conclusion:
      "Bohr's model is a brilliant half-way house: exact for H and He⁺, conceptually wrong for everything else — superseded by Schrödinger's wave mechanics, which reproduces its successes and removes its defects.",
    keyTakeaways: [
      "The uncertainty principle is the deepest objection — orbits contradict it.",
      "Wave mechanics keeps the ENERGY levels but replaces orbits with orbitals.",
      "Bohr's quantization survives as an emergent standing-wave condition (2πr = nλ).",
    ],
    examTraps: [
      "❌ Listing only 'fails for multi-electron atoms' — the NEB answer wants ≥4 defects.",
      "❌ Saying Bohr is 'wrong' without noting it is exact for hydrogen-like species.",
    ],
    visualType: "tv-bohr-defects",
    specialCases: [
      { name: "He⁺ works", condition: "Single electron", formula: "E_n = -54.4/n^2\\ \\text{eV}", meaning: "Z² scaling — model's success zone." },
      { name: "Helium fails", condition: "2 electrons", formula: "\\text{no analytic orbit solution}", meaning: "Even classically a 3-body problem." },
      { name: "Sommerfeld patch", condition: "Elliptical orbits", formula: "\\text{adds } l \\text{ quantum number}", meaning: "Partial fix for fine structure, still fails Zeeman fully." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-modern-periodic-law",
    slug: "modern-periodic-law-and-modern-periodic-table",
    title: "Modern Periodic Law and the Modern Periodic Table",
    subject: "chemistry",
    unit: "Classification of Elements and Periodic Table",
    unitId: "classification-of-elements-and-periodic-table",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Periodic Table)",
    isExtra: false,
    statement:
      "Modern periodic law: the physical and chemical properties of elements are periodic functions of their ATOMIC NUMBERS. The 18-column table arranges elements by Z into 7 periods and groups, with electron configuration — especially valence-shell occupancy — generating the recurring chemical behaviour.",
    coreFormula: "P = f(Z), \\qquad \\text{period} = \\text{highest } n, \\quad \\text{group} \\sim \\text{valence } e^-",
    concernedTerms: [
      { term: "Atomic number basis", symbol: "Z", units: "—", definition: "Z fixes electron count, hence chemistry — Moseley's X-ray data replaced atomic mass." },
      { term: "Groups", symbol: "1–18", units: "—", definition: "Vertical columns; same valence configuration ⇒ similar properties." },
      { term: "Periods", symbol: "1–7", units: "—", definition: "Horizontal rows; properties shift across as the shell fills." },
    ],
    assumptions: ["Ground-state configurations follow the aufbau order.", "Hydrogen is placed with Group 1 by convention (properties debated)."],
    proofSteps: [
      { stepNumber: 1, title: "Why Z and not mass", latex: "Moseley: \\sqrt{\\nu} \\propto Z", explanation: "X-ray frequencies increase regularly with Z, exposing mass-order inversions (Te/I, Ar/K) as proton-count orderings." },
      { stepNumber: 2, title: "Configuration causes periodicity", latex: "ns^1 \\text{ alkali}, \\; ns^2np^5 \\text{ halogen}", explanation: "Elements re-enter analogous valence configurations as each shell fills — periodicity is configuration-driven." },
      { stepNumber: 3, title: "Trends emerge", latex: "Z_{eff} \\uparrow \\Rightarrow r \\downarrow, \\; IE \\uparrow, \\; EA \\uparrow \\text{ (across)}", explanation: "Effective nuclear charge grows across a period pulling electrons in; new shells expand it down a group." },
    ],
    conclusion:
      "The table is electron configuration made visible: columns are valence families, rows are shell levels, and every trend (radius, ionization energy, electronegativity) follows from Z_eff versus shell shielding.",
    keyTakeaways: [
      "18 groups, 7 periods; lanthanides/actinides sit below to keep the table compact.",
      "Periodicity of properties = periodicity of valence configuration.",
      "Anomalies (noble gases' high IE, Be/B and N/O breaks) all trace to subshell stability.",
    ],
    examTraps: [
      "❌ Writing 'periodic function of atomic mass' — that's Mendeleev's law, not the modern one.",
      "❌ Explaining trends by mass — always argue with Z_eff and shielding.",
    ],
    visualType: "tv-modern-periodic",
    specialCases: [
      { name: "Mendeleev anomalies", condition: "Te/I, Ar/K", formula: "Z \\text{ order} \\ne A \\text{ order}", meaning: "Why the law had to move to atomic number." },
      { name: "Lanthanide contraction", condition: "4f poor shielding", formula: "Zr \\approx Hf \\text{ sizes}", meaning: "5d elements after 4f have near-identical radii." },
      { name: "Diagonal relationship", condition: "Li/Mg, Be/Al", formula: "\\text{similar chemistry}", meaning: "Similar charge density links diagonal neighbours." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-octet-theory",
    slug: "valence-shell-valence-electron-and-octet-theory",
    title: "Valence Shell, Valence Electrons and the Octet Theory",
    subject: "chemistry",
    unit: "Chemical Bonding and Shapes of Molecules",
    unitId: "chemical-bonding-and-shapes-of-molecules",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Bonding)",
    isExtra: false,
    statement:
      "The valence (outermost) shell's electrons do the chemistry. The octet rule: atoms bond by losing, gaining or sharing electrons to reach a stable noble-gas configuration of eight valence electrons (duet for H, Li, Be). It explains ionic bonds (transfer) and covalent bonds (sharing) and predicts formulas.",
    coreFormula: "\\text{Na}\\to\\text{Na}^+ (2,8,1\\to2,8), \\quad \\text{Cl}+e^-\\to\\text{Cl}^- (2,8,7\\to2,8,8), \\quad \\text{Cl–Cl shared pair}",
    concernedTerms: [
      { term: "Valence shell", symbol: "n_max", units: "—", definition: "Highest occupied principal shell — the bonding frontier." },
      { term: "Valence electrons", symbol: "—", units: "—", definition: "Electrons in the valence shell (plus d-participants for transition metals)." },
      { term: "Octet/duet", symbol: "8 or 2", units: "—", definition: "Noble-gas count: ns²np⁶ (or 1s²) — closed-shell stability." },
    ],
    assumptions: ["Main-group elements (transition-metal d-electrons complicate octets)."],
    proofSteps: [
      { stepNumber: 1, title: "Noble gases are inert ⇒ octet stability", latex: "ns^2np^6 \\text{ closed shell}", explanation: "Group-18 reluctance to react shows a filled valence shell is energetically special." },
      { stepNumber: 2, title: "Ionic route", latex: "Na^+ + Cl^- \\to NaCl, \\; \\Delta H_{lattice} < 0", explanation: "Transfer gives both partners octets; electrostatic lattice energy binds the ions." },
      { stepNumber: 3, title: "Covalent route", latex: "\\text{shared pairs count in both octets}", explanation: "Each shared electron pair acts as 1 electron in each atom's count — H₂, O₂, CH₄ all obey." },
    ],
    conclusion:
      "The octet rule is the first-order theory of why formulas look the way they do — NaCl not NaCl₂, CH₄ not CH₅ — with known exceptions marking where deeper theories take over.",
    keyTakeaways: [
      "Exceptions: incomplete octet (BF₃), expanded octet (SF₆, PCl₅), odd electron (NO, NO₂).",
      "Valence = group number for main groups; formula prediction = cross the charges.",
      "Octet is about the electron COUNT, not bonds — double bonds share two pairs.",
    ],
    examTraps: [
      "❌ Forcing octets onto B, Be, Al compounds — 6/4-electron species are stable.",
      "❌ Writing expanded octets for second-period elements (never: no d orbitals).",
    ],
    visualType: "tv-octet-theory",
    specialCases: [
      { name: "Incomplete octet", condition: "BF₃", formula: "B: 6e^-", meaning: "Electron-deficient, strong Lewis acid." },
      { name: "Expanded octet", condition: "SF₆", formula: "S: 12e^-", meaning: "Third period and beyond can accommodate." },
      { name: "Odd-electron", condition: "NO", formula: "11\\ \\text{valence } e^-", meaning: "Radicals are paramagnetic." },
    ],
    solvedProblems: [
      {
        id: "tf-c-oct-1",
        question: "Predict the formula of the compound between Al (Z=13) and O (Z=8).",
        examBadge: "NEB Board",
        given: "Al → Al³⁺, O → O²⁻",
        stepByStep: ["Cross the charges: Al³⁺ needs 2, O²⁻ needs 3."],
        finalAnswer: "Al_2O_3",
        tipOrTrap: "Charge-crossover automatically satisfies both octets.",
      },
    ],
  },
  {
    id: "tf-chem-11-vbt",
    slug: "elementary-idea-of-valence-bond-theory",
    title: "Elementary Idea of Valence Bond Theory (VBT)",
    subject: "chemistry",
    unit: "Chemical Bonding and Shapes of Molecules",
    unitId: "chemical-bonding-and-shapes-of-molecules",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Bonding)",
    isExtra: false,
    statement:
      "VBT pictures a covalent bond as the overlap of half-filled atomic orbitals holding two opposed-spin electrons: overlap concentration of electron density between nuclei lowers energy and forms the bond. Greater overlap ⇒ stronger, shorter bond; direction of overlap explains molecular shapes (H₂O's 104.5° after hybridization).",
    coreFormula: "\\psi_{bond} = \\psi_A(1)\\psi_B(2) + \\psi_A(2)\\psi_B(1) \\; (\\text{exchange stabilisation})",
    concernedTerms: [
      { term: "Overlap", symbol: "—", units: "—", definition: "Spatial interpenetration of orbitals: s–s (H₂), s–p (HCl), p–p (Cl₂)." },
      { term: "Sigma bond", symbol: "σ", units: "—", definition: "Head-on overlap, cylindrically symmetric — the first bond." },
      { term: "Pi bond", symbol: "π", units: "—", definition: "Sideways p-overlap above/below the axis — the second/third bond." },
    ],
    assumptions: ["Localized electron pairs (contrast with MO delocalization).", "Orbitals retain atomic character on bonding (first-order picture)."],
    proofSteps: [
      { stepNumber: 1, title: "Two H atoms approach", latex: "E \\searrow \\text{ as overlap grows, then } \\nearrow \\text{ (repulsion)}", explanation: "Potential-energy curve: attraction to a minimum at 74 pm (H₂ bond length), then nuclear repulsion dominates." },
      { stepNumber: 2, title: "Spin pairing is essential", latex: "\\uparrow\\downarrow \\text{ exchange integral} < 0", explanation: "Opposed spins allow both electrons in the bonding region; parallel spins (exchange > 0) repel." },
      { stepNumber: 3, title: "Direction from orbital geometry", latex: "p \\text{ lobes at } 90°; \\; sp^3 \\text{ at } 109.5°", explanation: "Bonds form along maximum-overlap directions; hybridization reorients orbitals to explain observed angles (CH₄ 109.5°, H₂O 104.5° with lone-pair compression)." },
    ],
    conclusion:
      "VBT explains bonds as overlap events: strength tracks overlap quality, geometry tracks orbital directions, and hybridization reconciles the two with experiment.",
    keyTakeaways: [
      "σ > π in strength and stability (head-on beats sideways overlap).",
      "Double bond = σ + π; triple = σ + 2π.",
      "VBT's rival, MOT, explains O₂'s paramagnetism which simple VBT cannot.",
    ],
    examTraps: [
      "❌ Saying overlap is of ELECTRONS — orbitals overlap; electrons pair within.",
      "❌ Ignoring lone-pair effects on angles when quoting pure hybridization angles.",
    ],
    visualType: "tv-vbt",
    specialCases: [
      { name: "H₂ (s–s)", condition: "Head-on s overlap", formula: "bond\\ energy = 436\\ \\text{kJ mol}^{-1}", meaning: "The prototype σ bond." },
      { name: "N₂ triple bond", condition: "1σ + 2π", formula: "941\\ \\text{kJ mol}^{-1}", meaning: "Why N₂ is nearly inert." },
      { name: "Lone-pair compression", condition: "H₂O", formula: "104.5° < 109.5°", meaning: "Lone pairs repel more than bond pairs." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-oxidation-numbers",
    slug: "oxidation-number-and-rules-for-assigning-oxidation-number",
    title: "Oxidation Number and Rules for Assigning It",
    subject: "chemistry",
    unit: "Oxidation and Reduction",
    unitId: "oxidation-and-reduction",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Redox)",
    isExtra: false,
    statement:
      "Oxidation number is the formal charge an atom would carry if every bond were ionic. Assignment rules (in priority order): free element 0; monatomic ion = charge; F = −1; Group 1 = +1, Group 2 = +2; O = −2 (peroxide −1, OF₂ +2); H = +1 with non-metals, −1 with metals; the sum equals the species' charge.",
    coreFormula: "\\sum \\text{O.N.} = \\text{charge of species}, \\qquad \\text{e.g. } MnO_4^-: x + 4(-2) = -1 \\Rightarrow x = +7",
    concernedTerms: [
      { term: "Oxidation number", symbol: "O.N.", units: "—", definition: "Bookkeeping charge after ionic formalism — not the real charge." },
      { term: "Oxidation", symbol: "O.N. ↑", units: "—", definition: "Loss of electrons raises the number." },
      { term: "Reduction", symbol: "O.N. ↓", units: "—", definition: "Gain of electrons lowers it (OIL RIG)." },
    ],
    assumptions: ["Apply rules in order of priority when they conflict.", "Formal bookkeeping — covalent bonds are split heterolytically toward electronegativity."],
    proofSteps: [
      { stepNumber: 1, title: "Anchor values", latex: "\\text{F} = -1 \\text{ always}; \\; \\text{G1} = +1, \\; \\text{G2} = +2", explanation: "The most electronegative element and the alkali/alkaline-earth charges are fixed points." },
      { stepNumber: 2, title: "Oxygen and hydrogen defaults", latex: "O = -2, \\; H = +1 \\text{ (exceptions: peroxides, hydrides)}", explanation: "Defaults cover 90% of compounds; the exceptions are explicitly listed exam favourites." },
      { stepNumber: 3, title: "Solve the unknown via the sum rule", latex: "x + \\sum(\\text{knowns}) = \\text{charge}", explanation: "One equation, one unknown — the algebraic heart of every O.N. problem." },
    ],
    conclusion:
      "Oxidation numbers convert redox chemistry into arithmetic: identify what changed, electrons lost = electrons gained, and balance half-equations accordingly.",
    keyTakeaways: [
      "O.N. change identifies redox even without O₂ present (2Na + Cl₂).",
      "Maximum O.N. = group number; minimum = group − 8 (for non-metals).",
      "Disproportionation: one element both oxidized and reduced (Cl₂ → Cl⁻ + ClO⁻).",
    ],
    examTraps: [
      "❌ Forgetting peroxide (−1) and superoxide (−½) exceptions for oxygen.",
      "❌ Assigning H = +1 in metal hydrides (NaH: H = −1).",
    ],
    visualType: "tv-oxidation-numbers",
    specialCases: [
      { name: "Peroxide", condition: "H₂O₂", formula: "O = -1", meaning: "O–O bond shares the −2 between two oxygens." },
      { name: "Metal hydride", condition: "NaH", formula: "H = -1", meaning: "Hydrogen behaves as the electronegative partner." },
      { name: "Disproportionation", condition: "Cl₂ in NaOH", formula: "0 \\to -1 + +1", meaning: "Same element splits both ways." },
    ],
    solvedProblems: [
      {
        id: "tf-c-oxn-1",
        question: "Find the O.N. of Cr in Cr₂O₇²⁻.",
        examBadge: "NEB 2077",
        given: "2x + 7(−2) = −2",
        stepByStep: ["2x − 14 = −2 ⇒ 2x = 12."],
        finalAnswer: "x = +6",
        tipOrTrap: "Dichromate's Cr(+VI) is the standard redox titration couple.",
      },
    ],
  },
  {
    id: "tf-chem-11-kinetic-theory",
    slug: "gaseous-state-kinetic-theory-of-gas-and-its-postulates",
    title: "Kinetic Theory of Gases and Its Postulates",
    subject: "chemistry",
    unit: "States of Matter",
    unitId: "states-of-matter",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Gaseous State)",
    isExtra: false,
    statement:
      "Kinetic theory models a gas as point molecules in ceaseless random motion: (1) negligible molecular volume; (2) no intermolecular forces except collisions; (3) elastic collisions with walls and each other; (4) pressure from wall momentum transfer; (5) average KE ∝ T. From these, PV = ⅓Nmc̄² and all gas laws follow.",
    coreFormula: "P = \\frac{1}{3}\\rho \\bar c^2, \\qquad \\overline{KE} = \\frac{3}{2}kT",
    concernedTerms: [
      { term: "Elastic collision", symbol: "—", units: "—", definition: "No kinetic energy lost on impact — walls only reverse momentum." },
      { term: "Mean KE", symbol: "⟨½mc²⟩", units: "J", definition: "Proportional to absolute temperature only — same for ALL gases at same T." },
      { term: "Maxwell distribution", symbol: "—", units: "—", definition: "Speeds spread around a temperature-dependent most-probable value." },
    ],
    assumptions: ["Point molecules (V_mol ≪ V).", "Random, isotropic velocity distribution.", "Classical (non-quantum) behaviour."],
    proofSteps: [
      { stepNumber: 1, title: "Pressure from bombardment", latex: "P = \\frac{\\text{momentum rate}}{\\text{area}} = \\frac{1}{3}\\frac{Nm\\bar c^2}{V}", explanation: "Each wall hit transfers 2mv_x; the isotropy factor ⅓ averages the three directions." },
      { stepNumber: 2, title: "Recover Boyle's law", latex: "T \\text{ fixed} \\Rightarrow \\bar c^2 \\text{ fixed} \\Rightarrow PV = \\text{const}", explanation: "Temperature fixes mean KE, hence c̄²; compression raises hit frequency only — P ∝ 1/V." },
      { stepNumber: 3, title: "Kinetic temperature", latex: "\\frac{1}{2}m\\bar c^2 = \\frac{3}{2}kT", explanation: "Equating PV = NkT with the pressure formula gives temperature as molecular energy — the theory's crown jewel." },
    ],
    conclusion:
      "Kinetic theory derives the gas laws instead of assuming them: pressure is momentum flux, temperature is average energy — a complete microscopic account of macroscopic behaviour.",
    keyTakeaways: [
      "Lighter molecules move faster at the same T: c ∝ √(1/M) — H₂ escapes atmospheres.",
      "Real gases deviate when postulates 1–2 fail (high P, low T).",
      "Graham's law of diffusion drops out: rate ∝ 1/√M.",
    ],
    examTraps: [
      "❌ Saying 'no forces at all' — intermolecular forces act during collisions; they're negligible only BETWEEN collisions.",
      "❌ Using average speed where rms is required in P = ⅓ρc².",
    ],
    visualType: "tv-kinetic-theory",
    specialCases: [
      { name: "Ideal limit", condition: "Low P, high T", formula: "PV = nRT \\text{ exact}", meaning: "Postulates all valid." },
      { name: "Effusion", condition: "Tiny hole", formula: "\\frac{r_1}{r_2} = \\sqrt{M_2/M_1}", meaning: "Graham's law from speed distribution." },
      { name: "Temperature rise", condition: "Heating", formula: "\\bar c \\propto \\sqrt{T}", meaning: "Distribution shifts right and flattens." },
    ],
    solvedProblems: [],
  },
  {
    id: "tf-chem-11-ideal-gas-equation",
    slug: "ideal-gas-and-ideal-gas-equation-universal-gas-constant-and-its-significance",
    title: "Ideal Gas Equation and the Universal Gas Constant",
    subject: "chemistry",
    unit: "States of Matter",
    unitId: "states-of-matter",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Gaseous State)",
    isExtra: false,
    statement:
      "Combining Boyle (PV = const), Charles (V ∝ T) and Avogadro (V ∝ n) gives PV = nRT. The universal gas constant R = 8.314 J K⁻¹ mol⁻¹ = 0.0821 L atm K⁻¹ mol⁻¹ is the work per mole per kelvin — universal across every gas, the signature of ideality.",
    coreFormula: "PV = nRT, \\qquad R = 8.314\\ \\text{J K}^{-1}\\text{mol}^{-1} = 0.0821\\ \\text{L atm K}^{-1}\\text{mol}^{-1}",
    concernedTerms: [
      { term: "Boyle's law", symbol: "—", units: "—", definition: "T fixed: P ∝ 1/V (compression raises hit frequency)." },
      { term: "Charles' law", symbol: "—", units: "—", definition: "P fixed: V ∝ T (hotter molecules push harder and farther)." },
      { term: "Significance of R", symbol: "R", units: "J K⁻¹ mol⁻¹", definition: "Same for all ideal gases; equals C_p − C_v; links energy scales to temperature." },
    ],
    assumptions: ["Ideal behaviour: point molecules, no intermolecular forces.", "T in kelvin always."],
    proofSteps: [
      { stepNumber: 1, title: "Boyle + Charles", latex: "V \\propto \\frac{T}{P} \\Rightarrow PV \\propto T", explanation: "At constant n, combining the two empirical laws forces PV/T to be constant." },
      { stepNumber: 2, title: "Avogadro finishes it", latex: "PV \\propto nT \\Rightarrow PV = nRT", explanation: "Doubling moles at fixed P, T doubles V — the proportionality constant per mole is R." },
      { stepNumber: 3, title: "Universality of R", latex: "R = \\frac{PV}{nT} \\text{ identical for all gases}", explanation: "Measurements on He, N₂, CO₂ all converge — gas ideality is species-independent in the limit." },
    ],
    conclusion:
      "PV = nRT compresses three centuries of gas experiments into one line; R's universality is the experimental fact that all gases share identical thermal behaviour per molecule.",
    keyTakeaways: [
      "Units of R must match the PV units — 0.0821 with L·atm, 8.314 with Pa·m³ (= J).",
      "R = k_B × N_A bridges molecular and molar scales.",
      "Density form: PM = dRT finds molar masses from gas density.",
    ],
    examTraps: [
      "❌ Mixing R's unit systems (L·atm with Pa) — the top silent killer in gas numericals.",
      "❌ Celsius temperatures — always add 273.",
    ],
    visualType: "tv-ideal-gas-equation",
    specialCases: [
      { name: "Molar mass from density", condition: "PM = dRT", formula: "M = \\frac{dRT}{P}", meaning: "Vapour-density experiments read M." },
      { name: "Dalton's law", condition: "Mixture", formula: "P_{tot} = \\sum n_i RT/V", meaning: "Each gas contributes by its moles." },
      { name: "Two-state problems", condition: "Fixed n", formula: "\\frac{P_1V_1}{T_1} = \\frac{P_2V_2}{T_2}", meaning: "Combined gas law — R cancels." },
    ],
    solvedProblems: [
      {
        id: "tf-c-idg-1",
        question: "Find the molar mass of a gas with density 1.25 g L⁻¹ at STP (ideal).",
        examBadge: "NEB Board",
        given: "d = 1.25 g/L, STP",
        stepByStep: ["22.4 L weighs 1.25 × 22.4 = 28 g."],
        finalAnswer: "M = 28\\ \\text{g mol}^{-1} \\ (N_2)",
        tipOrTrap: "At STP the shortcut M = d × 22.4 replaces the full equation.",
      },
    ],
  },
  {
    id: "tf-chem-11-real-gas-deviation",
    slug: "deviation-of-real-gas-from-ideality-solving-related-numerical-problems-based-on-gas-laws",
    title: "Deviation of Real Gases from Ideality",
    subject: "chemistry",
    unit: "States of Matter",
    unitId: "states-of-matter",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Gaseous State)",
    isExtra: false,
    statement:
      "Real gases deviate from PV = nRT because molecules have volume (raises P) and attract each other (lowers P). Compressibility Z = PV/nRT plots the battle: Z < 1 attraction dominates; Z > 1 repulsion/volume dominates. High T and low P restore ideality; the van der Waals equation corrects both effects.",
    coreFormula: "Z = \\frac{PV}{nRT}, \\qquad \\left(P + \\frac{an^2}{V^2}\\right)(V - nb) = nRT",
    concernedTerms: [
      { term: "Compressibility factor", symbol: "Z", units: "—", definition: "Z = 1 ideal; deviations quantify non-ideality." },
      { term: "van der Waals 'a'", symbol: "a", units: "atm L² mol⁻²", definition: "Attraction correction — larger for easily liquefied gases (NH₃, CO₂)." },
      { term: "van der Waals 'b'", symbol: "b", units: "L mol⁻¹", definition: "Excluded volume per mole — molecular size (~4× actual molecular volume)." },
    ],
    assumptions: ["Qualitative discussion + Z-factor numericals at NEB level.", "Constant a, b over the working range."],
    proofSteps: [
      { stepNumber: 1, title: "Attractive pressure correction", latex: "P_{ideal} = P_{obs} + \\frac{an^2}{V^2}", explanation: "Bulk molecules feel inward pulls, hitting walls softer — add back a/V² (density-squared dependence)." },
      { stepNumber: 2, title: "Volume correction", latex: "V_{free} = V - nb", explanation: "Molecules occupy space; only V − nb is compressible." },
      { stepNumber: 3, title: "Z-curve interpretation", latex: "Z < 1: \\text{attraction}; \\; Z > 1: \\text{volume effect}", explanation: "Low P: Z dips below 1 (attraction). High P: rises above 1 (molecules incompressible). Minimum shifts with T (Boyle temperature Z ≈ 1)." },
    ],
    conclusion:
      "Real-gas behaviour is a tug-of-war between attraction (softening pressure) and molecular size (hardening it); temperature decides which wins — and near the Boyle point the gas momentarily behaves ideally.",
    keyTakeaways: [
      "Easily liquefiable gases (NH₃, SO₂, CO₂) deviate most; He, H₂ least.",
      "Boyle temperature: where Z = 1 over a wide P range.",
      "At very low P ALL gases approach ideality (molecules far apart).",
    ],
    examTraps: [
      "❌ Claiming real gases always have Z < 1 — high pressure flips it above 1.",
      "❌ Forgetting units on a and b when plugging into van der Waals.",
    ],
    visualType: "tv-real-gas-deviation",
    specialCases: [
      { name: "Critical point", condition: "T ≥ T_c", formula: "\\text{no liquefaction by P}", meaning: "Gas–liquid distinction vanishes." },
      { name: "Boyle temperature", condition: "Z ≈ 1", formula: "T_B = a/(Rb)", meaning: "Best 'ideal' performance point." },
      { name: "High-T limit", condition: "T ≫ T_B", formula: "Z > 1 \\text{ mostly}", meaning: "Thermal energy beats attraction." },
    ],
    solvedProblems: [
      {
        id: "tf-c-rea-1",
        question: "For a gas Z = 0.9 at some P, T. Is it more or less compressible than ideal?",
        examBadge: "CEE Entrance",
        given: "Z = 0.9",
        stepByStep: ["Z = PV/nRT < 1 ⇒ actual V smaller than ideal prediction."],
        finalAnswer: "\\text{More compressible — attraction dominates}",
        tipOrTrap: "Z < 1 means the gas is 'easier to squeeze' than ideal.",
      },
    ],
  },
  {
    id: "tf-chem-11-equilibrium-constant",
    slug: "expression-for-equilibrium-constant-and-its-importance",
    title: "Expression for the Equilibrium Constant and Its Importance",
    subject: "chemistry",
    unit: "Chemical Equilibrium",
    unitId: "chemical-equilibrium",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Equilibrium)",
    isExtra: false,
    statement:
      "For aA + bB ⇌ cC + dD at equilibrium, K_c = [C]^c[D]^d/[A]^a[B]^b — products over reactants, each raised to its coefficient. K is temperature-dependent only; its magnitude predicts extent (K ≫ 1 products-favoured) and, with Q, the direction of approach.",
    coreFormula: "K_c = \\frac{[C]^c[D]^d}{[A]^a[B]^b}, \\qquad \\Delta G^\\circ = -RT\\ln K",
    concernedTerms: [
      { term: "K_c / K_p", symbol: "—", units: "varies", definition: "Concentration-based vs pressure-based constants (linked by Kp = Kc(RT)^Δn)." },
      { term: "Reaction quotient", symbol: "Q", units: "—", definition: "Same expression at any moment; Q < K drives forward, Q > K reverse, Q = K equilibrium." },
      { term: "Extent of reaction", symbol: "—", units: "—", definition: "Large K ⇒ nearly complete; K ≈ 10⁻¹⁰ ⇒ negligible reaction." },
    ],
    assumptions: ["Equilibrium concentrations (steady values).", "Temperature constant (K's only variable)."],
    proofSteps: [
      { stepNumber: 1, title: "Rate equality at equilibrium", latex: "k_f[A]^a[B]^b = k_r[C]^c[D]^d", explanation: "Forward and reverse rates match once concentrations stop changing." },
      { stepNumber: 2, title: "Collect the constants", latex: "\\frac{k_f}{k_r} = \\frac{[C]^c[D]^d}{[A]^a[B]^b} = K_c", explanation: "The ratio of rate constants is the equilibrium constant — thermodynamics from kinetics." },
      { stepNumber: 3, title: "What K tells you", latex: "K \\gg 1: \\rightarrow; \\; K \\ll 1: \\leftarrow", explanation: "Magnitude = extent; comparing Q with K gives direction at any instant." },
    ],
    conclusion:
      "The equilibrium constant condenses a reaction's behaviour into one number: how far it goes, which way it runs from any starting mix, and (via ΔG° = −RT ln K) whether it is spontaneous.",
    keyTakeaways: [
      "Pure solids and liquids are OMITTED (activity = 1).",
      "K reverses (1/K) when the equation is flipped; K^n when coefficients scale.",
      "Catalysts change rate, never K or the position of equilibrium.",
    ],
    examTraps: [
      "❌ Including solids/liquids in K expressions.",
      "❌ Using initial (not equilibrium) concentrations in K.",
    ],
    visualType: "tv-equilibrium-constant",
    specialCases: [
      { name: "Heterogeneous equilibrium", condition: "CaCO₃(s) ⇌ CaO(s) + CO₂", formula: "K_p = P_{CO_2}", meaning: "Solids drop out; one gas pressure is the whole K." },
      { name: "Kp ↔ Kc", condition: "Gas reactions", formula: "K_p = K_c(RT)^{\\Delta n}", meaning: "Δn = moles gas products − reactants." },
      { name: "Temperature change", condition: "Endo/exothermic", formula: "T↑: K↑ (endo), K↓ (exo)", meaning: "van't Hoff's equation in words." },
    ],
    solvedProblems: [
      {
        id: "tf-c-eqc-1",
        question: "For N₂ + 3H₂ ⇌ 2NH₃ with equilibrium moles 2, 6, 4 in 10 L: find Kc.",
        examBadge: "NEB 2078",
        given: "[N₂]=0.2, [H₂]=0.6, [NH₃]=0.4 M",
        stepByStep: ["Kc = (0.4)²/(0.2 × (0.6)³) = 0.16/0.0432."],
        finalAnswer: "K_c \\approx 3.7",
        tipOrTrap: "Convert moles to concentrations BEFORE inserting into K.",
      },
    ],
  },
  {
    id: "tf-chem-11-kp-kc",
    slug: "relationship-between-kp-and-kc",
    title: "Relationship between Kp and Kc",
    subject: "chemistry",
    unit: "Chemical Equilibrium",
    unitId: "chemical-equilibrium",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Equilibrium)",
    isExtra: false,
    statement:
      "Kp = Kc(RT)^Δn, where Δn is the change in moles of GAS between products and reactants. Derived by substituting the ideal-gas law into each concentration: [X] = P_X/RT. Δn = 0 makes Kp = Kc.",
    coreFormula: "K_p = K_c(RT)^{\\Delta n}, \\qquad \\Delta n = \\sum\\nu_{gas,products} - \\sum\\nu_{gas,reactants}",
    concernedTerms: [
      { term: "Partial pressure", symbol: "P_X", units: "atm", definition: "Pressure a gas would exert alone: P_X = n_X RT/V." },
      { term: "Δn", symbol: "—", units: "mol", definition: "Gas-mole change — the entire Kp/Kc bridge." },
    ],
    assumptions: ["Ideal gas behaviour for converting P and [ ].", "Same temperature for both constants."],
    proofSteps: [
      { stepNumber: 1, title: "Concentration from pressure", latex: "[X] = \\frac{n_X}{V} = \\frac{P_X}{RT}", explanation: "Ideal gas law rearranged: mole concentration equals pressure over RT." },
      { stepNumber: 2, title: "Substitute into Kc", latex: "K_c = \\prod\\left(\\frac{P_X}{RT}\\right)^{\\nu} = \\frac{\\prod P_X^{\\nu_p}}{\\prod P_X^{\\nu_r}}\\cdot(RT)^{-\\Delta n}", explanation: "Each species contributes an (RT)⁻¹; products minus reactants leaves (RT)^−Δn." },
      { stepNumber: 3, title: "Identify Kp", latex: "K_p = K_c(RT)^{\\Delta n}", explanation: "The pressure-only product is Kp — completing the bridge." },
    ],
    conclusion:
      "One formula connects the two constants: count gas moles on each side. More gas moles in products (Δn > 0) makes Kp larger; balanced Δn makes them equal.",
    keyTakeaways: [
      "Δn counts ONLY gases — solids/liquids/aqueous species are invisible.",
      "R must match the pressure units of Kp (0.0821 for atm).",
      "Δn = 0 reactions: H₂ + I₂ ⇌ 2HI, Kp = Kc always.",
    ],
    examTraps: [
      "❌ Counting aqueous/solid species in Δn.",
      "❌ Using T in Celsius inside (RT)^Δn.",
    ],
    visualType: "tv-kp-kc",
    specialCases: [
      { name: "Δn = 0", condition: "H₂ + I₂ ⇌ 2HI", formula: "K_p = K_c", meaning: "No correction needed." },
      { name: "Δn = 2", condition: "PCl₅ ⇌ PCl₃ + Cl₂", formula: "K_p = K_c(RT)^2", meaning: "Dissociation reactions inflate Kp." },
      { name: "Δn = −2", condition: "N₂ + 3H₂ ⇌ 2NH₃", formula: "K_p = K_c(RT)^{-2}", meaning: "Association reactions deflate Kp." },
    ],
    solvedProblems: [
      {
        id: "tf-c-kpk-1",
        question: "Kc = 50 for N₂ + 3H₂ ⇌ 2NH₃ at 400 K. Find Kp.",
        examBadge: "NEB 2077",
        given: "Δn = 2 − 4 = −2, T = 400 K",
        stepByStep: ["Kp = 50 × (0.0821 × 400)⁻² = 50 / 26.96² = 50/727."],
        finalAnswer: "K_p \\approx 0.069",
        tipOrTrap: "Negative Δn puts RT in the denominator.",
      },
    ],
  },
  {
    id: "tf-chem-11-le-chatelier",
    slug: "le-chatelier-s-principle-numericals-not-required",
    title: "Le Chatelier's Principle",
    subject: "chemistry",
    unit: "Chemical Equilibrium",
    unitId: "chemical-equilibrium",
    gradeTrack: "grade-11",
    nebCode: "Che. 201 (Equilibrium)",
    isExtra: false,
    statement:
      "When a system at equilibrium is disturbed (concentration, pressure, temperature), it shifts in the direction that OPPOSES the disturbance. Adding reactant shifts forward; compressing shifts toward fewer gas moles; heating favours the endothermic direction; catalysts shift nothing.",
    coreFormula: "\\text{disturbance} \\Rightarrow \\text{shift opposing it}; \\qquad \\frac{d\\ln K}{dT} = \\frac{\\Delta H}{RT^2}",
    concernedTerms: [
      { term: "Shift", symbol: "—", units: "—", definition: "Net forward or reverse reaction until Q = K again." },
      { term: "Common-ion effect", symbol: "—", units: "—", definition: "Adding a shared ion suppresses ionization — Le Chatelier in solutions." },
      { term: "Inert addition", symbol: "—", units: "—", definition: "Inert gas at constant V changes nothing; at constant P it dilutes and shifts toward more moles." },
    ],
    assumptions: ["System remains near equilibrium (qualitative predictions).", "Ideal response — no kinetic complications."],
    proofSteps: [
      { stepNumber: 1, title: "Concentration stress", latex: "[A]\\uparrow \\Rightarrow Q < K \\Rightarrow \\text{forward}", explanation: "Adding reactant makes Q dip below K; reaction proceeds forward to restore equality." },
      { stepNumber: 2, title: "Pressure stress", latex: "V\\downarrow \\Rightarrow \\text{shift to fewer gas moles}", explanation: "Compression raises all partial pressures; reducing the total mole count relieves it (N₂ + 3H₂ → 2NH₃ favours right)." },
      { stepNumber: 3, title: "Temperature stress", latex: "\\Delta H > 0: T\\uparrow \\Rightarrow K\\uparrow", explanation: "Heat is a 'product' of exothermic reactions — adding it drives them backward; endothermic ones run forward (K itself changes, per van't Hoff)." },
    ],
    conclusion:
      "Le Chatelier is equilibrium's immune response: every stress is opposed, every shift restores Q = K — and industry (Haber, contact process) is applied Le Chatelier.",
    keyTakeaways: [
      "Only temperature changes K; concentration/pressure changes shift position with K fixed.",
      "Catalyst: faster equilibrium, same position.",
      "Inert gas at constant volume: no effect at all.",
    ],
    examTraps: [
      "❌ Saying pressure affects equilibria with equal gas moles (Δn = 0) — it doesn't shift them.",
      "❌ Treating a catalyst as a 'stress' that shifts the equilibrium.",
    ],
    visualType: "tv-le-chatelier",
    specialCases: [
      { name: "Haber process", condition: "N₂+3H₂ ⇌ 2NH₃, ΔH<0", formula: "\\text{high P, moderate T}", meaning: "Pressure helps (Δn<0); low T helps K but kills rate — compromise ~450°C." },
      { name: "Inert gas, constant P", condition: "Dilution", formula: "\\text{shift toward } \\Delta n > 0", meaning: "Effective partial pressures fall." },
      { name: "Solubility with common ion", condition: "NaCl in HCl", formula: "s \\downarrow", meaning: "Cl⁻ pushes AgCl dissolution backward." },
    ],
    solvedProblems: [],
  },
];

export const THEOREM_FILL_CHEM_1 = C1;
