"use client";

import React from "react";
import { ChapterAnimation } from "@/components/lab/chapter-animation";

type LabComponentMap = Record<string, () => React.ReactNode>;

const make = (slug: string, title: string, unit?: string, subject?: string) => {
  const TopicLab = () =>
    React.createElement(ChapterAnimation, { topicSlug: slug, topicTitle: title, unitSlug: unit, subjectSlug: subject });
  TopicLab.displayName = `TopicLab(${slug})`;
  return TopicLab;
};

const PHYSICS_11: LabComponentMap = {
  "physical-quantities": make("physical-quantities", "Physical Quantities", "physical-quantities", "physics"),
  "precision-and-significant-figures": make("precision", "Precision and Significant Figures", "physical-quantities", "physics"),
  "dimensions-and-uses-of-dimensional-analysis": make("dimensions", "Dimensions and Dimensional Analysis", "physical-quantities", "physics"),
  "vectors": make("vectors", "Vectors", "vectors", "physics"),
  "triangle-parallelogram-and-polygon-laws-of-vectors": make("triangle", "Triangle Parallelogram Polygon Laws", "vectors", "physics"),
  "resolution-of-vectors-unit-vectors": make("resolution", "Resolution of Vectors", "vectors", "physics"),
  "scalar-and-vector-products": make("dot product", "Scalar and Vector Products", "vectors", "physics"),
  "kinematics": make("kinematics", "Kinematics", "kinematics", "physics"),
  "instantaneous-velocity-and-acceleration": make("instantaneous velocity", "Instantaneous Velocity & Acceleration", "kinematics", "physics"),
  "relative-velocity": make("relative velocity", "Relative Velocity", "kinematics", "physics"),
  "equation-of-motion-graphical-treatment": make("equation of motion", "Equation of Motion", "kinematics", "physics"),
  "motion-of-a-freely-falling-body": make("freely falling", "Freely Falling Body", "kinematics", "physics"),
  "projectile-motion-and-its-applications": make("projectile", "Projectile Motion", "kinematics", "physics"),
  "dynamics": make("dynamics", "Dynamics", "dynamics", "physics"),
  "linear-momentum-impulse": make("momentum", "Linear Momentum and Impulse", "dynamics", "physics"),
  "conservation-of-linear-momentum": make("momentum", "Conservation of Linear Momentum", "dynamics", "physics"),
  "application-of-newtons-laws": make("newton", "Application of Newton's Laws", "dynamics", "physics"),
  "moment-torque-and-equilibrium": make("torque", "Moment, Torque & Equilibrium", "dynamics", "physics"),
  "solid-friction-laws-of-solid-friction-and-their-verifications": make("friction", "Solid Friction", "dynamics", "physics"),
  "work-energy-and-power": make("work", "Work, Energy and Power", "work-energy-and-power", "physics"),
  "work-done-by-a-constant-force-and-a-variable-force": make("work", "Work Done", "work-energy-and-power", "physics"),
  "power": make("power", "Power", "work-energy-and-power", "physics"),
  "work-energy-theorem-kinetic-and-potential-energy": make("kinetic energy", "Work-Energy Theorem", "work-energy-and-power", "physics"),
  "conservation-of-energy": make("conservation of energy", "Conservation of Energy", "work-energy-and-power", "physics"),
  "conservative-and-non-conservative-forces": make("conservative", "Conservative Forces", "work-energy-and-power", "physics"),
  "elastic-and-inelastic-collisions": make("elastic collision", "Elastic and Inelastic Collisions", "work-energy-and-power", "physics"),
  "circular-motion": make("circular", "Circular Motion", "circular-motion", "physics"),
  "angular-displacement-velocity-and-acceleration": make("angular", "Angular Motion", "circular-motion", "physics"),
  "relation-between-angular-and-linear-velocity-and-acceleration": make("angular", "Angular vs Linear", "circular-motion", "physics"),
  "centripetal-acceleration-and-centripetal-force": make("centripetal", "Centripetal Force", "circular-motion", "physics"),
  "conical-pendulum": make("conical pendulum", "Conical Pendulum", "circular-motion", "physics"),
  "motion-in-a-vertical-circle": make("vertical circle", "Motion in Vertical Circle", "circular-motion", "physics"),
  "applications-of-banking": make("banking", "Banking of Roads", "circular-motion", "physics"),
  "gravitation": make("gravitation", "Gravitation", "gravitation", "physics"),
  "newtons-law-of-gravitation": make("newton", "Newton's Law of Gravitation", "gravitation", "physics"),
  "gravitational-field-strength": make("gravitational", "Gravitational Field", "gravitation", "physics"),
  "gravitational-potential-gravitational-potential-energy": make("potential", "Gravitational Potential", "gravitation", "physics"),
  "variation-in-value-of-g-due-to-altitude-and-depth": make("altitude", "Variation of g", "gravitation", "physics"),
  "centre-of-mass-and-centre-of-gravity": make("centre of mass", "Centre of Mass", "gravitation", "physics"),
  "motion-of-a-satellite-orbital-velocity-and-time-period-of-the-satellite": make("satellite", "Satellite Motion", "gravitation", "physics"),
  "escape-velocity": make("escape velocity", "Escape Velocity", "gravitation", "physics"),
  "potential-and-kinetic-energy-of-the-satellite": make("satellite", "Satellite Energy", "gravitation", "physics"),
  "geostationary-satellite": make("geostationary", "Geostationary Satellite", "gravitation", "physics"),
  "gps": make("satellite", "GPS", "gravitation", "physics"),
  "elasticity": make("elastic", "Elasticity", "elasticity", "physics"),
  "hookes-law-force-constant": make("hooke", "Hooke's Law", "elasticity", "physics"),
  "stress-strain-elasticity-and-plasticity": make("stress", "Stress & Strain", "elasticity", "physics"),
  "elastic-modulus-young-modulus-bulk-modulus-shear-modulus": make("young", "Elastic Modulus", "elasticity", "physics"),
  "poissons-ratio": make("poisson", "Poisson's Ratio", "elasticity", "physics"),
  "elastic-potential-energy": make("elastic potential", "Elastic Potential Energy", "elasticity", "physics"),
  "heat-and-temperature": make("heat", "Heat and Temperature", "heat-and-temperature", "physics"),
  "molecular-concept-of-thermal-energy-heat-and-temperature-cause-and-direction-of-heat-flow": make("thermal", "Thermal Energy", "heat-and-temperature", "physics"),
  "meaning-of-thermal-equilibrium-and-zeroth-law-of-thermodynamics": make("zeroth law", "Zeroth Law", "heat-and-temperature", "physics"),
  "thermal-equilibrium-as-a-working-principle-of-a-mercury-thermometer": make("mercury thermometer", "Mercury Thermometer", "heat-and-temperature", "physics"),
  "thermal-expansion": make("thermal expansion", "Thermal Expansion", "thermal-expansion", "physics"),
  "linear-expansion-and-its-measurement": make("linear expansion", "Linear Expansion", "thermal-expansion", "physics"),
  "cubical-expansion-superficial-expansion-and-their-relation-with-linear-expansion": make("cubical expansion", "Cubical Expansion", "thermal-expansion", "physics"),
  "liquid-expansion-absolute-and-apparent": make("liquid expansion", "Liquid Expansion", "thermal-expansion", "physics"),
  "dulong-and-petit-method-of-determining-expansivity-of-liquid": make("dulong", "Dulong-Petit", "thermal-expansion", "physics"),
  "quantity-of-heat": make("specific heat", "Quantity of Heat", "quantity-of-heat", "physics"),
  "newtons-law-of-cooling": make("newtons law of cooling", "Newton's Law of Cooling", "quantity-of-heat", "physics"),
  "measurement-of-specific-heat-capacity-of-solids-and-liquids": make("specific heat", "Specific Heat Capacity", "quantity-of-heat", "physics"),
  "change-of-phases-latent-heat": make("change of phase", "Change of Phases", "quantity-of-heat", "physics"),
  "specific-latent-heat-of-fusion-and-vaporization": make("specific latent", "Specific Latent Heat", "quantity-of-heat", "physics"),
  "measurement-of-specific-latent-heat-of-fusion-and-vaporization": make("specific latent", "Latent Heat Measurement", "quantity-of-heat", "physics"),
  "triple-point": make("triple point", "Triple Point", "quantity-of-heat", "physics"),
  "rate-of-heat-flow": make("conduction", "Rate of Heat Flow", "rate-of-heat-flow", "physics"),
  "conduction-thermal-conductivity-and-measurement": make("thermal conductivity", "Thermal Conductivity", "rate-of-heat-flow", "physics"),
  "convection": make("convection", "Convection", "rate-of-heat-flow", "physics"),
  "radiation-ideal-radiator": make("radiation", "Radiation", "rate-of-heat-flow", "physics"),
  "black-body-radiation": make("black body", "Black-body Radiation", "rate-of-heat-flow", "physics"),
  "stefan-boltzmann-law": make("stefan", "Stefan-Boltzmann Law", "rate-of-heat-flow", "physics"),
  "ideal-gas": make("ideal gas", "Ideal Gas", "ideal-gas", "physics"),
  "ideal-gas-equation": make("ideal gas", "Ideal Gas Equation", "ideal-gas", "physics"),
  "molecular-properties-of-matter": make("molecular", "Molecular Properties", "ideal-gas", "physics"),
  "kinetic-molecular-model-of-an-ideal-gas": make("kinetic theory", "Kinetic-molecular Model", "ideal-gas", "physics"),
  "derivation-of-pressure-exerted-by-gas": make("kinetic theory", "Pressure Derivation", "ideal-gas", "physics"),
  "average-translational-kinetic-energy-of-gas-molecule": make("kinetic energy", "Translational KE", "ideal-gas", "physics"),
  "boltzmann-constant-root-mean-square-speed": make("boltzmann", "Boltzmann Constant", "ideal-gas", "physics"),
  "heat-capacities-of-gases-and-solids": make("heat capacity", "Heat Capacities", "ideal-gas", "physics"),
  "reflection-at-curved-mirror": make("mirror", "Reflection at Curved Mirror", "reflection-at-curved-mirror", "physics"),
  "real-and-virtual-images": make("real", "Real & Virtual Images", "reflection-at-curved-mirror", "physics"),
  "mirror-formula": make("mirror", "Mirror Formula", "reflection-at-curved-mirror", "physics"),
  "refraction-at-plane-surfaces": make("refraction", "Refraction at Plane Surfaces", "refraction-at-plane-surfaces", "physics"),
  "laws-of-refraction-refractive-index": make("refraction", "Laws of Refraction", "refraction-at-plane-surfaces", "physics"),
  "relation-between-refractive-indices": make("refraction", "Refractive Indices", "refraction-at-plane-surfaces", "physics"),
  "lateral-shift": make("lateral shift", "Lateral Shift", "refraction-at-plane-surfaces", "physics"),
  "total-internal-reflection": make("total internal", "Total Internal Reflection", "refraction-at-plane-surfaces", "physics"),
  "refraction-through-prisms": make("prism", "Refraction through Prisms", "refraction-through-prisms", "physics"),
  "minimum-deviation-condition": make("minimum deviation", "Minimum Deviation", "refraction-through-prisms", "physics"),
  "relation-between-the-angle-of-prism-minimum-deviation-and-refractive-index": make("prism", "Prism Formula", "refraction-through-prisms", "physics"),
  "deviation-in-small-angle-prism": make("small-angle prism", "Small-Angle Prism", "refraction-through-prisms", "physics"),
  "lenses": make("lens", "Lenses", "lenses", "physics"),
  "spherical-lenses-angular-magnification": make("angular magnification", "Spherical Lenses", "lenses", "physics"),
  "lens-makers-formula": make("lens maker", "Lens Maker's Formula", "lenses", "physics"),
  "power-of-a-lens": make("power of a lens", "Power of a Lens", "lenses", "physics"),
  "dispersion": make("dispersive", "Dispersion", "dispersion", "physics"),
  "pure-spectrum-and-dispersive-power": make("pure spectrum", "Pure Spectrum", "dispersion", "physics"),
  "chromatic-and-spherical-aberration": make("chromatic", "Aberration", "dispersion", "physics"),
  "achromatism-and-its-applications": make("achromatism", "Achromatism", "dispersion", "physics"),
  "electric-charges": make("electric charge", "Electric Charges", "electric-charges", "physics"),
  "coulombs-law-force-between-two-point-charges": make("coulomb", "Coulomb's Law", "electric-charges", "physics"),
  "force-between-multiple-electric-charges": make("coulomb", "Force Between Charges", "electric-charges", "physics"),
  "charging-by-induction": make("induction", "Charging by Induction", "electric-charges", "physics"),
  "electric-field": make("electric field", "Electric Field", "electric-field", "physics"),
  "electric-field-due-to-point-charges-field-lines": make("field lines", "Field Lines", "electric-field", "physics"),
  "gauss-law-electric-flux": make("gauss", "Gauss Law", "electric-field", "physics"),
  "application-of-gauss-law-field-of-a-charge-sphere-and-line-charge-and-charged-plane-conductor": make("gauss", "Gauss Applications", "electric-field", "physics"),
  "potential-potential-difference-and-potential-energy": make("potential", "Potential & Potential Energy", "potential-potential-difference-and-potential-energy", "physics"),
  "potential-difference-potential-due-to-a-point-charge-potential-energy-electron-volt": make("potential", "Potential Difference", "potential-potential-difference-and-potential-energy", "physics"),
  "equipotential-lines-and-surfaces": make("equipotential", "Equipotential Surfaces", "potential-potential-difference-and-potential-energy", "physics"),
  "potential-gradient": make("potential gradient", "Potential Gradient", "potential-potential-difference-and-potential-energy", "physics"),
  "capacitor": make("capacit", "Capacitor", "capacitor", "physics"),
  "capacitance-and-capacitor": make("capacit", "Capacitance & Capacitor", "capacitor", "physics"),
  "parallel-plate-capacitor": make("parallel plate", "Parallel Plate Capacitor", "capacitor", "physics"),
  "combination-of-capacitors": make("capacit", "Combination of Capacitors", "capacitor", "physics"),
  "energy-of-a-charged-capacitor": make("capacit", "Energy of a Capacitor", "capacitor", "physics"),
  "effect-of-a-dielectric-polarization-and-displacement": make("dielectric", "Dielectric", "capacitor", "physics"),
  "dc-circuits": make("circuit", "DC Circuits", "dc-circuits", "physics"),
  "electric-currents-drift-velocity-and-its-relation-with-current": make("drift velocity", "Drift Velocity", "dc-circuits", "physics"),
  "ohms-law-electrical-resistance-resistivity-conductivity": make("ohm", "Ohm's Law", "dc-circuits", "physics"),
  "current-voltage-relations-ohmic-and-non-ohmic-resistance": make("ohmic", "Ohmic and Non-ohmic", "dc-circuits", "physics"),
  "resistances-in-series-and-parallel": make("series and parallel", "Series & Parallel", "dc-circuits", "physics"),
  "potential-divider": make("potential divider", "Potential Divider", "dc-circuits", "physics"),
  "electromotive-force-of-a-source-internal-resistance": make("emf", "EMF & Internal Resistance", "dc-circuits", "physics"),
  "work-and-power-in-electrical-circuits": make("power", "Work & Power in Circuits", "dc-circuits", "physics"),
  "nuclear-physics": make("nuclear", "Nuclear Physics", "nuclear-physics", "physics"),
  "nucleus-discovery-of-nucleus": make("nucleus", "Discovery of Nucleus", "nuclear-physics", "physics"),
  "nuclear-density-mass-number-atomic-number": make("nuclear", "Nuclear Density", "nuclear-physics", "physics"),
  "atomic-mass-isotopes": make("isotope", "Atomic Mass & Isotopes", "nuclear-physics", "physics"),
  "einsteins-mass-energy-relation": make("einstein", "Einstein's Mass-Energy Relation", "nuclear-physics", "physics"),
  "mass-defect-packing-factor-binding-energy-per-nucleon": make("binding energy", "Mass Defect", "nuclear-physics", "physics"),
  "creation-and-annihilation": make("creation", "Creation & Annihilation", "nuclear-physics", "physics"),
  "nuclear-fission-and-fusion": make("fission", "Nuclear Fission & Fusion", "nuclear-physics", "physics"),
  "solids": make("semiconductor", "Solids", "solids", "physics"),
  "energy-bands-in-solids-qualitative-ideas": make("energy band", "Energy Bands", "solids", "physics"),
  "difference-between-metals-insulators-and-semiconductors-using-band-theory": make("semiconductor", "Metals vs Insulators", "solids", "physics"),
  "intrinsic-and-extrinsic-semiconductors": make("intrinsic", "Intrinsic & Extrinsic Semiconductors", "solids", "physics"),
  "recent-trends-in-physics": make("particle", "Recent Trends in Physics", "recent-trends-in-physics", "physics"),
  "particle-physics-particles-and-antiparticles-quarks-baryons-and-mesons-and-leptons-neutrinos": make("quark", "Particle Physics", "recent-trends-in-physics", "physics"),
  "universe-big-bang-and-hubble-law-expansion-of-the-universe": make("big bang", "Big Bang & Hubble", "recent-trends-in-physics", "physics"),
  "dark-matter-black-hole-and-gravitational-wave": make("dark matter", "Dark Matter & Black Holes", "recent-trends-in-physics", "physics"),
};

export { PHYSICS_11 };
const CHEMISTRY_11: LabComponentMap = {
  "foundation-and-fundamentals": make("atom", "Foundation & Fundamentals", "foundation-and-fundamentals", "chemistry"),
  "general-introduction-of-chemistry": make("atom", "General Introduction", "foundation-and-fundamentals", "chemistry"),
  "importance-and-scope-of-chemistry": make("atom", "Scope of Chemistry", "foundation-and-fundamentals", "chemistry"),
  "basic-concepts-of-chemistry-atoms-molecules-relative-masses-of-atoms-and-molecules-atomic-mass-unit-amu-radicals-molecular-formula-empirical-formula": make("atom", "Basic Concepts", "foundation-and-fundamentals", "chemistry"),
  "percentage-composition-from-molecular-formula": make("molecular formula", "Percentage Composition", "foundation-and-fundamentals", "chemistry"),
  "stoichiometry": make("stoichi", "Stoichiometry", "stoichiometry", "chemistry"),
  "daltons-atomic-theory-and-its-postulates": make("dalton", "Dalton's Atomic Theory", "stoichiometry", "chemistry"),
  "laws-of-stoichiometry": make("law of conservation", "Laws of Stoichiometry", "stoichiometry", "chemistry"),
  "avogadros-law-and-some-deductions-molecular-mass-and-vapour-density-molecular-mass-and-volume-of-gas-molecular-mass-and-number-of-particles": make("avogadro", "Avogadro's Law", "stoichiometry", "chemistry"),
  "mole-and-its-relation-with-mass-volume-and-number-of-particles": make("mole", "Mole Concept", "stoichiometry", "chemistry"),
  "calculations-based-on-mole-concept": make("mole", "Mole Calculations", "stoichiometry", "chemistry"),
  "limiting-reactant-and-excess-reactant": make("limiting reactant", "Limiting Reactant", "stoichiometry", "chemistry"),
  "theoretical-yield-experimental-yield-and-yield": make("yield", "Yields", "stoichiometry", "chemistry"),
  "calculation-of-empirical-and-molecular-formula-from-composition-solving-related-numerical-problems": make("empirical formula", "Empirical & Molecular Formula", "stoichiometry", "chemistry"),
  "atomic-structure": make("atom", "Atomic Structure", "atomic-structure", "chemistry"),
  "rutherfords-atomic-model-and-its-limitations": make("rutherford", "Rutherford's Model", "atomic-structure", "chemistry"),
  "postulates-of-bohrs-atomic-model-and-its-application": make("bohr", "Bohr's Model", "atomic-structure", "chemistry"),
  "spectrum-of-hydrogen-atom": make("hydrogen spectrum", "Hydrogen Spectrum", "atomic-structure", "chemistry"),
  "defects-of-bohrs-theory": make("bohr", "Defects of Bohr's Theory", "atomic-structure", "chemistry"),
  "elementary-idea-of-quantum-mechanical-model-de-broglies-wave-equation": make("de broglie", "Quantum Mechanical Model", "atomic-structure", "chemistry"),
  "heisenbergs-uncertainty-principle-and-concept-of-probability": make("uncertainty", "Uncertainty Principle", "atomic-structure", "chemistry"),
  "quantum-numbers": make("quantum number", "Quantum Numbers", "atomic-structure", "chemistry"),
  "orbitals-and-shape-of-s-and-p-orbitals-only": make("orbital", "Orbitals", "atomic-structure", "chemistry"),
  "aufbau-principle-paulis-exclusion-principle-hunds-rule-and-electronic-configurations-of-atoms-and-ions-up-to-atomic-no-30": make("aufbau", "Aufbau Principle", "atomic-structure", "chemistry"),
  "classification-of-elements-and-periodic-table": make("periodic", "Periodic Table", "classification-of-elements-and-periodic-table", "chemistry"),
  "modern-periodic-law-and-modern-periodic-table": make("periodic", "Modern Periodic Law", "classification-of-elements-and-periodic-table", "chemistry"),
  "classification-of-elements-into-different-groups-periods-and-blocks": make("periodic", "Groups Periods Blocks", "classification-of-elements-and-periodic-table", "chemistry"),
  "iupac-classification-of-elements": make("periodic", "IUPAC Classification", "classification-of-elements-and-periodic-table", "chemistry"),
  "nuclear-charge-and-effective-nuclear-charge": make("effective nuclear", "Nuclear Charge", "classification-of-elements-and-periodic-table", "chemistry"),
  "periodic-trend-and-periodicity-atomic-radii-ionic-radii-ionization-energy-electron-affinity-electronegativity-metallic-characters-general-trend-and-explanation-only": make("ionization", "Periodic Trends", "classification-of-elements-and-periodic-table", "chemistry"),
  "chemical-bonding-and-shapes-of-molecules": make("bond", "Chemical Bonding", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "valence-shell-valence-electron-and-octet-theory": make("octet", "Octet Theory", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "ionic-bond-and-its-properties": make("ionic", "Ionic Bond", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "covalent-bond-and-coordinate-covalent-bond-properties-of-covalent-compounds": make("covalent", "Covalent Bond", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "lewis-dot-structure-of-some-common-compounds-of-s-and-p-block-elements": make("lewis", "Lewis Dot Structures", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "resonance": make("resonance", "Resonance", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "vsepr-theory-and-shapes-of-simple-molecules-bef2-bf3-ch4-ch3cl-pcl5-sf6-h2o-nh3-co2-h2s-ph3": make("vsepr", "VSEPR Theory", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "elementary-idea-of-valence-bond-theory": make("valence bond", "Valence Bond Theory", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "hybridization-involving-s-and-p-orbitals-only": make("hybrid", "Hybridization", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "bond-characteristics-bond-length-ionic-character-dipole-moment": make("dipole", "Bond Characteristics", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "vander-waals-force-and-molecular-solids-hydrogen-bonding-and-its-application": make("hydrogen bond", "Vander Waals & H-bond", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "metallic-bonding-and-properties-of-metallic-solids": make("metallic bond", "Metallic Bonding", "chemical-bonding-and-shapes-of-molecules", "chemistry"),
  "oxidation-and-reduction": make("oxidation", "Oxidation & Reduction", "oxidation-and-reduction", "chemistry"),
  "general-and-electronic-concept-of-oxidation-and-reduction": make("oxidation", "Concepts of Redox", "oxidation-and-reduction", "chemistry"),
  "oxidation-number-and-rules-for-assigning-oxidation-number": make("oxidation number", "Oxidation Number", "oxidation-and-reduction", "chemistry"),
  "balancing-redox-reactions-by-oxidation-number-and-ion-electron-half-reaction-method": make("redox", "Balancing Redox", "oxidation-and-reduction", "chemistry"),
  "electrolysis-qualitative-aspect": make("electrolysis", "Electrolysis Qualitative", "oxidation-and-reduction", "chemistry"),
  "electrolysis-quantitative-aspect-faradays-laws-of-electrolysis": make("faraday", "Faraday's Laws", "oxidation-and-reduction", "chemistry"),
  "states-of-matter": make("state", "States of Matter", "states-of-matter", "chemistry"),
  "gaseous-state-kinetic-theory-of-gas-and-its-postulates": make("kinetic theory", "Kinetic Theory", "states-of-matter", "chemistry"),
  "gas-laws-boyles-law-charles-law-avogadros-law-combined-gas-equation-daltons-law-of-partial-pressure-grahams-law-of-diffusion": make("boyle", "Gas Laws", "states-of-matter", "chemistry"),
  "ideal-gas-and-ideal-gas-equation-universal-gas-constant-and-its-significance": make("ideal gas", "Ideal Gas Equation", "states-of-matter", "chemistry"),
  "deviation-of-real-gas-from-ideality-solving-related-numerical-problems-based-on-gas-laws": make("ideal gas", "Real Gas Deviation", "states-of-matter", "chemistry"),
  "liquid-state-physical-properties-of-liquids-evaporation-and-condensation-vapour-pressure-and-boiling-point-surface-tension-and-viscosity-qualitative-idea-only": make("vapour pressure", "Liquid Properties", "states-of-matter", "chemistry"),
  "liquid-crystals-and-their-applications": make("liquid crystal", "Liquid Crystals", "states-of-matter", "chemistry"),
  "solid-state-types-of-solids-amorphous-and-crystalline-solids": make("amorphous", "Amorphous & Crystalline", "states-of-matter", "chemistry"),
  "efflorescent-deliquescent-and-hygroscopic-solids-crystallization-and-crystal-growth-water-of-crystallization": make("crystallization", "Crystallization", "states-of-matter", "chemistry"),
  "introduction-to-unit-crystal-lattice-and-unit-cell": make("unit cell", "Crystal Lattice", "states-of-matter", "chemistry"),
  "chemical-equilibrium": make("equilibrium", "Chemical Equilibrium", "chemical-equilibrium", "chemistry"),
  "physical-and-chemical-equilibrium-dynamic-nature-of-chemical-equilibrium": make("dynamic", "Dynamic Equilibrium", "chemical-equilibrium", "chemistry"),
  "law-of-mass-action": make("mass action", "Law of Mass Action", "chemical-equilibrium", "chemistry"),
  "expression-for-equilibrium-constant-and-its-importance": make("equilibrium", "Equilibrium Constant", "chemical-equilibrium", "chemistry"),
  "relationship-between-kp-and-kc": make("kp", "Kp and Kc", "chemical-equilibrium", "chemistry"),
  "le-chateliers-principle-numericals-not-required": make("le chatelier", "Le Chatelier's Principle", "chemical-equilibrium", "chemistry"),
};

const CHEMISTRY_11_NONMETALS = [
  "chemistry-of-non-metals",
  "hydrogen-chemistry-of-atomic-and-nascent-hydrogen-isotopes-of-hydrogen-and-their-uses",
  "application-of-hydrogen-as-fuel-heavy-water-and-its-applications",
  "allotropes-of-oxygen-definition-of-allotropy-and-examples-oxygen-types-of-oxides-acidic-basic-neutral-amphoteric-peroxide-and-mixed-oxides",
  "applications-of-hydrogen-peroxide-medical-and-industrial-application-of-oxygen",
  "ozone-occurrence-preparation-of-ozone-from-oxygen-structure-of-ozone-test-for-ozone-uses-of-ozone",
  "ozone-layer-depletion-causes-effects-and-control-measures",
  "nitrogen-reason-for-inertness-of-nitrogen-and-active-nitrogen",
  "chemical-properties-of-ammonia-action-with-cuso4-solution-water-fecl3-solution-conc-hcl-mercurous-nitrate-paper-o2-applications-and-harmful-effects-of-ammonia",
  "oxy-acids-of-nitrogen-name-and-formula",
  "chemical-properties-of-nitric-acid-hno3-as-an-acid-and-oxidizing-agent-action-with-zinc-magnesium-iron-copper-sulphur-carbon-so2-and-h2s-ring-test-for-nitrate-ion",
  "halogens-general-characteristics-of-halogens-comparative-study-on-preparation-chemical-properties-with-water-alkali-ammonia-oxidizing-character-bleaching-action-and-uses-of-cl2-br2-and-i2",
  "test-for-cl2-br2-and-i2",
  "haloacids-hcl-hbr-and-hi-comparative-study-on-preparation-properties-reducing-strength-acidic-nature-and-solubility-and-uses",
  "carbon-allotropes-of-carbon-crystalline-and-amorphous-including-fullerenes-structure-general-properties-and-uses-only",
  "properties-reducing-action-reaction-with-metals-and-nonmetals-and-uses-of-carbon-monoxide",
  "phosphorus-allotropes-of-phosphorus-name-only",
  "phosphine-preparation-properties-basic-nature-reducing-nature-action-with-halogens-and-oxygen-and-uses",
  "sulphur-allotropes-of-sulphur-name-only-and-uses-of-sulphur",
  "hydrogen-sulphide-preparation-from-kipps-apparatus-with-diagram-properties-acidic-nature-reducing-nature-analytical-reagent-and-uses",
  "sulphur-dioxide-properties-acidic-nature-reducing-nature-oxidising-nature-and-bleaching-action-and-uses",
  "sulphuric-acid-properties-acidic-nature-oxidising-nature-dehydrating-nature-and-uses",
  "sodium-thiosulphate-formula-and-uses",
];
const CHEMISTRY_11_METALS = [
  "chemistry-of-metals",
  "metals-and-metallurgical-principles-definition-of-metallurgy-and-its-types-hydrometallurgy-pyrometallurgy-electrometallurgy",
  "introduction-of-ores-gangue-or-matrix-flux-and-slag-alloy-and-amalgam",
  "general-principles-of-extraction-of-metals-concentration-calcination-and-roasting-smelting-carbon-reduction-thermite-and-electrochemical-reduction",
  "refining-of-metals-poling-and-electro-refinement",
  "alkali-metals-general-characteristics-of-alkali-metals",
  "sodium-extraction-from-downs-process-properties-action-with-oxygen-water-acids-nonmetals-and-ammonia-and-uses",
  "sodium-hydroxide-properties-precipitation-reaction-and-action-with-carbon-monoxide-and-uses",
  "sodium-carbonate-properties-action-with-co2o-so2-water-precipitation-reactions-and-uses",
  "alkaline-earth-metals-general-characteristics-of-alkaline-earth-metals",
  "molecular-formula-and-uses-of-quick-lime-bleaching-powder-magnesia-plaster-of-paris-and-epsom-salt",
  "solubility-of-hydroxides-carbonates-and-sulphates-of-alkaline-earth-metals-general-trend-with-explanation",
  "stability-of-carbonate-and-nitrate-of-alkaline-earth-metals-general-trend-with-explanation",
];
const CHEMISTRY_11_BIO = [
  "bio-inorganic-chemistry", "introduction-to-bio-inorganic-chemistry", "micro-and-macro-nutrients",
  "importance-of-metal-ions-in-biological-systems-ions-of-na-k-mg-ca-fe-cu-zn-ni-co-cr",
  "ion-pumps-sodium-potassium-and-sodium-glucose-pump", "metal-toxicity-toxicity-due-to-iron-arsenic-mercury-lead-and-cadmium",
];
const CHEMISTRY_11_ORGANIC = [
  "basic-concept-of-organic-chemistry", "introduction-to-organic-chemistry-and-organic-compounds",
  "reasons-for-the-separate-study-of-organic-compounds-from-inorganic-compounds",
  "tetra-covalency-and-catenation-properties-of-carbon", "classification-of-organic-compounds",
  "alkyl-groups-functional-groups-and-homologous-series",
  "idea-of-structural-formula-contracted-formula-and-bond-line-structural-formula",
  "preliminary-idea-of-cracking-and-reforming-quality-of-gasoline-octane-number-cetane-number-and-gasoline-additive",
];
const CHEMISTRY_11_PRINCIPLES = [
  "fundamental-principles-of-organic-chemistry", "iupac-nomenclature-of-organic-compounds-up-to-chain-having-6-carbon-atoms",
  "qualitative-analysis-of-organic-compounds-detection-of-n-s-and-halogens-by-lassaignes-test",
  "isomerism-in-organic-compounds-definition-and-classification-of-isomerism",
  "structural-isomerism-and-its-types-chain-isomerism-position-isomerism-functional-isomerism-metamerism-and-tautomerism",
  "concept-of-geometrical-isomerism-cis-and-trans-and-optical-isomerism-d-and-l-form",
  "preliminary-idea-of-reaction-mechanism-homolytic-and-heterolytic-fission",
  "electrophiles-nucleophiles-and-free-radicals", "inductive-effect-i-and-i-effect", "resonance-effect-r-and-r-effect",
];
const CHEMISTRY_11_HYDRO = [
  "hydrocarbons",
  "saturated-hydrocarbons-alkanes-preparation-from-haloalkanes-reduction-and-wurtz-reaction-decarboxylation-catalytic-hydrogenation-of-alkene-and-alkyne",
  "chemical-properties-of-alkanes-substitution-reactions-halogenation-nitration-and-sulphonation-only-oxidation-of-ethane",
  "unsaturated-hydrocarbons-alkenes-preparation-by-dehydration-of-alcohol-dehydrohalogenation-catalytic-hydrogenation-of-alkyne",
  "chemical-properties-of-alkenes-addition-reaction-with-hx-markovnikovs-addition-and-peroxide-effect-h2o-o3-h2so4-only",
  "alkynes-preparation-from-carbon-and-hydrogen-12-dibromoethane-chloroform-iodoform-only",
  "chemical-properties-of-alkynes-addition-reaction-with-h2-hx-h2o-acidic-nature-action-with-sodium-ammoniacal-agno3-and-ammoniacal-cu2cl2",
  "test-of-unsaturation-ethene-and-ethyne-bromine-water-test-and-baeyers-test",
  "comparative-studies-of-physical-properties-of-alkane-alkene-and-alkyne",
  "kolbes-electrolysis-methods-for-the-preparation-of-alkanes-alkenes-and-alkynes",
];
const CHEMISTRY_11_AROMATIC = [
  "aromatic-hydrocarbons", "introduction-and-characteristics-of-aromatic-compounds", "huckels-rule-of-aromaticity",
  "kekule-structure-of-benzene", "resonance-and-isomerism-in-benzene",
  "preparation-of-benzene-from-decarboxylation-of-sodium-benzoate-phenol-and-ethyne-only",
  "physical-properties-of-benzene",
  "chemical-properties-of-benzene-addition-reactions-hydrogen-halogen-electrophilic-substitution-reactions-orientation-of-benzene-derivatives-o-m-and-p-nitration-sulphonation-halogenation-friedel-crafts-reaction-alkylation-and-acylation",
  "combustion-of-benzene-free-combustion-only-and-uses",
];
const CHEMISTRY_11_APPLIED = [
  "fundamentals-of-applied-chemistry", "fundamentals-of-applied-chemistry-chemical-industry-and-its-importance",
  "stages-in-producing-a-new-product", "economics-of-production-cash-flow-in-the-production-cycle",
  "running-a-chemical-plant-designing-a-chemical-plant", "continuous-and-batch-processing",
  "environmental-impact-of-the-chemical-industry",
];
const CHEMISTRY_11_MANUFACTURE = [
  "modern-chemical-manufactures", "manufacture-of-ammonia-by-habers-process-principle-and-flow-sheet-diagram-only",
  "manufacture-of-nitric-acid-by-ostwalds-process", "manufacture-of-sulphuric-acid-by-contact-process",
  "manufacture-of-sodium-hydroxide-by-diaphragm-cell",
  "manufacture-of-sodium-carbonate-by-ammonia-soda-or-solvay-process",
  "fertilizers-chemical-fertilizers-types-of-chemical-fertilizers-production-of-urea-with-flow-sheet-diagram",
];

CHEMISTRY_11_NONMETALS.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "non-metal" : "hydrogen", i === 0 ? "Chemistry of Non-metals" : "Non-metals Topic", "chemistry-of-non-metals", "chemistry"); });
CHEMISTRY_11_METALS.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "metal" : "metallurgy", i === 0 ? "Chemistry of Metals" : "Metals Topic", "chemistry-of-metals", "chemistry"); });
CHEMISTRY_11_BIO.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "bio-inorganic" : "metal ion", i === 0 ? "Bio-inorganic Chemistry" : "Bio-inorganic Topic", "bio-inorganic-chemistry", "chemistry"); });
CHEMISTRY_11_ORGANIC.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "organic" : "tetra-covalency", i === 0 ? "Basic Concept of Organic Chemistry" : "Organic Topic", "basic-concept-of-organic-chemistry", "chemistry"); });
CHEMISTRY_11_PRINCIPLES.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "iupac" : "isomerism", i === 0 ? "Fundamental Principles of Organic Chemistry" : "Organic Principles Topic", "fundamental-principles-of-organic-chemistry", "chemistry"); });
CHEMISTRY_11_HYDRO.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "alkane" : "alkene", i === 0 ? "Hydrocarbons" : "Hydrocarbons Topic", "hydrocarbons", "chemistry"); });
CHEMISTRY_11_AROMATIC.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "aromatic" : "benzene", i === 0 ? "Aromatic Hydrocarbons" : "Aromatic Topic", "aromatic-hydrocarbons", "chemistry"); });
CHEMISTRY_11_APPLIED.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "applied chemistry" : "continuous processing", i === 0 ? "Applied Chemistry" : "Applied Chemistry Topic", "fundamentals-of-applied-chemistry", "chemistry"); });
CHEMISTRY_11_MANUFACTURE.forEach((slug, i) => { CHEMISTRY_11[slug] = make(i === 0 ? "haber" : "contact process", i === 0 ? "Modern Chemical Manufactures" : "Manufacture Topic", "modern-chemical-manufactures", "chemistry"); });

export { CHEMISTRY_11 };

const BIOLOGY_11: LabComponentMap = {
  "biomolecules-and-cell-biology": make("biomolecule", "Biomolecules and Cell Biology", "biomolecules-and-cell-biology", "biology"),
  "biomolecules-introduction-and-functions-of-carbohydrates-proteins-lipids-nucleic-acids-minerals-enzymes-and-water": make("biomolecule", "Biomolecules", "biomolecules-and-cell-biology", "biology"),
  "cell-introduction-of-cell-concepts-of-prokaryotic-and-eukaryotic-cells": make("cell", "Cell Introduction", "biomolecules-and-cell-biology", "biology"),
  "detail-structure-of-eukaryotic-cells-cell-wall-cell-membrane-mitochondria-plastids-endoplasmic-reticulum-golgi-bodies-lysosomes-ribosomes-nucleus-chromosomes-cilia-flagella-and-cell-inclusions": make("cell", "Eukaryotic Cell", "biomolecules-and-cell-biology", "biology"),
  "cell-division-concept-of-cell-cycle-types-of-cell-division-amitosis-mitosis-and-meiosis-and-significances": make("mitosis", "Cell Division", "biomolecules-and-cell-biology", "biology"),
  "floral-diversity": make("floral diversity", "Floral Diversity", "floral-diversity", "biology"),
  "introduction-three-domains-of-life-binomial-nomenclature-five-kingdom-classification-system-monera-protista-fungi-plae-and-animalia": make("five kingdom", "Five Kingdom Classification", "floral-diversity", "biology"),
  "status-of-flora-in-nepal-and-world-representation": make("floral diversity", "Flora in Nepal", "floral-diversity", "biology"),
  "fungi-general-introduction-and-characteristic-features-of-phycomycetes-ascomycetes-basidiomycetes-and-deuteromycetes": make("fungi", "Fungi", "floral-diversity", "biology"),
  "structure-and-reproduction-of-mucor-and-yeast": make("fungi", "Mucor & Yeast", "floral-diversity", "biology"),
  "introduction-of-mushrooms-poisonous-and-non-poisonous-mushrooms-economic-importance-of-fungi": make("mushroom", "Mushrooms", "floral-diversity", "biology"),
  "lichen-general-introduction-characteristic-features-and-economic-importance-of-lichen": make("lichen", "Lichen", "floral-diversity", "biology"),
  "algae-general-introduction-and-characteristic-features-of-green-brown-and-red-algae-structure-and-reproduction-of-spirogyra-economic-importance-of-algae": make("algae", "Algae", "floral-diversity", "biology"),
  "bryophyta-general-introduction-characteristic-features-of-liverworts-hornworts-and-moss-morphological-structure-and-reproduction-of-marchantia-economic-importance-of-bryophytes": make("bryophyt", "Bryophyta", "floral-diversity", "biology"),
  "pteridophyta-general-introduction-characteristic-features-of-pteridophytes-morphological-structure-and-reproduction-of-dryopteris-economic-importance-of-pteridophytes": make("pteridophyt", "Pteridophyta", "floral-diversity", "biology"),
  "gymnosperm-general-introduction-characteristic-features-of-gymnosperms-morphology-and-reproduction-of-pinus-economic-importance-of-gymnosperm": make("gymnosperm", "Gymnosperm", "floral-diversity", "biology"),
  "angiosperm-morphology-of-root-stem-leaves-inflorescences-flowers-and-fruit": make("angiosperm", "Angiosperm Morphology", "floral-diversity", "biology"),
  "taxonomic-study-definition-taxonomic-hierarchy-classification-systems-artificial-natural-and-phylogenetic-of-angiosperms": make("taxonomic", "Taxonomic Study", "floral-diversity", "biology"),
  "angiosperm-families-with-economic-importance-brassicaceae-fabaceae-solanaceae-and-liliaceae": make("angiosperm families", "Angiosperm Families", "floral-diversity", "biology"),
  "introductory-microbiology": make("microbiology", "Introductory Microbiology", "introductory-microbiology", "biology"),
  "monera-general-introduction-structure-of-bacterial-cell-mode-of-nutrition-bacterial-growth-cyanobacteria-blue-green-algae": make("monera", "Monera", "introductory-microbiology", "biology"),
  "virus-general-introduction-structure-and-importance-of-virus-bacteriophage": make("virus", "Virus & Bacteriophage", "introductory-microbiology", "biology"),
  "impacts-of-biotechnology-in-the-field-of-microbiology": make("biotechnology", "Biotechnology in Microbiology", "introductory-microbiology", "biology"),
  "ecology": make("ecosystem", "ecology", "ecology", "biology"),
  "ecosystem-ecology-concept-of-ecology-biotic-and-abiotic-factors-species-interactions": make("ecosystem", "Ecosystem Ecology", "ecology", "biology"),
  "concept-of-ecosystem-structural-and-functional-aspects-of-pond-and-forest-ecosystem": make("pond", "Pond & Forest Ecosystem", "ecology", "biology"),
  "food-chain-food-web-trophic-level-ecological-pyramids-productivity": make("food chain", "Food Chain & Web", "ecology", "biology"),
  "biogeochemical-cycles-carbon-and-nitrogen-cycles-concept-of-succession": make("biogeochemical", "Biogeochemical Cycles", "ecology", "biology"),
  "ecological-adaptation-concept-of-adaptation-hydrophytes-and-xerophytes": make("hydrophyte", "Ecological Adaptation", "ecology", "biology"),
  "ecological-imbalances-greenhouse-effects-and-climate-change-depletion-of-ozone-layer-acid-rain-and-biological-invasion": make("greenhouse", "Ecological Imbalances", "ecology", "biology"),
  "vegetation": make("vegetation", "Vegetation", "vegetation", "biology"),
  "vegetation-introduction-types-of-vegetation-in-nepal": make("vegetation", "Vegetation in Nepal", "vegetation", "biology"),
  "in-situ-protected-areas-and-ex-situ-botanical-garden-seed-bank-conservation": make("in-situ", "Conservation Methods", "vegetation", "biology"),
  "natural-environment-vegetation-and-human-activities": make("vegetation", "Natural Environment", "vegetation", "biology"),
  "introduction-to-biology": make("cell", "Introduction to Biology", "introduction-to-biology", "biology"),
  "introduction-to-biology-scope-and-fields-of-biology": make("cell", "Scope of Biology", "introduction-to-biology", "biology"),
  "relation-of-biology-with-other-sciences": make("cell", "Biology and Other Sciences", "introduction-to-biology", "biology"),
  "evolutionary-biology": make("evolution", "Evolutionary Biology", "evolutionary-biology", "biology"),
  "life-and-its-origin-oparin-haldane-theory-miller-and-ureys-experiment": make("oparin", "Origin of Life", "evolutionary-biology", "biology"),
  "evidences-of-evolution-morphological-anatomical-paleontological-embryological-and-biochemical": make("morphological", "Evidences of Evolution", "evolutionary-biology", "biology"),
  "theories-of-evolution-lamarckism-darwinism-and-concept-of-neo-darwinism": make("darwinism", "Theories of Evolution", "evolutionary-biology", "biology"),
  "human-evolution-position-of-man-in-animal-kingdom": make("human evolution", "Human Evolution", "evolutionary-biology", "biology"),
  "differences-between-new-world-monkeys-and-old-world-monkeys-apes-and-man": make("apes", "Monkeys & Apes", "evolutionary-biology", "biology"),
  "evolution-of-modern-man-starting-from-anthropoid-ancestor": make("anthropoid", "Modern Man", "evolutionary-biology", "biology"),
};

const BIOLOGY_11_FAUNAL = [
  "faunal-diversity",
  "protista-outline-classification-protozoa-diagnostic-features-and-classification-up-to-class-with-examples",
  "paramecium-caudatum-plasmodium-vivax-habits-and-habitat-structure-reproduction-life-cycle",
  "economic-importance-of-p-falciparum",
  "animalia-level-of-organization-body-plan-body-symmetry-body-cavity-and-segmentation-in-animals",
  "diagnostic-features-and-classification-of-phyla-up-to-class-porifera-coelenterata-cnidaria-platyhelminthes-aschelminthes-nemathelminthes-annelida-arthropoda-mollusca-echinodermata-and-chordata",
  "earthworm-pheretima-posthuma-habit-and-habitat-external-features-digestive-system-alimentary-canal-and-physiology-of-digestion",
  "earthworm-excretory-system-types-of-nephridia-structure-and-arrangement-of-septal-nephridia-nervous-system-central-and-peripheral-working-mechanism",
  "earthworm-reproductive-systems-male-and-female-reproductive-organs-copulation-cocoon-formation-and-economic-importance",
  "frog-rana-tigrina-habit-and-habitat-external-features-digestive-system-alimentary-canal-digestive-glands-and-physiology-of-digestion",
  "frog-blood-vascular-system-structure-and-working-mechanism-of-heart-respiratory-system-respiratory-organs-and-physiology-of-respiration",
  "frog-reproductive-system-male-and-female-reproductive-organs",
];
const BIOLOGY_11_BIOTA = [
  "biota-and-environment",
  "animal-adaptation-aquatic-primary-and-secondary-terrestrial-cursorial-fossorial-and-arboreal-and-volant-adaptation",
  "animal-behavior-reflex-action-taxes-dominance-and-leadership",
  "fish-and-bird-migration",
  "environmental-pollution-sources-effects-and-control-measures-of-air-water-and-soil-pollution",
  "pesticides-and-their-effects",
];
const BIOLOGY_11_CONSERVATION = [
  "conservation-biology",
  "conservation-biology-concept-of-biodiversity-biodiversity-conservation",
  "national-parks-wildlife-reserves-conservation-areas-biodiversity-hotspots-wetland-and-ramsar-sites-wildlife-importance-causes-of-extinction-and-conservation-strategies-iucn-categories-of-threatened-species-endangered-species-in-nepal",
  "wildlife-importance-causes-of-extinction-and-conservation-strategies",
  "iucn-categories-of-threatened-species-meaning-of-extinct-endangered-vulnerable-rare-and-threatened-species",
  "endangered-species-in-nepal",
];
BIOLOGY_11_FAUNAL.forEach((slug, i) => { BIOLOGY_11[slug] = make(i === 0 ? "faunal" : "frog", i === 0 ? "Faunal Diversity" : "Faunal Topic", "faunal-diversity", "biology"); });
BIOLOGY_11_BIOTA.forEach((slug, i) => { BIOLOGY_11[slug] = make(i === 0 ? "biota" : "pollution", i === 0 ? "Biota & Environment" : "Biota Topic", "biota-and-environment", "biology"); });
BIOLOGY_11_CONSERVATION.forEach((slug, i) => { BIOLOGY_11[slug] = make(i === 0 ? "conservation" : "iucn", i === 0 ? "Conservation Biology" : "Conservation Topic", "conservation-biology", "biology"); });

export { BIOLOGY_11 };

const MATH_11: LabComponentMap = {
  "algebra": make("function", "Algebra", "algebra", "mathematics"),
  "logic-and-set-statements-logical-connectives-truth-tables-theorems-based-on-set-operations": make("set", "Logic & Sets", "algebra", "mathematics"),
  "real-numbers-geometric-representation-of-real-numbers-interval-absolute-value": make("real number", "Real Numbers", "algebra", "mathematics"),
  "function-domain-and-range-of-a-function-inverse-function-composite-function-algebraic-linear-quadratic-and-cubic-and-transcendental-trigonometric-exponential-logarithmic-functions": make("function", "Functions", "algebra", "mathematics"),
  "curve-sketching-odd-and-even-functions-periodicity-symmetry-about-origin-x-and-y-axis-monotonicity-graphs-of-quadratic-cubic-and-rational-functions-trigonometric-asinbx-and-acosbx-exponential-ex-lnx": make("curve sketching", "Curve Sketching", "algebra", "mathematics"),
  "sequence-and-series-arithmetic-geometric-harmonic-sequences-and-series-and-their-properties-am-gm-hm-and-their-relations-sum-of-infinite-geometric-series": make("sequence", "Sequences & Series", "algebra", "mathematics"),
  "matrices-and-determinants-transpose-of-a-matrix-and-its-properties-minors-and-cofactors-adjoint-inverse-matrix-determinant-properties-of-determinants-without-proof": make("matrix", "Matrices & Determinants", "algebra", "mathematics"),
  "quadratic-equation-nature-and-roots-of-a-quadratic-equation-relation-between-roots-and-coefficient-formation-of-a-quadratic-equation-symmetric-roots-one-or-both-roots-common": make("quadratic equation", "Quadratic Equations", "algebra", "mathematics"),
  "complex-number-imaginary-unit-algebra-of-complex-numbers-geometric-representation-absolute-modulus-value-and-conjugate-of-complex-numbers-and-their-properties-square-root-of-a-complex-number": make("complex number", "Complex Numbers", "algebra", "mathematics"),
  "trigonometry": make("trigonometric function", "Trigonometry", "trigonometry", "mathematics"),
  "inverse-circular-functions": make("inverse circular", "Inverse Circular Functions", "trigonometry", "mathematics"),
  "trigonometric-equations-and-general-values": make("trigonometric equation", "Trigonometric Equations", "trigonometry", "mathematics"),
  "analytic-geometry": make("straight line", "Analytic Geometry", "analytic-geometry", "mathematics"),
  "straight-line-length-of-perpendicular-from-a-given-point-to-a-given-line-bisectors-of-the-angles-between-two-straight-lines": make("straight line", "Straight Line", "analytic-geometry", "mathematics"),
  "pair-of-straight-lines-general-equation-of-second-degree-in-x-and-y-condition-for-representing-a-pair-of-lines-homogenous-second-degree-equation-in-x-and-y-angle-between-pair-of-lines-bisectors-of-the-angles-between-pair-of-lines": make("homogenous", "Pair of Straight Lines", "analytic-geometry", "mathematics"),
  "coordinates-in-space-points-in-space-distance-between-two-points-direction-cosines-and-ratios-of-a-line": make("direction cosine", "Coordinates in Space", "analytic-geometry", "mathematics"),
  "vectors": make("vector", "Vectors", "vectors", "mathematics"),
  "collinear-and-non-collinear-vectors-coplanar-and-non-coplanar-vectors": make("collinear", "Collinear Vectors", "vectors", "mathematics"),
  "linear-combination-of-vectors-linearly-dependent-and-independent-vectors": make("linear combination", "Linear Combination", "vectors", "mathematics"),
  "statistics-and-probability": make("measure of dispersion", "Statistics & Probability", "statistics-and-probability", "mathematics"),
  "measure-of-dispersion-standard-deviation-variance-coefficient-of-variation-skewness-karl-pearsons-coefficient-of-skewness": make("standard deviation", "Measure of Dispersion", "statistics-and-probability", "mathematics"),
  "probability-independent-cases-mathematical-and-empirical-definition-of-probability-two-basic-laws-of-probability-without-proof": make("probability", "Probability", "statistics-and-probability", "mathematics"),
  "calculus": make("calculus", "Calculus", "calculus", "mathematics"),
  "limits-and-continuity-limits-of-a-function-indeterminate-forms-alal-form-algebraic-properties-of-limits-without-proof-basic-theorems-on-limits-of-algebraic-trigonometric-exponential-and-logarithal-functions": make("limit", "Limits", "calculus", "mathematics"),
  "continuity-of-a-function-types-of-discontinuity-graphs-of-discontinuous-function": make("continuity", "Continuity", "calculus", "mathematics"),
  "derivatives-derivative-of-a-function-derivatives-of-algebraic-trigonometric-inverse-trigonometric-exponential-and-logarithal-functions-by-definition-simple-forms": make("derivative", "Derivatives", "calculus", "mathematics"),
  "rules-of-differentiation-derivatives-of-parametric-and-implicit-functions-higher-order-derivatives": make("differentiation", "Differentiation Rules", "calculus", "mathematics"),
  "geometric-interpretation-of-derivative-monotonicity-of-a-function-interval-of-monotonicity-extreme-values-of-a-function-concavity-points-of-inflexion": make("monotonicity", "Geometric Interpretation", "calculus", "mathematics"),
  "anti-derivatives-integration-using-basic-integrals-integration-by-substitution-and-by-parts-methods": make("integral", "Anti-derivatives", "calculus", "mathematics"),
  "the-definite-integral-the-definite-integral-as-an-area-under-the-given-curve-area-between-two-curves": make("definite integral", "Definite Integrals", "calculus", "mathematics"),
  "computational-methods-or-mechanics": make("numerical computation", "Computational Methods", "computational-methods-or-mechanics", "mathematics"),
  "numerical-computation-roots-of-algebraic-and-transcendental-equations-bisection-and-newton-raphson-method": make("bisection", "Roots of Equations", "computational-methods-or-mechanics", "mathematics"),
  "numerical-integration-trapezoidal-rule-and-simpsons-rule": make("trapezoidal", "Numerical Integration", "computational-methods-or-mechanics", "mathematics"),
  "mechanics-optional-statics-forces-and-resultant-forces-parallelogram-law-of-forces-composition-and-resolution-of-forces-resultant-of-coplanar-forces-acting-on-a-point": make("parallelogram law", "Statics", "computational-methods-or-mechanics", "mathematics"),
  "mechanics-optional-dynamics-motion-of-particle-in-a-straight-line-motion-with-uniform-acceleration-motion-under-gravity-motion-down-a-smooth-inclined-plane": make("uniform acceleration", "Dynamics", "computational-methods-or-mechanics", "mathematics"),
};

export { MATH_11 };

const PHYSICS_12: LabComponentMap = {
  "electrostatics": make("coulomb", "Electrostatics", "electrostatics", "physics"),
  "coulombs-law-and-its-applications": make("coulomb", "Coulomb's Law", "electrostatics", "physics"),
  "electric-field-and-electric-field-intensity-due-to-point-charges-line-charges-and-charged-sheets": make("electric field", "Electric Field", "electrostatics", "physics"),
  "electric-potential-and-potential-difference": make("potential", "Potential Difference", "electrostatics", "physics"),
  "capacitance-and-capacitors-parallel-plate-series-and-parallel-combination": make("capacit", "Capacitance", "electrostatics", "physics"),
  "dielectric-and-dielectric-constant": make("dielectric", "Dielectric", "electrostatics", "physics"),
  "energy-stored-in-a-capacitor": make("capacit", "Energy in Capacitor", "electrostatics", "physics"),
  "current-electricity": make("circuit", "Current Electricity", "current-electricity", "physics"),
  "electric-current-drift-velocity-and-relaxation-time": make("drift velocity", "Drift Velocity", "current-electricity", "physics"),
  "ohms-law-and-its-limitations": make("ohm", "Ohm's Law", "current-electricity", "physics"),
  "resistance-and-resistivity-temperature-dependence": make("resistivity", "Resistance & Resistivity", "current-electricity", "physics"),
  "series-and-parallel-combination-of-resistors": make("series and parallel", "Resistor Combination", "current-electricity", "physics"),
  "kirchhoffs-laws-and-their-applications": make("kirchhoff", "Kirchhoff's Laws", "current-electricity", "physics"),
  "electromotive-force-emf-internal-resistance-and-cells-in-combination": make("emf", "EMF", "current-electricity", "physics"),
  "wheatstone-bridge-and-meter-bridge": make("wheatstone", "Wheatstone Bridge", "current-electricity", "physics"),
  "potentiometer-and-its-applications": make("potentiometer", "Potentiometer", "current-electricity", "physics"),
  "magnetism-and-magnetic-effect-of-current": make("magnetic", "Magnetism", "magnetism-and-magnetic-effect", "physics"),
  "magnetic-field-and-magnetic-force-on-moving-charges": make("magnetic field", "Magnetic Force", "magnetism-and-magnetic-effect", "physics"),
  "lorentz-force-and-motion-of-charged-particles-in-magnetic-fields": make("lorentz", "Lorentz Force", "magnetism-and-magnetic-effect", "physics"),
  "biot-savart-law-and-its-applications-straight-wire-circular-loop-solenoid": make("biot", "Biot-Savart Law", "magnetism-and-magnetic-effect", "physics"),
  "amperes-circuital-law-and-its-applications": make("ampere", "Ampere's Law", "magnetism-and-magnetic-effect", "physics"),
  "force-between-two-parallel-current-carrying-conductors": make("parallel current", "Force Between Conductors", "magnetism-and-magnetic-effect", "physics"),
  "moving-coil-galvanometer-ammeter-and-voltmeter": make("galvanometer", "Galvanometer", "magnetism-and-magnetic-effect", "physics"),
  "electromagnetic-induction": make("electromagnetic induction", "Electromagnetic Induction", "electromagnetic-induction", "physics"),
  "faradays-laws-of-electromagnetic-induction": make("faraday", "Faraday's Laws", "electromagnetic-induction", "physics"),
  "lenzs-law-and-conservation-of-energy": make("lenz", "Lenz's Law", "electromagnetic-induction", "physics"),
  "self-induction-and-self-inductance": make("self-inductance", "Self Induction", "electromagnetic-induction", "physics"),
  "mutual-induction-and-mutual-inductance": make("mutual", "Mutual Induction", "electromagnetic-induction", "physics"),
  "growing-and-decaying-current-in-lr-circuits": make("lr circuit", "LR Circuits", "electromagnetic-induction", "physics"),
  "alternating-current": make("alternating", "Alternating Current", "alternating-current", "physics"),
  "ac-voltage-applied-to-resistor-inductor-and-capacitor": make("ac voltage", "AC Voltage", "alternating-current", "physics"),
  "lc-oscillations-and-resonance": make("lc oscillation", "LC Oscillations", "alternating-current", "physics"),
  "lcr-series-circuit-and-power-factor": make("lcr", "LCR Circuit", "alternating-current", "physics"),
  "transformer-principle-types-and-losses": make("transformer", "Transformer", "alternating-current", "physics"),
  "ray-optics": make("mirror", "Ray Optics", "ray-optics", "physics"),
  "reflection-at-plane-and-curved-surfaces-mirrors": make("mirror", "Reflection at Mirrors", "ray-optics", "physics"),
  "refraction-at-plane-surfaces-total-internal-reflection": make("total internal", "TIR", "ray-optics", "physics"),
  "refraction-through-prisms-angle-of-deviation-and-minimum-deviation": make("minimum deviation", "Prism Deviation", "ray-optics", "physics"),
  "thin-lenses-lens-maker-s-formula-and-power-of-lens": make("lens maker", "Thin Lenses", "ray-optics", "physics"),
  "combination-of-lenses-and-mirrors": make("lens", "Lens & Mirror Combinations", "ray-optics", "physics"),
  "optical-instruments-microscope-and-telescope": make("microscope", "Optical Instruments", "ray-optics", "physics"),
  "wave-optics": make("interference", "Wave Optics", "wave-optics", "physics"),
  "wavefront-and-huygens-principle": make("huygens", "Huygens' Principle", "wave-optics", "physics"),
  "interference-of-light-youngs-double-slit-experiment": make("interference", "Young's Double Slit", "wave-optics", "physics"),
  "diffraction-of-light-single-slit-diffraction": make("diffraction", "Diffraction", "wave-optics", "physics"),
  "polarization-brewsters-law-and-polaroids": make("polarization", "Polarization", "wave-optics", "physics"),
  "modern-physics": make("photoelectric", "Modern Physics", "modern-physics", "physics"),
  "photoelectric-effect-and-einsteins-photoelectric-equation": make("photoelectric", "Photoelectric Effect", "modern-physics", "physics"),
  "de-broglie-wavelength-and-matter-waves": make("de broglie", "De Broglie Wavelength", "modern-physics", "physics"),
  "atom-bohrs-model-and-hydrogen-spectrum": make("bohr", "Bohr's Atom", "modern-physics", "physics"),
  "nucleus-binding-energy-nuclear-fission-and-fusion": make("binding energy", "Binding Energy", "modern-physics", "physics"),
  "semiconductors-intrinsic-and-extrinsic-p-n-junction-diode-transistor": make("semiconductor", "Semiconductors", "modern-physics", "physics"),
  "logic-gates-and-or-not-nand-nor": make("logic gate", "Logic Gates", "modern-physics", "physics"),
  "communication-systems": make("modulation", "Communication Systems", "communication-systems", "physics"),
  "elements-of-a-communication-system": make("communication", "Communication Elements", "communication-systems", "physics"),
  "modulation-amplitude-modulation-and-frequency-modulation": make("modulation", "Modulation", "communication-systems", "physics"),
  "bandwidth-and-propagation-of-electromagnetic-waves": make("bandwidth", "Bandwidth", "communication-systems", "physics"),
};
export { PHYSICS_12 };

const CHEMISTRY_12: LabComponentMap = {
  "solutions": make("solution", "Solutions", "solutions", "chemistry"),
  "types-of-solutions-and-expression-of-concentration": make("concentration", "Types of Solutions", "solutions", "chemistry"),
  "solubility-of-gases-and-solids-in-liquids": make("solubility", "Solubility", "solutions", "chemistry"),
  "vapour-pressure-of-solutions-raoults-law": make("raoult", "Raoult's Law", "solutions", "chemistry"),
  "colligative-properties-relative-lowering-of-vapour-pressure-elevation-of-boiling-point-depression-of-freezing-point-osmosis-and-osmotic-pressure": make("colligative", "Colligative Properties", "solutions", "chemistry"),
  "vant-hoff-factor-and-abnormal-molar-masses": make("vant hoff", "Van't Hoff Factor", "solutions", "chemistry"),
  "electro-chemistry": make("electro-chem", "Electrochemistry", "electro-chemistry", "chemistry"),
  "oxidation-and-reduction-electrode-reactions": make("oxidation", "Electrode Reactions", "electro-chemistry", "chemistry"),
  "electrochemical-cells-galvanic-cell-cell-potential-standard-electrode-potential": make("galvanic", "Galvanic Cell", "electro-chemistry", "chemistry"),
  "nernst-equation-and-its-applications": make("nernst", "Nernst Equation", "electro-chemistry", "chemistry"),
  "conductance-of-electrolytic-solutions": make("conductance", "Conductance", "electro-chemistry", "chemistry"),
  "electrolysis-and-faradays-laws": make("electrolysis", "Electrolysis", "electro-chemistry", "chemistry"),
  "batteries-primary-and-secondary-cells": make("battery", "Batteries", "electro-chemistry", "chemistry"),
  "fuel-cells": make("fuel cell", "Fuel Cells", "electro-chemistry", "chemistry"),
  "chemical-kinetics": make("kinetics", "Chemical Kinetics", "chemical-kinetics", "chemistry"),
  "rate-of-reaction-average-and-instantaneous-rate": make("rate of reaction", "Rate of Reaction", "chemical-kinetics", "chemistry"),
  "factors-affecting-rate-of-reaction": make("rate of reaction", "Factors Affecting Rate", "chemical-kinetics", "chemistry"),
  "rate-law-and-order-of-reaction": make("rate law", "Rate Law", "chemical-kinetics", "chemistry"),
  "integrated-rate-equations-zero-order-and-first-order-reactions": make("integrated rate", "Integrated Rate", "chemical-kinetics", "chemistry"),
  "arrhenius-equation-and-activation-energy": make("arrhenius", "Arrhenius Equation", "chemical-kinetics", "chemistry"),
  "general-and-organic-fundamentals": make("organic", "General & Organic Fundamentals", "general-and-organic-fundamentals", "chemistry"),
  "purification-and-qualitative-quantitative-analysis-of-organic-compounds": make("qualitative analysis", "Organic Analysis", "general-and-organic-fundamentals", "chemistry"),
  "inductive-effect-resonance-hyperconjugation": make("hyperconjugation", "Inductive & Resonance", "general-and-organic-fundamentals", "chemistry"),
  "electrophilic-and-nucleophilic-substitution-reactions": make("electrophilic substitution", "Substitution Reactions", "general-and-organic-fundamentals", "chemistry"),
  "free-radical-reactions": make("free radical", "Free Radical Reactions", "general-and-organic-fundamentals", "chemistry"),
  "important-organic-reactions-oxidation-reduction-addition-elimination": make("oxidation", "Important Organic Reactions", "general-and-organic-fundamentals", "chemistry"),
  "hydrocarbons": make("alkane", "Hydrocarbons", "hydrocarbons", "chemistry"),
  "alkanes-conformations-combustion-free-radical-halogenation": make("alkane", "Alkanes", "hydrocarbons", "chemistry"),
  "alkenes-preparation-geometrical-isomerism-electrophilic-addition-markovnikov-anti-markovnikov-ozonolysis-polymerisation": make("alkene", "Alkenes", "hydrocarbons", "chemistry"),
  "alkynes-preparation-acidic-character-addition-reactions": make("alkyne", "Alkynes", "hydrocarbons", "chemistry"),
  "aromatic-hydrocarbons-benzene-resonance-aromaticity-electrophilic-substitution-halogenation-nitration-sulphonation-friedel-crafts": make("aromatic", "Aromatic Hydrocarbons", "hydrocarbons", "chemistry"),
  "alcohols-phenols-ethers": make("alcohol", "Alcohols, Phenols, Ethers", "alcohols-phenols-ethers", "chemistry"),
  "alcohols-classification-preparation-physical-and-chemical-properties": make("alcohol", "Alcohols", "alcohols-phenols-ethers", "chemistry"),
  "phenols-acidity-electrophilic-substitution-kolbes-reaction-reimer-tiemann-reaction": make("phenol", "Phenols", "alcohols-phenols-ethers", "chemistry"),
  "ethers-preparation-and-chemical-reactions-cleavage-by-hi": make("ether", "Ethers", "alcohols-phenols-ethers", "chemistry"),
  "aldehydes-ketones-carboxylic-acids": make("aldehyde", "Aldehydes, Ketones, Carboxylic Acids", "aldehydes-ketones-carboxylic-acids", "chemistry"),
  "aldehydes-and-ketones-preparation-physical-properties-nucleophilic-addition-reactions": make("aldehyde", "Aldehydes & Ketones", "aldehydes-ketones-carboxylic-acids", "chemistry"),
  "carboxylic-acids-preparation-physical-properties-acidic-character-reactions": make("carboxylic acid", "Carboxylic Acids", "aldehydes-ketones-carboxylic-acids", "chemistry"),
  "name-reactions-aldol-condensation-cannizzaro-reaction-hvz-reaction": make("aldol", "Name Reactions", "aldehydes-ketones-carboxylic-acids", "chemistry"),
  "amines": make("amine", "Amines", "amines", "chemistry"),
  "classification-nomenclature-and-preparation": make("amine", "Classification of Amines", "amines", "chemistry"),
  "physical-and-chemical-properties": make("amine", "Properties of Amines", "amines", "chemistry"),
  "basic-character-of-amines": make("basic character", "Basic Character", "amines", "chemistry"),
  "reactions-diazotisation-coupling-reactions-hinsberg-test": make("diazotisation", "Diazotisation", "amines", "chemistry"),
  "biomolecules": make("biomolecule", "Biomolecules", "biomolecules", "chemistry"),
  "carbohydrates-monosaccharides-glucose-fructose-disaccharides-polysaccharides": make("carbohydrate", "Carbohydrates", "biomolecules", "chemistry"),
  "proteins-amino-acids-peptide-bond-primary-to-quaternary-structure-denaturation": make("protein", "Proteins", "biomolecules", "chemistry"),
  "enzymes-definition-classification-enzyme-action": make("enzyme", "Enzymes", "biomolecules", "chemistry"),
  "vitamins-classification-and-functions": make("vitamin", "Vitamins", "biomolecules", "chemistry"),
  "hormones-definition-types-functions": make("hormone", "Hormones", "biomolecules", "chemistry"),
  "chemistry-in-everyday-life": make("everyday", "Chemistry in Everyday Life", "chemistry-in-everyday-life", "chemistry"),
  "medicinal-chemicals-analgesics-tranquilizers-antipyretics-antibiotics-antihistamines-antacids": make("analgesic", "Medicinal Chemicals", "chemistry-in-everyday-life", "chemistry"),
  "chemical-cleansers-soaps-and-detergents": make("soap", "Soaps & Detergents", "chemistry-in-everyday-life", "chemistry"),
  "food-additives-preservatives-and-artificial-sweetening-agents": make("preservative", "Food Additives", "chemistry-in-everyday-life", "chemistry"),
  "chemistry-of-element": make("p-block", "Chemistry of Elements", "chemistry-of-element", "chemistry"),
  "p-block-elements-group-15-18-important-compounds-trends-in-properties": make("p-block", "p-block Elements", "chemistry-of-element", "chemistry"),
  "d-block-elements-general-characteristics-important-compounds-kmno4-k2cr2o7": make("d-block", "d-block Elements", "chemistry-of-element", "chemistry"),
  "f-block-elements-lanthanoids-and-actinoids": make("f-block", "f-block Elements", "chemistry-of-element", "chemistry"),
  "coordination-compounds-werners-theory-iupac-nomenclature-vbt-cft-qualitative-isomerism": make("coordination", "Coordination Compounds", "chemistry-of-element", "chemistry"),
};

const MATH_12: LabComponentMap = {
  "limits-and-continuity": make("limit", "Limits & Continuity", "limits-and-continuity", "mathematics"),
  "concept-of-limit-geometric-and-physical-interpretation": make("limit", "Concept of Limit", "limits-and-continuity", "mathematics"),
  "standard-limits-and-evaluation-algebraic-trigonometric-exponential-logarithmic": make("limit", "Standard Limits", "limits-and-continuity", "mathematics"),
  "indeterminate-forms": make("indeterminate", "Indeterminate Forms", "limits-and-continuity", "mathematics"),
  "continuity-of-algebraic-trigonometric-exponential-logarithmic-functions": make("continuity", "Continuity", "limits-and-continuity", "mathematics"),
  "differentiability-and-its-relation-with-continuity": make("differentiability", "Differentiability", "limits-and-continuity", "mathematics"),
  "differentiation": make("derivative", "Differentiation", "differentiation", "mathematics"),
  "derivatives-of-algebraic-trigonometric-inverse-trigonometric-exponential-and-logarithmic-functions": make("derivative", "Derivatives", "differentiation", "mathematics"),
  "rules-of-differentiation-product-rule-quotient-rule-chain-rule": make("chain rule", "Rules of Differentiation", "differentiation", "mathematics"),
  "derivatives-of-parametric-and-implicit-functions": make("implicit function", "Parametric & Implicit", "differentiation", "mathematics"),
  "higher-order-derivatives": make("higher order", "Higher Order Derivatives", "differentiation", "mathematics"),
  "logarithmic-differentiation": make("logarithmic differentiation", "Logarithmic Differentiation", "differentiation", "mathematics"),
  "leibnizs-theorem-for-nth-derivative": make("leibniz", "Leibniz's Theorem", "differentiation", "mathematics"),
  "geometric-interpretation-tangent-and-normal": make("tangent", "Tangent & Normal", "differentiation", "mathematics"),
  "monotonicity-maxima-and-minima-first-and-second-derivative-tests": make("maxima", "Maxima & Minima", "differentiation", "mathematics"),
  "applications-rate-of-change-approximation-error-estimation": make("approximation", "Approximation", "differentiation", "mathematics"),
  "integration": make("integral", "Integration", "integration", "mathematics"),
  "integration-as-inverse-of-differentiation": make("integral", "Integration Basics", "integration", "mathematics"),
  "standard-integrals-and-methods-substitution-parts-partial-fractions": make("by parts", "Integration Methods", "integration", "mathematics"),
  "definite-integrals-and-properties": make("definite integral", "Definite Integrals", "integration", "mathematics"),
  "integration-of-trigonometric-functions": make("trigonometric function", "Trigonometric Integration", "integration", "mathematics"),
  "applications-area-under-curve-area-between-two-curves": make("area under", "Area Applications", "integration", "mathematics"),
  "differential-equations": make("differential equation", "Differential Equations", "differential-equations", "mathematics"),
  "formation-of-differential-equations": make("differential equation", "Formation", "differential-equations", "mathematics"),
  "solving-first-order-first-degree-equations-variable-separable-homogeneous-linear": make("variable separable", "Solving DE", "differential-equations", "mathematics"),
  "applications-growth-and-decay-population-dynamics": make("growth", "Growth & Decay", "differential-equations", "mathematics"),
  "vector-algebra": make("scalar", " vector", "vector-algebra", "mathematics"),
  "scalar-and-vector-quantities-types-of-vectors": make("scalar", "Scalar & Vector", "vector-algebra", "mathematics"),
  "addition-subtraction-and-scalar-multiplication-of-vectors": make("addition", "Vector Operations", "vector-algebra", "mathematics"),
  "dot-product-scalar-product-and-its-applications": make("dot product", "Dot Product", "vector-algebra", "mathematics"),
  "cross-product-vector-product-and-its-applications": make("cross product", "Cross Product", "vector-algebra", "mathematics"),
  "scalar-and-vector-triple-products": make("triple product", "Triple Products", "vector-algebra", "mathematics"),
  "applications-work-torque-angular-momentum": make("work", "Applications", "vector-algebra", "mathematics"),
  "three-dimensional-geometry": make("direction cosine", "3D Geometry", "three-dimensional-geometry", "mathematics"),
  "direction-cosines-and-direction-ratios-of-a-line": make("direction cosine", "Direction Cosines", "three-dimensional-geometry", "mathematics"),
  "equation-of-a-line-in-space-standard-and-general-form": make("equation of a line", "Line in Space", "three-dimensional-geometry", "mathematics"),
  "equation-of-a-plane-normal-form-general-form": make("equation of a plane", "Plane Equation", "three-dimensional-geometry", "mathematics"),
  "angle-between-two-lines-two-planes-and-a-line-and-a-plane": make("angle between", "Angles", "three-dimensional-geometry", "mathematics"),
  "distance-of-a-point-from-a-plane-and-line": make("distance of a point", "Distance", "three-dimensional-geometry", "mathematics"),
  "linear-programming": make("linear programming", "Linear Programming", "linear-programming", "mathematics"),
  "linear-programming-formulation-of-lpp": make("linear programming", "Formulation of LPP", "linear-programming", "mathematics"),
  "graphical-method-for-solving-lpp-with-two-variables": make("graphical method", "Graphical Method", "linear-programming", "mathematics"),
  "maximization-and-minimization-problems": make("maximization", "Max/Min Problems", "linear-programming", "mathematics"),
  "probability": make("probability", "Probability", "probability", "mathematics"),
  "conditional-probability-and-multiplication-theorem": make("conditional probability", "Conditional Probability", "probability", "mathematics"),
  "independent-events": make("independent", "Independent Events", "probability", "mathematics"),
  "bayes-theorem-and-its-applications": make("bayes", "Bayes' Theorem", "probability", "mathematics"),
  "random-variable-and-its-probability-distribution": make("random variable", "Random Variable", "probability", "mathematics"),
  "mean-variance-and-standard-deviation-of-a-random-variable": make("variance", "Mean & Variance", "probability", "mathematics"),
  "binomial-distribution-definition-mean-variance": make("binomial", "Binomial Distribution", "probability", "mathematics"),
  "poisson-distribution-definition-mean-variance": make("poisson", "Poisson Distribution", "probability", "mathematics"),
};

export { CHEMISTRY_12, MATH_12 };

const BIOLOGY_12: LabComponentMap = {
  "heredity-and-evolution": make("mendel", "Heredity & Evolution", "heredity-and-evolution", "biology"),
  "mendels-laws-of-inheritance-monochromo-and-dihybrid-cross": make("mendel", "Mendel's Laws", "heredity-and-evolution", "biology"),
  "incomplete-dominance-and-codominance": make("incomplete dominance", "Incomplete Dominance", "heredity-and-evolution", "biology"),
  "linkage-and-crossing-over": make("linkage", "Linkage", "heredity-and-evolution", "biology"),
  "sex-determination-and-sex-linked-disorders": make("sex determination", "Sex Determination", "heredity-and-evolution", "biology"),
  "chromosome-theory-of-inheritance": make("chromosome theory", "Chromosome Theory", "heredity-and-evolution", "biology"),
  "molecular-basis-of-inheritance-dna-structure-replication-transcription-translation-gene-regulation": make("molecular basis", "Molecular Basis", "heredity-and-evolution", "biology"),
  "human-genome-project-objectives-and-significance": make("human genome", "Human Genome Project", "heredity-and-evolution", "biology"),
  "evolution-evidences-adaptive-radiation-hardy-weinberg-equilibrium-human-evolution": make("evolution", "Evolution", "heredity-and-evolution", "biology"),
  "human-health-and-diseases": make("pathogen", "Health & Diseases", "human-health-and-diseases", "biology"),
  "pathogens-and-diseases-malaria-dengue-filariasis-ascariasis-pneumonia-typhoid-tuberculosis-common-cold-aids-ringworm": make("pathogen", "Pathogens", "human-health-and-diseases", "biology"),
  "immune-system-innate-and-adaptive-immunity": make("immune system", "Immune System", "human-health-and-diseases", "biology"),
  "antigens-and-antibodies-immune-response": make("antigen", "Antigens & Antibodies", "human-health-and-diseases", "biology"),
  "vaccination-and-immunization": make("vaccination", "Vaccination", "human-health-and-diseases", "biology"),
  "allergy-and-autoimmune-diseases": make("allergy", "Allergy", "human-health-and-diseases", "biology"),
  "strategies-for-food-production": make("plant breeding", "Food Production", "strategies-for-food-production", "biology"),
  "plant-breeding-methods-and-examples": make("plant breeding", "Plant Breeding", "strategies-for-food-production", "biology"),
  "single-cell-protein-scp": make("scp", "Single Cell Protein", "strategies-for-food-production", "biology"),
  "animal-husbandry-breeds-and-management": make("animal husbandry", "Animal Husbandry", "strategies-for-food-production", "biology"),
  "biofertilizers-and-sustainable-agriculture": make("biofertilizer", "Biofertilizers", "strategies-for-food-production", "biology"),
  "microbes-in-human-welfare": make("microbes", "Microbes in Welfare", "microbes-in-human-welfare", "biology"),
  "microorganisms-in-household-products": make("microbes", "Household Microbes", "microbes-in-human-welfare", "biology"),
  "industrial-production-of-antibiotics-alcoholic-beverages-citric-acid": make("antibiotics", "Industrial Production", "microbes-in-human-welfare", "biology"),
  "microbes-as-biocontrol-agents-and-biofertilizers": make("biocontrol", "Biocontrol", "microbes-in-human-welfare", "biology"),
  "bioremediation-biogas": make("bioremediation", "Bioremediation", "microbes-in-human-welfare", "biology"),
  "biotechnology-principles": make("recombinant", "Biotechnology Principles", "biotechnology-principles", "biology"),
  "principles-of-biotechnology-recombinant-dna-technology": make("recombinant", "Principles", "biotechnology-principles", "biology"),
  "tools-restriction-enzymes-vectors-competent-host": make("restriction enzyme", "Tools", "biotechnology-principles", "biology"),
  "processes-dna-isolation-pcr-gel-electrophoresis-gene-transfer": make("pcr", "Processes", "biotechnology-principles", "biology"),
  "applications-of-recombinant-dna-technology": make("recombinant", "Applications", "biotechnology-principles", "biology"),
  "biotechnology-applications": make("biotechnology applications", "Biotechnology Applications", "biotechnology-applications", "biology"),
  "biotechnological-applications-in-agriculture-bt-cotton-nematode-resistant-tobacco": make("bt cotton", "Agriculture Applications", "biotechnology-applications", "biology"),
  "biotechnological-applications-in-medicine-insulin-gene-therapy-therapeutic-proteins": make("insulin", "Medicine Applications", "biotechnology-applications", "biology"),
  "transgenic-animals": make("transgenic", "Transgenic Animals", "biotechnology-applications", "biology"),
  "biopiracy-and-patent-issues": make("biopiracy", "Biopiracy", "biotechnology-applications", "biology"),
  "organisms-and-environment": make("organisms and environment", "Organisms & Environment", "organisms-and-environment", "biology"),
  "adaptations-of-organisms-to-environmental-conditions": make("adaptation", "Adaptations", "organisms-and-environment", "biology"),
  "population-ecology-growth-regulation-interactions": make("population ecology", "Population Ecology", "organisms-and-environment", "biology"),
  "ecosystem-structure-and-function-productivity-decomposition": make("ecosystem", "Ecosystem Structure", "organisms-and-environment", "biology"),
  "ecological-succession": make("succession", "Ecological Succession", "organisms-and-environment", "biology"),
  "nutrient-cycling-carbon-nitrogen-phosphorus": make("nutrient cycling", "Nutrient Cycling", "organisms-and-environment", "biology"),
  "ecological-pyramids-and-energy-flow": make("ecological pyramid", "Ecological Pyramids", "organisms-and-environment", "biology"),
  "biodiversity-and-conservation": make("biodiversity", "Biodiversity & Conservation", "biodiversity-and-conservation", "biology"),
  "biodiversity-genetic-species-and-ecosystem-levels": make("biodiversity", "Levels of Biodiversity", "biodiversity-and-conservation", "biology"),
  "patterns-of-biodiversity-global-and-nepal": make("patterns of biodiversity", "Biodiversity Patterns", "biodiversity-and-conservation", "biology"),
  "biodiversity-loss-causes-and-consequences": make("biodiversity loss", "Biodiversity Loss", "biodiversity-and-conservation", "biology"),
  "conservation-strategies-in-situ-and-ex-situ": make("conservation", "Conservation Strategies", "biodiversity-and-conservation", "biology"),
  "red-data-book-and-iucn-categories": make("red data book", "Red Data Book", "biodiversity-and-conservation", "biology"),
  "environmental-issues": make("environmental issues", "Environmental Issues", "environmental-issues", "biology"),
  "air-pollution-causes-effects-and-control": make("air pollution", "Air Pollution", "environmental-issues", "biology"),
  "water-pollution-causes-effects-and-control": make("water pollution", "Water Pollution", "environmental-issues", "biology"),
  "solid-waste-management": make("solid waste", "Solid Waste", "environmental-issues", "biology"),
  "nuclear-radiation-hazards": make("nuclear radiation", "Nuclear Hazards", "environmental-issues", "biology"),
  "greenhouse-effect-global-warming-climate-change": make("greenhouse", "Greenhouse Effect", "environmental-issues", "biology"),
  "ozone-layer-depletion": make("ozone", "Ozone Depletion", "environmental-issues", "biology"),
  "rainwater-harvesting-and-wasteland-development": make("rainwater harvesting", "Rainwater Harvesting", "environmental-issues", "biology"),
};

export const TOPIC_3D_MAP: LabComponentMap = {
  ...PHYSICS_11, ...PHYSICS_12,
  ...CHEMISTRY_11, ...CHEMISTRY_12,
  ...BIOLOGY_11, ...BIOLOGY_12,
  ...MATH_11, ...MATH_12,
};

export function get3DComponentForTopic(topicSlug: string) {
  const normalized = topicSlug.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return TOPIC_3D_MAP[normalized] || null;
}
